import { describe, expect, it } from "vitest";

import { dashboardHtml } from "../src/ui/dashboard.js";

describe("dashboardHtml", () => {
  it("renders upstream overview detail panels for v56", () => {
    const html = dashboardHtml();

    expect(html).toContain("Upstream Overview");
    expect(html).toContain('id="overviewOverallState"');
    expect(html).toContain('id="javaFailedSummarySignal"');
    expect(html).toContain('id="javaBacklogSignal"');
    expect(html).toContain('id="kvIdentitySignal"');
    expect(html).toContain('id="kvCommandSignal"');
    expect(html).toContain('id="kvRiskSignal"');
    expect(html).toContain('id="failedEventId"');
    expect(html).toContain("Replay Readiness");
    expect(html).toContain("refreshFailedEventReadiness");
    expect(html).toContain('id="kvPrefix"');
    expect(html).toContain("Key Inventory");
    expect(html).toContain("refreshMiniKvKeyInventory");
    expect(html).toContain("Preflight");
    expect(html).toContain('data-action="intentPreflight"');
    expect(html).toContain('data-action="intentPreflightReport"');
    expect(html).toContain('data-action="intentPreflightVerification"');
    expect(html).toContain('data-action="intentExecutionPreview"');
    expect(html).toContain('data-action="createApprovalRequest"');
    expect(html).toContain('data-action="listApprovalRequests"');
    expect(html).toContain('id="approvalRequestId"');
    expect(html).toContain('data-action="approveApprovalRequest"');
    expect(html).toContain('data-action="rejectApprovalRequest"');
    expect(html).toContain('data-action="listApprovalDecisions"');
    expect(html).toContain('data-action="approvalEvidenceReport"');
    expect(html).toContain('data-action="approvalEvidenceVerification"');
    expect(html).toContain("failed-event-replay-simulation");
    expect(html).toContain("/preflight");
    expect(html).toContain("/preflight/report");
    expect(html).toContain("/preflight/verification");
    expect(html).toContain("/execution-preview");
    expect(html).toContain("/api/v1/operation-approval-requests");
    expect(html).toContain("/api/v1/operation-approval-decisions");
    expect(html).toContain("/decision");
    expect(html).toContain("/evidence?format=markdown");
    expect(html).toContain("/verification");
    expect(html).toContain("function renderUpstreamOverview");
    expect(html).toContain("refreshUpstreamOverview");
    expect(html).toContain("Fixture Report");
    expect(html).toContain('id="fixtureReportState"');
    expect(html).toContain('id="fixtureDigestSignal"');
    expect(html).toContain('id="fixtureJavaContractDigestSignal"');
    expect(html).toContain('id="fixtureJavaExecutionChecksSignal"');
    expect(html).toContain('id="fixtureMiniKvCommandDigestSignal"');
    expect(html).toContain('id="fixtureDriftSignal"');
    expect(html).toContain('id="fixtureDriftMappingSignal"');
    expect(html).toContain("/api/v1/upstream-contract-fixtures");
    expect(html).toContain("/api/v1/upstream-contract-fixtures/drift-diagnostics");
    expect(html).toContain('data-action="fixtureDiagnostics"');
    expect(html).toContain('data-action="fixtureReportMarkdown"');
    expect(html).toContain('data-action="fixtureDriftMarkdown"');
    expect(html).toContain("function renderFixtureDiagnostics");
    expect(html).toContain("refreshFixtureDiagnostics");
    expect(html).toContain("Scenario Matrix");
    expect(html).toContain('id="scenarioMatrixState"');
    expect(html).toContain('id="scenarioMatrixDigestSignal"');
    expect(html).toContain('id="scenarioMatrixCountSignal"');
    expect(html).toContain('id="scenarioMatrixIssueSignal"');
    expect(html).toContain('id="scenarioJavaApprovedSignal"');
    expect(html).toContain('id="scenarioJavaBlockedSignal"');
    expect(html).toContain('id="scenarioMiniKvWriteSignal"');
    expect(html).toContain('id="scenarioMiniKvReadSignal"');
    expect(html).toContain("/api/v1/upstream-contract-fixtures/scenario-matrix");
    expect(html).toContain('data-action="scenarioMatrix"');
    expect(html).toContain('data-action="scenarioMatrixMarkdown"');
    expect(html).toContain("function renderScenarioMatrix");
    expect(html).toContain("refreshScenarioMatrix");
    expect(html).toContain("Scenario Verification");
    expect(html).toContain('id="scenarioVerificationState"');
    expect(html).toContain('id="scenarioVerificationValidSignal"');
    expect(html).toContain('id="scenarioVerificationDigestSignal"');
    expect(html).toContain('id="scenarioVerificationScenarioCountSignal"');
    expect(html).toContain('id="scenarioVerificationBlockedReplaySignal"');
    expect(html).toContain('id="scenarioVerificationMiniKvReadSignal"');
    expect(html).toContain('id="scenarioVerificationSourcePathsSignal"');
    expect(html).toContain("/api/v1/upstream-contract-fixtures/scenario-matrix/verification");
    expect(html).toContain('data-action="scenarioVerification"');
    expect(html).toContain('data-action="scenarioVerificationMarkdown"');
    expect(html).toContain("function renderScenarioVerification");
    expect(html).toContain("refreshScenarioVerification");
    expect(html).toContain("Scenario Archive Bundle");
    expect(html).toContain('id="scenarioArchiveBundleState"');
    expect(html).toContain('id="scenarioArchiveBundleValidSignal"');
    expect(html).toContain('id="scenarioArchiveBundleReadExecuteSignal"');
    expect(html).toContain('id="scenarioArchiveBundleSourcePathSignal"');
    expect(html).toContain('id="scenarioArchiveBundleDigestSignal"');
    expect(html).toContain('id="scenarioArchiveBundleVerificationDigestSignal"');
    expect(html).toContain('id="scenarioArchiveBundleMatrixDigestSignal"');
    expect(html).toContain('id="scenarioArchiveBundleScenarioSignal"');
    expect(html).toContain("/api/v1/upstream-contract-fixtures/scenario-matrix/verification/archive-bundle");
    expect(html).toContain('data-action="scenarioArchiveBundle"');
    expect(html).toContain('data-action="scenarioArchiveBundleMarkdown"');
    expect(html).toContain("function renderScenarioArchiveBundle");
    expect(html).toContain("refreshScenarioArchiveBundle");
  });
});
