import type { AuditJsonMarkdownRouteRegistration } from "./auditJsonMarkdownRouteRegistrar.js";
import { auditJsonMarkdownRouteGroups } from "./auditJsonMarkdownRouteGroups.js";

export const auditJsonMarkdownRouteGroupSourceAnchors: readonly string[] = [
  "...foundationalAuditJsonMarkdownRoutes",
  "...managedAuditAdapterAuditJsonMarkdownRoutes",
  "...managedAuditPersistenceAuditJsonMarkdownRoutes",
  "...managedAuditIdentityApprovalAuditJsonMarkdownRoutes",
  "...managedAuditRestoreDrillAuditJsonMarkdownRoutes",
  "...managedAuditDryRunAdapterAuditJsonMarkdownRoutes",
  "...managedAuditRouteQualityAuditJsonMarkdownRoutes",
  "...managedAuditAdapterImplementationAuditJsonMarkdownRoutes",
  "...managedAuditLocalAdapterAuditJsonMarkdownRoutes",
  "...managedAuditSandboxAdapterAuditJsonMarkdownRoutes",
  "...managedAuditManualSandboxConnectionPacketAuditJsonMarkdownRoutes",
  "...managedAuditManualSandboxConnectionReadinessAuditJsonMarkdownRoutes",
  "...managedAuditManualSandboxConnectionCommandAuditJsonMarkdownRoutes",
  "...managedAuditManualSandboxConnectionPrecheckAuditJsonMarkdownRoutes",
  "...managedAuditManualSandboxConnectionAdapterClientAuditJsonMarkdownRoutes",
  "...managedAuditManualSandboxConnectionFakeTransportAuditJsonMarkdownRoutes",
  "...sandboxEndpointCredentialResolverAuditJsonMarkdownRoutes",
  "...credentialResolverFakeShellReadinessAuditJsonMarkdownRoutes",
  "...credentialResolverPreImplementationReadinessAuditJsonMarkdownRoutes",
  "...credentialResolverApprovalRequiredReadinessAuditJsonMarkdownRoutes",
  "...credentialResolverImplementationPlanAuditJsonMarkdownRoutes",
  "...credentialResolverFakeHarnessContractAuditJsonMarkdownRoutes",
  "...credentialResolverFakeHarnessExecutionReadinessAuditJsonMarkdownRoutes",
  "...credentialResolverDisabledRuntimeShellReadinessAuditJsonMarkdownRoutes",
  "...credentialResolverRuntimeShellDecisionAuditJsonMarkdownRoutes",
  "...credentialResolverRuntimeShellPostDecisionAuditJsonMarkdownRoutes",
  "...credentialResolverRuntimeShellPrerequisiteAuditJsonMarkdownRoutes",
  "...credentialResolverHumanApprovalArtifactReviewAuditJsonMarkdownRoutes",
  "...credentialResolverSignedHumanApprovalArtifactAuditJsonMarkdownRoutes",
  "...credentialResolverCredentialHandleApprovalAuditJsonMarkdownRoutes",
  "...credentialResolverEndpointHandleAllowlistApprovalAuditJsonMarkdownRoutes",
  "...credentialResolverNoNetworkSafetyFixtureAuditJsonMarkdownRoutes",
  "...credentialResolverFinalPrerequisiteAuditJsonMarkdownRoutes",
  "...credentialResolverImplementationCandidateGateAuditJsonMarkdownRoutes",
  "...credentialResolverDisabledRuntimeShellDesignDraftCandidateAuditJsonMarkdownRoutes",
  "...credentialResolverDisabledRuntimeShellDesignDraftOutlineAuditJsonMarkdownRoutes",
  "...credentialResolverDisabledRuntimeShellDesignDraftBodyIntakeAuditJsonMarkdownRoutes",
  "...credentialResolverDisabledRuntimeShellDesignDraftBodyCandidateAuditJsonMarkdownRoutes",
  "...credentialResolverDisabledRuntimeShellDesignDraftBodyPreDraftDecisionAuditJsonMarkdownRoutes",
  "...credentialResolverDisabledRuntimeShellDesignDraftBodyPreparationPlanAuditJsonMarkdownRoutes",
  "...credentialResolverDisabledRuntimeShellDesignDraftBodyDraftCandidateAuditJsonMarkdownRoutes",
  "...minimalReadOnlyIntegrationAuditJsonMarkdownRoutes",
  "...minimalShardReadinessAuditJsonMarkdownRoutes",
  "...javaMiniKvShardReadinessEvidenceAuditJsonMarkdownRoutes",
  "...javaMiniKvActiveShardPlanAuditJsonMarkdownRoutes",
  "...javaMiniKvDeclaredOperatorLifecycleAuditJsonMarkdownRoutes",
  "...javaMiniKvRuntimeExecutionAuditJsonMarkdownRoutes",
  "...managedAuditDisabledReadOnlyIntegrationAuditJsonMarkdownRoutes",
  "...sandboxHandleReviewAuditJsonMarkdownRoutes",
];

export const auditJsonMarkdownRoutes: readonly AuditJsonMarkdownRouteRegistration[] = auditJsonMarkdownRouteGroups
  .flatMap((group) => group.routes);
