import type {
  JavaReleaseOperatorSignoffFixtureReference,
  MiniKvRetainedRestoreArtifactDigestReference,
} from "./approvalDecisionPrerequisiteGateTypes.js";

export const JAVA_V64_RELEASE_OPERATOR_SIGNOFF_FIXTURE: JavaReleaseOperatorSignoffFixtureReference = {
  project: "advanced-order-platform",
  plannedVersion: "Java v64",
  evidenceTag: "v64 release operator signoff fixture",
  fixtureVersion: "java-release-operator-signoff-fixture.v1",
  scenario: "RELEASE_OPERATOR_SIGNOFF_FIXTURE_SAMPLE",
  sourceEvidenceEndpoint: "/api/v1/ops/evidence",
  fixtureEndpoint: "/contracts/release-operator-signoff.fixture.json",
  fixtureMode: "READ_ONLY_RELEASE_OPERATOR_SIGNOFF_FIXTURE",
  signoffRecord: {
    releaseOperator: "release-operator-placeholder",
    rollbackApprover: "rollback-approver-placeholder",
    releaseWindow: "release-window-placeholder",
    artifactTarget: "release-tag-or-artifact-version-placeholder",
    operatorSignoffPlaceholder: "operator-signoff-placeholder",
    operatorMustReplacePlaceholders: true,
    signoffStatus: "PENDING_OPERATOR_SIGNOFF_CONFIRMATION",
  },
  requiredSignoffFields: [
    { name: "release-operator", required: true, nodeMayInfer: false },
    { name: "rollback-approver", required: true, nodeMayInfer: false },
    { name: "release-window", required: true, nodeMayInfer: false },
    { name: "artifact-target", required: true, nodeMayInfer: false },
    { name: "operator-signoff-placeholder", required: true, nodeMayCreateApprovalDecision: false },
    { name: "release-audit-retention-fixture", required: true, expectedEndpoint: "/contracts/release-audit-retention.fixture.json", nodeMayWriteAuditExport: false },
    { name: "no-secret-value-boundary", required: true, nodeMayReadSecretValues: false },
  ],
  signoffArtifacts: [
    "/contracts/release-handoff-checklist.fixture.json",
    "/contracts/release-audit-retention.fixture.json",
    "/contracts/release-bundle-manifest.sample.json",
    "/contracts/release-verification-manifest.sample.json",
    "/contracts/production-deployment-runbook-contract.sample.json",
    "/contracts/rollback-approval-handoff.sample.json",
  ],
  noSecretValueBoundaries: [
    "Signoff fixture stores metadata only",
    "Secret values must not be read by Java or Node when rendering this signoff",
    "Secret values must not be embedded in release operator signoff JSON",
    "Node may render the approval prerequisite gate only",
  ],
  nodeConsumption: {
    nodeMayConsume: true,
    nodeMayRenderApprovalPrerequisiteGate: true,
    nodeMayCreateApprovalDecision: false,
    nodeMayWriteApprovalLedger: false,
    nodeMayTriggerDeployment: false,
    nodeMayTriggerRollback: false,
    nodeMayExecuteRollbackSql: false,
    nodeMayReadSecretValues: false,
    requiresUpstreamActionsEnabled: false,
  },
  boundaries: {
    deploymentExecutionAllowed: false,
    rollbackExecutionAllowed: false,
    rollbackSqlExecutionAllowed: false,
    approvalDecisionCreated: false,
    approvalLedgerWriteAllowed: false,
    requiresProductionDatabase: false,
    requiresProductionSecrets: false,
    changesOrderCreateSemantics: false,
    changesPaymentOrInventoryTransaction: false,
    changesOutboxOrReplayExecution: false,
    changesOrderTransactionSemantics: false,
    connectsMiniKv: false,
  },
  forbiddenOperations: [
    "Creating a real approval decision from this fixture",
    "Writing approval ledger entries from this fixture",
    "Executing Java deployment from this fixture",
    "Executing Java rollback from this fixture",
    "Executing database rollback SQL from this fixture",
    "Connecting production database from this fixture",
    "Reading production secret values from this fixture",
    "Embedding secret values in release operator signoff JSON",
    "Triggering Java deployment from Node",
    "Triggering Java rollback from Node",
    "POST /api/v1/orders",
    "POST /api/v1/failed-events/{id}/replay",
  ],
  readOnly: true,
  executionAllowed: false,
};

export const MINI_KV_V73_RETAINED_RESTORE_ARTIFACT_DIGEST: MiniKvRetainedRestoreArtifactDigestReference = {
  project: "mini-kv",
  plannedVersion: "mini-kv v73",
  evidenceTag: "v73 retained restore artifact digest fixture",
  digestVersion: "mini-kv-retained-restore-artifact-digest.v1",
  projectVersion: "0.73.0",
  releaseVersion: "v73",
  path: "fixtures/release/retained-restore-artifact-digest.json",
  readOnly: true,
  executionAllowed: false,
  restoreExecutionAllowed: false,
  orderAuthoritative: false,
  consumerHint: "Node v180 approval decision prerequisite gate",
  digestTarget: {
    targetReleaseVersion: "v73",
    sourceRetentionFixture: "fixtures/release/restore-evidence-retention.json",
    sourceVerificationManifest: "fixtures/release/verification-manifest.json",
    retentionId: "mini-kv-retained-restore-artifact-digest-v73",
    restoreTargetPlaceholder: "restore-target:<operator-recorded-restore-target>",
    restoreArtifactDigestPlaceholder: "sha256:<operator-retained-restore-artifact-digest>",
    snapshotReviewDigestPlaceholder: "sha256:<operator-retained-snapshot-review-digest>",
    walReviewDigestPlaceholder: "sha256:<operator-retained-wal-review-digest>",
    retentionOwner: "operator:<retained-restore-artifact-owner>",
    boundary: "retained digest fixture records approval input evidence only and does not execute restore",
  },
  retainedDigestEvidence: {
    fields: [
      "restore_artifact_digest_retained_at",
      "snapshot_review_digest_retained_at",
      "wal_review_digest_retained_at",
      "retention_owner",
      "restore_target_placeholder",
      "order_authoritative",
      "approval_prerequisite_ready_for_node_review",
    ],
    requiredConfirmations: [
      "restore artifact digest retained outside mini-kv",
      "Snapshot review digest retained outside mini-kv",
      "WAL review digest retained outside mini-kv",
      "restore target placeholder recorded without production secret value",
      "retention owner recorded without production secret value",
      "mini-kv order_authoritative remains false",
    ],
    storagePolicy: "fixture records retained digest field names and placeholders only; artifact bytes and operator records live outside mini-kv",
  },
  checkjsonDigestEvidence: {
    commands: [
      "INFOJSON",
      "CHECKJSON LOAD data/retained-digest-restore.snap",
      "CHECKJSON COMPACT",
      "CHECKJSON SETNXEX restore:digest-token 30 value",
      "STORAGEJSON",
      "HEALTH",
      "GET restore:digest-token",
      "QUIT",
    ],
    expected: [
      "INFOJSON version matches 0.73.0",
      "CHECKJSON LOAD explains restore target risk without executing LOAD",
      "CHECKJSON COMPACT explains WAL rewrite risk without executing COMPACT",
      "CHECKJSON SETNXEX explains token claim risk without executing SETNXEX",
      "STORAGEJSON keeps order_authoritative=false",
      "GET restore:digest-token returns (nil)",
    ],
    writeCommandsExecuted: false,
    adminCommandsExecuted: false,
    approvalPrerequisiteInput: true,
  },
  fixtureInputs: [
    "fixtures/release/verification-manifest.json",
    "fixtures/release/restore-evidence-retention.json",
    "fixtures/release/restore-handoff-checklist.json",
    "fixtures/release/restore-drill-evidence.json",
    "fixtures/release/release-artifact-digest-package.json",
    "fixtures/release/artifact-digest-compatibility-matrix.json",
    "fixtures/release/restore-dry-run-operator-package.json",
    "fixtures/release/runtime-artifact-bundle-manifest.json",
    "fixtures/release/restore-compatibility-handoff.json",
    "fixtures/readonly/infojson-empty-inline.json",
    "fixtures/recovery/restart-recovery-evidence.json",
    "fixtures/ttl-token/recovery-evidence.json",
  ],
  boundaries: [
    "retained restore artifact digest fixture only",
    "artifact digest placeholder only",
    "Snapshot review digest placeholder only",
    "WAL review digest placeholder only",
    "restore target placeholder only",
    "retention owner placeholder only",
    "no runtime command added",
    "does not execute restore",
    "does not execute LOAD/COMPACT/SETNXEX",
    "does not run Java or Node",
    "does not read production secrets",
    "does not open UPSTREAM_ACTIONS_ENABLED",
    "not connected to Java transaction chain",
    "mini-kv remains not Java order authority",
  ],
  diagnostics: {
    warnings: [
      "Node v180 may consume this fixture only after Java v64, mini-kv v73, and Node v179 are complete",
      "retained digest fixture is not an approval decision and not a restore executor",
      "artifact digest, Snapshot review digest, WAL review digest, restore target, and retention owner must be verified outside mini-kv before approval decision prerequisite review",
    ],
    pauseConditions: [
      "needs production secrets",
      "needs production database access",
      "needs Node to auto-start Java or mini-kv",
      "needs mini-kv LOAD/COMPACT/SETNXEX execution",
      "needs mini-kv in Java transaction consistency chain",
      "restore target or retained digest owner is unclear",
    ],
  },
};

export const ENDPOINTS = Object.freeze({
  approvalDecisionPrerequisiteGateJson: "/api/v1/production/approval-decision-prerequisite-gate",
  approvalDecisionPrerequisiteGateMarkdown: "/api/v1/production/approval-decision-prerequisite-gate?format=markdown",
  productionReleasePreApprovalPacketJson: "/api/v1/production/release-pre-approval-packet",
  javaReleaseOperatorSignoffFixture: "/contracts/release-operator-signoff.fixture.json",
  miniKvRetainedRestoreArtifactDigest: "fixtures/release/retained-restore-artifact-digest.json",
  currentRoadmap: "docs/plans/v179-post-pre-approval-roadmap.md",
});
