import { renderEntries, renderProfileEntrySections } from "./liveProbeReportUtils.js";
import type { ControlledReadOnlyShardPreviewProfile } from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewTypes.js";

export function renderControlledReadOnlyShardPreviewOperatorEvidenceValueSupplyApprovalPacketProfileSections(
  profile: ControlledReadOnlyShardPreviewProfile,
): string[] {
  return renderProfileEntrySections([
    {
      heading: "Live Read-Only Window Operator Evidence Value Supply Approval Packet Draft",
      lines: renderEntries({
      approvalPacketDraftVersion:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.approvalPacketDraftVersion,
      sourceValueSupplyEnvelopeVersion:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.sourceValueSupplyEnvelopeVersion,
      javaValueSupplyEvidenceVersion:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.javaValueSupplyEvidenceVersion,
      miniKvValueSupplyEvidenceVersion:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.miniKvValueSupplyEvidenceVersion,
      draftState:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.draftState,
      readyForValueSupplyApprovalPacketDraft:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft
          .readyForValueSupplyApprovalPacketDraft,
      readyForOperatorValueSupply:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.readyForOperatorValueSupply,
      readyForOperatorValueSubmission:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft
          .readyForOperatorValueSubmission,
      readyForEvidenceImport:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.readyForEvidenceImport,
      readyForRuntimePayload:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.readyForRuntimePayload,
      draftSlotCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.draftSlotCount,
      javaEvidenceSlotCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.javaEvidenceSlotCount,
      miniKvEvidenceSlotCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.miniKvEvidenceSlotCount,
      nodeValueSupplyEnvelopeSlotCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.nodeValueSupplyEnvelopeSlotCount,
      presentFileCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.presentFileCount,
      matchedSnippetCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.matchedSnippetCount,
      historicalFixtureResolvedFileCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft
          .historicalFixtureResolvedFileCount,
      approvalFieldCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.approvalFieldCount,
      reviewRecordFieldCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.reviewRecordFieldCount,
      suppliedValueCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.suppliedValueCount,
      acceptedValueCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.acceptedValueCount,
      importedValueCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.importedValueCount,
      approvalCaptured:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.approvalCaptured,
      approvalGrantPresent:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.approvalGrantPresent,
      signedApprovalPresent:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.signedApprovalPresent,
      importsRuntimePayload:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.importsRuntimePayload,
      acceptsSyntheticEvidence:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.acceptsSyntheticEvidence,
      containsSecretValue:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.containsSecretValue,
      approvalPacketDraftDigest:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft.approvalPacketDraftDigest,
      }),
    },
    {
      heading: "Live Read-Only Window Operator Evidence Value Supply Approval Packet Review",
      lines: renderEntries({
      approvalPacketReviewVersion:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.approvalPacketReviewVersion,
      sourceApprovalPacketDraftVersion:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.sourceApprovalPacketDraftVersion,
      reviewPackageState:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.reviewPackageState,
      readyForValueSupplyApprovalPacketReview:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview
          .readyForValueSupplyApprovalPacketReview,
      readyForSignedApprovalCapture:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.readyForSignedApprovalCapture,
      readyForOperatorValueSupply:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.readyForOperatorValueSupply,
      readyForOperatorValueSubmission:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview
          .readyForOperatorValueSubmission,
      readyForEvidenceImport:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.readyForEvidenceImport,
      readyForRuntimePayload:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.readyForRuntimePayload,
      reviewControlCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.reviewControlCount,
      approvalFieldReviewControlCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview
          .approvalFieldReviewControlCount,
      policyReviewControlCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.policyReviewControlCount,
      sourceEvidenceReviewControlCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview
          .sourceEvidenceReviewControlCount,
      executionLockReviewControlCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview
          .executionLockReviewControlCount,
      closeoutReviewControlCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.closeoutReviewControlCount,
      manualReviewRequiredControlCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview
          .manualReviewRequiredControlCount,
      autoApprovalBlockedControlCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview
          .autoApprovalBlockedControlCount,
      suppliedValueCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.suppliedValueCount,
      acceptedValueCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.acceptedValueCount,
      importedValueCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.importedValueCount,
      approvalCaptured:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.approvalCaptured,
      approvalGrantPresent:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.approvalGrantPresent,
      signedApprovalPresent:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.signedApprovalPresent,
      importsRuntimePayload:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.importsRuntimePayload,
      acceptsSyntheticEvidence:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.acceptsSyntheticEvidence,
      containsSecretValue:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.containsSecretValue,
      approvalPacketReviewDigest:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview.approvalPacketReviewDigest,
      }),
    },
    {
      heading: "Live Read-Only Window Operator Evidence Value Supply Signed Approval Template",
      lines: renderEntries({
      signedApprovalTemplateVersion:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate
          .signedApprovalTemplateVersion,
      sourceApprovalPacketReviewVersion:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate
          .sourceApprovalPacketReviewVersion,
      templateState:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.templateState,
      readyForSignedApprovalTemplatePreflight:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate
          .readyForSignedApprovalTemplatePreflight,
      readyForSignedApprovalCapture:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate
          .readyForSignedApprovalCapture,
      readyForOperatorValueSupply:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.readyForOperatorValueSupply,
      readyForOperatorValueSubmission:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate
          .readyForOperatorValueSubmission,
      readyForEvidenceImport:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.readyForEvidenceImport,
      readyForRuntimePayload:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.readyForRuntimePayload,
      templateFieldCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.templateFieldCount,
      templateClauseCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.templateClauseCount,
      identityFieldCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.identityFieldCount,
      sourceEvidenceFieldCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.sourceEvidenceFieldCount,
      policyFieldCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.policyFieldCount,
      executionLockFieldCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.executionLockFieldCount,
      requiredFieldCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.requiredFieldCount,
      readyFieldCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.readyFieldCount,
      readyClauseCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.readyClauseCount,
      missingFieldBlockerCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.missingFieldBlockerCount,
      rejectionClauseCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.rejectionClauseCount,
      nonExecutionClauseCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.nonExecutionClauseCount,
      templateValueProvidedCount:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate
          .templateValueProvidedCount,
      approvalCaptured:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.approvalCaptured,
      approvalGrantPresent:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.approvalGrantPresent,
      signedApprovalPresent:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.signedApprovalPresent,
      importsRuntimePayload:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.importsRuntimePayload,
      acceptsSyntheticEvidence:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.acceptsSyntheticEvidence,
      containsSecretValue:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate.containsSecretValue,
      signedApprovalTemplateDigest:
        profile.preview.liveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplate
          .signedApprovalTemplateDigest,
      }),
    },
  ]);
}
