import type {
  ControlledReadOnlyShardPreviewCandidateDocumentRequestCheckKind,
  ControlledReadOnlyShardPreviewCandidateDocumentRequestCheckTemplate,
  ControlledReadOnlyShardPreviewCandidateDocumentRequestItemKind,
  ControlledReadOnlyShardPreviewCandidateDocumentRequestItemTemplate,
  ControlledReadOnlyShardPreviewCandidateDocumentRequestVersion,
} from "./controlledReadOnlyShardPreviewCandidateDocumentRequestTypes.js";
import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageComparedEvidenceCandidateIntakeGuardKind,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageComparedEvidenceCandidateIntakeTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_CANDIDATE_DOCUMENT_REQUEST_VERSIONS = [
  "Node v1372",
  "Node v1373",
  "Node v1374",
  "Node v1375",
  "Node v1376",
  "Node v1377",
  "Node v1378",
  "Node v1379",
  "Node v1380",
  "Node v1381",
  "Node v1382",
  "Node v1383",
  "Node v1384",
  "Node v1385",
  "Node v1386",
] as const satisfies readonly ControlledReadOnlyShardPreviewCandidateDocumentRequestVersion[];

const ALL_INTAKE_GUARD_KINDS: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageComparedEvidenceCandidateIntakeGuardKind[] = [
  "source-lineage-candidate-intake-guard",
  "artifact-shape-candidate-intake-guard",
  "operator-provenance-candidate-intake-guard",
  "comparison-result-candidate-intake-guard",
  "identity-digest-candidate-intake-guard",
  "signature-envelope-candidate-intake-guard",
  "evidence-handle-candidate-intake-guard",
  "policy-lock-candidate-intake-guard",
  "approval-separation-candidate-intake-guard",
  "archive-closeout-candidate-intake-guard",
];

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_CANDIDATE_DOCUMENT_REQUEST_ITEM_TEMPLATES: ControlledReadOnlyShardPreviewCandidateDocumentRequestItemTemplate[] = [
  {
    nodeVersion: "Node v1372",
    code: "CANDIDATE_DOCUMENT_REQUEST_SOURCE_LINEAGE",
    itemName: "Source lineage document request",
    kind: "source-lineage-document-request",
    sourceSlotKinds: ["source-lineage-candidate-intake-slot"],
    sourceGuardKinds: ["source-lineage-candidate-intake-guard"],
    requestInstruction: "Request a real source-lineage candidate document with durable upstream version and fixture lineage.",
    acceptanceCriterion: "Accept only a reviewed real document that covers the source-lineage candidate fields.",
  },
  {
    nodeVersion: "Node v1373",
    code: "CANDIDATE_DOCUMENT_REQUEST_ARTIFACT_SHAPE",
    itemName: "Artifact shape document request",
    kind: "artifact-shape-document-request",
    sourceSlotKinds: ["artifact-shape-candidate-intake-slot"],
    sourceGuardKinds: ["artifact-shape-candidate-intake-guard"],
    requestInstruction: "Request the real document shape, field list, and archive handle for the compared evidence candidate.",
    acceptanceCriterion: "Accept only a reviewed artifact-shape document whose fields match the intake slot.",
  },
  {
    nodeVersion: "Node v1374",
    code: "CANDIDATE_DOCUMENT_REQUEST_OPERATOR_PROVENANCE",
    itemName: "Operator provenance document request",
    kind: "operator-provenance-document-request",
    sourceSlotKinds: ["operator-provenance-candidate-intake-slot"],
    sourceGuardKinds: ["operator-provenance-candidate-intake-guard"],
    requestInstruction: "Request operator identity, provenance, and review responsibility for the real candidate document.",
    acceptanceCriterion: "Accept only reviewed provenance that does not grant approval by itself.",
  },
  {
    nodeVersion: "Node v1375",
    code: "CANDIDATE_DOCUMENT_REQUEST_COMPARISON_RESULT",
    itemName: "Comparison result document request",
    kind: "comparison-result-document-request",
    sourceSlotKinds: ["comparison-result-candidate-intake-slot"],
    sourceGuardKinds: ["comparison-result-candidate-intake-guard"],
    requestInstruction: "Request the offline comparison result that explains how the candidate document matches the package evidence.",
    acceptanceCriterion: "Accept only a reviewed comparison result; do not evaluate or import payloads in this package.",
  },
  {
    nodeVersion: "Node v1376",
    code: "CANDIDATE_DOCUMENT_REQUEST_IDENTITY_DIGEST",
    itemName: "Identity digest document request",
    kind: "identity-digest-document-request",
    sourceSlotKinds: ["identity-digest-candidate-intake-slot"],
    sourceGuardKinds: ["identity-digest-candidate-intake-guard"],
    requestInstruction: "Request identity and digest lineage for the real compared evidence candidate document.",
    acceptanceCriterion: "Accept only reviewed digest lineage that can be checked without reading secret values.",
  },
  {
    nodeVersion: "Node v1377",
    code: "CANDIDATE_DOCUMENT_REQUEST_SIGNATURE_ENVELOPE",
    itemName: "Signature envelope document request",
    kind: "signature-envelope-document-request",
    sourceSlotKinds: ["signature-envelope-candidate-intake-slot"],
    sourceGuardKinds: ["signature-envelope-candidate-intake-guard"],
    requestInstruction: "Request the signature envelope required for later signed approval review.",
    acceptanceCriterion: "Accept only a reviewed envelope; do not treat it as signed approval capture.",
  },
  {
    nodeVersion: "Node v1378",
    code: "CANDIDATE_DOCUMENT_REQUEST_EVIDENCE_HANDLE",
    itemName: "Evidence handle document request",
    kind: "evidence-handle-document-request",
    sourceSlotKinds: ["evidence-handle-candidate-intake-slot"],
    sourceGuardKinds: ["evidence-handle-candidate-intake-guard"],
    requestInstruction: "Request durable evidence handles that identify where the real candidate document was produced.",
    acceptanceCriterion: "Accept only reviewed handles; do not synthesize missing handles from historical fixtures.",
  },
  {
    nodeVersion: "Node v1379",
    code: "CANDIDATE_DOCUMENT_REQUEST_POLICY_LOCK",
    itemName: "Policy lock document request",
    kind: "policy-lock-document-request",
    sourceSlotKinds: ["policy-lock-candidate-intake-slot"],
    sourceGuardKinds: ["policy-lock-candidate-intake-guard"],
    requestInstruction: "Request policy-lock evidence proving the candidate document cannot bypass write and execution gates.",
    acceptanceCriterion: "Accept only reviewed policy-lock material while writes and sibling mutation remain blocked.",
  },
  {
    nodeVersion: "Node v1380",
    code: "CANDIDATE_DOCUMENT_REQUEST_APPROVAL_SEPARATION",
    itemName: "Approval separation document request",
    kind: "approval-separation-document-request",
    sourceSlotKinds: ["approval-separation-candidate-intake-slot"],
    sourceGuardKinds: ["approval-separation-candidate-intake-guard"],
    requestInstruction: "Request evidence that candidate document intake remains separate from approval grant and signed approval.",
    acceptanceCriterion: "Accept only reviewed separation evidence; do not infer approval from candidate document presence.",
  },
  {
    nodeVersion: "Node v1381",
    code: "CANDIDATE_DOCUMENT_REQUEST_ARCHIVE_CLOSEOUT",
    itemName: "Archive closeout document request",
    kind: "archive-closeout-document-request",
    sourceSlotKinds: ["archive-closeout-candidate-intake-slot"],
    sourceGuardKinds: ["archive-closeout-candidate-intake-guard"],
    requestInstruction: "Request archive closeout references for the real compared evidence candidate document.",
    acceptanceCriterion: "Accept only reviewed archive references that can be recorded without starting services.",
  },
  {
    nodeVersion: "Node v1382",
    code: "CANDIDATE_DOCUMENT_REQUEST_MISSING_DOCUMENT_REJECTION",
    itemName: "Missing document rejection request",
    kind: "missing-document-rejection-request",
    sourceSlotKinds: [],
    sourceGuardKinds: ALL_INTAKE_GUARD_KINDS,
    requestInstruction: "Request explicit rejection rules for missing candidate documents across every intake guard.",
    acceptanceCriterion: "Accept only rules that reject missing candidate documents before payload import.",
  },
  {
    nodeVersion: "Node v1383",
    code: "CANDIDATE_DOCUMENT_REQUEST_SYNTHETIC_DOCUMENT_REJECTION",
    itemName: "Synthetic document rejection request",
    kind: "synthetic-document-rejection-request",
    sourceSlotKinds: [],
    sourceGuardKinds: ALL_INTAKE_GUARD_KINDS,
    requestInstruction: "Request explicit rejection rules for synthetic candidate documents across every intake guard.",
    acceptanceCriterion: "Accept only rules that keep synthetic candidate evidence unusable for this path.",
  },
  {
    nodeVersion: "Node v1384",
    code: "CANDIDATE_DOCUMENT_REQUEST_UNREVIEWED_DOCUMENT_QUARANTINE",
    itemName: "Unreviewed document quarantine request",
    kind: "unreviewed-document-quarantine-request",
    sourceSlotKinds: [],
    sourceGuardKinds: ALL_INTAKE_GUARD_KINDS,
    requestInstruction: "Request quarantine instructions for unreviewed real candidate documents.",
    acceptanceCriterion: "Accept only quarantine instructions that keep unreviewed material out of import and evaluation.",
  },
  {
    nodeVersion: "Node v1385",
    code: "CANDIDATE_DOCUMENT_REQUEST_IMPORT_EVALUATION_FREEZE",
    itemName: "Import and evaluation freeze request",
    kind: "import-evaluation-freeze-request",
    sourceSlotKinds: [],
    sourceGuardKinds: ALL_INTAKE_GUARD_KINDS,
    requestInstruction: "Request freeze rules proving document request does not import, evaluate, accept, or reject payloads.",
    acceptanceCriterion: "Accept only freeze rules that keep payload import, evaluation, and acceptance blocked.",
  },
  {
    nodeVersion: "Node v1386",
    code: "CANDIDATE_DOCUMENT_REQUEST_EXECUTION_WRITE_MUTATION_FREEZE",
    itemName: "Execution, write, and mutation freeze request",
    kind: "execution-write-mutation-freeze-request",
    sourceSlotKinds: [],
    sourceGuardKinds: ALL_INTAKE_GUARD_KINDS,
    requestInstruction: "Request freeze rules proving document request does not start services, execute, write, or mutate siblings.",
    acceptanceCriterion: "Accept only freeze rules that keep runtime payloads, writes, and sibling mutation blocked.",
  },
];

const CHECK_KIND_BY_ITEM_KIND: Record<
  ControlledReadOnlyShardPreviewCandidateDocumentRequestItemKind,
  ControlledReadOnlyShardPreviewCandidateDocumentRequestCheckKind
> = {
  "source-lineage-document-request": "source-lineage-document-request-check",
  "artifact-shape-document-request": "artifact-shape-document-request-check",
  "operator-provenance-document-request": "operator-provenance-document-request-check",
  "comparison-result-document-request": "comparison-result-document-request-check",
  "identity-digest-document-request": "identity-digest-document-request-check",
  "signature-envelope-document-request": "signature-envelope-document-request-check",
  "evidence-handle-document-request": "evidence-handle-document-request-check",
  "policy-lock-document-request": "policy-lock-document-request-check",
  "approval-separation-document-request": "approval-separation-document-request-check",
  "archive-closeout-document-request": "archive-closeout-document-request-check",
  "missing-document-rejection-request": "missing-document-rejection-request-check",
  "synthetic-document-rejection-request": "synthetic-document-rejection-request-check",
  "unreviewed-document-quarantine-request": "unreviewed-document-quarantine-request-check",
  "import-evaluation-freeze-request": "import-evaluation-freeze-request-check",
  "execution-write-mutation-freeze-request": "execution-write-mutation-freeze-request-check",
};

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_CANDIDATE_DOCUMENT_REQUEST_CHECK_TEMPLATES:
  ControlledReadOnlyShardPreviewCandidateDocumentRequestCheckTemplate[] =
    CONTROLLED_READ_ONLY_SHARD_PREVIEW_CANDIDATE_DOCUMENT_REQUEST_ITEM_TEMPLATES.map((item) => ({
      nodeVersion: item.nodeVersion,
      code: `${item.code}_CHECK`,
      kind: CHECK_KIND_BY_ITEM_KIND[item.kind],
      sourceItemCode: item.code,
      checkText:
        `Verify ${item.itemName.toLowerCase()} stays read-only, requires real reviewed material, and blocks synthetic or executable payloads.`,
    }));
