import type {
  JavaDeploymentRunbookContractReference,
  MiniKvReleaseArtifactDigestPackageReference,
} from "./deploymentEvidenceIntakeGateTypes.js";

export const JAVA_V60_DEPLOYMENT_RUNBOOK: JavaDeploymentRunbookContractReference = Object.freeze({
  project: "advanced-order-platform",
  plannedVersion: "Java v60",
  evidenceTag: "v60订单平台production-deployment-runbook-contract",
  contractVersion: "java-production-deployment-runbook-contract.v1",
  scenario: "PRODUCTION_DEPLOYMENT_RUNBOOK_CONTRACT_SAMPLE",
  sourceEvidenceEndpoint: "/api/v1/ops/evidence",
  contractEndpoint: "/contracts/production-deployment-runbook-contract.sample.json",
  contractSource: "src/main/resources/static/contracts/production-deployment-runbook-contract.sample.json",
  archivePath: "c/60",
  walkthroughPath: "代码讲解记录_生产雏形阶段/64-version-60-production-deployment-runbook-contract.md",
  contractMode: "READ_ONLY_DEPLOYMENT_RUNBOOK_CONTRACT",
  deploymentWindow: {
    owner: "release-window-owner",
    rollbackApprover: "rollback-approval-owner",
    operatorStartRequired: true,
    nodeMayScheduleWindow: false,
    nodeMayTriggerDeployment: false,
  } as JavaDeploymentRunbookContractReference["deploymentWindow"],
  databaseMigration: {
    directionOptions: [
      "forward-only",
      "rollback-script-reviewed",
      "no-database-change",
    ] as JavaDeploymentRunbookContractReference["databaseMigration"]["directionOptions"],
    selectedDirection: "no-database-change",
    rollbackSqlExecutionAllowed: false,
    requiresProductionDatabase: false,
  } as JavaDeploymentRunbookContractReference["databaseMigration"],
  secretSourceConfirmation: {
    endpoint: "/contracts/production-secret-source-contract.sample.json",
    required: true,
    nodeMayReadSecretValues: false,
    secretValueRecorded: false,
  } as JavaDeploymentRunbookContractReference["secretSourceConfirmation"],
  requiredConfirmationFields: [
    "deployment-window-owner",
    "rollback-approver",
    "database-migration-direction",
    "secret-source-confirmation",
    "rollback-sql-review-gate",
    "operator-approval-placeholder",
  ] as JavaDeploymentRunbookContractReference["requiredConfirmationFields"],
  runbookArtifacts: [
    "/contracts/release-bundle-manifest.sample.json",
    "/contracts/deployment-rollback-evidence.sample.json",
    "/contracts/rollback-approval-handoff.sample.json",
    "/contracts/rollback-sql-review-gate.sample.json",
    "/contracts/production-secret-source-contract.sample.json",
  ] as JavaDeploymentRunbookContractReference["runbookArtifacts"],
  nodeConsumption: {
    nodeMayConsume: true,
    nodeMayRenderIntakeGate: true,
    nodeMayTriggerDeployment: false,
    nodeMayTriggerRollback: false,
    nodeMayExecuteRollbackSql: false,
    nodeMayModifyRuntimeConfig: false,
    requiresUpstreamActionsEnabled: false,
  } as JavaDeploymentRunbookContractReference["nodeConsumption"],
  boundaries: {
    sqlExecutionAllowed: false,
    requiresProductionDatabase: false,
    requiresProductionSecrets: false,
    changesOrderCreateSemantics: false,
    changesPaymentOrInventoryTransaction: false,
    changesOutboxOrReplayExecution: false,
    changesOrderTransactionSemantics: false,
    connectsMiniKv: false,
  } as JavaDeploymentRunbookContractReference["boundaries"],
  forbiddenOperations: [
    "Executing Java deployment from this runbook contract",
    "Triggering Java rollback from Node",
    "Executing rollback SQL from this runbook contract",
    "Connecting production database",
    "Reading production secret values from this runbook contract",
    "Modifying Java runtime configuration from Node",
    "POST /api/v1/orders",
    "POST /api/v1/failed-events/{id}/replay",
  ] as JavaDeploymentRunbookContractReference["forbiddenOperations"],
  readOnlyEvidence: true,
  executionAllowed: false,
});

export const MINI_KV_V69_RELEASE_ARTIFACT_PACKAGE: MiniKvReleaseArtifactDigestPackageReference = Object.freeze({
  project: "mini-kv",
  plannedVersion: "mini-kv v69",
  evidenceTag: "第六十九版发布产物摘要包",
  packageVersion: "mini-kv-release-artifact-digest-package.v1",
  packagePath: "fixtures/release/release-artifact-digest-package.json",
  archivePath: "c/69",
  walkthroughPath: "代码讲解记录_生产雏形阶段/125-version-69-release-artifact-digest-package.md",
  projectVersion: "0.69.0",
  releaseVersion: "v69",
  targetReleaseVersion: "v69",
  previousReleaseVersion: "v68",
  previousEvidence: [
    "fixtures/release/verification-manifest.json",
    "fixtures/release/artifact-digest-compatibility-matrix.json",
    "fixtures/release/restore-dry-run-operator-package.json",
    "fixtures/release/runtime-artifact-bundle-manifest.json",
  ] as MiniKvReleaseArtifactDigestPackageReference["previousEvidence"],
  artifactDigestIds: [
    "binary-digest",
    "wal-checksum-evidence",
    "snapshot-digest-evidence",
    "fixture-digest",
  ] as MiniKvReleaseArtifactDigestPackageReference["artifactDigestIds"],
  restoreDrillCommands: [
    "INFOJSON",
    "CHECKJSON LOAD data/release-artifact-drill.snap",
    "CHECKJSON COMPACT",
    "CHECKJSON SETNXEX release:token 30 value",
    "STORAGEJSON",
    "HEALTH",
    "GET release:token",
    "QUIT",
  ] as MiniKvReleaseArtifactDigestPackageReference["restoreDrillCommands"],
  operatorConfirmationFields: [
    "release_operator_id",
    "binary_digest_recorded_at",
    "wal_snapshot_digest_recorded_at",
    "fixture_digest_recorded_at",
    "restore_drill_profile_reviewed",
    "artifact_matrix_cross_checked",
  ] as MiniKvReleaseArtifactDigestPackageReference["operatorConfirmationFields"],
  fixtureInputs: [
    "fixtures/release/verification-manifest.json",
    "fixtures/release/artifact-digest-compatibility-matrix.json",
    "fixtures/readonly/infojson-empty-inline.json",
    "fixtures/recovery/restart-recovery-evidence.json",
    "fixtures/ttl-token/recovery-evidence.json",
  ] as MiniKvReleaseArtifactDigestPackageReference["fixtureInputs"],
  writeCommandsExecuted: false,
  adminCommandsExecuted: false,
  restoreExecutionAllowed: false,
  operatorConfirmationRequired: true,
  digestPlaceholdersOnly: true,
  noRuntimeCommandAdded: true,
  orderAuthoritative: false,
  connectedToJavaTransactionChain: false,
  doesNotRunJavaOrNode: true,
  doesNotReadProductionSecrets: true,
  doesNotOpenUpstreamActions: true,
  readOnlyEvidence: true,
  executionAllowed: false,
});

export const ENDPOINTS = Object.freeze({
  deploymentEvidenceIntakeGateJson: "/api/v1/production/deployment-evidence-intake-gate",
  deploymentEvidenceIntakeGateMarkdown: "/api/v1/production/deployment-evidence-intake-gate?format=markdown",
  postV166ReadinessSummaryJson: "/api/v1/production/post-v166-readiness-summary",
  javaDeploymentRunbookContract: "/contracts/production-deployment-runbook-contract.sample.json",
  miniKvReleaseArtifactDigestPackage: "fixtures/release/release-artifact-digest-package.json",
  currentRoadmap: "docs/plans/v169-post-production-environment-preflight-roadmap.md",
});
