import {
  renderEntries,
  renderList,
} from "./liveProbeReportUtils.js";
import type {
  JavaMiniKvRouteCatalogCleanupReadinessHandoffEvidenceReport,
} from "./javaMiniKvRouteCatalogCleanupReadinessHandoffEvidenceReport.js";

export function renderJavaMiniKvRouteCatalogCleanupReadinessHandoffEvidenceReportMarkdown(
  report: JavaMiniKvRouteCatalogCleanupReadinessHandoffEvidenceReport,
): string {
  return [
    "# Java / mini-kv route catalog cleanup readiness handoff evidence report",
    "",
    `- Service: ${report.service}`,
    `- Generated at: ${report.generatedAt}`,
    `- Profile version: ${report.profileVersion}`,
    `- Report state: ${report.reportState}`,
    `- Ready: ${report.readyForRouteCatalogCleanupReadinessHandoffEvidenceReport}`,
    `- Active Node version: ${report.activeNodeVersion}`,
    `- Source Node version: ${report.sourceNodeVersion}`,
    `- Execution allowed: ${report.executionAllowed}`,
    "",
    "## Summary",
    "",
    ...renderEntries(report.summary),
    "",
    "## Checks",
    "",
    ...renderEntries(report.checks),
    "",
    "## Java v225 Readiness Handoff",
    "",
    ...renderEntries(report.evidence.javaV225ConsumerReadinessHandoff),
    "",
    "## Java v225 Readiness Handoff Fixture",
    "",
    ...renderEntries(report.evidence.javaV225ConsumerReadinessHandoffFixture),
    "",
    "## Java v226-v231 Readiness Guards",
    "",
    ...[
      report.evidence.javaV226ConsumerReadinessHandoffSnapshotFreeze,
      report.evidence.javaV227ConsumerReadinessHandoffHistoricalCompatibility,
      report.evidence.javaV228ConsumerReadinessHandoffIntegrity,
      report.evidence.javaV229ConsumerReadinessHandoffRouteInventory,
      report.evidence.javaV230ConsumerReadinessHandoffEvidenceChain,
      report.evidence.javaV231ConsumerReadinessHandoffOpsEvidenceAlignment,
    ].flatMap((guard) => [
      `- ${guard.version}: ${guard.scope}`,
      `  - status: ${guard.status}`,
      `  - guardCount: ${guard.guardCount}`,
      `  - boundaryRuntimeClosed: ${guard.boundaryRuntimeClosed}`,
    ]),
    "",
    "## mini-kv v211-v212 Retention",
    "",
    ...[
      report.evidence.miniKvV211RouteCatalogPostCloseoutRetention,
      report.evidence.miniKvV212RouteCatalogPostCloseoutRetentionAudit,
    ].flatMap((release) => [
      `- ${release.releaseVersion}: ${release.status}`,
      `  - previousConsumedReleaseVersion: ${release.previousConsumedReleaseVersion}`,
      `  - continuityStage: ${release.continuityStage}`,
      `  - historicalFixtureCount: ${release.historicalFixtureCount}`,
    ]),
    "",
    "## Evidence Files",
    "",
    ...Object.values(report.evidence.files).flatMap((file) => [
      `- ${file.id}: ${file.exists ? "present" : "missing"}`,
      `  - Resolved path: ${file.resolvedPath}`,
      `  - SHA-256: ${file.digest ?? "missing"}`,
    ]),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(report.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(report.nextActions, "No next actions."),
    "",
  ].join("\n");
}
