import {
  renderEntries,
  renderList,
} from "./liveProbeReportUtils.js";
import type {
  JavaMiniKvRouteCatalogCleanupLatestSiblingEvidenceReport,
} from "./javaMiniKvRouteCatalogCleanupLatestSiblingEvidenceReport.js";

export function renderJavaMiniKvRouteCatalogCleanupLatestSiblingEvidenceReportMarkdown(
  report: JavaMiniKvRouteCatalogCleanupLatestSiblingEvidenceReport,
): string {
  return [
    "# Java / mini-kv route catalog cleanup latest sibling evidence report",
    "",
    `- Service: ${report.service}`,
    `- Generated at: ${report.generatedAt}`,
    `- Profile version: ${report.profileVersion}`,
    `- Report state: ${report.reportState}`,
    `- Ready: ${report.readyForRouteCatalogCleanupLatestSiblingEvidenceReport}`,
    `- Active Node version: ${report.activeNodeVersion}`,
    `- Source Node version: ${report.sourceNodeVersion}`,
    `- CI stabilization version: ${report.ciStabilizationVersion}`,
    `- Execution allowed: ${report.executionAllowed}`,
    "",
    "## Summary",
    "",
    ...renderEntries(report.summary),
    "",
    "## Checks",
    "",
    ...renderEntries(report.checks),
    "",
    "## Java v274 Receipt",
    "",
    ...renderEntries(report.evidence.javaReceipt),
    "",
    "## mini-kv v247 Release",
    "",
    ...renderEntries(report.evidence.miniKvRelease),
    "",
    "## Route Catalog",
    "",
    ...renderEntries(report.routeCatalog),
    "",
    "## Evidence Files",
    "",
    ...Object.values(report.evidence.files).flatMap((file) => [
      `- ${file.id}: ${file.exists ? "present" : "missing"}`,
      `  - Resolved path: ${file.resolvedPath}`,
      `  - SHA-256: ${file.digest ?? "missing"}`,
    ]),
    "",
    "## Documentation Snippets",
    "",
    ...report.evidence.snippets.map((snippet) =>
      `- ${snippet.id}: ${snippet.matched ? "matched" : "missing"}`,
    ),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(report.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(report.nextActions, "No next actions."),
    "",
  ].join("\n");
}
