import {
  renderEntries,
  renderList,
} from "./liveProbeReportUtils.js";
import type {
  JavaMiniKvRouteCatalogCleanupExtendedRunFinalCloseout,
} from "./javaMiniKvRouteCatalogCleanupExtendedRunFinalCloseout.js";

export function renderJavaMiniKvRouteCatalogCleanupExtendedRunFinalCloseoutMarkdown(
  closeout: JavaMiniKvRouteCatalogCleanupExtendedRunFinalCloseout,
): string {
  return [
    "# Java / mini-kv route catalog cleanup extended run final closeout",
    "",
    `- Service: ${closeout.service}`,
    `- Generated at: ${closeout.generatedAt}`,
    `- Profile version: ${closeout.profileVersion}`,
    `- Closeout state: ${closeout.closeoutState}`,
    `- Ready: ${closeout.readyForRouteCatalogCleanupExtendedRunFinalCloseout}`,
    `- Active Node version: ${closeout.activeNodeVersion}`,
    `- Source Node version: ${closeout.sourceNodeVersion}`,
    `- Execution allowed: ${closeout.executionAllowed}`,
    "",
    "## Cross-Project Mode",
    "",
    ...renderEntries(closeout.crossProjectMode),
    "",
    "## Completed Follow-Up Versions",
    "",
    ...closeout.completedFollowUpVersions.map((version) => `- ${version}`),
    "",
    "## Final Gate",
    "",
    ...renderEntries(closeout.finalGate),
    "",
    "## Route Quality",
    "",
    ...renderEntries(closeout.routeQuality),
    "",
    "## CI Observation",
    "",
    ...renderEntries(closeout.ciObservation),
    "",
    "## Route Catalog",
    "",
    ...renderEntries(closeout.routeCatalog),
    "",
    "## Summary",
    "",
    ...renderEntries(closeout.summary),
    "",
    "## Checks",
    "",
    ...renderEntries(closeout.checks),
    "",
    "## Next Actions",
    "",
    ...renderList(closeout.nextActions, "No next actions."),
    "",
  ].join("\n");
}
