import {
  renderEntries,
  renderList,
} from "./liveProbeReportUtils.js";
import type {
  JavaMiniKvRouteCatalogCleanupConsumerReadinessBatchCloseoutReport,
} from "./javaMiniKvRouteCatalogCleanupConsumerReadinessBatchCloseoutReport.js";

export function renderJavaMiniKvRouteCatalogCleanupConsumerReadinessBatchCloseoutReportMarkdown(
  report: JavaMiniKvRouteCatalogCleanupConsumerReadinessBatchCloseoutReport,
): string {
  return [
    "# Java / mini-kv route catalog cleanup consumer readiness batch closeout",
    "",
    `- Service: ${report.service}`,
    `- Generated at: ${report.generatedAt}`,
    `- Profile version: ${report.profileVersion}`,
    `- Closeout state: ${report.closeoutState}`,
    `- Ready: ${report.readyForRouteCatalogCleanupConsumerReadinessBatchCloseout}`,
    `- Active Node version: ${report.activeNodeVersion}`,
    `- Source Node version: ${report.sourceNodeVersion}`,
    `- Execution allowed: ${report.executionAllowed}`,
    "",
    "## Cross-Project Mode",
    "",
    ...renderEntries(report.crossProjectMode),
    "",
    "## Closed Versions",
    "",
    ...report.closedVersions.map((version) => `- ${version}`),
    "",
    "## Route Catalog",
    "",
    ...renderEntries(report.routeCatalog),
    "",
    "## Source Archive",
    "",
    ...renderEntries(report.sourceArchive),
    "",
    "## Summary",
    "",
    ...renderEntries(report.summary),
    "",
    "## Checks",
    "",
    ...renderEntries(report.checks),
    "",
    "## Files",
    "",
    ...Object.values(report.files).flatMap((file) => [
      `- ${file.path}: ${file.exists ? "present" : "missing"}`,
      `  - Size bytes: ${file.sizeBytes}`,
      `  - SHA-256: ${file.sha256 ?? "missing"}`,
    ]),
    "",
    "## Next Actions",
    "",
    ...renderList(report.nextActions, "No next actions."),
    "",
  ].join("\n");
}
