import {
  renderEntries,
  renderList,
} from "./liveProbeReportUtils.js";
import type {
  JavaMiniKvRouteCatalogCleanupCiCatalogHealthCloseout,
} from "./javaMiniKvRouteCatalogCleanupCiCatalogHealthCloseout.js";

export function renderJavaMiniKvRouteCatalogCleanupCiCatalogHealthCloseoutMarkdown(
  closeout: JavaMiniKvRouteCatalogCleanupCiCatalogHealthCloseout,
): string {
  return [
    "# Java / mini-kv route catalog cleanup CI/catalog health closeout",
    "",
    `- Service: ${closeout.service}`,
    `- Generated at: ${closeout.generatedAt}`,
    `- Profile version: ${closeout.profileVersion}`,
    `- Closeout state: ${closeout.closeoutState}`,
    `- Ready: ${closeout.readyForRouteCatalogCleanupCiCatalogHealthCloseout}`,
    `- Active Node version: ${closeout.activeNodeVersion}`,
    `- Source Node version: ${closeout.sourceNodeVersion}`,
    `- Execution allowed: ${closeout.executionAllowed}`,
    "",
    "## Cross-Project Mode",
    "",
    ...renderEntries(closeout.crossProjectMode),
    "",
    "## Closed Gate",
    "",
    ...renderEntries(closeout.closedGate),
    "",
    "## Route Quality",
    "",
    ...renderEntries(closeout.routeQuality),
    "",
    "## CI Observation",
    "",
    ...renderEntries(closeout.ciObservation),
    "",
    "## Planned Segment",
    "",
    ...closeout.plannedSegment.map((version) => `- ${version}`),
    "",
    "## Route Catalog",
    "",
    ...renderEntries(closeout.routeCatalog),
    "",
    "## Summary",
    "",
    ...renderEntries(closeout.summary),
    "",
    "## Checks",
    "",
    ...renderEntries(closeout.checks),
    "",
    "## Next Actions",
    "",
    ...renderList(closeout.nextActions, "No next actions."),
    "",
  ].join("\n");
}
