import {
  renderEntries,
  renderList,
} from "./liveProbeReportUtils.js";
import type {
  JavaMiniKvRouteCatalogCleanupLatestEvidenceReport,
} from "./javaMiniKvRouteCatalogCleanupLatestEvidenceReport.js";

export function renderJavaMiniKvRouteCatalogCleanupLatestEvidenceReportMarkdown(
  report: JavaMiniKvRouteCatalogCleanupLatestEvidenceReport,
): string {
  return [
    "# Java / mini-kv route catalog cleanup latest evidence report",
    "",
    `- Service: ${report.service}`,
    `- Generated at: ${report.generatedAt}`,
    `- Profile version: ${report.profileVersion}`,
    `- Report state: ${report.reportState}`,
    `- Ready: ${report.readyForRouteCatalogCleanupLatestEvidenceReport}`,
    `- Active Node version: ${report.activeNodeVersion}`,
    `- Source Node version: ${report.sourceNodeVersion}`,
    `- Execution allowed: ${report.executionAllowed}`,
    "",
    "## Summary",
    "",
    ...renderEntries(report.summary),
    "",
    "## Checks",
    "",
    ...renderEntries(report.checks),
    "",
    "## Java v207 Controller Split",
    "",
    ...renderEntries(report.evidence.javaV207ControllerSplit),
    "",
    "## Java v208 Endpoint Catalog",
    "",
    ...renderEntries(report.evidence.javaV208EndpointCatalog),
    "",
    "## Java v208 Endpoint Catalog Fixture",
    "",
    ...renderEntries(report.evidence.javaV208EndpointCatalogFixture),
    "",
    "## mini-kv v193 Handoff Audit Freeze",
    "",
    ...renderEntries(report.evidence.miniKvV193HandoffAuditFreeze),
    "",
    "## Evidence Files",
    "",
    ...Object.values(report.evidence.files).flatMap((file) => [
      `- ${file.id}: ${file.exists ? "present" : "missing"}`,
      `  - Resolved path: ${file.resolvedPath}`,
      `  - SHA-256: ${file.digest ?? "missing"}`,
    ]),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(report.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(report.nextActions, "No next actions."),
    "",
  ].join("\n");
}
