import {
  renderEntries,
  renderList,
} from "./liveProbeReportUtils.js";
import type {
  JavaMiniKvRouteCatalogCleanupConsumerReadinessEvidenceReport,
} from "./javaMiniKvRouteCatalogCleanupConsumerReadinessEvidenceReport.js";

export function renderJavaMiniKvRouteCatalogCleanupConsumerReadinessEvidenceReportMarkdown(
  report: JavaMiniKvRouteCatalogCleanupConsumerReadinessEvidenceReport,
): string {
  return [
    "# Java / mini-kv route catalog cleanup consumer readiness evidence report",
    "",
    `- Service: ${report.service}`,
    `- Generated at: ${report.generatedAt}`,
    `- Profile version: ${report.profileVersion}`,
    `- Report state: ${report.reportState}`,
    `- Ready: ${report.readyForRouteCatalogCleanupConsumerReadinessEvidenceReport}`,
    `- Active Node version: ${report.activeNodeVersion}`,
    `- Source Node version: ${report.sourceNodeVersion}`,
    `- Execution allowed: ${report.executionAllowed}`,
    "",
    "## Summary",
    "",
    ...renderEntries(report.summary),
    "",
    "## Checks",
    "",
    ...renderEntries(report.checks),
    "",
    "## Java v220 Consumer Evidence Digest",
    "",
    ...renderEntries(report.evidence.javaV220ConsumerEvidenceDigest),
    "",
    "## Java v220 Consumer Evidence Digest Fixture",
    "",
    ...renderEntries(report.evidence.javaV220ConsumerEvidenceDigestFixture),
    "",
    "## Java v221-v224 Consumer Readiness Guards",
    "",
    ...[
      report.evidence.javaV221ConsumerEvidenceDigestSnapshotFreeze,
      report.evidence.javaV222ConsumerEvidenceDigestHistoricalCompatibility,
      report.evidence.javaV223ConsumerEvidenceDigestIntegrity,
      report.evidence.javaV224ConsumerReadinessCompletion,
    ].flatMap((guard) => [
      `- ${guard.version}: ${guard.scope}`,
      `  - status: ${guard.status}`,
      `  - guardCount: ${guard.guardCount}`,
      `  - boundaryRuntimeClosed: ${guard.boundaryRuntimeClosed}`,
    ]),
    "",
    "## mini-kv v202-v209 Versioned Continuity",
    "",
    ...report.evidence.miniKvPostCloseoutReleases.flatMap((release) => [
      `- ${release.releaseVersion}: ${release.status}`,
      `  - previousConsumedReleaseVersion: ${release.previousConsumedReleaseVersion}`,
      `  - sourceFrozenReleaseVersion: ${release.sourceFrozenReleaseVersion}`,
      `  - evidenceDigest: ${release.evidenceDigest}`,
      `  - historicalFixtureCount: ${release.historicalFixtureCount}`,
    ]),
    "",
    "## mini-kv v210 Audit Note",
    "",
    ...renderEntries(report.evidence.miniKvLatestAuditNote),
    "",
    "## Evidence Files",
    "",
    ...Object.values(report.evidence.files).flatMap((file) => [
      `- ${file.id}: ${file.exists ? "present" : "missing"}`,
      `  - Resolved path: ${file.resolvedPath}`,
      `  - SHA-256: ${file.digest ?? "missing"}`,
    ]),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(report.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(report.nextActions, "No next actions."),
    "",
  ].join("\n");
}
