import {
  renderEntries,
  renderList,
} from "./liveProbeReportUtils.js";
import type {
  JavaMiniKvRouteCatalogCleanupFreshBaselineBatchCloseout,
} from "./javaMiniKvRouteCatalogCleanupFreshBaselineBatchCloseout.js";

export function renderJavaMiniKvRouteCatalogCleanupFreshBaselineBatchCloseoutMarkdown(
  closeout: JavaMiniKvRouteCatalogCleanupFreshBaselineBatchCloseout,
): string {
  return [
    "# Java / mini-kv route catalog cleanup fresh baseline batch closeout",
    "",
    `- Service: ${closeout.service}`,
    `- Generated at: ${closeout.generatedAt}`,
    `- Profile version: ${closeout.profileVersion}`,
    `- Closeout state: ${closeout.closeoutState}`,
    `- Ready: ${closeout.readyForRouteCatalogCleanupFreshBaselineBatchCloseout}`,
    `- Active Node version: ${closeout.activeNodeVersion}`,
    `- Source Node version: ${closeout.sourceNodeVersion}`,
    `- Execution allowed: ${closeout.executionAllowed}`,
    "",
    "## Cross-Project Mode",
    "",
    ...renderEntries(closeout.crossProjectMode),
    "",
    "## Closed Versions",
    "",
    ...closeout.closedVersions.map((version) => `- ${version}`),
    "",
    "## Route Catalog",
    "",
    ...renderEntries(closeout.routeCatalog),
    "",
    "## Source Archive",
    "",
    ...renderEntries(closeout.sourceArchive),
    "",
    "## Archive Verification",
    "",
    ...renderEntries(closeout.archiveVerification),
    "",
    "## Summary",
    "",
    ...renderEntries(closeout.summary),
    "",
    "## Checks",
    "",
    ...renderEntries(closeout.checks),
    "",
    "## Files",
    "",
    ...Object.values(closeout.files).flatMap((file) => [
      `- ${file.path}: ${file.exists ? "present" : "missing"}`,
      `  - Size bytes: ${file.sizeBytes}`,
      `  - SHA-256: ${file.sha256 ?? "missing"}`,
    ]),
    "",
    "## Next Actions",
    "",
    ...renderList(closeout.nextActions, "No next actions."),
    "",
  ].join("\n");
}
