import { renderEntries, renderList } from "./liveProbeReportUtils.js";
import type {
  JavaMiniKvRouteCatalogCleanupLatestSiblingLiveSmokePreflightProfile,
} from "./javaMiniKvRouteCatalogCleanupLatestSiblingLiveSmokePreflight.js";

export function renderJavaMiniKvRouteCatalogCleanupLatestSiblingLiveSmokePreflightMarkdown(
  profile: JavaMiniKvRouteCatalogCleanupLatestSiblingLiveSmokePreflightProfile,
): string {
  return [
    "# Java / mini-kv route catalog cleanup latest sibling live smoke preflight",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Preflight state: ${profile.preflightState}`,
    `- Ready for preflight: ${profile.readyForRouteCatalogCleanupLatestSiblingLiveSmokePreflight}`,
    `- Ready for live smoke execution: ${profile.readyForRouteCatalogCleanupLatestSiblingLiveSmokeExecution}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Planned execution version: ${profile.plannedExecutionVersion}`,
    `- Preflight only: ${profile.preflightOnly}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Archive Verification",
    "",
    ...renderEntries(profile.sourceArchiveVerification),
    "",
    "## Live Smoke Window",
    "",
    ...renderEntries(profile.liveSmokeWindow),
    "",
    "## Node Smoke Environment",
    "",
    ...renderEntries(profile.nodeSmokeEnvironment),
    "",
    "## Process Plan",
    "",
    ...profile.processPlan.flatMap((step) => [
      `- ${step.id}`,
      `  - Project: ${step.project}`,
      `  - Owner: ${step.owner}`,
      `  - CWD: ${step.cwd}`,
      `  - Host: ${step.host}`,
      `  - Port: ${step.port}`,
      `  - Start command: ${step.startCommand}`,
      `  - Readiness probe: ${step.readinessProbe}`,
      `  - Stop policy: ${step.stopPolicy}`,
      `  - Cleanup verification: ${step.cleanupVerification}`,
      `  - Fail closed: ${step.failClosedRule}`,
    ]),
    "",
    "## Read Targets",
    "",
    ...profile.readTargets.flatMap((target) => [
      `- ${target.id}`,
      `  - Project: ${target.project}`,
      `  - Protocol: ${target.protocol}`,
      `  - Method or command: ${target.methodOrCommand}`,
      `  - Target: ${target.target}`,
      `  - Expected evidence: ${target.expectedEvidence}`,
      `  - Read only: ${target.readOnly}`,
      `  - Mutates state: ${target.mutatesState}`,
    ]),
    "",
    "## Command Policy",
    "",
    ...renderEntries(profile.commandPolicy),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
