import {
  renderEntries,
  renderList,
} from "./liveProbeReportUtils.js";
import type {
  JavaMiniKvRouteCatalogCleanupCurrentEvidenceReport,
} from "./javaMiniKvRouteCatalogCleanupCurrentEvidenceReport.js";

export function renderJavaMiniKvRouteCatalogCleanupCurrentEvidenceReportMarkdown(
  report: JavaMiniKvRouteCatalogCleanupCurrentEvidenceReport,
): string {
  return [
    "# Java / mini-kv route catalog cleanup current evidence report",
    "",
    `- Service: ${report.service}`,
    `- Generated at: ${report.generatedAt}`,
    `- Profile version: ${report.profileVersion}`,
    `- Report state: ${report.reportState}`,
    `- Ready: ${report.readyForRouteCatalogCleanupCurrentEvidenceReport}`,
    `- Active Node version: ${report.activeNodeVersion}`,
    `- Source Node version: ${report.sourceNodeVersion}`,
    `- Execution allowed: ${report.executionAllowed}`,
    "",
    "## Summary",
    "",
    ...renderEntries(report.summary),
    "",
    "## Checks",
    "",
    ...renderEntries(report.checks),
    "",
    "## Java v211 Consumer Handoff Bundle",
    "",
    ...renderEntries(report.evidence.javaV211ConsumerHandoffBundle),
    "",
    "## Java v211 Consumer Handoff Bundle Fixture",
    "",
    ...renderEntries(report.evidence.javaV211ConsumerHandoffBundleFixture),
    "",
    "## Java v214 Consumer Handoff Bundle Integrity",
    "",
    ...renderEntries(report.evidence.javaV214ConsumerHandoffBundleIntegrity),
    "",
    "## mini-kv v199 Batch Closeout",
    "",
    ...renderEntries(report.evidence.miniKvV199RouteCatalogCleanupBatchCloseout),
    "",
    "## mini-kv v200 Batch Closeout Audit",
    "",
    ...renderEntries(report.evidence.miniKvV200RouteCatalogCleanupBatchCloseoutAudit),
    "",
    "## Evidence Files",
    "",
    ...Object.values(report.evidence.files).flatMap((file) => [
      `- ${file.id}: ${file.exists ? "present" : "missing"}`,
      `  - Resolved path: ${file.resolvedPath}`,
      `  - SHA-256: ${file.digest ?? "missing"}`,
    ]),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(report.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(report.nextActions, "No next actions."),
    "",
  ].join("\n");
}
