import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  DisabledFakeHarnessDeniedRouteAttempt,
  ManagedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessExecutionDeniedRoutePreflightProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessExecutionDeniedRoutePreflightTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessExecutionDeniedRoutePreflightMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessExecutionDeniedRoutePreflightProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver disabled fake harness execution-denied route preflight",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Preflight state: ${profile.preflightState}`,
    `- Ready for execution-denied route preflight: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessExecutionDeniedRoutePreflight}`,
    `- Ready for Java v127 + mini-kv v128 evidence: ${profile.readyForJavaV127MiniKvV128ParallelEvidence}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Fake harness invocation allowed: ${profile.fakeHarnessInvocationAllowed}`,
    "",
    "## Source Node v289",
    "",
    ...renderEntries(profile.sourceNodeV289),
    "",
    "## Execution-Denied Route Preflight",
    "",
    ...renderEntries({
      preflightDigest: profile.executionDeniedRoutePreflight.preflightDigest,
      preflightMode: profile.executionDeniedRoutePreflight.preflightMode,
      sourceSpan: profile.executionDeniedRoutePreflight.sourceSpan,
      routeSurface: profile.executionDeniedRoutePreflight.routeSurface,
      routePath: profile.executionDeniedRoutePreflight.routePath,
      httpMethod: profile.executionDeniedRoutePreflight.httpMethod,
      formatModes: profile.executionDeniedRoutePreflight.formatModes,
      routeRegistered: profile.executionDeniedRoutePreflight.routeRegistered,
      routeReadOnly: profile.executionDeniedRoutePreflight.routeReadOnly,
      routeExecutionDenied: profile.executionDeniedRoutePreflight.routeExecutionDenied,
      approvalGateRequired: profile.executionDeniedRoutePreflight.approvalGateRequired,
      approvalGateSatisfied: profile.executionDeniedRoutePreflight.approvalGateSatisfied,
      fakeHarnessRuntimeImplementationAllowed:
        profile.executionDeniedRoutePreflight.fakeHarnessRuntimeImplementationAllowed,
      fakeHarnessRuntimeInvocationAllowed:
        profile.executionDeniedRoutePreflight.fakeHarnessRuntimeInvocationAllowed,
    }),
    "",
    "## Denial Reasons",
    "",
    ...renderList(profile.executionDeniedRoutePreflight.denialReasons, "No denial reasons."),
    "",
    "## Simulated Denied Route Attempts",
    "",
    ...profile.simulatedRouteAttempts.flatMap(renderAttempt),
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No execution-denied route preflight blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No execution-denied route preflight warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No execution-denied route preflight recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderAttempt(attempt: DisabledFakeHarnessDeniedRouteAttempt): string[] {
  return [
    `- ${attempt.id}`,
    `  - surface: ${attempt.surface}`,
    `  - requestedOperation: ${attempt.requestedOperation}`,
    `  - simulatedOnly: ${attempt.simulatedOnly}`,
    `  - actualExecutionAttempted: ${attempt.actualExecutionAttempted}`,
    `  - denied: ${attempt.denied}`,
    `  - executionAllowed: ${attempt.executionAllowed}`,
    `  - deniedBy: ${attempt.deniedBy}`,
    `  - sourceEvidence: ${attempt.sourceEvidence}`,
  ];
}
