import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionPacketApprovalGateReviewProfile,
  RuntimeExecutionPacketApprovalGateInput,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionPacketApprovalGateReviewTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionPacketApprovalGateReviewMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionPacketApprovalGateReviewProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Approval gate review state: ${profile.approvalGateReviewState}`,
    `- Approval gate decision: ${profile.approvalGateDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for Node v399 runtime execution packet approval gate archive verification: ${profile.readyForNodeV399RuntimeExecutionPacketApprovalGateArchiveVerification}`,
    `- Ready for runtime execution packet: ${profile.readyForRuntimeExecutionPacket}`,
    `- Ready for runtime live-read gate: ${profile.readyForRuntimeLiveReadGate}`,
    `- Runtime execution artifacts complete: ${profile.runtimeExecutionArtifactsComplete}`,
    `- Present runtime execution artifact count: ${profile.presentRuntimeExecutionArtifactCount}`,
    `- Missing runtime execution artifact count: ${profile.missingRuntimeExecutionArtifactCount}`,
    `- Runtime execution packet present: ${profile.runtimeExecutionPacketPresent}`,
    `- Runtime execution packet executable: ${profile.runtimeExecutionPacketExecutable}`,
    `- Runtime gate approval present: ${profile.runtimeGateApprovalPresent}`,
    `- Concrete loopback ports assigned: ${profile.concreteLoopbackPortsAssigned}`,
    `- Execution attempted: ${profile.executionAttempted}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Active shard prototype enabled: ${profile.activeShardPrototypeEnabled}`,
    "",
    "## Source Node v397",
    "",
    ...renderEntries(profile.sourceNodeV397),
    "",
    "## Approval Gate Inputs",
    "",
    ...profile.approvalGateInputs.flatMap(renderApprovalGateInput),
    "",
    "## Approval Gate Review",
    "",
    ...renderEntries(profile.approvalGateReview),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderApprovalGateInput(input: RuntimeExecutionPacketApprovalGateInput): string[] {
  return [
    `- ${input.key}`,
    `  - label: ${input.label}`,
    `  - required: ${input.required}`,
    `  - file: ${JSON.stringify(input.file)}`,
    `  - present: ${input.present}`,
    `  - gateSatisfied: ${input.gateSatisfied}`,
    `  - missingReasonCode: ${input.missingReasonCode}`,
  ];
}
