import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverNoNetworkSafetyFixturePrerequisiteClosureReviewProfile,
  NoNetworkSafetyFixtureClosurePrerequisite,
  SourceNodeV324NoNetworkSafetyFixtureUpstreamEchoVerificationReference,
} from "./managedAuditManualSandboxConnectionCredentialResolverNoNetworkSafetyFixturePrerequisiteClosureReviewTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverNoNetworkSafetyFixturePrerequisiteClosureReviewMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverNoNetworkSafetyFixturePrerequisiteClosureReviewProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver no-network safety fixture prerequisite closure review",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Review state: ${profile.reviewState}`,
    `- Prerequisite closure decision: ${profile.prerequisiteClosureDecision}`,
    `- Ready for closure review: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverNoNetworkSafetyFixturePrerequisiteClosureReview}`,
    `- Active Node review version: ${profile.activeNodeReviewVersion}`,
    `- Ready for abort/rollback semantics contract intake: ${profile.readyForAbortRollbackSemanticsContractIntake}`,
    `- New Java + mini-kv echo requested: ${profile.newJavaMiniKvEchoRequested}`,
    `- Runtime shell implemented: ${profile.runtimeShellImplemented}`,
    `- Runtime shell invocation allowed: ${profile.runtimeShellInvocationAllowed}`,
    `- Network safety fixture executed: ${profile.networkSafetyFixtureExecuted}`,
    `- HTTP request sent: ${profile.httpRequestSent}`,
    `- TCP connection attempted: ${profile.tcpConnectionAttempted}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v324",
    "",
    ...renderSourceNodeV324(profile.sourceNodeV324),
    "",
    "## Closure Review",
    "",
    ...renderEntries({
      reviewDigest: profile.closureReview.reviewDigest,
      reviewMode: profile.closureReview.reviewMode,
      sourceSpan: profile.closureReview.sourceSpan,
      sourceVerificationDigest: profile.closureReview.sourceVerificationDigest,
      completedPrerequisiteCount: profile.closureReview.completedPrerequisiteCount,
      remainingPrerequisiteCount: profile.closureReview.remainingPrerequisiteCount,
      originalPrerequisiteCount: profile.closureReview.originalPrerequisiteCount,
      movedPrerequisiteId: profile.closureReview.movedPrerequisiteId,
      movedFrom: profile.closureReview.movedFrom,
      movedTo: profile.closureReview.movedTo,
      nextConcretePrerequisiteId: profile.closureReview.nextConcretePrerequisiteId,
      nextConcretePrerequisiteContractRequired: profile.closureReview.nextConcretePrerequisiteContractRequired,
      nextNodeVersionSuggested: profile.closureReview.nextNodeVersionSuggested,
      nextJavaVersionRequested: profile.closureReview.nextJavaVersionRequested,
      nextMiniKvVersionRequested: profile.closureReview.nextMiniKvVersionRequested,
      chainContinuationAllowed: profile.closureReview.chainContinuationAllowed,
      runtimeShellStillBlocked: profile.closureReview.runtimeShellStillBlocked,
      closureReason: profile.closureReview.closureReason,
    }),
    "",
    "### Completed Prerequisites",
    "",
    ...renderPrerequisites(profile.closureReview.completedPrerequisites),
    "",
    "### Remaining Prerequisites",
    "",
    ...renderPrerequisites(profile.closureReview.remainingPrerequisites),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No no-network safety fixture prerequisite closure review blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No no-network safety fixture prerequisite closure review warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(
      profile.recommendations,
      "No no-network safety fixture prerequisite closure review recommendations.",
    ),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderSourceNodeV324(
  reference: SourceNodeV324NoNetworkSafetyFixtureUpstreamEchoVerificationReference,
): string[] {
  return renderEntries({
    sourceVersion: reference.sourceVersion,
    profileVersion: reference.profileVersion,
    verificationState: reference.verificationState,
    readyForNoNetworkSafetyFixtureUpstreamEchoVerification:
      reference.readyForNoNetworkSafetyFixtureUpstreamEchoVerification,
    readOnlyUpstreamEchoVerification: reference.readOnlyUpstreamEchoVerification,
    verificationDigest: reference.verificationDigest,
    sourceSpan: reference.sourceSpan,
    sourceNodeV323Ready: reference.sourceNodeV323Ready,
    javaV149EchoReady: reference.javaV149EchoReady,
    miniKvV141ReceiptReady: reference.miniKvV141ReceiptReady,
    upstreamEchoAligned: reference.upstreamEchoAligned,
    noNetworkSafetyFixtureContractAligned: reference.noNetworkSafetyFixtureContractAligned,
    sideEffectBoundariesAligned: reference.sideEffectBoundariesAligned,
    implementationStillBlocked: reference.implementationStillBlocked,
    remainingPrerequisitesAfterV324: reference.remainingPrerequisitesAfterV324,
    contractDigest: reference.contractDigest,
    requiredFieldCount: reference.requiredFieldCount,
    prohibitedFieldCount: reference.prohibitedFieldCount,
    rejectionReasonCount: reference.rejectionReasonCount,
    noGoBoundaryCount: reference.noGoBoundaryCount,
    upstreamEchoRequestCount: reference.upstreamEchoRequestCount,
    sourceProductionBlockerCount: reference.sourceProductionBlockerCount,
  });
}

function renderPrerequisites(prerequisites: NoNetworkSafetyFixtureClosurePrerequisite[]): string[] {
  return renderList(
    prerequisites.map((prerequisite) =>
      `${prerequisite.id}: ${prerequisite.closureState}; requiredBeforeRuntimeShell=${prerequisite.requiredBeforeRuntimeShell}; opensRuntimeShell=${prerequisite.opensRuntimeShell}; evidence=${prerequisite.evidence}`),
    "No prerequisites.",
  );
}
