import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverTestOnlyFakeHarnessPrecheckProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverTestOnlyFakeHarnessPrecheckTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverTestOnlyFakeHarnessPrecheckMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverTestOnlyFakeHarnessPrecheckProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver test-only fake harness precheck",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Precheck state: ${profile.precheckState}`,
    `- Ready for test-only fake harness precheck: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverTestOnlyFakeHarnessPrecheck}`,
    `- Ready for disabled fake harness contract: ${profile.readyForDisabledFakeHarnessContract}`,
    `- Ready for real resolver implementation: ${profile.readyForManagedAuditResolverImplementation}`,
    `- Fake harness runtime enabled: ${profile.fakeHarnessRuntimeEnabled}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v286",
    "",
    ...renderEntries(profile.sourceNodeV286),
    "",
    "## Fake Harness Precheck",
    "",
    ...renderEntries({
      precheckDigest: profile.fakeHarnessPrecheck.precheckDigest,
      precheckMode: profile.fakeHarnessPrecheck.precheckMode,
      sourceSpan: profile.fakeHarnessPrecheck.sourceSpan,
      fakeHarnessName: profile.fakeHarnessPrecheck.fakeHarnessName,
      runtimeToggleName: profile.fakeHarnessPrecheck.runtimeToggleName,
      defaultRuntimeToggleValue: profile.fakeHarnessPrecheck.defaultRuntimeToggleValue,
      fakeHarnessRuntimeEnabled: profile.fakeHarnessPrecheck.fakeHarnessRuntimeEnabled,
      fakeHarnessInvocationAllowed: profile.fakeHarnessPrecheck.fakeHarnessInvocationAllowed,
      testOnlyFakeHarnessExecutionAllowed: profile.fakeHarnessPrecheck.testOnlyFakeHarnessExecutionAllowed,
    }),
    "",
    "## Boundary Summary",
    "",
    ...renderEntries({
      credentialHandleOnly: profile.fakeHarnessPrecheck.credentialBoundary.credentialHandleOnly,
      credentialValueRead: profile.fakeHarnessPrecheck.credentialBoundary.credentialValueRead,
      credentialValueProvided: profile.fakeHarnessPrecheck.credentialBoundary.credentialValueProvided,
      endpointHandleOnly: profile.fakeHarnessPrecheck.endpointBoundary.endpointHandleOnly,
      rawEndpointUrlParsed: profile.fakeHarnessPrecheck.endpointBoundary.rawEndpointUrlParsed,
      rawEndpointUrlRendered: profile.fakeHarnessPrecheck.endpointBoundary.rawEndpointUrlRendered,
      realSecretProviderInstantiated:
        profile.fakeHarnessPrecheck.providerClientBoundary.realSecretProviderInstantiated,
      realResolverClientInstantiated:
        profile.fakeHarnessPrecheck.providerClientBoundary.realResolverClientInstantiated,
      fakeSecretProviderInstantiated:
        profile.fakeHarnessPrecheck.providerClientBoundary.fakeSecretProviderInstantiated,
      fakeResolverClientInstantiated:
        profile.fakeHarnessPrecheck.providerClientBoundary.fakeResolverClientInstantiated,
      externalRequestSent: profile.fakeHarnessPrecheck.networkBoundary.externalRequestSent,
      connectsManagedAudit: profile.fakeHarnessPrecheck.networkBoundary.connectsManagedAudit,
      executionAllowed: profile.fakeHarnessPrecheck.writeBoundary.executionAllowed,
      schemaMigrationExecuted: profile.fakeHarnessPrecheck.writeBoundary.schemaMigrationExecuted,
      approvalLedgerWritten: profile.fakeHarnessPrecheck.writeBoundary.approvalLedgerWritten,
      automaticUpstreamStart: profile.fakeHarnessPrecheck.autoStartBoundary.automaticUpstreamStart,
    }),
    "",
    "## Required Artifacts",
    "",
    ...renderList(profile.fakeHarnessPrecheck.requiredArtifacts, "No required artifacts."),
    "",
    "## Prohibited Actions",
    "",
    ...renderList(profile.fakeHarnessPrecheck.prohibitedActions, "No prohibited actions."),
    "",
    "## Upstream Echo Decision",
    "",
    ...renderEntries(profile.upstreamEchoDecision),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No test-only fake harness precheck blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No test-only fake harness precheck warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No test-only fake harness precheck recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
