import { renderEntries, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyIntakeProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyIntakeTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyIntakeMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyIntakeProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver disabled runtime shell design draft body intake",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Body intake state: ${profile.bodyIntakeState}`,
    `- Body intake decision: ${profile.bodyIntakeDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for v335 body intake: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyIntake}`,
    `- Ready for Node v336 body intake archive verification: ${profile.readyForNodeV336DisabledRuntimeShellDesignDraftBodyIntakeArchiveVerification}`,
    `- Ready for disabled runtime shell design draft: ${profile.readyForDisabledRuntimeShellDesignDraft}`,
    `- Ready for disabled runtime shell design draft outline: ${profile.readyForDisabledRuntimeShellDesignDraftOutline}`,
    `- Ready for runtime shell implementation: ${profile.readyForRuntimeShellImplementation}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Credential value read: ${profile.credentialValueRead}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    `- HTTP request sent: ${profile.httpRequestSent}`,
    `- TCP connection attempted: ${profile.tcpConnectionAttempted}`,
    `- Java SQL execution allowed: ${profile.javaSqlExecutionAllowed}`,
    `- mini-kv write command allowed: ${profile.miniKvWriteCommandAllowed}`,
    `- Automatic upstream start: ${profile.automaticUpstreamStart}`,
    "",
    "## Source Node v334",
    "",
    ...renderEntries({
      archiveVerificationState: profile.sourceNodeV334.archiveVerificationState,
      archiveVerificationDecision: profile.sourceNodeV334.archiveVerificationDecision,
      readyForArchiveVerification: profile.sourceNodeV334.readyForArchiveVerification,
      readyForNodeV335DisabledRuntimeShellDesignDraftBodyIntake:
        profile.sourceNodeV334.readyForNodeV335DisabledRuntimeShellDesignDraftBodyIntake,
      archiveVerificationDigest: profile.sourceNodeV334.archiveVerificationDigest,
      sourceOutlineIntakeDigest: profile.sourceNodeV334.sourceOutlineIntakeDigest,
      sourceChecks: `${profile.sourceNodeV334.sourcePassedCheckCount}/${profile.sourceNodeV334.sourceCheckCount}`,
      archiveFiles: `${profile.sourceNodeV334.presentArchiveFileCount}/${profile.sourceNodeV334.archiveFileCount}`,
      sourceProductionBlockers: profile.sourceNodeV334.sourceProductionBlockerCount,
    }),
    "",
    "## Necessity Proof",
    "",
    ...renderEntries(profile.necessityProof),
    "",
    "## Body Intake",
    "",
    ...renderEntries(profile.bodyIntake),
    "",
    "## Body Section Catalog",
    "",
    ...profile.bodySections.flatMap((section) => [
      `- ${section.id}: ${section.title}`,
      `  - Source outline section: ${section.sourceOutlineSection}`,
      `  - Required evidence: ${section.requiredEvidence}`,
      `  - Allowed: ${section.allowedBodyContent}`,
      `  - Forbidden: ${section.forbiddenBodyContent}`,
      `  - Requires future archive verification: ${section.requiresFutureArchiveVerification}`,
    ]),
    "",
    "## Evidence Catalog",
    "",
    ...profile.evidenceCatalog.map((entry) =>
      `- ${entry.id}: source=${entry.source}; required=${entry.requiredForBodyIntake}; allowsRuntime=${entry.allowsRuntimeBehavior}`),
    "",
    "## Stop Conditions",
    "",
    ...profile.stopConditions.map((entry) => `- ${entry.code}: ${entry.condition}; action=${entry.action}`),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    `- Checks: ${profile.summary.passedCheckCount}/${profile.summary.checkCount}`,
    `- Source Node v334 checks: ${profile.summary.sourceNodeV334PassedCheckCount}/${profile.summary.sourceNodeV334CheckCount}`,
    `- Source archive files: ${profile.summary.sourcePresentArchiveFileCount}/${profile.summary.sourceArchiveFileCount}`,
    `- Body sections: ${profile.summary.bodySectionCount}`,
    `- Evidence items: ${profile.summary.evidenceItemCount}`,
    `- Stop conditions: ${profile.summary.stopConditionCount}`,
    `- Production blockers: ${profile.summary.productionBlockerCount}`,
    `- Warnings: ${profile.summary.warningCount}`,
    `- Recommendations: ${profile.summary.recommendationCount}`,
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...profile.nextActions.map((item) => `- ${item}`),
    "",
  ].join("\n");
}
