import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionFakeTransportPacketArchiveVerificationProfile,
} from "./managedAuditManualSandboxConnectionFakeTransportPacketArchiveVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionFakeTransportPacketArchiveVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionFakeTransportPacketArchiveVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection fake transport packet archive verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Archive verification state: ${profile.archiveVerificationState}`,
    `- Ready for archive verification: ${profile.readyForManagedAuditManualSandboxConnectionFakeTransportPacketArchiveVerification}`,
    `- Read-only archive verification: ${profile.readOnlyArchiveVerification}`,
    `- Reruns fake transport behavior: ${profile.archiveVerificationRerunsFakeTransportBehavior}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v255",
    "",
    ...renderEntries(profile.sourceNodeV255),
    "",
    "## Archive Verification",
    "",
    ...renderEntries(profile.archiveVerification),
    "",
    "## Archive Files",
    "",
    ...profile.archivedEvidence.files.map(
      (file) => `- ${file.id}: ${file.workspacePath} exists=${file.exists} sizeBytes=${file.sizeBytes} digest=${file.digest ?? "missing"}`,
    ),
    "",
    "## Snippet Matches",
    "",
    ...profile.archivedEvidence.snippetMatches.map(
      (snippet) => `- ${snippet.id}: ${snippet.workspacePath} matched=${snippet.matched}`,
    ),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No fake transport packet archive verification blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No fake transport packet archive verification warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No fake transport packet archive verification recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
