import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  HumanApprovalArtifactReviewGovernanceStopPrerequisite,
  ManagedAuditManualSandboxConnectionCredentialResolverHumanApprovalArtifactReviewGovernanceStopPrerequisiteClosureDecisionProfile,
  SourceNodeV311HumanApprovalArtifactReviewPostEchoDecisionUpstreamEchoVerificationReference,
} from "./managedAuditManualSandboxConnectionCredentialResolverHumanApprovalArtifactReviewGovernanceStopPrerequisiteClosureDecisionTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverHumanApprovalArtifactReviewGovernanceStopPrerequisiteClosureDecisionMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverHumanApprovalArtifactReviewGovernanceStopPrerequisiteClosureDecisionProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver human approval artifact review governance stop prerequisite closure decision",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Decision state: ${profile.decisionState}`,
    `- Governance chain decision: ${profile.governanceChainDecision}`,
    `- Ready for closure decision: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverHumanApprovalArtifactReviewGovernanceStopPrerequisiteClosureDecision}`,
    `- Active Node decision version: ${profile.activeNodeDecisionVersion}`,
    `- Ready for new Java + mini-kv echo request: ${profile.readyForNewJavaMiniKvEchoRequest}`,
    `- New Java + mini-kv echo requested: ${profile.newJavaMiniKvEchoRequested}`,
    `- Runtime shell implemented: ${profile.runtimeShellImplemented}`,
    `- Runtime shell invocation allowed: ${profile.runtimeShellInvocationAllowed}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v311",
    "",
    ...renderSourceNodeV311(profile.sourceNodeV311),
    "",
    "## Closure Decision",
    "",
    ...renderEntries({
      decisionDigest: profile.closureDecision.decisionDigest,
      decisionMode: profile.closureDecision.decisionMode,
      sourceSpan: profile.closureDecision.sourceSpan,
      sourceVerificationDigest: profile.closureDecision.sourceVerificationDigest,
      completedPrerequisiteCount: profile.closureDecision.completedPrerequisiteCount,
      remainingPrerequisiteCount: profile.closureDecision.remainingPrerequisiteCount,
      originalPrerequisiteCount: profile.closureDecision.originalPrerequisiteCount,
      noGoConditionCount: profile.closureDecision.noGoConditionCount,
      chainContinuationAllowed: profile.closureDecision.chainContinuationAllowed,
      nextConcretePrerequisiteContractRequired: profile.closureDecision.nextConcretePrerequisiteContractRequired,
      nextJavaVersionRequested: profile.closureDecision.nextJavaVersionRequested,
      nextMiniKvVersionRequested: profile.closureDecision.nextMiniKvVersionRequested,
      nextNodeVersionSuggested: profile.closureDecision.nextNodeVersionSuggested,
      pauseReason: profile.closureDecision.pauseReason,
    }),
    "",
    "### Completed Prerequisites",
    "",
    ...renderPrerequisites(profile.closureDecision.completedPrerequisites),
    "",
    "### Remaining Prerequisites",
    "",
    ...renderPrerequisites(profile.closureDecision.remainingPrerequisites),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No governance stop prerequisite closure decision blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No governance stop prerequisite closure decision warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No governance stop prerequisite closure decision recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderSourceNodeV311(
  reference: SourceNodeV311HumanApprovalArtifactReviewPostEchoDecisionUpstreamEchoVerificationReference,
): string[] {
  return renderEntries({
    sourceVersion: reference.sourceVersion,
    profileVersion: reference.profileVersion,
    verificationState: reference.verificationState,
    readyForPostEchoDecisionUpstreamEchoVerification: reference.readyForPostEchoDecisionUpstreamEchoVerification,
    readOnlyUpstreamEchoVerification: reference.readOnlyUpstreamEchoVerification,
    verificationDigest: reference.verificationDigest,
    sourceSpan: reference.sourceSpan,
    upstreamEchoAligned: reference.upstreamEchoAligned,
    decisionGateContractAligned: reference.decisionGateContractAligned,
    sideEffectBoundariesAligned: reference.sideEffectBoundariesAligned,
    implementationStillBlocked: reference.implementationStillBlocked,
    originalPrerequisiteCount: reference.originalPrerequisiteCount,
    originalMissingPrerequisiteCount: reference.originalMissingPrerequisiteCount,
    noGoConditionCount: reference.noGoConditionCount,
    sourceProductionBlockerCount: reference.sourceProductionBlockerCount,
    sourceWarningCount: reference.sourceWarningCount,
    sourceRecommendationCount: reference.sourceRecommendationCount,
  });
}

function renderPrerequisites(prerequisites: HumanApprovalArtifactReviewGovernanceStopPrerequisite[]): string[] {
  return renderList(
    prerequisites.map((prerequisite) =>
      `${prerequisite.id}: ${prerequisite.closureState}; requiredBeforeRuntimeShell=${prerequisite.requiredBeforeRuntimeShell}; opensRuntimeShell=${prerequisite.opensRuntimeShell}; evidence=${prerequisite.evidence}`),
    "No prerequisites.",
  );
}
