import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ApprovalPrerequisiteArtifactIntakePlan,
  ManagedAuditManualSandboxConnectionCredentialResolverApprovalPrerequisiteArtifactIntakePlanProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverApprovalPrerequisiteArtifactIntakePlanTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverApprovalPrerequisiteArtifactIntakePlanMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverApprovalPrerequisiteArtifactIntakePlanProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver approval prerequisite artifact intake plan",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Plan state: ${profile.planState}`,
    `- Runtime shell chain decision: ${profile.runtimeShellChainDecision}`,
    `- Ready for artifact intake plan: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverApprovalPrerequisiteArtifactIntakePlan}`,
    `- Ready for parallel Java v142 + mini-kv v135 echo: ${profile.readyForParallelJavaV142MiniKvV135Echo}`,
    `- Runtime shell implemented: ${profile.runtimeShellImplemented}`,
    `- Runtime shell invocation allowed: ${profile.runtimeShellInvocationAllowed}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v305",
    "",
    ...renderEntries(profile.sourceNodeV305),
    "",
    "## Artifact Intake Plan",
    "",
    ...renderArtifactIntakePlan(profile.artifactIntakePlan),
    "",
    "## Necessity Proof",
    "",
    ...renderEntries(profile.necessityProof),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No approval prerequisite artifact intake blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No approval prerequisite artifact intake warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No approval prerequisite artifact intake recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderArtifactIntakePlan(plan: ApprovalPrerequisiteArtifactIntakePlan): string[] {
  return [
    ...renderEntries({
      artifactDigest: plan.artifactDigest,
      artifactName: plan.artifactName,
      artifactVersion: plan.artifactVersion,
      intakeMode: plan.intakeMode,
      sourceSpan: plan.sourceSpan,
      purpose: plan.purpose,
      requiredFieldCount: plan.requiredFieldCount,
      prohibitedFieldCount: plan.prohibitedFieldCount,
      rejectionReasonCount: plan.rejectionReasonCount,
      noGoBoundaryCount: plan.noGoBoundaryCount,
      javaMiniKvEchoCanRunInParallel: plan.javaMiniKvEchoCanRunInParallel,
      implementationStillBlocked: plan.implementationStillBlocked,
    }),
    "",
    "### Required Fields",
    "",
    ...renderList(
      plan.requiredFields.map((field) =>
        `${field.id}: source=${field.source}; shape=${field.acceptedShape}; purpose=${field.purpose}`),
      "No required artifact fields.",
    ),
    "",
    "### Prohibited Fields",
    "",
    ...renderList(
      plan.prohibitedFields.map((field) => `${field.id}: rejection=${field.rejectionCode}; reason=${field.reason}`),
      "No prohibited artifact fields.",
    ),
    "",
    "### Rejection Reasons",
    "",
    ...renderList(
      plan.rejectionReasons.map((reason) => `${reason.code}: ${reason.source}; ${reason.message}`),
      "No rejection reasons.",
    ),
    "",
    "### No-Go Boundaries",
    "",
    ...renderList(
      plan.noGoBoundaries.map((boundary) => `${boundary.id}: allowed=${boundary.allowed}; ${boundary.message}`),
      "No no-go boundaries.",
    ),
    "",
    "### Upstream Echo Requests",
    "",
    ...renderList(
      plan.upstreamEchoRequests.map((request) =>
        `${request.version}: project=${request.project}; parallel=${request.canRunInParallel}; readOnly=${request.mustRemainReadOnly}; ${request.requestedEcho}`),
      "No upstream echo requests.",
    ),
  ];
}
