import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  JavaV146CredentialHandleApprovalContractIntakeEchoReference,
  ManagedAuditManualSandboxConnectionCredentialResolverCredentialHandleApprovalContractUpstreamEchoVerificationProfile,
  MiniKvV139CredentialHandleApprovalContractIntakeNonParticipationReceiptReference,
  SourceNodeV317CredentialHandleApprovalContractIntakeReference,
} from "./managedAuditManualSandboxConnectionCredentialResolverCredentialHandleApprovalContractUpstreamEchoVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverCredentialHandleApprovalContractUpstreamEchoVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverCredentialHandleApprovalContractUpstreamEchoVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver credential handle approval contract upstream echo verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Verification state: ${profile.verificationState}`,
    `- Runtime shell chain decision: ${profile.runtimeShellChainDecision}`,
    `- Ready for verification: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverCredentialHandleApprovalContractUpstreamEchoVerification}`,
    `- Active Node verification version: ${profile.activeNodeVerificationVersion}`,
    `- Runtime shell implemented: ${profile.runtimeShellImplemented}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Credential value read: ${profile.credentialValueRead}`,
    "",
    "## Source Node v317",
    "",
    ...renderSourceNodeV317(profile.sourceNodeV317),
    "",
    "## Java v146 Echo",
    "",
    ...renderJavaV146(profile.upstreamEvidence.javaV146),
    "",
    "## mini-kv v139 Receipt",
    "",
    ...renderMiniKvV139(profile.upstreamEvidence.miniKvV139),
    "",
    "## Echo Verification",
    "",
    ...renderEntries(profile.echoVerification),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No credential handle approval contract upstream echo verification blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No credential handle approval contract upstream echo verification warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No credential handle approval contract upstream echo verification recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderSourceNodeV317(reference: SourceNodeV317CredentialHandleApprovalContractIntakeReference): string[] {
  return renderEntries({
    sourceVersion: reference.sourceVersion,
    profileVersion: reference.profileVersion,
    contractState: reference.contractState,
    readyForCredentialHandleApprovalContractIntake: reference.readyForCredentialHandleApprovalContractIntake,
    contractDigest: reference.contractDigest,
    targetPrerequisiteId: reference.targetPrerequisiteId,
    nextJavaVersion: reference.nextJavaVersion,
    nextMiniKvVersion: reference.nextMiniKvVersion,
    nextNodeVerificationVersion: reference.nextNodeVerificationVersion,
    readyForParallelJavaV146MiniKvV139Echo: reference.readyForParallelJavaV146MiniKvV139Echo,
    requiredFieldIds: reference.requiredFieldIds,
    prohibitedFieldIds: reference.prohibitedFieldIds,
    rejectionReasonCodes: reference.rejectionReasonCodes,
    noGoBoundaryIds: reference.noGoBoundaryIds,
    upstreamEchoRequestVersions: reference.upstreamEchoRequestVersions,
    runtimeShellImplemented: reference.runtimeShellImplemented,
    executionAllowed: reference.executionAllowed,
    connectsManagedAudit: reference.connectsManagedAudit,
    credentialValueRead: reference.credentialValueRead,
    rawEndpointUrlParsed: reference.rawEndpointUrlParsed,
    externalRequestSent: reference.externalRequestSent,
  });
}

function renderJavaV146(reference: JavaV146CredentialHandleApprovalContractIntakeEchoReference): string[] {
  return [
    ...renderEntries({
      sourceVersion: reference.sourceVersion,
      receiptVersion: reference.receiptVersion,
      echoMode: reference.echoMode,
      sourceSpan: reference.sourceSpan,
      nextNodeVersion: reference.nextNodeVersion,
      expectedProfileVersion: reference.expectedProfileVersion,
      evidencePresent: reference.evidencePresent,
      verificationDocumented: reference.verificationDocumented,
      echoesNodeV317Plan: reference.echoesNodeV317Plan,
      readyForNodeV318: reference.readyForNodeV318,
      credentialHandleContractEchoed: reference.credentialHandleContractEchoed,
      sideEffectBoundariesClosed: reference.sideEffectBoundariesClosed,
    }),
    "",
    "### Evidence Files",
    "",
    ...renderList(
      reference.evidenceFiles.map((file) => `${file.id}: exists=${file.exists}; digest=${file.digest}; resolved=${file.resolvedPath}`),
      "No Java v146 evidence files.",
    ),
  ];
}

function renderMiniKvV139(reference: MiniKvV139CredentialHandleApprovalContractIntakeNonParticipationReceiptReference): string[] {
  return [
    ...renderEntries({
      sourceVersion: reference.sourceVersion,
      receiptVersion: reference.receiptVersion,
      releaseVersion: reference.releaseVersion,
      consumerHint: reference.consumerHint,
      receiptDigest: reference.receiptDigest,
      evidencePresent: reference.evidencePresent,
      verificationDocumented: reference.verificationDocumented,
      echoesNodeV317Plan: reference.echoesNodeV317Plan,
      readyForNodeV318: reference.readyForNodeV318,
      sourceNodeV317ProfileVersion: reference.sourceNodeV317ProfileVersion,
      sourceNodeV317ContractState: reference.sourceNodeV317ContractState,
      sourceNodeV317ContractDigest: reference.sourceNodeV317ContractDigest,
      requiredFieldCount: reference.requiredFieldCount,
      prohibitedFieldCount: reference.prohibitedFieldCount,
      rejectionReasonCount: reference.rejectionReasonCount,
      noGoBoundaryCount: reference.noGoBoundaryCount,
      upstreamEchoRequestCount: reference.upstreamEchoRequestCount,
      nonParticipationReceiptOnly: reference.nonParticipationReceiptOnly,
      sideEffectBoundariesClosed: reference.sideEffectBoundariesClosed,
    }),
    "",
    "### Evidence Files",
    "",
    ...renderList(
      reference.evidenceFiles.map((file) => `${file.id}: exists=${file.exists}; digest=${file.digest}; resolved=${file.resolvedPath}`),
      "No mini-kv v139 evidence files.",
    ),
  ];
}
