import { renderEntries } from "./liveProbeReportUtils.js";
import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyEnvelope,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyEnvelopeSlot,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyEnvelopeTypes.js";

export function renderControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyEnvelopeMarkdown(
  envelope: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyEnvelope,
): string {
  return [
    "# Controlled read-only shard preview live read-only window operator evidence value supply envelope",
    "",
    `- Value supply envelope version: ${envelope.valueSupplyEnvelopeVersion}`,
    `- Source fresh sibling intake version: ${envelope.sourceFreshSiblingIntakeVersion}`,
    `- Java value draft evidence version: ${envelope.javaValueDraftEvidenceVersion}`,
    `- Java value draft response version: ${envelope.javaValueDraftResponseVersion}`,
    `- mini-kv value draft evidence version: ${envelope.miniKvValueDraftEvidenceVersion}`,
    `- Envelope state: ${envelope.envelopeState}`,
    `- Ready for value supply envelope review: ${envelope.readyForValueSupplyEnvelopeReview}`,
    `- Ready for operator value supply: ${envelope.readyForOperatorValueSupply}`,
    `- Ready for evidence import: ${envelope.readyForEvidenceImport}`,
    `- Ready for manual evidence entry: ${envelope.readyForManualEvidenceEntry}`,
    `- Ready for live execution: ${envelope.readyForLiveExecution}`,
    `- Ready for production execution: ${envelope.readyForProductionExecution}`,
    `- Envelope slot count: ${envelope.envelopeSlotCount}`,
    `- Java evidence slot count: ${envelope.javaEvidenceSlotCount}`,
    `- mini-kv evidence slot count: ${envelope.miniKvEvidenceSlotCount}`,
    `- Node fresh sibling intake slot count: ${envelope.nodeFreshSiblingIntakeSlotCount}`,
    `- Evidence files present: ${envelope.presentFileCount}/${envelope.fileCount}`,
    `- Evidence snippets matched: ${envelope.matchedSnippetCount}/${envelope.snippetCount}`,
    `- Historical fixture resolved file count: ${envelope.historicalFixtureResolvedFileCount}`,
    `- Supplied value count: ${envelope.suppliedValueCount}`,
    `- Accepted value count: ${envelope.acceptedValueCount}`,
    `- Imported value count: ${envelope.importedValueCount}`,
    `- Passed gates: ${envelope.passedGateCount}/${envelope.gateCount}`,
    `- Imports runtime payload: ${envelope.importsRuntimePayload}`,
    `- Accepts synthetic evidence: ${envelope.acceptsSyntheticEvidence}`,
    `- Contains secret value: ${envelope.containsSecretValue}`,
    `- Value supply envelope digest: ${envelope.valueSupplyEnvelopeDigest}`,
    "",
    "## Gates",
    ...renderEntries(envelope.gates),
    "",
    "## Evidence Files",
    ...Object.values(envelope.files).flatMap((file) => [
      `### ${file.id}`,
      `- Path: ${file.path}`,
      `- Resolved path: ${file.resolvedPath}`,
      `- Exists: ${file.exists}`,
      `- Size bytes: ${file.sizeBytes}`,
      `- Digest: ${file.digest ?? "none"}`,
      "",
    ]),
    "## Snippets",
    ...envelope.snippets.map((snippet) =>
      `- ${snippet.id}: matched=${snippet.matched}, resolvedPath=${snippet.resolvedPath}`),
    "",
    "## Slots",
    ...envelope.slots.flatMap(renderSlot),
    "## Blocked Reasons",
    ...(envelope.blockedReasonCodes.length === 0
      ? ["- none"]
      : envelope.blockedReasonCodes.map((reason) => `- ${reason}`)),
  ].join("\n");
}

function renderSlot(
  slot: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyEnvelopeSlot,
): string[] {
  return [
    `### ${slot.order}. ${slot.nodeVersion} ${slot.code}`,
    `- Kind: ${slot.kind}`,
    `- Project: ${slot.project}`,
    `- Scope: ${slot.scope}`,
    `- Source fresh sibling intake slot: ${slot.sourceFreshSiblingIntakeSlotCode}`,
    `- Source fresh sibling intake node version: ${slot.sourceFreshSiblingIntakeNodeVersion}`,
    `- Source fresh sibling intake slot ready: ${slot.sourceFreshSiblingIntakeSlotReady}`,
    `- Evidence file id: ${slot.evidenceFileId}`,
    `- Evidence snippet id: ${slot.evidenceSnippetId}`,
    `- Evidence file present: ${slot.evidenceFilePresent}`,
    `- Evidence snippet matched: ${slot.evidenceSnippetMatched}`,
    `- Evidence resolved from historical fixture: ${slot.evidenceResolvedFromHistoricalFixture}`,
    `- Evidence expectation: ${slot.evidenceExpectation}`,
    `- Value draft evidence version: ${slot.valueDraftEvidenceVersion}`,
    `- Envelope field names: ${slot.envelopeFieldNames.join(", ")}`,
    `- Envelope value state: ${slot.envelopeValueState}`,
    `- Value supply policy: ${slot.valueSupplyPolicy}`,
    `- Missing value policy: ${slot.missingValuePolicy}`,
    `- Supplied value count: ${slot.suppliedValueCount}`,
    `- Accepted value count: ${slot.acceptedValueCount}`,
    `- Imported value count: ${slot.importedValueCount}`,
    `- Value supply adapter enabled: ${slot.valueSupplyAdapterEnabled}`,
    `- Ready for value supply envelope review: ${slot.readyForValueSupplyEnvelopeReview}`,
    `- Ready for operator value supply: ${slot.readyForOperatorValueSupply}`,
    `- Ready for evidence import: ${slot.readyForEvidenceImport}`,
    `- Ready for manual evidence entry: ${slot.readyForManualEvidenceEntry}`,
    `- Ready for live execution: ${slot.readyForLiveExecution}`,
    `- Ready for production execution: ${slot.readyForProductionExecution}`,
    `- Imports runtime payload: ${slot.importsRuntimePayload}`,
    `- Accepts synthetic evidence: ${slot.acceptsSyntheticEvidence}`,
    `- Contains secret value: ${slot.containsSecretValue}`,
    `- Writes allowed: ${slot.writesAllowed}`,
    `- Automatic service start: ${slot.automaticServiceStart}`,
    `- Starts services: ${slot.startsServices}`,
    `- Mutates sibling state: ${slot.mutatesSiblingState}`,
    "",
  ];
}
