import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverImplementationPlanUpstreamEchoVerificationProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverImplementationPlanUpstreamEchoVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverImplementationPlanUpstreamEchoVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverImplementationPlanUpstreamEchoVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver implementation plan upstream echo verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Verification state: ${profile.verificationState}`,
    `- Ready for upstream echo verification: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverImplementationPlanUpstreamEchoVerification}`,
    `- Original expected Node verification: ${profile.originalExpectedNodeVerificationVersion}`,
    `- Executed as: ${profile.executedAsNodeVersion}`,
    `- Ready for real resolver implementation: ${profile.readyForManagedAuditResolverImplementation}`,
    `- Ready for test-only fake harness precheck: ${profile.readyForTestOnlyFakeHarnessPrecheck}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Version Offset",
    "",
    profile.nodeVersionOffsetReason,
    "",
    "## Source Node v283",
    "",
    ...renderEntries({
      profileVersion: profile.sourceNodeV283.profileVersion,
      planState: profile.sourceNodeV283.planState,
      readyForImplementationPlanDraft: profile.sourceNodeV283.readyForImplementationPlanDraft,
      readyForJavaV121MiniKvV126Echo: profile.sourceNodeV283.readyForJavaV121MiniKvV126Echo,
      planDigest: profile.sourceNodeV283.planDigest,
      reviewDigest: profile.sourceNodeV283.reviewDigest,
      interfaceBoundaryCount: profile.sourceNodeV283.interfaceBoundaryCount,
      requiredArtifactCount: profile.sourceNodeV283.requiredArtifactCount,
      prohibitedActionCount: profile.sourceNodeV283.prohibitedActionCount,
      checkCount: profile.sourceNodeV283.checkCount,
      passedCheckCount: profile.sourceNodeV283.passedCheckCount,
    }),
    "",
    "## Java v121 Echo",
    "",
    ...renderEntries({
      evidencePresent: profile.upstreamEchoes.javaV121.evidencePresent,
      verificationDocumented: profile.upstreamEchoes.javaV121.verificationDocumented,
      receiptDigest: profile.upstreamEchoes.javaV121.receiptDigest,
      planEchoMode: profile.upstreamEchoes.javaV121.planEchoMode,
      sourceSpan: profile.upstreamEchoes.javaV121.sourceSpan,
      originalExpectedNodeVerificationVersion:
        profile.upstreamEchoes.javaV121.originalExpectedNodeVerificationVersion,
      javaPlanDigestRequirementNamed: profile.upstreamEchoes.javaV121.javaPlanDigestRequirementNamed,
      concretePlanDigestValueEchoed: profile.upstreamEchoes.javaV121.concretePlanDigestValueEchoed,
      proofClaimCount: profile.upstreamEchoes.javaV121.proofClaimCount,
      nodeVerificationActionCount: profile.upstreamEchoes.javaV121.nodeVerificationActionCount,
    }),
    "",
    "## mini-kv v126 Receipt",
    "",
    ...renderEntries({
      evidencePresent: profile.upstreamEchoes.miniKvV126.evidencePresent,
      verificationDocumented: profile.upstreamEchoes.miniKvV126.verificationDocumented,
      receiptDigest: profile.upstreamEchoes.miniKvV126.receiptDigest,
      releaseVersion: profile.upstreamEchoes.miniKvV126.releaseVersion,
      consumerHint: profile.upstreamEchoes.miniKvV126.consumerHint,
      sourcePlanState: profile.upstreamEchoes.miniKvV126.sourcePlanState,
      planDigest: profile.upstreamEchoes.miniKvV126.planDigest,
      reviewDigest: profile.upstreamEchoes.miniKvV126.reviewDigest,
      readOnly: profile.upstreamEchoes.miniKvV126.readOnly,
      executionAllowed: profile.upstreamEchoes.miniKvV126.executionAllowed,
      connectsManagedAudit: profile.upstreamEchoes.miniKvV126.connectsManagedAudit,
      managedAuditStorageBackend: profile.upstreamEchoes.miniKvV126.managedAuditStorageBackend,
    }),
    "",
    "## Echo Verification",
    "",
    ...renderEntries(profile.echoVerification),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No credential resolver implementation plan upstream echo blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No credential resolver implementation plan upstream echo warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No credential resolver implementation plan upstream echo recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
