import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvDeclaredOperatorLifecycleRuntimeExecutionArtifactIntakePreflightProfile,
  RuntimeExecutionArtifactIntakePreflightFileReference,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvDeclaredOperatorLifecycleRuntimeExecutionArtifactIntakePreflightTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvDeclaredOperatorLifecycleRuntimeExecutionArtifactIntakePreflightMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvDeclaredOperatorLifecycleRuntimeExecutionArtifactIntakePreflightProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Intake preflight state: ${profile.intakePreflightState}`,
    `- Intake decision: ${profile.intakeDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for Node v395 archive verification: ${profile.readyForNodeV395ArchiveVerification}`,
    `- Ready for runtime execution packet: ${profile.readyForRuntimeExecutionPacket}`,
    `- Ready for runtime live-read gate: ${profile.readyForRuntimeLiveReadGate}`,
    `- Artifact intake preflight only: ${profile.artifactIntakePreflightOnly}`,
    `- Runtime execution artifacts complete: ${profile.runtimeExecutionArtifactsComplete}`,
    `- Present runtime execution artifact count: ${profile.presentRuntimeExecutionArtifactCount}`,
    `- Missing runtime execution artifact count: ${profile.missingRuntimeExecutionArtifactCount}`,
    `- Runtime execution packet present: ${profile.runtimeExecutionPacketPresent}`,
    `- Runtime execution packet executable: ${profile.runtimeExecutionPacketExecutable}`,
    `- Runtime gate approval present: ${profile.runtimeGateApprovalPresent}`,
    `- Concrete loopback ports assigned: ${profile.concreteLoopbackPortsAssigned}`,
    `- Execution attempted: ${profile.executionAttempted}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Stops Java service: ${profile.stopsJavaService}`,
    `- Stops mini-kv service: ${profile.stopsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Active shard prototype enabled: ${profile.activeShardPrototypeEnabled}`,
    "",
    "## Source Node v393",
    "",
    ...renderEntries(profile.sourceNodeV393),
    "",
    "## Replay From Frozen Evidence",
    "",
    ...renderEntries(profile.replay),
    "",
    "## Sibling Workspace Snapshot",
    "",
    ...renderEntries(profile.siblingWorkspaceSnapshot),
    "",
    "## Runtime Execution Artifact Requirements",
    "",
    ...profile.artifactRequirements.flatMap((artifact) => [
      `- ${artifact.key}: present=${artifact.present}; source=${artifact.source}; missingReasonCode=${artifact.missingReasonCode}`,
      ...artifact.candidatePaths.map((file) =>
        `  - ${file.path}: exists=${file.exists}; bytes=${file.byteLength}; digest=${file.digest}`),
    ]),
    "",
    "## Artifact Intake Preflight",
    "",
    ...renderEntries(profile.artifactIntakePreflight),
    "",
    "## Source Archive References",
    "",
    ...Object.values(profile.sourceArchiveReferences)
      .filter(isFileReference)
      .map((file) => `- ${file.path}: exists=${file.exists}; bytes=${file.byteLength}; digest=${file.digest}`),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function isFileReference(value: unknown): value is RuntimeExecutionArtifactIntakePreflightFileReference {
  return typeof value === "object" && value !== null && "path" in value && "exists" in value;
}
