import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionFakeTransportPacketUpstreamEchoVerificationProfile,
} from "./managedAuditManualSandboxConnectionFakeTransportPacketUpstreamEchoVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionFakeTransportPacketUpstreamEchoVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionFakeTransportPacketUpstreamEchoVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection fake transport packet upstream echo verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Verification state: ${profile.verificationState}`,
    `- Ready for upstream echo verification: ${profile.readyForManagedAuditManualSandboxConnectionFakeTransportPacketUpstreamEchoVerification}`,
    `- Ready for sandbox adapter connection: ${profile.readyForManagedAuditSandboxAdapterConnection}`,
    "",
    "## Source Node v255",
    "",
    ...renderEntries(profile.sourceNodeV255),
    "",
    "## Source Node v256",
    "",
    ...renderEntries(profile.sourceNodeV256),
    "",
    "## Java v103 Echo",
    "",
    ...renderEntries(profile.upstreamEchoes.javaV103),
    "",
    "## mini-kv v112 Non-Participation",
    "",
    ...renderEntries(profile.upstreamEchoes.miniKvV112),
    "",
    "## Echo Verification",
    "",
    ...renderEntries(profile.echoVerification),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No fake transport packet upstream echo verification blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No fake transport packet upstream echo verification warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No fake transport packet upstream echo verification recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
