import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionCanonicalApprovalInputPrecheckIntakeProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionCanonicalApprovalInputPrecheckIntakeTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionCanonicalApprovalInputPrecheckIntakeMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionCanonicalApprovalInputPrecheckIntakeProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Intake state: ${profile.intakeState}`,
    `- Intake decision: ${profile.intakeDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Java source version: ${profile.javaSourceVersion}`,
    `- mini-kv source version: ${profile.miniKvSourceVersion}`,
    `- Ready for runtime execution canonical approval input precheck intake: ${profile.readyForRuntimeExecutionCanonicalApprovalInputPrecheckIntake}`,
    `- Ready for runtime execution packet: ${profile.readyForRuntimeExecutionPacket}`,
    `- Ready for runtime live-read gate: ${profile.readyForRuntimeLiveReadGate}`,
    `- Runtime execution packet executable: ${profile.runtimeExecutionPacketExecutable}`,
    `- Runtime gate approval present: ${profile.runtimeGateApprovalPresent}`,
    `- Execution attempted: ${profile.executionAttempted}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v403",
    "",
    ...renderEntries(profile.sourceNodeV403),
    "",
    "## Java v167 Template Compatibility Intake",
    "",
    ...renderEntries(profile.javaV167TemplateCompatibilityIntake),
    "",
    "## mini-kv v158 Canonical Approval Input Precheck",
    "",
    ...renderEntries(profile.miniKvV158CanonicalApprovalInputPrecheck),
    "",
    "## Canonical Approval Input Precheck Intake",
    "",
    ...renderEntries(profile.canonicalApprovalInputPrecheckIntake),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
