import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  JavaV143HumanApprovalArtifactReviewPacketEchoReference,
  ManagedAuditManualSandboxConnectionCredentialResolverHumanApprovalArtifactReviewUpstreamEchoVerificationProfile,
  MiniKvV136HumanApprovalArtifactReviewNonParticipationReceiptReference,
  SourceNodeV308HumanApprovalArtifactReviewPacketReference,
} from "./managedAuditManualSandboxConnectionCredentialResolverHumanApprovalArtifactReviewUpstreamEchoVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverHumanApprovalArtifactReviewUpstreamEchoVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverHumanApprovalArtifactReviewUpstreamEchoVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver human approval artifact review upstream echo verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Verification state: ${profile.verificationState}`,
    `- Runtime shell chain decision: ${profile.runtimeShellChainDecision}`,
    `- Ready for upstream echo verification: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverHumanApprovalArtifactReviewUpstreamEchoVerification}`,
    `- Active Node verification version: ${profile.activeNodeVerificationVersion}`,
    `- Runtime shell implemented: ${profile.runtimeShellImplemented}`,
    `- Runtime shell invocation allowed: ${profile.runtimeShellInvocationAllowed}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v308",
    "",
    ...renderSourceNodeV308(profile.sourceNodeV308),
    "",
    "## Java v143 Echo",
    "",
    ...renderJavaReference(profile.upstreamEvidence.javaV143),
    "",
    "## mini-kv v136 Receipt",
    "",
    ...renderMiniKvReference(profile.upstreamEvidence.miniKvV136),
    "",
    "## Echo Verification",
    "",
    ...renderEntries(profile.echoVerification),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No human approval artifact review upstream echo verification blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No human approval artifact review upstream echo verification warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No human approval artifact review upstream echo verification recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderSourceNodeV308(reference: SourceNodeV308HumanApprovalArtifactReviewPacketReference): string[] {
  return renderEntries({
    sourceVersion: reference.sourceVersion,
    profileVersion: reference.profileVersion,
    reviewPacketState: reference.reviewPacketState,
    readyForHumanApprovalArtifactReviewPacket: reference.readyForHumanApprovalArtifactReviewPacket,
    reviewPacketDigest: reference.reviewPacketDigest,
    nextJavaVersion: reference.nextJavaVersion,
    nextMiniKvVersion: reference.nextMiniKvVersion,
    nextNodeVerificationVersion: reference.nextNodeVerificationVersion,
    readyForParallelJavaV143MiniKvV136Echo: reference.readyForParallelJavaV143MiniKvV136Echo,
  });
}

function renderJavaReference(reference: JavaV143HumanApprovalArtifactReviewPacketEchoReference): string[] {
  return [
    ...renderEntries({
      sourceVersion: reference.sourceVersion,
      receiptVersion: reference.receiptVersion,
      echoMode: reference.echoMode,
      sourceSpan: reference.sourceSpan,
      nextNodeVersion: reference.nextNodeVersion,
      evidencePresent: reference.evidencePresent,
      verificationDocumented: reference.verificationDocumented,
      echoesNodeV308Packet: reference.echoesNodeV308Packet,
      readyForNodeV309: reference.readyForNodeV309,
      reviewPacketContractEchoed: reference.reviewPacketContractEchoed,
      requiredFieldCountEchoed: reference.requiredFieldCountEchoed,
      prohibitedFieldCountEchoed: reference.prohibitedFieldCountEchoed,
      rejectionReasonCountEchoed: reference.rejectionReasonCountEchoed,
      missingFieldCheckCountEchoed: reference.missingFieldCheckCountEchoed,
      noGoBoundaryCountEchoed: reference.noGoBoundaryCountEchoed,
      upstreamEchoRequestsEchoed: reference.upstreamEchoRequestsEchoed,
      necessityProofEchoed: reference.necessityProofEchoed,
      sideEffectBoundariesClosed: reference.sideEffectBoundariesClosed,
    }),
    "",
    "### Evidence Files",
    "",
    ...renderList(
      reference.evidenceFiles.map((file) => `${file.id}: exists=${file.exists}; size=${file.sizeBytes}; resolved=${file.resolvedPath}`),
      "No Java evidence files.",
    ),
    "",
    "### Expected Snippets",
    "",
    ...renderList(
      reference.expectedSnippets.map((snippet) => `${snippet.id}: matched=${snippet.matched}; resolved=${snippet.resolvedPath}`),
      "No Java expected snippets.",
    ),
  ];
}

function renderMiniKvReference(
  reference: MiniKvV136HumanApprovalArtifactReviewNonParticipationReceiptReference,
): string[] {
  return [
    ...renderEntries({
      sourceVersion: reference.sourceVersion,
      receiptVersion: reference.receiptVersion,
      releaseVersion: reference.releaseVersion,
      consumerHint: reference.consumerHint,
      receiptDigest: reference.receiptDigest,
      evidencePresent: reference.evidencePresent,
      verificationDocumented: reference.verificationDocumented,
      echoesNodeV308Packet: reference.echoesNodeV308Packet,
      readyForNodeV309: reference.readyForNodeV309,
      sourceNodeV308ProfileVersion: reference.sourceNodeV308ProfileVersion,
      sourceNodeV308ReviewPacketState: reference.sourceNodeV308ReviewPacketState,
      sourceNodeV308PacketDigest: reference.sourceNodeV308PacketDigest,
      requiredFieldCount: reference.requiredFieldCount,
      prohibitedFieldCount: reference.prohibitedFieldCount,
      rejectionReasonCount: reference.rejectionReasonCount,
      missingFieldCheckCount: reference.missingFieldCheckCount,
      noGoBoundaryCount: reference.noGoBoundaryCount,
      upstreamEchoRequestCount: reference.upstreamEchoRequestCount,
      nonParticipationReceiptOnly: reference.nonParticipationReceiptOnly,
      sideEffectBoundariesClosed: reference.sideEffectBoundariesClosed,
    }),
    "",
    "### Evidence Files",
    "",
    ...renderList(
      reference.evidenceFiles.map((file) => `${file.id}: exists=${file.exists}; size=${file.sizeBytes}; resolved=${file.resolvedPath}`),
      "No mini-kv evidence files.",
    ),
    "",
    "### Expected Snippets",
    "",
    ...renderList(
      reference.expectedSnippets.map((snippet) => `${snippet.id}: matched=${snippet.matched}; resolved=${snippet.resolvedPath}`),
      "No mini-kv expected snippets.",
    ),
  ];
}
