import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationRerunDecisionProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationRerunDecisionTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationRerunDecisionMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationRerunDecisionProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver minimal read-only integration rerun decision",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Rerun decision state: ${profile.rerunDecisionState}`,
    `- Rerun decision: ${profile.rerunDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Source archive result: ${profile.sourceArchiveResult}`,
    `- Source archive decision: ${profile.sourceArchiveDecision}`,
    `- Ready for rerun decision: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationRerunDecision}`,
    `- Ready for Node v349 rerun or pending archive: ${profile.readyForNodeV349MinimalReadOnlyIntegrationRerunOrPendingArchive}`,
    `- External read window required: ${profile.externalReadWindowRequired}`,
    `- Requires Java v153 + mini-kv v144 echo: ${profile.requiresParallelJavaV153MiniKvV144ReadOnlyEcho}`,
    `- Reruns live probe: ${profile.rerunsLiveProbe}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Reads managed audit credential: ${profile.readsManagedAuditCredential}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v347",
    "",
    ...renderEntries(profile.sourceNodeV347),
    "",
    "## Rerun Decision Record",
    "",
    ...renderEntries(profile.rerunDecisionRecord),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
