import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessRequirementTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_VERSIONS = [
  "Node v1162",
  "Node v1163",
  "Node v1164",
  "Node v1165",
  "Node v1166",
  "Node v1167",
  "Node v1168",
  "Node v1169",
  "Node v1170",
  "Node v1171",
  "Node v1172",
  "Node v1173",
  "Node v1174",
  "Node v1175",
  "Node v1176",
  "Node v1177",
  "Node v1178",
  "Node v1179",
  "Node v1180",
  "Node v1181",
  "Node v1182",
  "Node v1183",
  "Node v1184",
  "Node v1185",
  "Node v1186",
] as const;

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_REQUIREMENTS:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessRequirementTemplate[]
  = Object.freeze([
    requirement("Node v1162", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_REQUEST_MANIFEST",
      "draftAuthoringRequestManifest", "identity-authoring-requirement", "human-authoring-metadata",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REQUEST_MANIFEST_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REQUEST_MANIFEST_GUARD",
      "manual-review-package-entry",
      "Require the future human-authored draft to cite the review package request manifest."),
    requirement("Node v1163", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_ARTIFACT_PREFLIGHT_DIGEST",
      "artifactPreflightDigestAuthoringPin", "digest-binding-authoring-requirement",
      "digest-authoring-pin",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_ARTIFACT_PREFLIGHT_DIGEST_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_ARTIFACT_PREFLIGHT_DIGEST_GUARD",
      "digest-review-package-entry",
      "Require the future draft to cite the artifact preflight digest pin."),
    requirement("Node v1164", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_TEMPLATE_DIGEST",
      "templateDigestAuthoringPin", "digest-binding-authoring-requirement", "digest-authoring-pin",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_TEMPLATE_DIGEST_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_TEMPLATE_DIGEST_GUARD",
      "digest-review-package-entry",
      "Require the future draft to cite the signed approval template digest."),
    requirement("Node v1165", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_REVIEW_DIGEST",
      "approvalReviewDigestAuthoringPin", "digest-binding-authoring-requirement",
      "digest-authoring-pin",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REVIEW_DIGEST_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REVIEW_DIGEST_GUARD",
      "digest-review-package-entry",
      "Require the future draft to cite the approval packet review digest."),
    requirement("Node v1166", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_OPERATOR_IDENTITY",
      "operatorIdentityAuthoringRequirement", "identity-authoring-requirement",
      "human-authoring-metadata",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_OPERATOR_IDENTITY_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_OPERATOR_IDENTITY_GUARD",
      "manual-review-package-entry",
      "Require human draft authoring to preserve reviewed operator identity metadata."),
    requirement("Node v1167", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_OPERATOR_ROLE",
      "operatorRoleAuthoringRequirement", "identity-authoring-requirement",
      "human-authoring-metadata",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_OPERATOR_ROLE_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_OPERATOR_ROLE_GUARD",
      "manual-review-package-entry",
      "Require human draft authoring to preserve reviewed operator role metadata."),
    requirement("Node v1168", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_WINDOW_ID",
      "captureWindowAuthoringRequirement", "identity-authoring-requirement",
      "human-authoring-metadata",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_WINDOW_ID_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_WINDOW_ID_GUARD",
      "manual-review-package-entry",
      "Require the future draft to cite the planned capture window id without opening it."),
    requirement("Node v1169", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_CHANNEL_POLICY",
      "captureChannelPolicyAuthoringRequirement", "policy-authoring-requirement",
      "policy-authoring-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_CHANNEL_POLICY_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_CHANNEL_POLICY_GUARD",
      "policy-review-package-entry",
      "Require human draft authoring to keep capture channel policy visible."),
    requirement("Node v1170", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_SIGNATURE_ALGORITHM",
      "signatureAlgorithmAuthoringRequirement", "signature-envelope-authoring-requirement",
      "policy-authoring-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIGNATURE_ALGORITHM_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIGNATURE_ALGORITHM_GUARD",
      "policy-review-package-entry",
      "Require the future draft to cite signature algorithm policy while no signature is accepted."),
    requirement("Node v1171", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_DETACHED_SIGNATURE",
      "detachedSignatureAuthoringRequirement", "signature-envelope-authoring-requirement",
      "human-authoring-metadata",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_DETACHED_SIGNATURE_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_DETACHED_SIGNATURE_GUARD",
      "manual-review-package-entry",
      "Require detached signature material to stay out of band for later human handling."),
    requirement("Node v1172", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_SIGNATURE_REDACTION",
      "signatureRedactionAuthoringRequirement", "signature-envelope-authoring-requirement",
      "policy-authoring-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIGNATURE_REDACTION_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIGNATURE_REDACTION_GUARD",
      "policy-review-package-entry",
      "Require the future draft to preserve signature redaction policy."),
    requirement("Node v1173", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_APPROVAL_STATEMENT_DIGEST",
      "approvalStatementDigestAuthoringPin", "digest-binding-authoring-requirement",
      "digest-authoring-pin",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_APPROVAL_STATEMENT_DIGEST_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_APPROVAL_STATEMENT_DIGEST_GUARD",
      "digest-review-package-entry",
      "Require the future draft to cite approval statement digest without storing signed text."),
    requirement("Node v1174", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_SOURCE_VERSION",
      "sourceEvidenceVersionAuthoringRequirement", "source-evidence-authoring-requirement",
      "human-authoring-metadata",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_VERSION_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_VERSION_GUARD",
      "manual-review-package-entry",
      "Require the future draft to cite the source evidence version."),
    requirement("Node v1175", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_SOURCE_FILE",
      "sourceEvidenceFileAuthoringRequirement", "source-evidence-authoring-requirement",
      "human-authoring-metadata",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_FILE_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_FILE_GUARD",
      "manual-review-package-entry",
      "Require the future draft to cite the source evidence file id."),
    requirement("Node v1176", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_SOURCE_SNIPPET",
      "sourceEvidenceSnippetAuthoringRequirement", "source-evidence-authoring-requirement",
      "human-authoring-metadata",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_SNIPPET_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_SNIPPET_GUARD",
      "manual-review-package-entry",
      "Require the future draft to cite the source snippet id without assembling runtime payload."),
    requirement("Node v1177", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_REDACTED_VALUE_DIGEST",
      "redactedValueDigestAuthoringPin", "value-binding-authoring-requirement",
      "digest-authoring-pin",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REDACTED_VALUE_DIGEST_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REDACTED_VALUE_DIGEST_GUARD",
      "digest-review-package-entry",
      "Require the future draft to cite redacted value digest while raw values remain absent."),
    requirement("Node v1178", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_VALUE_SHAPE",
      "valueShapeAuthoringRequirement", "value-binding-authoring-requirement",
      "human-authoring-metadata",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_VALUE_SHAPE_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_VALUE_SHAPE_GUARD",
      "manual-review-package-entry",
      "Require the future draft to cite value shape metadata without accepting values."),
    requirement("Node v1179", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_REDACTION_POLICY",
      "redactionPolicyAuthoringRequirement", "policy-authoring-requirement",
      "policy-authoring-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REDACTION_POLICY_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REDACTION_POLICY_GUARD",
      "policy-review-package-entry",
      "Require the future draft to preserve redaction policy."),
    requirement("Node v1180", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_PROVENANCE_POLICY",
      "provenancePolicyAuthoringRequirement", "policy-authoring-requirement",
      "policy-authoring-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_PROVENANCE_POLICY_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_PROVENANCE_POLICY_GUARD",
      "policy-review-package-entry",
      "Require the future draft to preserve provenance policy."),
    requirement("Node v1181", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_RAW_SECRET_EMBARGO",
      "rawSecretEmbargoAuthoringRequirement", "execution-lock-authoring-requirement",
      "execution-lock-authoring-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_RAW_SECRET_EMBARGO_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_RAW_SECRET_EMBARGO_GUARD",
      "execution-lock-review-package-entry",
      "Require raw secret embargo evidence before any human draft artifact package exists."),
    requirement("Node v1182", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_APPROVAL_GRANT_EMBARGO",
      "approvalGrantEmbargoAuthoringRequirement", "execution-lock-authoring-requirement",
      "execution-lock-authoring-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_APPROVAL_GRANT_EMBARGO_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_APPROVAL_GRANT_EMBARGO_GUARD",
      "execution-lock-review-package-entry",
      "Require approval grant embargo evidence before any draft artifact package exists."),
    requirement("Node v1183", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_ZERO_VALUE_IMPORT_EMBARGO",
      "zeroValueImportEmbargoAuthoringRequirement", "execution-lock-authoring-requirement",
      "execution-lock-authoring-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_ZERO_VALUE_IMPORT_EMBARGO_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_ZERO_VALUE_IMPORT_EMBARGO_GUARD",
      "execution-lock-review-package-entry",
      "Require zero value import evidence before any human draft artifact package exists."),
    requirement("Node v1184", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_WRITE_ROUTE_EMBARGO",
      "writeRouteEmbargoAuthoringRequirement", "execution-lock-authoring-requirement",
      "execution-lock-authoring-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_WRITE_ROUTE_EMBARGO_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_WRITE_ROUTE_EMBARGO_GUARD",
      "execution-lock-review-package-entry",
      "Require write route embargo evidence until a real approval grant exists."),
    requirement("Node v1185", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_SIBLING_NON_MUTATION",
      "siblingNonMutationAuthoringRequirement", "execution-lock-authoring-requirement",
      "execution-lock-authoring-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIBLING_NON_MUTATION_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIBLING_NON_MUTATION_GUARD",
      "execution-lock-review-package-entry",
      "Require sibling non-mutation evidence before draft artifact authoring can proceed."),
    requirement("Node v1186", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_AUTHORING_READINESS_CLOSEOUT",
      "signedApprovalCaptureArtifactDraftAuthoringReadinessCloseout",
      "archive-closeout-authoring-requirement", "authoring-closeout",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_CLOSEOUT_SLOT",
      "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_CLOSEOUT_GUARD",
      "archive-closeout-review-package-entry",
      "Close authoring readiness and limit the next step to a separate manual draft artifact package."),
  ]);

function requirement(
  nodeVersion:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessRequirementTemplate[
      "nodeVersion"
    ],
  code: string,
  authoringRequirementName: string,
  kind:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessRequirementTemplate[
      "kind"
    ],
  requirementMode:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessRequirementTemplate[
      "requirementMode"
    ],
  sourcePackageSlotCode: string,
  sourcePackageGuardCode: string,
  requiredPackageSlotMode:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessRequirementTemplate[
      "requiredPackageSlotMode"
    ],
  authoringPurpose: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessRequirementTemplate {
  return {
    nodeVersion,
    code,
    authoringRequirementName,
    kind,
    requirementMode,
    sourcePackageSlotCode,
    sourcePackageGuardCode,
    requiredPackageSlotMode,
    authoringPurpose,
  };
}
