import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReviewControlTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReviewTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_APPROVAL_PACKET_REVIEW_VERSIONS = [
  "Node v987",
  "Node v988",
  "Node v989",
  "Node v990",
  "Node v991",
  "Node v992",
  "Node v993",
  "Node v994",
  "Node v995",
  "Node v996",
  "Node v997",
  "Node v998",
  "Node v999",
  "Node v1000",
  "Node v1001",
  "Node v1002",
  "Node v1003",
  "Node v1004",
  "Node v1005",
  "Node v1006",
  "Node v1007",
  "Node v1008",
  "Node v1009",
  "Node v1010",
  "Node v1011",
] as const;

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_APPROVAL_PACKET_REVIEW_CONTROLS:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReviewControlTemplate[]
  = Object.freeze([
    control("Node v987", "VALUE_SUPPLY_APPROVAL_REVIEW_PACKET_ID", "approval-field-review-control",
      "operator-identity", "VALUE_SUPPLY_APPROVAL_PACKET_JAVA_CLOSEOUT_PROFILE", "approvalPacketId",
      "sourceEvidenceFileId", "approvalPolicy", "signed-human-approval-required",
      "Does every future approval record carry a stable approval packet id before values are supplied?",
      "The reviewer can trace the packet id to a source evidence file before any operator value exists.",
      "APPROVAL_REVIEW_PACKET_ID_MISSING"),
    control("Node v988", "VALUE_SUPPLY_APPROVAL_REVIEW_OPERATOR_IDENTITY", "approval-field-review-control",
      "operator-identity", "VALUE_SUPPLY_APPROVAL_PACKET_JAVA_CLOSEOUT_VERSION", "operatorIdentity",
      "sourceEvidenceSnippetId", "approvalPolicy", "signed-human-approval-required",
      "Is the human operator identity mandatory and still absent in the draft?",
      "The review package requires operator identity but confirms no identity has been captured yet.",
      "APPROVAL_REVIEW_OPERATOR_IDENTITY_NOT_REQUIRED"),
    control("Node v989", "VALUE_SUPPLY_APPROVAL_REVIEW_APPROVAL_TIMESTAMP", "approval-field-review-control",
      "approval-timestamp", "VALUE_SUPPLY_APPROVAL_PACKET_JAVA_VERSION_RANGE", "approvalTimestamp",
      "sourceEnvelopeSlotCode", "packetPolicy", "draft-only-no-approval-grant",
      "Is approval time represented as a required field without implying a grant?",
      "The review package keeps approval timestamp mandatory and confirms the draft remains grant-free.",
      "APPROVAL_REVIEW_TIMESTAMP_NOT_BOUND"),
    control("Node v990", "VALUE_SUPPLY_APPROVAL_REVIEW_SOURCE_EVIDENCE_VERSION", "approval-field-review-control",
      "source-evidence", "VALUE_SUPPLY_APPROVAL_PACKET_JAVA_READY_ENVELOPE", "sourceEvidenceVersion",
      "sourceEvidenceFileId", "provenancePolicy", "source-evidence-required",
      "Can the reviewer bind every value candidate back to the source evidence version?",
      "The source evidence version field is present and provenance still requires source evidence.",
      "APPROVAL_REVIEW_SOURCE_VERSION_NOT_BOUND"),
    control("Node v991", "VALUE_SUPPLY_APPROVAL_REVIEW_VALUE_SHAPE", "approval-field-review-control",
      "value-shape", "VALUE_SUPPLY_APPROVAL_PACKET_JAVA_SUPPLIED_STATE", "valueShape",
      "missingValuePolicy", "valueShapeRule", "explicit-typed-value-envelope",
      "Is a typed value envelope required before any manual value can be accepted?",
      "The value shape field exists and the source policy still requires an explicit typed envelope.",
      "APPROVAL_REVIEW_VALUE_SHAPE_NOT_DECLARED"),
    control("Node v992", "VALUE_SUPPLY_APPROVAL_REVIEW_REDACTED_DIGEST", "approval-field-review-control",
      "redaction", "VALUE_SUPPLY_APPROVAL_PACKET_JAVA_REDACTION_STATE", "redactedValueDigest",
      "redactionPolicy", "redactionPolicy", "redact-before-persist",
      "Is the redacted value digest required before any value persistence path can open?",
      "The redacted value digest field exists and redaction still happens before persistence.",
      "APPROVAL_REVIEW_REDACTED_DIGEST_NOT_REQUIRED"),
    control("Node v993", "VALUE_SUPPLY_APPROVAL_REVIEW_PROJECT_JUSTIFICATION", "approval-field-review-control",
      "provenance", "VALUE_SUPPLY_APPROVAL_PACKET_JAVA_PROVENANCE_STATE", "javaApprovalJustification",
      "provenancePolicy", "provenancePolicy", "source-evidence-required",
      "Does the Java value-supply evidence require a project-specific approval justification?",
      "The project justification field is present and provenance remains source-evidence backed.",
      "APPROVAL_REVIEW_PROJECT_JUSTIFICATION_MISSING"),
    control("Node v994", "VALUE_SUPPLY_APPROVAL_REVIEW_SIGNED_HUMAN_POLICY", "policy-review-control",
      "operator-identity", "VALUE_SUPPLY_APPROVAL_PACKET_JAVA_SUBMISSION_BLOCK", "operatorIdentity",
      "javaExecutionLock", "approvalPolicy", "signed-human-approval-required",
      "Is signed human approval still the only approval policy?",
      "The source slot requires signed human approval and operator submission remains blocked.",
      "APPROVAL_REVIEW_POLICY_NOT_SIGNED_HUMAN"),
    control("Node v995", "VALUE_SUPPLY_APPROVAL_REVIEW_DRAFT_ONLY_POLICY", "policy-review-control",
      "closeout", "VALUE_SUPPLY_APPROVAL_PACKET_JAVA_IMPORT_BLOCK", "approvalPacketId",
      "javaCloseoutEndpoint", "packetPolicy", "draft-only-no-approval-grant",
      "Does the packet remain a review draft rather than an approval grant?",
      "The source slot is still draft-only and does not grant approval or import evidence.",
      "APPROVAL_REVIEW_PACKET_GRANTS_APPROVAL"),
    control("Node v996", "VALUE_SUPPLY_APPROVAL_REVIEW_TYPED_VALUE_POLICY", "policy-review-control",
      "value-shape", "VALUE_SUPPLY_APPROVAL_PACKET_JAVA_RUNTIME_BLOCK", "valueShape",
      "malformedValuePolicy", "valueShapeRule", "explicit-typed-value-envelope",
      "Will malformed or untyped operator values be rejected before runtime payload construction?",
      "The policy requires an explicit typed envelope and malformed values remain rejected.",
      "APPROVAL_REVIEW_TYPED_VALUE_POLICY_MISSING"),
    control("Node v997", "VALUE_SUPPLY_APPROVAL_REVIEW_MISSING_VALUE_POLICY", "policy-review-control",
      "value-shape", "VALUE_SUPPLY_APPROVAL_PACKET_JAVA_CLOSEOUT_ROUTE_TEST", "valueShape",
      "missingValuePolicy", "missingValuePolicy", "fail-closed",
      "Does a missing operator value fail closed instead of silently passing?",
      "The source slot carries a fail-closed missing value policy.",
      "APPROVAL_REVIEW_MISSING_VALUE_POLICY_NOT_FAIL_CLOSED"),
    control("Node v998", "VALUE_SUPPLY_APPROVAL_REVIEW_MALFORMED_VALUE_POLICY", "policy-review-control",
      "value-shape", "VALUE_SUPPLY_APPROVAL_PACKET_JAVA_LOCKS_TEST", "valueShape",
      "malformedValuePolicy", "malformedValuePolicy", "reject",
      "Does a malformed operator value stay rejected before import?",
      "The malformed value policy rejects invalid values while execution locks remain held.",
      "APPROVAL_REVIEW_MALFORMED_VALUE_POLICY_NOT_REJECTING"),
    control("Node v999", "VALUE_SUPPLY_APPROVAL_REVIEW_REDACTION_POLICY", "policy-review-control",
      "redaction", "VALUE_SUPPLY_APPROVAL_PACKET_MINI_KV_CONTRACT", "redactedValueDigest",
      "redactionPolicy", "redactionPolicy", "redact-before-persist",
      "Does the mini-kv contract stay compatible with redact-before-persist semantics?",
      "The redaction policy is satisfied before any persistence route can be used.",
      "APPROVAL_REVIEW_REDACTION_POLICY_NOT_SAFE"),
    control("Node v1000", "VALUE_SUPPLY_APPROVAL_REVIEW_PROVENANCE_POLICY", "policy-review-control",
      "provenance", "VALUE_SUPPLY_APPROVAL_PACKET_MINI_KV_COMMAND", "sourceEvidenceVersion",
      "provenancePolicy", "provenancePolicy", "source-evidence-required",
      "Is every future value tied to source evidence rather than synthetic input?",
      "The provenance policy requires source evidence and synthetic evidence remains blocked.",
      "APPROVAL_REVIEW_PROVENANCE_POLICY_NOT_REQUIRED"),
    control("Node v1001", "VALUE_SUPPLY_APPROVAL_REVIEW_JAVA_EVIDENCE_COVERAGE", "source-evidence-review-control",
      "source-evidence", "VALUE_SUPPLY_APPROVAL_PACKET_MINI_KV_RANGE_START", "sourceEvidenceVersion",
      "sourceEvidenceFileId", "provenancePolicy", "source-evidence-required",
      "Can Java closeout evidence still be traced through the approval review package?",
      "The control preserves source evidence file coverage before any approval template is captured.",
      "APPROVAL_REVIEW_JAVA_EVIDENCE_NOT_COVERED"),
    control("Node v1002", "VALUE_SUPPLY_APPROVAL_REVIEW_MINI_KV_EVIDENCE_COVERAGE",
      "source-evidence-review-control", "source-evidence", "VALUE_SUPPLY_APPROVAL_PACKET_MINI_KV_RANGE_END",
      "sourceEvidenceVersion", "sourceEvidenceSnippetId", "provenancePolicy", "source-evidence-required",
      "Can mini-kv value-supply evidence still be traced through the approval review package?",
      "The control preserves mini-kv snippet coverage before any value can be accepted.",
      "APPROVAL_REVIEW_MINI_KV_EVIDENCE_NOT_COVERED"),
    control("Node v1003", "VALUE_SUPPLY_APPROVAL_REVIEW_NODE_ENVELOPE_COVERAGE",
      "source-evidence-review-control", "source-evidence", "VALUE_SUPPLY_APPROVAL_PACKET_MINI_KV_SLOT_COUNT",
      "sourceEvidenceVersion", "sourceEnvelopeSlotCode", "provenancePolicy", "source-evidence-required",
      "Can the Node value-supply envelope still be traced for every review control?",
      "The control binds review coverage to the source envelope slot code.",
      "APPROVAL_REVIEW_NODE_ENVELOPE_NOT_COVERED"),
    control("Node v1004", "VALUE_SUPPLY_APPROVAL_REVIEW_DRAFT_DIGEST_COVERAGE",
      "source-evidence-review-control", "closeout", "VALUE_SUPPLY_APPROVAL_PACKET_MINI_KV_ACCEPTED_ZERO",
      "approvalPacketId", "sourceEnvelopeSlotCode", "packetPolicy", "draft-only-no-approval-grant",
      "Is the source approval packet draft digest present before review package promotion?",
      "The source draft digest is present and the control still records zero accepted values.",
      "APPROVAL_REVIEW_DRAFT_DIGEST_MISSING"),
    control("Node v1005", "VALUE_SUPPLY_APPROVAL_REVIEW_HISTORICAL_FALLBACK_COVERAGE",
      "source-evidence-review-control", "source-evidence", "VALUE_SUPPLY_APPROVAL_PACKET_MINI_KV_IMPORTED_ZERO",
      "sourceEvidenceVersion", "sourceEvidenceFileId", "provenancePolicy", "source-evidence-required",
      "Can the package still be reviewed with frozen sibling historical fixtures?",
      "The control keeps historical fallback reviewable without live Java or mini-kv services.",
      "APPROVAL_REVIEW_HISTORICAL_FALLBACK_NOT_COVERED"),
    control("Node v1006", "VALUE_SUPPLY_APPROVAL_REVIEW_NO_APPROVAL_CAPTURED",
      "execution-lock-review-control", "non-execution", "VALUE_SUPPLY_APPROVAL_PACKET_MINI_KV_DISABLED_STATE",
      "operatorIdentity", "miniKvEnvelopeMode", "packetPolicy", "draft-only-no-approval-grant",
      "Does the review package prove no approval has already been captured?",
      "No approval, approval grant, or signed approval exists in the source draft.",
      "APPROVAL_REVIEW_APPROVAL_ALREADY_CAPTURED"),
    control("Node v1007", "VALUE_SUPPLY_APPROVAL_REVIEW_ZERO_VALUE_COUNTS",
      "execution-lock-review-control", "non-execution", "VALUE_SUPPLY_APPROVAL_PACKET_MINI_KV_READY_FALSE",
      "valueShape", "miniKvCommand", "missingValuePolicy", "fail-closed",
      "Are supplied, accepted, and imported value counts still zero?",
      "The source draft and review control keep all operator value counts at zero.",
      "APPROVAL_REVIEW_VALUES_ALREADY_PRESENT"),
    control("Node v1008", "VALUE_SUPPLY_APPROVAL_REVIEW_RUNTIME_PAYLOAD_BLOCK",
      "execution-lock-review-control", "non-execution", "VALUE_SUPPLY_APPROVAL_PACKET_MINI_KV_ADAPTER_DISABLED",
      "redactedValueDigest", "miniKvEnvelopeMode", "malformedValuePolicy", "reject",
      "Is runtime payload import still blocked while the adapter is disabled?",
      "Runtime payload import remains blocked and malformed values still reject.",
      "APPROVAL_REVIEW_RUNTIME_PAYLOAD_ENABLED"),
    control("Node v1009", "VALUE_SUPPLY_APPROVAL_REVIEW_WRITE_AND_SERVICE_BLOCK",
      "execution-lock-review-control", "non-execution", "VALUE_SUPPLY_APPROVAL_PACKET_MINI_KV_NO_PERSIST",
      "redactedValueDigest", "miniKvStoreUnchangedProof", "redactionPolicy", "redact-before-persist",
      "Do writes, service starts, and sibling mutation remain unavailable?",
      "No writes, service starts, or sibling mutations are allowed by the review package.",
      "APPROVAL_REVIEW_WRITE_OR_SERVICE_ENABLED"),
    control("Node v1010", "VALUE_SUPPLY_APPROVAL_REVIEW_OPERATOR_SUPPLY_BLOCK",
      "execution-lock-review-control", "non-execution", "VALUE_SUPPLY_APPROVAL_PACKET_MINI_KV_STORE_UNCHANGED_TEST",
      "operatorIdentity", "miniKvStoreUnchangedProof", "approvalPolicy", "signed-human-approval-required",
      "Is operator value supply still disabled until a signed approval template exists?",
      "Operator value supply and submission remain disabled even though the package is reviewable.",
      "APPROVAL_REVIEW_OPERATOR_SUPPLY_ENABLED"),
    control("Node v1011", "VALUE_SUPPLY_APPROVAL_REVIEW_CLOSEOUT",
      "closeout-review-control", "closeout", "VALUE_SUPPLY_APPROVAL_PACKET_DRAFT_CLOSEOUT",
      "approvalPacketId", "nodeCloseoutPlan", "packetPolicy", "draft-only-no-approval-grant",
      "Is the only next step a signed approval template rather than value import or execution?",
      "The review package is closed out for signed approval template design only.",
      "APPROVAL_REVIEW_CLOSEOUT_NEXT_STEP_UNSAFE"),
  ]);

function control(
  nodeVersion: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReviewControlTemplate[
    "nodeVersion"
  ],
  code: string,
  kind: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReviewControlTemplate[
    "kind"
  ],
  scope: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReviewControlTemplate[
    "scope"
  ],
  sourceApprovalPacketDraftSlotCode: string,
  requiredApprovalFieldName: string,
  requiredReviewRecordFieldName: string,
  expectedPolicyField: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReviewControlTemplate[
    "expectedPolicyField"
  ],
  expectedPolicyValue: string,
  reviewerQuestion: string,
  acceptanceCriterion: string,
  blockerCode: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReviewControlTemplate {
  return {
    nodeVersion,
    code,
    kind,
    scope,
    sourceApprovalPacketDraftSlotCode,
    requiredApprovalFieldName,
    requiredReviewRecordFieldName,
    expectedPolicyField,
    expectedPolicyValue,
    reviewerQuestion,
    acceptanceCriterion,
    blockerCode,
  };
}
