import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReadinessControlTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReadinessTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_CONTROLS:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReadinessControlTemplate[]
  = Object.freeze([
    control("Node v1112", "ARTIFACT_DRAFT_READINESS_REQUEST_MANIFEST_CONTROL",
      "identity-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_REQUEST_MANIFEST",
      "REJECT_DRAFT_READINESS_REQUEST_MANIFEST_MISSING",
      "Block draft readiness unless the request manifest lane is sourced from v1111 preflight."),
    control("Node v1113", "ARTIFACT_DRAFT_READINESS_ARTIFACT_PREFLIGHT_DIGEST_CONTROL",
      "digest-binding-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_ARTIFACT_PREFLIGHT_DIGEST_PIN",
      "REJECT_DRAFT_READINESS_ARTIFACT_PREFLIGHT_DIGEST_UNPINNED",
      "Block draft readiness unless the artifact preflight digest is pinned."),
    control("Node v1114", "ARTIFACT_DRAFT_READINESS_TEMPLATE_DIGEST_CONTROL",
      "digest-binding-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_TEMPLATE_DIGEST_PIN",
      "REJECT_DRAFT_READINESS_TEMPLATE_DIGEST_UNPINNED",
      "Block draft readiness unless the template digest is pinned."),
    control("Node v1115", "ARTIFACT_DRAFT_READINESS_REVIEW_DIGEST_CONTROL",
      "digest-binding-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_REVIEW_DIGEST_PIN",
      "REJECT_DRAFT_READINESS_REVIEW_DIGEST_UNPINNED",
      "Block draft readiness unless the approval packet review digest is pinned."),
    control("Node v1116", "ARTIFACT_DRAFT_READINESS_OPERATOR_IDENTITY_CONTROL",
      "identity-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_OPERATOR_IDENTITY_REVIEW",
      "REJECT_DRAFT_READINESS_OPERATOR_IDENTITY_UNREVIEWED",
      "Block draft readiness unless operator identity is ready for human review."),
    control("Node v1117", "ARTIFACT_DRAFT_READINESS_OPERATOR_ROLE_CONTROL",
      "identity-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_OPERATOR_ROLE_REVIEW",
      "REJECT_DRAFT_READINESS_OPERATOR_ROLE_UNREVIEWED",
      "Block draft readiness unless operator role is ready for human review."),
    control("Node v1118", "ARTIFACT_DRAFT_READINESS_WINDOW_ID_CONTROL",
      "identity-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_WINDOW_ID_REVIEW",
      "REJECT_DRAFT_READINESS_WINDOW_ID_UNREVIEWED",
      "Block draft readiness unless the capture window id lane is reviewed."),
    control("Node v1119", "ARTIFACT_DRAFT_READINESS_CHANNEL_POLICY_CONTROL",
      "policy-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_CHANNEL_POLICY_REVIEW",
      "REJECT_DRAFT_READINESS_CHANNEL_POLICY_UNREVIEWED",
      "Block draft readiness unless the capture channel policy lane is reviewed."),
    control("Node v1120", "ARTIFACT_DRAFT_READINESS_SIGNATURE_ALGORITHM_CONTROL",
      "signature-envelope-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SIGNATURE_ALGORITHM_REVIEW",
      "REJECT_DRAFT_READINESS_SIGNATURE_ALGORITHM_UNREVIEWED",
      "Block draft readiness unless signature algorithm policy is reviewed."),
    control("Node v1121", "ARTIFACT_DRAFT_READINESS_DETACHED_SIGNATURE_CONTROL",
      "signature-envelope-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_DETACHED_SIGNATURE_REVIEW",
      "REJECT_DRAFT_READINESS_DETACHED_SIGNATURE_PLACEHOLDER_UNREVIEWED",
      "Block draft readiness unless the detached signature lane remains a placeholder."),
    control("Node v1122", "ARTIFACT_DRAFT_READINESS_SIGNATURE_REDACTION_CONTROL",
      "signature-envelope-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SIGNATURE_REDACTION_REVIEW",
      "REJECT_DRAFT_READINESS_SIGNATURE_REDACTION_UNREVIEWED",
      "Block draft readiness unless signature material redaction is reviewed."),
    control("Node v1123", "ARTIFACT_DRAFT_READINESS_APPROVAL_STATEMENT_DIGEST_CONTROL",
      "digest-binding-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_APPROVAL_STATEMENT_DIGEST_PIN",
      "REJECT_DRAFT_READINESS_APPROVAL_STATEMENT_DIGEST_UNPINNED",
      "Block draft readiness unless approval statement digest lane is pinned."),
    control("Node v1124", "ARTIFACT_DRAFT_READINESS_SOURCE_VERSION_CONTROL",
      "source-evidence-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SOURCE_VERSION_REVIEW",
      "REJECT_DRAFT_READINESS_SOURCE_VERSION_UNREVIEWED",
      "Block draft readiness unless source version lane is reviewed."),
    control("Node v1125", "ARTIFACT_DRAFT_READINESS_SOURCE_FILE_CONTROL",
      "source-evidence-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SOURCE_FILE_REVIEW",
      "REJECT_DRAFT_READINESS_SOURCE_FILE_UNREVIEWED",
      "Block draft readiness unless source file lane is reviewed."),
    control("Node v1126", "ARTIFACT_DRAFT_READINESS_SOURCE_SNIPPET_CONTROL",
      "source-evidence-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SOURCE_SNIPPET_REVIEW",
      "REJECT_DRAFT_READINESS_SOURCE_SNIPPET_UNREVIEWED",
      "Block draft readiness unless source snippet lane is reviewed."),
    control("Node v1127", "ARTIFACT_DRAFT_READINESS_REDACTED_VALUE_DIGEST_CONTROL",
      "value-binding-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_REDACTED_VALUE_DIGEST_PIN",
      "REJECT_DRAFT_READINESS_REDACTED_VALUE_DIGEST_UNPINNED",
      "Block draft readiness unless the redacted value digest lane is pinned."),
    control("Node v1128", "ARTIFACT_DRAFT_READINESS_VALUE_SHAPE_CONTROL",
      "value-binding-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_VALUE_SHAPE_REVIEW",
      "REJECT_DRAFT_READINESS_VALUE_SHAPE_UNREVIEWED",
      "Block draft readiness unless value shape lane is reviewed."),
    control("Node v1129", "ARTIFACT_DRAFT_READINESS_REDACTION_POLICY_CONTROL",
      "policy-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_REDACTION_POLICY_REVIEW",
      "REJECT_DRAFT_READINESS_REDACTION_POLICY_UNREVIEWED",
      "Block draft readiness unless redaction policy lane is reviewed."),
    control("Node v1130", "ARTIFACT_DRAFT_READINESS_PROVENANCE_POLICY_CONTROL",
      "policy-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_PROVENANCE_POLICY_REVIEW",
      "REJECT_DRAFT_READINESS_PROVENANCE_POLICY_UNREVIEWED",
      "Block draft readiness unless provenance policy lane is reviewed."),
    control("Node v1131", "ARTIFACT_DRAFT_READINESS_RAW_SECRET_EMBARGO_CONTROL",
      "execution-lock-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_RAW_SECRET_EMBARGO",
      "REJECT_DRAFT_READINESS_RAW_SECRET_PRESENT",
      "Block draft readiness if raw secrets or signature material are present."),
    control("Node v1132", "ARTIFACT_DRAFT_READINESS_APPROVAL_GRANT_EMBARGO_CONTROL",
      "execution-lock-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_APPROVAL_GRANT_EMBARGO",
      "REJECT_DRAFT_READINESS_APPROVAL_GRANT_EMITTED",
      "Block draft readiness if an approval grant is already emitted."),
    control("Node v1133", "ARTIFACT_DRAFT_READINESS_ZERO_VALUE_IMPORT_EMBARGO_CONTROL",
      "execution-lock-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_ZERO_VALUE_IMPORT_EMBARGO",
      "REJECT_DRAFT_READINESS_VALUE_IMPORT_NONZERO",
      "Block draft readiness if value submission or evidence import counts are nonzero."),
    control("Node v1134", "ARTIFACT_DRAFT_READINESS_WRITE_ROUTE_EMBARGO_CONTROL",
      "execution-lock-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_WRITE_ROUTE_EMBARGO",
      "REJECT_DRAFT_READINESS_WRITE_ROUTE_ENABLED",
      "Block draft readiness if write routing is enabled."),
    control("Node v1135", "ARTIFACT_DRAFT_READINESS_SIBLING_NON_MUTATION_CONTROL",
      "execution-lock-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SIBLING_NON_MUTATION_EVIDENCE",
      "REJECT_DRAFT_READINESS_SIBLING_MUTATION_ENABLED",
      "Block draft readiness if sibling mutation is enabled."),
    control("Node v1136", "ARTIFACT_DRAFT_READINESS_CLOSEOUT_CONTROL",
      "archive-closeout-readiness-control",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_CLOSEOUT",
      "REJECT_DRAFT_READINESS_NEXT_STEP_NOT_MANUAL_PACKAGE",
      "Block draft readiness unless the next step is a separate manual draft artifact package."),
  ]);

function control(
  nodeVersion:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReadinessControlTemplate[
      "nodeVersion"
    ],
  code: string,
  kind:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReadinessControlTemplate[
      "kind"
    ],
  sourceReadinessLaneCode: string,
  blockerCode: string,
  controlText: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReadinessControlTemplate {
  return {
    nodeVersion,
    code,
    kind,
    sourceReadinessLaneCode,
    blockerCode,
    controlText,
  };
}
