import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  JavaV147EndpointHandleAllowlistApprovalContractEchoReference,
  ManagedAuditManualSandboxConnectionCredentialResolverEndpointHandleAllowlistApprovalContractUpstreamEchoVerificationProfile,
  MiniKvV140EndpointHandleAllowlistApprovalContractNonParticipationReceiptReference,
  SourceNodeV320EndpointHandleAllowlistApprovalContractIntakeReference,
} from "./managedAuditManualSandboxConnectionCredentialResolverEndpointHandleAllowlistApprovalContractUpstreamEchoVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverEndpointHandleAllowlistApprovalContractUpstreamEchoVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverEndpointHandleAllowlistApprovalContractUpstreamEchoVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver endpoint handle allowlist approval contract upstream echo verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Verification state: ${profile.verificationState}`,
    `- Runtime shell chain decision: ${profile.runtimeShellChainDecision}`,
    `- Ready for verification: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverEndpointHandleAllowlistApprovalContractUpstreamEchoVerification}`,
    `- Active Node verification version: ${profile.activeNodeVerificationVersion}`,
    `- Credential value read: ${profile.credentialValueRead}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    `- Secret provider instantiated: ${profile.secretProviderInstantiated}`,
    `- Resolver client instantiated: ${profile.resolverClientInstantiated}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v320",
    "",
    ...renderSourceNodeV320(profile.sourceNodeV320),
    "",
    "## Java v147 Echo",
    "",
    ...renderJavaV147(profile.upstreamEvidence.javaV147),
    "",
    "## mini-kv v140 Receipt",
    "",
    ...renderMiniKvV140(profile.upstreamEvidence.miniKvV140),
    "",
    "## Java v148 Quality Split",
    "",
    ...renderEntries(profile.upstreamEvidence.javaV148QualitySplit),
    "",
    "## Echo Verification",
    "",
    ...renderEntries(profile.echoVerification),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No endpoint handle allowlist upstream echo blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No endpoint handle allowlist upstream echo warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No endpoint handle allowlist upstream echo recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderSourceNodeV320(
  reference: SourceNodeV320EndpointHandleAllowlistApprovalContractIntakeReference,
): string[] {
  return renderEntries({
    sourceVersion: reference.sourceVersion,
    profileVersion: reference.profileVersion,
    contractState: reference.contractState,
    readyForEndpointHandleAllowlistApprovalContractIntake:
      reference.readyForEndpointHandleAllowlistApprovalContractIntake,
    targetPrerequisiteId: reference.targetPrerequisiteId,
    contractDigest: reference.contractDigest,
    nextJavaVersion: reference.nextJavaVersion,
    nextMiniKvVersion: reference.nextMiniKvVersion,
    nextNodeVerificationVersion: reference.nextNodeVerificationVersion,
    readyForParallelJavaV147MiniKvV140Echo: reference.readyForParallelJavaV147MiniKvV140Echo,
    requiredFieldIds: reference.requiredFieldIds,
    prohibitedFieldIds: reference.prohibitedFieldIds,
    rejectionReasonCodes: reference.rejectionReasonCodes,
    noGoBoundaryIds: reference.noGoBoundaryIds,
    upstreamEchoRequestVersions: reference.upstreamEchoRequestVersions,
    executionAllowed: reference.executionAllowed,
    connectsManagedAudit: reference.connectsManagedAudit,
    credentialValueRead: reference.credentialValueRead,
    rawEndpointUrlParsed: reference.rawEndpointUrlParsed,
    externalRequestSent: reference.externalRequestSent,
  });
}

function renderJavaV147(reference: JavaV147EndpointHandleAllowlistApprovalContractEchoReference): string[] {
  return [
    ...renderEntries({
      sourceVersion: reference.sourceVersion,
      receiptVersion: reference.receiptVersion,
      echoMode: reference.echoMode,
      sourceSpan: reference.sourceSpan,
      nextNodeVersion: reference.nextNodeVersion,
      evidencePresent: reference.evidencePresent,
      verificationDocumented: reference.verificationDocumented,
      echoesNodeV320Plan: reference.echoesNodeV320Plan,
      readyForNodeV321: reference.readyForNodeV321,
      endpointHandleAllowlistContractEchoed: reference.endpointHandleAllowlistContractEchoed,
      sideEffectBoundariesClosed: reference.sideEffectBoundariesClosed,
    }),
    "",
    "### Evidence Files",
    "",
    ...renderList(
      reference.evidenceFiles.map((file) => `${file.id}: exists=${file.exists}; digest=${file.digest ?? "missing"}`),
      "No Java v147 evidence files.",
    ),
  ];
}

function renderMiniKvV140(
  reference: MiniKvV140EndpointHandleAllowlistApprovalContractNonParticipationReceiptReference,
): string[] {
  return [
    ...renderEntries({
      sourceVersion: reference.sourceVersion,
      receiptVersion: reference.receiptVersion,
      releaseVersion: reference.releaseVersion,
      consumerHint: reference.consumerHint,
      evidencePresent: reference.evidencePresent,
      verificationDocumented: reference.verificationDocumented,
      sourceNodeV320ContractDigest: reference.sourceNodeV320ContractDigest,
      echoesNodeV320Plan: reference.echoesNodeV320Plan,
      readyForNodeV321: reference.readyForNodeV321,
      requiredFieldCount: reference.requiredFieldCount,
      prohibitedFieldCount: reference.prohibitedFieldCount,
      rejectionReasonCount: reference.rejectionReasonCount,
      noGoBoundaryCount: reference.noGoBoundaryCount,
      upstreamEchoRequestCount: reference.upstreamEchoRequestCount,
      sideEffectBoundariesClosed: reference.sideEffectBoundariesClosed,
      endpointAuthorityClaimed: reference.endpointAuthorityClaimed,
      endpointAllowlistAuthority: reference.endpointAllowlistAuthority,
      auditAuthoritative: reference.auditAuthoritative,
      orderAuthoritative: reference.orderAuthoritative,
    }),
    "",
    "### Evidence Files",
    "",
    ...renderList(
      reference.evidenceFiles.map((file) => `${file.id}: exists=${file.exists}; digest=${file.digest ?? "missing"}`),
      "No mini-kv v140 evidence files.",
    ),
  ];
}
