import type {
  ManagedAuditManualSandboxConnectionCredentialResolverImplementationCandidateGateInputHardeningDecisionProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverImplementationCandidateGateInputHardeningDecisionTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverImplementationCandidateGateInputHardeningDecisionMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverImplementationCandidateGateInputHardeningDecisionProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver implementation candidate gate input-hardening decision",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Candidate gate state: ${profile.candidateGateState}`,
    `- Candidate gate decision: ${profile.candidateGateDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source closure version: ${profile.sourceNodeClosureVersion}`,
    `- Ready for candidate gate decision: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverImplementationCandidateGateInputHardeningDecision}`,
    `- Ready for parallel Java v151 + mini-kv v143: ${profile.readyForParallelJavaV151MiniKvV143EchoRequest}`,
    `- Ready for Node v330 before upstream echo: ${profile.readyForNodeV330CandidateGateUpstreamAlignment}`,
    `- Ready for disabled runtime shell design draft: ${profile.readyForDisabledRuntimeShellDesignDraft}`,
    `- Ready for runtime shell implementation: ${profile.readyForRuntimeShellImplementation}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Credential value read: ${profile.credentialValueRead}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    `- HTTP request sent: ${profile.httpRequestSent}`,
    `- TCP connection attempted: ${profile.tcpConnectionAttempted}`,
    `- Java SQL execution allowed: ${profile.javaSqlExecutionAllowed}`,
    `- Rollback execution allowed: ${profile.rollbackExecutionAllowed}`,
    `- mini-kv write command allowed: ${profile.miniKvWriteCommandAllowed}`,
    `- Automatic upstream start: ${profile.automaticUpstreamStart}`,
    "",
    "## Source Node v328",
    "",
    `- Review state: ${profile.sourceNodeV328.reviewState}`,
    `- Ready for final closure review: ${profile.sourceNodeV328.readyForFinalPrerequisiteClosureReview}`,
    `- All prerequisites closed: ${profile.sourceNodeV328.allPrerequisitesClosed}`,
    `- Ready for implementation candidate gate: ${profile.sourceNodeV328.readyForImplementationCandidateGate}`,
    `- Closure digest: ${profile.sourceNodeV328.closureDigest}`,
    `- Source checks: ${profile.sourceNodeV328.sourcePassedCheckCount}/${profile.sourceNodeV328.sourceCheckCount}`,
    `- Source production blockers: ${profile.sourceNodeV328.sourceProductionBlockerCount}`,
    "",
    "## Necessity Proof",
    "",
    `- Blocker resolved: ${profile.necessityProof.blockerResolved}`,
    `- Consumer: ${profile.necessityProof.consumer}`,
    `- Why v328 cannot be reused: ${profile.necessityProof.whyV328CannotBeReused}`,
    `- Existing report reuse decision: ${profile.necessityProof.existingReportReuseDecision}`,
    `- Stop condition: ${profile.necessityProof.stopCondition}`,
    `- Proof complete: ${profile.necessityProof.proofComplete}`,
    "",
    "## Decision Record",
    "",
    `- Decision digest: ${profile.decisionRecord.decisionDigest}`,
    `- Record mode: ${profile.decisionRecord.recordMode}`,
    `- Decision scope: ${profile.decisionRecord.decisionScope}`,
    `- Decision: ${profile.decisionRecord.decision}`,
    `- Candidate gate entered: ${profile.decisionRecord.candidateGateEntered}`,
    `- Allows parallel Java v151 + mini-kv v143: ${profile.decisionRecord.allowsParallelJavaV151MiniKvV143EchoRequest}`,
    `- Allows Node v330 before upstream echo: ${profile.decisionRecord.allowsNodeV330BeforeUpstreamEcho}`,
    `- Allows disabled runtime design draft: ${profile.decisionRecord.allowsDisabledRuntimeShellDesignDraft}`,
    `- Allows disabled runtime implementation: ${profile.decisionRecord.allowsDisabledRuntimeShellImplementation}`,
    `- Allows managed audit connection: ${profile.decisionRecord.allowsManagedAuditConnection}`,
    `- Allows mini-kv write/admin command: ${profile.decisionRecord.allowsMiniKvWriteOrAdminCommand}`,
    `- Decision reason: ${profile.decisionRecord.decisionReason}`,
    "",
    "## Input Hardening Requirements",
    "",
    ...profile.decisionRecord.inputHardeningRequirements.map((entry) =>
      `- ${entry.id} [${entry.owner}] -> ${entry.requestedVersion}: ${entry.label}; status=${entry.status}; evidence=${entry.currentEvidence}`),
    "",
    "## No-Go Conditions",
    "",
    ...profile.decisionRecord.explicitNoGoConditions.map((condition) =>
      `- ${condition.code}: ${condition.condition}; action=${condition.action}`),
    "",
    "## Checks",
    "",
    ...Object.entries(profile.checks).map(([key, value]) => `- ${key}: ${value}`),
    "",
    "## Summary",
    "",
    `- Checks: ${profile.summary.passedCheckCount}/${profile.summary.checkCount}`,
    `- Source Node v328 checks: ${profile.summary.sourceNodeV328PassedCheckCount}/${profile.summary.sourceNodeV328CheckCount}`,
    `- Source production blockers: ${profile.summary.sourceProductionBlockerCount}`,
    `- Input hardening requirements: ${profile.summary.inputHardeningRequirementCount}`,
    `- No-go conditions: ${profile.summary.noGoConditionCount}`,
    `- Production blockers: ${profile.summary.productionBlockerCount}`,
    `- Warnings: ${profile.summary.warningCount}`,
    `- Recommendations: ${profile.summary.recommendationCount}`,
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...profile.nextActions.map((action) => `- ${action}`),
    "",
  ].join("\n");
}

function renderMessages(
  messages: readonly { code: string; severity: string; source: string; message: string }[],
  emptyMessage: string,
): string[] {
  if (messages.length === 0) {
    return [`- ${emptyMessage}`];
  }
  return messages.map((message) => `- [${message.severity}] ${message.code} (${message.source}): ${message.message}`);
}
