import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionArtifactUpstreamProgressIntakeProfile,
  RuntimePacketRequirementClarification,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionArtifactUpstreamProgressIntakeTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionArtifactUpstreamProgressIntakeMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionArtifactUpstreamProgressIntakeProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Upstream progress intake state: ${profile.upstreamProgressIntakeState}`,
    `- Upstream progress decision: ${profile.upstreamProgressDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for Node v397 runtime execution packet prerequisite review: ${profile.readyForNodeV397RuntimeExecutionPacketPrerequisiteReview}`,
    `- Ready for runtime execution packet: ${profile.readyForRuntimeExecutionPacket}`,
    `- Ready for runtime live-read gate: ${profile.readyForRuntimeLiveReadGate}`,
    `- Runtime execution artifacts complete: ${profile.runtimeExecutionArtifactsComplete}`,
    `- Present runtime execution artifact count: ${profile.presentRuntimeExecutionArtifactCount}`,
    `- Missing runtime execution artifact count: ${profile.missingRuntimeExecutionArtifactCount}`,
    `- Runtime execution packet present: ${profile.runtimeExecutionPacketPresent}`,
    `- Runtime execution packet executable: ${profile.runtimeExecutionPacketExecutable}`,
    `- Runtime gate approval present: ${profile.runtimeGateApprovalPresent}`,
    `- Concrete loopback ports assigned: ${profile.concreteLoopbackPortsAssigned}`,
    `- Execution attempted: ${profile.executionAttempted}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Stops Java service: ${profile.stopsJavaService}`,
    `- Stops mini-kv service: ${profile.stopsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Active shard prototype enabled: ${profile.activeShardPrototypeEnabled}`,
    "",
    "## Source Node v395",
    "",
    ...renderEntries(profile.sourceNodeV395),
    "",
    "## Java v162 Runtime Artifact Candidate",
    "",
    ...renderEntries(profile.javaV162RuntimeArtifactCandidate),
    "",
    "## mini-kv v153 Runtime Artifact Preflight",
    "",
    ...renderEntries(profile.miniKvV153RuntimeArtifactPreflight),
    "",
    "## Runtime Packet Requirement Clarification",
    "",
    ...profile.runtimePacketRequirements.flatMap(renderRequirement),
    "",
    "## Upstream Progress Clarification",
    "",
    ...renderEntries(profile.upstreamProgressClarification),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderRequirement(requirement: RuntimePacketRequirementClarification): string[] {
  return [
    `- ${requirement.key}: ${requirement.label}`,
    `  - javaCandidateStatus: ${requirement.javaCandidateStatus}`,
    `  - miniKvStatus: ${requirement.miniKvStatus}`,
    `  - operatorOrNodeStatus: ${requirement.operatorOrNodeStatus}`,
    `  - packetSatisfied: ${requirement.packetSatisfied}`,
  ];
}
