import { renderEntries } from "./liveProbeReportUtils.js";
import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftInstructionPreflight,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftInstructionPreflightGuard,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftInstructionPreflightSlot,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftInstructionPreflightTypes.js";

export function renderControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftInstructionPreflightMarkdown(
  preflight:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftInstructionPreflight,
): string {
  return [
    "# Controlled read-only shard preview live read-only window operator evidence value supply signed approval capture artifact draft instruction preflight",
    "",
    `- Signed approval capture artifact draft instruction preflight version: ${preflight.signedApprovalCaptureArtifactDraftInstructionPreflightVersion}`,
    `- Source signed approval capture artifact draft authoring readiness version: ${preflight.sourceSignedApprovalCaptureArtifactDraftAuthoringReadinessVersion}`,
    `- Artifact draft instruction preflight state: ${preflight.artifactDraftInstructionPreflightState}`,
    `- Ready for signed approval artifact draft instruction preflight: ${preflight.readyForSignedApprovalArtifactDraftInstructionPreflight}`,
    `- Ready for human signed approval draft instruction authoring: ${preflight.readyForHumanSignedApprovalDraftInstructionAuthoring}`,
    `- Ready for human signed approval draft artifact authoring: ${preflight.readyForHumanSignedApprovalDraftArtifactAuthoring}`,
    `- Ready for signed approval artifact draft: ${preflight.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${preflight.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${preflight.readyForOperatorValueSupply}`,
    `- Ready for operator value submission: ${preflight.readyForOperatorValueSubmission}`,
    `- Ready for evidence import: ${preflight.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${preflight.readyForRuntimePayload}`,
    `- Ready for live execution: ${preflight.readyForLiveExecution}`,
    `- Ready for production execution: ${preflight.readyForProductionExecution}`,
    `- Instruction slot count: ${preflight.instructionSlotCount}`,
    `- Instruction guard count: ${preflight.instructionGuardCount}`,
    `- Identity instruction slot count: ${preflight.identityInstructionSlotCount}`,
    `- Digest binding instruction slot count: ${preflight.digestBindingInstructionSlotCount}`,
    `- Signature envelope instruction slot count: ${preflight.signatureEnvelopeInstructionSlotCount}`,
    `- Source evidence instruction slot count: ${preflight.sourceEvidenceInstructionSlotCount}`,
    `- Value binding instruction slot count: ${preflight.valueBindingInstructionSlotCount}`,
    `- Policy instruction slot count: ${preflight.policyInstructionSlotCount}`,
    `- Execution lock instruction slot count: ${preflight.executionLockInstructionSlotCount}`,
    `- Archive closeout instruction slot count: ${preflight.archiveCloseoutInstructionSlotCount}`,
    `- Digest mode instruction slot count: ${preflight.digestModeInstructionSlotCount}`,
    `- Ready instruction slot count: ${preflight.readyInstructionSlotCount}`,
    `- Ready instruction guard count: ${preflight.readyInstructionGuardCount}`,
    `- Digest binding instruction guard count: ${preflight.digestBindingInstructionGuardCount}`,
    `- Signature envelope instruction guard count: ${preflight.signatureEnvelopeInstructionGuardCount}`,
    `- Policy instruction guard count: ${preflight.policyInstructionGuardCount}`,
    `- Execution lock instruction guard count: ${preflight.executionLockInstructionGuardCount}`,
    `- Archive closeout instruction guard count: ${preflight.archiveCloseoutInstructionGuardCount}`,
    `- Draft instruction materialized count: ${preflight.draftInstructionMaterializedCount}`,
    `- Draft artifact created: ${preflight.draftArtifactCreated}`,
    `- Signed draft text count: ${preflight.signedDraftTextCount}`,
    `- Draft signature payload count: ${preflight.draftSignaturePayloadCount}`,
    `- Approval captured: ${preflight.approvalCaptured}`,
    `- Approval grant present: ${preflight.approvalGrantPresent}`,
    `- Signed approval present: ${preflight.signedApprovalPresent}`,
    `- Source signed approval capture artifact draft authoring readiness digest: ${preflight.sourceSignedApprovalCaptureArtifactDraftAuthoringReadinessDigest}`,
    `- Source signed approval capture artifact draft review package preflight digest: ${preflight.sourceSignedApprovalCaptureArtifactDraftReviewPackagePreflightDigest}`,
    `- Source signed approval capture artifact draft readiness digest: ${preflight.sourceSignedApprovalCaptureArtifactDraftReadinessDigest}`,
    `- Source signed approval capture artifact draft preflight digest: ${preflight.sourceSignedApprovalCaptureArtifactDraftPreflightDigest}`,
    `- Source signed approval capture artifact preflight digest: ${preflight.sourceSignedApprovalCaptureArtifactPreflightDigest}`,
    `- Source signed approval capture preflight digest: ${preflight.sourceSignedApprovalCapturePreflightDigest}`,
    `- Source signed approval template digest: ${preflight.sourceSignedApprovalTemplateDigest}`,
    `- Source approval packet review digest: ${preflight.sourceApprovalPacketReviewDigest}`,
    `- Passed gates: ${preflight.passedGateCount}/${preflight.gateCount}`,
    `- Imports runtime payload: ${preflight.importsRuntimePayload}`,
    `- Accepts synthetic evidence: ${preflight.acceptsSyntheticEvidence}`,
    `- Contains secret value: ${preflight.containsSecretValue}`,
    `- Signed approval capture artifact draft instruction preflight digest: ${preflight.signedApprovalCaptureArtifactDraftInstructionPreflightDigest}`,
    "",
    "## Gates",
    ...renderEntries(preflight.gates),
    "",
    "## Instruction Slots",
    ...preflight.slots.flatMap(renderSlot),
    "## Instruction Guards",
    ...preflight.guards.flatMap(renderGuard),
    "## Blocked Reasons",
    ...(preflight.blockedReasonCodes.length === 0
      ? ["- none"]
      : preflight.blockedReasonCodes.map((reason) => `- ${reason}`)),
  ].join("\n");
}

function renderSlot(
  slot:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftInstructionPreflightSlot,
): string[] {
  return [
    `### ${slot.order}. ${slot.nodeVersion} ${slot.code}`,
    `- Instruction slot name: ${slot.instructionSlotName}`,
    `- Kind: ${slot.kind}`,
    `- Slot mode: ${slot.slotMode}`,
    `- Source authoring requirement: ${slot.sourceAuthoringRequirementCode}`,
    `- Source authoring requirement ready: ${slot.sourceAuthoringRequirementReady}`,
    `- Source authoring requirement kind: ${slot.sourceAuthoringRequirementKind}`,
    `- Source authoring requirement mode: ${slot.sourceAuthoringRequirementMode}`,
    `- Source authoring requirement read-only: ${slot.sourceAuthoringRequirementReadOnly}`,
    `- Source authoring instruction materialized: ${slot.sourceAuthoringInstructionMaterialized}`,
    `- Source draft artifact created: ${slot.sourceDraftArtifactCreated}`,
    `- Source signed draft text present: ${slot.sourceSignedDraftTextPresent}`,
    `- Source draft signature payload present: ${slot.sourceDraftSignaturePayloadPresent}`,
    `- Source approval grant present: ${slot.sourceApprovalGrantPresent}`,
    `- Source authoring blocker: ${slot.sourceAuthoringBlockerCode}`,
    `- Source authoring blocker ready: ${slot.sourceAuthoringBlockerReady}`,
    `- Source authoring blocker kind: ${slot.sourceAuthoringBlockerKind}`,
    `- Source authoring blocker read-only: ${slot.sourceAuthoringBlockerReadOnly}`,
    `- Source authoring blocker blocks instruction materialization: ${slot.sourceAuthoringBlockerBlocksInstructionMaterialization}`,
    `- Source authoring blocker blocks draft artifact creation: ${slot.sourceAuthoringBlockerBlocksDraftArtifactCreation}`,
    `- Source authoring blocker blocks signed draft text: ${slot.sourceAuthoringBlockerBlocksSignedDraftText}`,
    `- Source authoring blocker blocks signature payload: ${slot.sourceAuthoringBlockerBlocksSignaturePayload}`,
    `- Source authoring blocker blocks approval grant: ${slot.sourceAuthoringBlockerBlocksApprovalGrant}`,
    `- Source authoring blocker blocks runtime payload: ${slot.sourceAuthoringBlockerBlocksRuntimePayload}`,
    `- Source authoring blocker blocks writes: ${slot.sourceAuthoringBlockerBlocksWrites}`,
    `- Source authoring blocker blocks sibling mutation: ${slot.sourceAuthoringBlockerBlocksSiblingMutation}`,
    `- Instruction purpose: ${slot.instructionPurpose}`,
    `- Ready for human signed approval draft instruction slot: ${slot.readyForHumanSignedApprovalDraftInstructionSlot}`,
    `- Instruction materialized: ${slot.instructionMaterialized}`,
    `- Draft artifact created: ${slot.draftArtifactCreated}`,
    `- Signed draft text present: ${slot.signedDraftTextPresent}`,
    `- Draft signature payload present: ${slot.draftSignaturePayloadPresent}`,
    `- Approval grant present: ${slot.approvalGrantPresent}`,
    `- Ready for signed approval artifact draft: ${slot.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${slot.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${slot.readyForOperatorValueSupply}`,
    `- Ready for evidence import: ${slot.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${slot.readyForRuntimePayload}`,
    `- Writes allowed: ${slot.writesAllowed}`,
    `- Starts services: ${slot.startsServices}`,
    `- Mutates sibling state: ${slot.mutatesSiblingState}`,
    "",
  ];
}

function renderGuard(
  guard:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftInstructionPreflightGuard,
): string[] {
  return [
    `### ${guard.order}. ${guard.nodeVersion} ${guard.code}`,
    `- Kind: ${guard.kind}`,
    `- Source instruction slot: ${guard.sourceInstructionSlotCode}`,
    `- Source instruction slot ready: ${guard.sourceInstructionSlotReady}`,
    `- Source authoring blocker kind: ${guard.sourceAuthoringBlockerKind}`,
    `- Guard code: ${guard.guardCode}`,
    `- Guard text: ${guard.guardText}`,
    `- Rejects missing instruction slot: ${guard.rejectsMissingInstructionSlot}`,
    `- Blocks instruction materialization: ${guard.blocksInstructionMaterialization}`,
    `- Blocks draft artifact creation: ${guard.blocksDraftArtifactCreation}`,
    `- Blocks signed draft text: ${guard.blocksSignedDraftText}`,
    `- Blocks signature payload: ${guard.blocksSignaturePayload}`,
    `- Blocks approval grant: ${guard.blocksApprovalGrant}`,
    `- Blocks runtime payload: ${guard.blocksRuntimePayload}`,
    `- Blocks writes: ${guard.blocksWrites}`,
    `- Blocks sibling mutation: ${guard.blocksSiblingMutation}`,
    `- Ready for human signed approval draft instruction guard: ${guard.readyForHumanSignedApprovalDraftInstructionGuard}`,
    `- Ready for signed approval artifact draft: ${guard.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${guard.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${guard.readyForOperatorValueSupply}`,
    `- Ready for evidence import: ${guard.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${guard.readyForRuntimePayload}`,
    `- Writes allowed: ${guard.writesAllowed}`,
    `- Starts services: ${guard.startsServices}`,
    `- Mutates sibling state: ${guard.mutatesSiblingState}`,
    "",
  ];
}
