import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionFakeTransportAdapterDryRunVerificationPacketProfile,
} from "./managedAuditManualSandboxConnectionFakeTransportAdapterDryRunVerificationPacketTypes.js";

export function renderManagedAuditManualSandboxConnectionFakeTransportAdapterDryRunVerificationPacketMarkdown(
  profile: ManagedAuditManualSandboxConnectionFakeTransportAdapterDryRunVerificationPacketProfile,
): string {
  return [
    "# Managed audit manual sandbox connection fake transport adapter dry-run verification packet",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Packet state: ${profile.packetState}`,
    `- Ready for fake transport dry-run packet: ${profile.readyForManagedAuditManualSandboxConnectionFakeTransportAdapterDryRunVerificationPacket}`,
    `- Ready for sandbox adapter connection: ${profile.readyForManagedAuditSandboxAdapterConnection}`,
    "",
    "## Source Node v253",
    "",
    ...renderEntries(profile.sourceNodeV253),
    "",
    "## Source Node v254",
    "",
    ...renderEntries(profile.sourceNodeV254),
    "",
    "## Packet",
    "",
    ...renderEntries({
      packetDigest: profile.fakeTransportDryRunPacket.packetDigest,
      packetMode: profile.fakeTransportDryRunPacket.packetMode,
      sourceSpan: profile.fakeTransportDryRunPacket.sourceSpan,
    }),
    "",
    "## Request",
    "",
    ...renderEntries(profile.fakeTransportDryRunPacket.request),
    "",
    "## Response",
    "",
    ...renderEntries(profile.fakeTransportDryRunPacket.response),
    "",
    "## Timeout Budget",
    "",
    ...renderEntries(profile.fakeTransportDryRunPacket.timeoutBudget),
    "",
    "## Failure Mapping Verification",
    "",
    ...renderEntries(profile.fakeTransportDryRunPacket.failureMappingVerification),
    "",
    "## Cleanup",
    "",
    ...renderEntries(profile.fakeTransportDryRunPacket.cleanup),
    "",
    "## Boundaries",
    "",
    ...renderEntries(profile.fakeTransportDryRunPacket.boundaries),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No fake transport adapter dry-run packet blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No fake transport adapter dry-run packet warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No fake transport adapter dry-run packet recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
