import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftPreflightGuardTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftPreflightTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_GUARDS:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftPreflightGuardTemplate[]
  = Object.freeze([
    guard("Node v1087", "ARTIFACT_DRAFT_PREFLIGHT_REQUEST_ID_GUARD", "required-field-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_REQUEST_ID", "REJECT_DRAFT_REQUEST_ID_MISSING",
      "Reject artifact draft preflight without a stable draft request id field."),
    guard("Node v1088", "ARTIFACT_DRAFT_PREFLIGHT_ARTIFACT_PREFLIGHT_DIGEST_GUARD", "digest-binding-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_ARTIFACT_PREFLIGHT_DIGEST",
      "REJECT_ARTIFACT_PREFLIGHT_DIGEST_MISSING", "Reject draft preflight without v1086 digest binding."),
    guard("Node v1089", "ARTIFACT_DRAFT_PREFLIGHT_TEMPLATE_DIGEST_GUARD", "digest-binding-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_TEMPLATE_DIGEST",
      "REJECT_TEMPLATE_DIGEST_MISSING", "Reject draft preflight without v1036 template digest binding."),
    guard("Node v1090", "ARTIFACT_DRAFT_PREFLIGHT_REVIEW_DIGEST_GUARD", "digest-binding-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_REVIEW_DIGEST",
      "REJECT_REVIEW_DIGEST_MISSING", "Reject draft preflight without approval packet review digest binding."),
    guard("Node v1091", "ARTIFACT_DRAFT_PREFLIGHT_OPERATOR_IDENTITY_GUARD", "required-field-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_OPERATOR_IDENTITY",
      "REJECT_OPERATOR_IDENTITY_MISSING", "Reject draft preflight without operator identity."),
    guard("Node v1092", "ARTIFACT_DRAFT_PREFLIGHT_OPERATOR_ROLE_GUARD", "required-field-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_OPERATOR_ROLE",
      "REJECT_OPERATOR_ROLE_MISSING", "Reject draft preflight without operator role."),
    guard("Node v1093", "ARTIFACT_DRAFT_PREFLIGHT_WINDOW_ID_GUARD", "required-field-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_WINDOW_ID",
      "REJECT_CAPTURE_WINDOW_ID_MISSING", "Reject draft preflight without capture window id."),
    guard("Node v1094", "ARTIFACT_DRAFT_PREFLIGHT_CHANNEL_POLICY_GUARD", "policy-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_CHANNEL_POLICY",
      "REJECT_CAPTURE_CHANNEL_POLICY_MISSING", "Reject draft preflight without capture channel policy."),
    guard("Node v1095", "ARTIFACT_DRAFT_PREFLIGHT_SIGNATURE_ALGORITHM_GUARD", "signature-envelope-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SIGNATURE_ALGORITHM",
      "REJECT_SIGNATURE_ALGORITHM_MISSING", "Reject draft preflight without signature algorithm policy."),
    guard("Node v1096", "ARTIFACT_DRAFT_PREFLIGHT_DETACHED_SIGNATURE_PLACEHOLDER_GUARD",
      "signature-envelope-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_DETACHED_SIGNATURE_PLACEHOLDER",
      "REJECT_DETACHED_SIGNATURE_PLACEHOLDER_MISSING",
      "Reject draft preflight without detached signature placeholder."),
    guard("Node v1097", "ARTIFACT_DRAFT_PREFLIGHT_SIGNATURE_REDACTION_GUARD", "signature-envelope-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SIGNATURE_REDACTION",
      "REJECT_SIGNATURE_REDACTION_MISSING", "Reject draft preflight without signature redaction policy."),
    guard("Node v1098", "ARTIFACT_DRAFT_PREFLIGHT_APPROVAL_STATEMENT_DIGEST_GUARD", "digest-binding-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_APPROVAL_STATEMENT_DIGEST",
      "REJECT_APPROVAL_STATEMENT_DIGEST_MISSING",
      "Reject draft preflight without approval statement digest placeholder."),
    guard("Node v1099", "ARTIFACT_DRAFT_PREFLIGHT_SOURCE_VERSION_GUARD", "required-field-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SOURCE_VERSION",
      "REJECT_SOURCE_VERSION_MISSING", "Reject draft preflight without source evidence version."),
    guard("Node v1100", "ARTIFACT_DRAFT_PREFLIGHT_SOURCE_FILE_GUARD", "required-field-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SOURCE_FILE",
      "REJECT_SOURCE_FILE_MISSING", "Reject draft preflight without source evidence file id."),
    guard("Node v1101", "ARTIFACT_DRAFT_PREFLIGHT_SOURCE_SNIPPET_GUARD", "required-field-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SOURCE_SNIPPET",
      "REJECT_SOURCE_SNIPPET_MISSING", "Reject draft preflight without source evidence snippet id."),
    guard("Node v1102", "ARTIFACT_DRAFT_PREFLIGHT_REDACTED_VALUE_DIGEST_GUARD", "required-field-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_REDACTED_VALUE_DIGEST",
      "REJECT_REDACTED_VALUE_DIGEST_MISSING", "Reject draft preflight without redacted value digest."),
    guard("Node v1103", "ARTIFACT_DRAFT_PREFLIGHT_VALUE_SHAPE_GUARD", "required-field-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_VALUE_SHAPE",
      "REJECT_VALUE_SHAPE_MISSING", "Reject draft preflight without value shape."),
    guard("Node v1104", "ARTIFACT_DRAFT_PREFLIGHT_REDACTION_POLICY_GUARD", "policy-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_REDACTION_POLICY",
      "REJECT_REDACTION_POLICY_MISSING", "Reject draft preflight without redaction policy."),
    guard("Node v1105", "ARTIFACT_DRAFT_PREFLIGHT_PROVENANCE_POLICY_GUARD", "policy-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_PROVENANCE_POLICY",
      "REJECT_PROVENANCE_POLICY_MISSING", "Reject draft preflight without provenance policy."),
    guard("Node v1106", "ARTIFACT_DRAFT_PREFLIGHT_NO_RAW_SECRET_GUARD", "no-execution-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_NO_RAW_SECRET_LOCK",
      "REJECT_RAW_SECRET_PRESENT", "Block artifact draft preflight if raw secret or signature material is present."),
    guard("Node v1107", "ARTIFACT_DRAFT_PREFLIGHT_NO_GRANT_GUARD", "no-execution-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_NO_GRANT_LOCK",
      "REJECT_APPROVAL_GRANT_EMITTED", "Block artifact draft preflight if an approval grant was emitted."),
    guard("Node v1108", "ARTIFACT_DRAFT_PREFLIGHT_ZERO_VALUE_IMPORT_GUARD", "no-execution-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_ZERO_VALUE_IMPORT_LOCK",
      "REJECT_VALUE_IMPORT_NONZERO", "Block artifact draft preflight if value submission or import counts are nonzero."),
    guard("Node v1109", "ARTIFACT_DRAFT_PREFLIGHT_NO_WRITE_ROUTE_GUARD", "no-execution-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_NO_WRITE_ROUTE_LOCK",
      "REJECT_WRITE_ROUTE_ENABLED", "Block artifact draft preflight if write routing is enabled."),
    guard("Node v1110", "ARTIFACT_DRAFT_PREFLIGHT_SIBLING_NON_MUTATION_GUARD", "no-execution-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SIBLING_NON_MUTATION_LOCK",
      "REJECT_SIBLING_MUTATION_ENABLED", "Block artifact draft preflight if sibling mutation is enabled."),
    guard("Node v1111", "ARTIFACT_DRAFT_PREFLIGHT_CLOSEOUT_GUARD", "closeout-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_CLOSEOUT",
      "REJECT_NEXT_STEP_NOT_MANUAL_ARTIFACT_DRAFT",
      "Close artifact draft preflight at manual signed approval draft readiness."),
  ]);

function guard(
  nodeVersion:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftPreflightGuardTemplate[
      "nodeVersion"
    ],
  code: string,
  kind:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftPreflightGuardTemplate[
      "kind"
    ],
  sourceDraftFieldCode: string,
  rejectionCode: string,
  guardText: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftPreflightGuardTemplate {
  return {
    nodeVersion,
    code,
    kind,
    sourceDraftFieldCode,
    rejectionCode,
    guardText,
  };
}
