import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionApprovalInputIntakeContractProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionApprovalInputIntakeContractTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionApprovalInputIntakeContractMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionApprovalInputIntakeContractProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Intake state: ${profile.intakeState}`,
    `- Intake decision: ${profile.intakeDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Java source version: ${profile.javaSourceVersion}`,
    `- mini-kv source version: ${profile.miniKvSourceVersion}`,
    `- Ready for runtime execution approval input intake contract: ${profile.readyForRuntimeExecutionApprovalInputIntakeContract}`,
    `- Ready for runtime execution packet: ${profile.readyForRuntimeExecutionPacket}`,
    `- Ready for runtime live-read gate: ${profile.readyForRuntimeLiveReadGate}`,
    `- Runtime execution artifacts complete: ${profile.runtimeExecutionArtifactsComplete}`,
    `- Present runtime execution artifact count: ${profile.presentRuntimeExecutionArtifactCount}`,
    `- Missing runtime execution artifact count: ${profile.missingRuntimeExecutionArtifactCount}`,
    `- Runtime execution packet present: ${profile.runtimeExecutionPacketPresent}`,
    `- Runtime execution packet executable: ${profile.runtimeExecutionPacketExecutable}`,
    `- Runtime gate approval present: ${profile.runtimeGateApprovalPresent}`,
    `- Concrete loopback ports assigned: ${profile.concreteLoopbackPortsAssigned}`,
    `- Execution attempted: ${profile.executionAttempted}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Active shard prototype enabled: ${profile.activeShardPrototypeEnabled}`,
    "",
    "## Source Node v399",
    "",
    ...renderEntries(profile.sourceNodeV399),
    "",
    "## Java v164 Approval Gate Input",
    "",
    ...renderEntries(profile.javaV164ApprovalGateInput),
    "",
    "## mini-kv v155 Approval Gate Input Precheck",
    "",
    ...renderEntries(profile.miniKvV155ApprovalGateInputPrecheck),
    "",
    "## Required Node Approval Inputs",
    "",
    ...profile.nodeApprovalGateInputs.flatMap(renderNodeInput),
    "## Handoff Requirements",
    "",
    ...profile.handoffRequirements.flatMap(renderHandoffRequirement),
    "## Intake Contract",
    "",
    ...renderEntries(profile.intakeContract),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderNodeInput(input: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionApprovalInputIntakeContractProfile["nodeApprovalGateInputs"][number]): string[] {
  return [
    `- ${input.label}`,
    `  - key: ${input.key}`,
    `  - owner: ${input.owner}`,
    `  - present: ${input.present}`,
    `  - complete: ${input.complete}`,
    `  - file: ${JSON.stringify(input.file)}`,
    `  - missingReasonCode: ${input.missingReasonCode}`,
    `  - requiredContents: ${JSON.stringify(input.requiredContents)}`,
  ];
}

function renderHandoffRequirement(
  requirement: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionApprovalInputIntakeContractProfile["handoffRequirements"][number],
): string[] {
  return [
    `- ${requirement.id}`,
    `  - owner: ${requirement.owner}`,
    `  - currentStatus: ${requirement.currentStatus}`,
    `  - blocksRuntime: ${requirement.blocksRuntime}`,
    `  - expectedEvidence: ${requirement.expectedEvidence}`,
    `  - currentEvidence: ${requirement.currentEvidence}`,
    `  - nextAction: ${requirement.nextAction}`,
  ];
}
