import { renderEntries, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ArchiveFileReference,
  ManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyPreDraftDecisionArchiveVerificationProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyPreDraftDecisionArchiveVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyPreDraftDecisionArchiveVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyPreDraftDecisionArchiveVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver disabled runtime shell design draft body pre-draft decision archive verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Archive verification state: ${profile.archiveVerificationState}`,
    `- Archive verification decision: ${profile.archiveVerificationDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for v340 pre-draft decision archive verification: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyPreDraftDecisionArchiveVerification}`,
    `- Ready for Node v341 body preparation plan: ${profile.readyForNodeV341DisabledRuntimeShellDesignDraftBodyPreparationPlan}`,
    `- Ready for disabled runtime shell design draft: ${profile.readyForDisabledRuntimeShellDesignDraft}`,
    `- Ready for disabled runtime shell design draft outline: ${profile.readyForDisabledRuntimeShellDesignDraftOutline}`,
    `- Ready for runtime shell implementation: ${profile.readyForRuntimeShellImplementation}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Credential value read: ${profile.credentialValueRead}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    `- HTTP request sent: ${profile.httpRequestSent}`,
    `- TCP connection attempted: ${profile.tcpConnectionAttempted}`,
    `- Java SQL execution allowed: ${profile.javaSqlExecutionAllowed}`,
    `- mini-kv write command allowed: ${profile.miniKvWriteCommandAllowed}`,
    `- Automatic upstream start: ${profile.automaticUpstreamStart}`,
    "",
    "## Source Node v339",
    "",
    ...renderEntries({
      preDraftDecisionState: profile.sourceNodeV339.preDraftDecisionState,
      preDraftDecision: profile.sourceNodeV339.preDraftDecision,
      readyForPreDraftDecision: profile.sourceNodeV339.readyForPreDraftDecision,
      readyForNodeV340DisabledRuntimeShellDesignDraftBodyPreDraftDecisionArchiveVerification:
        profile.sourceNodeV339.readyForNodeV340DisabledRuntimeShellDesignDraftBodyPreDraftDecisionArchiveVerification,
      decisionDigest: profile.sourceNodeV339.decisionDigest,
      sourceArchiveVerificationDigest: profile.sourceNodeV339.sourceArchiveVerificationDigest,
      sourceReviewDigest: profile.sourceNodeV339.sourceReviewDigest,
      sourceChecks: `${profile.sourceNodeV339.sourcePassedCheckCount}/${profile.sourceNodeV339.sourceCheckCount}`,
      sourceArchiveFiles:
        `${profile.sourceNodeV339.sourcePresentArchiveFileCount}/${profile.sourceNodeV339.sourceArchiveFileCount}`,
      sourceProductionBlockers: profile.sourceNodeV339.sourceProductionBlockerCount,
      sourceBodySections: profile.sourceNodeV339.sourceBodySectionCount,
      sourceEvidenceItems: profile.sourceNodeV339.sourceEvidenceItemCount,
      sourceStopConditions: profile.sourceNodeV339.sourceStopConditionCount,
      decisionQuestions:
        `${profile.sourceNodeV339.answeredDecisionQuestionCount}/${profile.sourceNodeV339.decisionQuestionCount}`,
      preparationControls:
        `${profile.sourceNodeV339.enforcedPreparationControlCount}/${profile.sourceNodeV339.preparationControlCount}`,
    }),
    "",
    "## Archive Verification",
    "",
    ...renderEntries({
      verificationDigest: profile.archiveVerification.verificationDigest,
      verificationMode: profile.archiveVerification.verificationMode,
      sourceSpan: profile.archiveVerification.sourceSpan,
      decision: profile.archiveVerification.decision,
      archiveRoot: profile.archiveVerification.archiveRoot,
      verifiesRouteAndMarkdown: profile.archiveVerification.verifiesRouteAndMarkdown,
      verifiesSmokeSummary: profile.archiveVerification.verifiesSmokeSummary,
      verifiesScreenshotAndExplanation: profile.archiveVerification.verifiesScreenshotAndExplanation,
      verifiesCodeWalkthroughAndPlanIndex: profile.archiveVerification.verifiesCodeWalkthroughAndPlanIndex,
      verifiesHistoricalFallbackArchive: profile.archiveVerification.verifiesHistoricalFallbackArchive,
      rerunsSourceEndpoint: profile.archiveVerification.rerunsSourceEndpoint,
      writesBodyDraftNow: profile.archiveVerification.writesBodyDraftNow,
      opensDisabledDesignDraftBodyNow: profile.archiveVerification.opensDisabledDesignDraftBodyNow,
      implementsRuntimeShell: profile.archiveVerification.implementsRuntimeShell,
      invokesRuntimeShell: profile.archiveVerification.invokesRuntimeShell,
      requestsJavaMiniKvEcho: profile.archiveVerification.requestsJavaMiniKvEcho,
      readyForNodeV341DisabledRuntimeShellDesignDraftBodyPreparationPlan:
        profile.archiveVerification.readyForNodeV341DisabledRuntimeShellDesignDraftBodyPreparationPlan,
      nextNodeVersionSuggested: profile.archiveVerification.nextNodeVersionSuggested,
    }),
    "",
    "## Archive References",
    "",
    ...renderArchiveFileReferences([
      profile.archiveReferences.jsonEvidence,
      profile.archiveReferences.markdownEvidence,
      profile.archiveReferences.smokeSummary,
      profile.archiveReferences.routeSnapshot,
      profile.archiveReferences.browserSnapshot,
      profile.archiveReferences.htmlArchive,
      profile.archiveReferences.screenshot,
      profile.archiveReferences.explanation,
      profile.archiveReferences.codeWalkthrough,
      profile.archiveReferences.activePlan,
      profile.archiveReferences.plansIndex,
    ]),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    `- Checks: ${profile.summary.passedCheckCount}/${profile.summary.checkCount}`,
    `- Source Node v339 checks: ${profile.summary.sourceNodeV339PassedCheckCount}/${profile.summary.sourceNodeV339CheckCount}`,
    `- Source archive files: ${profile.summary.sourcePresentArchiveFileCount}/${profile.summary.sourceArchiveFileCount}`,
    `- Source production blockers: ${profile.summary.sourceProductionBlockerCount}`,
    `- Source body sections: ${profile.summary.sourceBodySectionCount}`,
    `- Source evidence items: ${profile.summary.sourceEvidenceItemCount}`,
    `- Source stop conditions: ${profile.summary.sourceStopConditionCount}`,
    `- Decision questions: ${profile.summary.answeredDecisionQuestionCount}/${profile.summary.decisionQuestionCount}`,
    `- Preparation controls: ${profile.summary.enforcedPreparationControlCount}/${profile.summary.preparationControlCount}`,
    `- Archive files present: ${profile.summary.presentArchiveFileCount}/${profile.summary.archiveFileCount}`,
    `- Production blockers: ${profile.summary.productionBlockerCount}`,
    `- Warnings: ${profile.summary.warningCount}`,
    `- Recommendations: ${profile.summary.recommendationCount}`,
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...profile.nextActions.map((item) => `- ${item}`),
    "",
  ].join("\n");
}

function renderArchiveFileReferences(files: readonly ArchiveFileReference[]): string[] {
  return files.map((file) =>
    `- ${file.path}: exists=${file.exists}; bytes=${file.byteLength}; digest=${file.digest ?? "missing"}`);
}
