import { renderEntries } from "./liveProbeReportUtils.js";
import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadiness,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessBlocker,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessRequirement,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessTypes.js";
import {
  renderVerificationBlockedReasonLines,
  renderVerificationReportMarkdown,
  trimVerificationTrailingBlankLine,
} from "./verificationReportBuilder.js";

export function renderControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessMarkdown(
  readiness:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadiness,
): string {
  return renderVerificationReportMarkdown({
    title: "Controlled read-only shard preview live read-only window operator evidence value supply signed approval capture artifact draft authoring readiness",
    meta: [
      ["Signed approval capture artifact draft authoring readiness version", `${readiness.signedApprovalCaptureArtifactDraftAuthoringReadinessVersion}`],
      ["Source signed approval capture artifact draft review package preflight version", `${readiness.sourceSignedApprovalCaptureArtifactDraftReviewPackagePreflightVersion}`],
      ["Artifact draft authoring readiness state", `${readiness.artifactDraftAuthoringReadinessState}`],
      ["Ready for signed approval artifact draft authoring readiness", `${readiness.readyForSignedApprovalArtifactDraftAuthoringReadiness}`],
      ["Ready for human signed approval draft artifact authoring", `${readiness.readyForHumanSignedApprovalDraftArtifactAuthoring}`],
      ["Ready for manual signed approval draft review package", `${readiness.readyForManualSignedApprovalDraftReviewPackage}`],
      ["Ready for signed approval artifact draft", `${readiness.readyForSignedApprovalArtifactDraft}`],
      ["Ready for signed approval capture", `${readiness.readyForSignedApprovalCapture}`],
      ["Ready for operator value supply", `${readiness.readyForOperatorValueSupply}`],
      ["Ready for operator value submission", `${readiness.readyForOperatorValueSubmission}`],
      ["Ready for evidence import", `${readiness.readyForEvidenceImport}`],
      ["Ready for runtime payload", `${readiness.readyForRuntimePayload}`],
      ["Ready for live execution", `${readiness.readyForLiveExecution}`],
      ["Ready for production execution", `${readiness.readyForProductionExecution}`],
      ["Authoring requirement count", `${readiness.authoringRequirementCount}`],
      ["Authoring blocker count", `${readiness.authoringBlockerCount}`],
      ["Identity authoring requirement count", `${readiness.identityAuthoringRequirementCount}`],
      ["Digest binding authoring requirement count", `${readiness.digestBindingAuthoringRequirementCount}`],
      ["Signature envelope authoring requirement count", `${readiness.signatureEnvelopeAuthoringRequirementCount}`],
      ["Source evidence authoring requirement count", `${readiness.sourceEvidenceAuthoringRequirementCount}`],
      ["Value binding authoring requirement count", `${readiness.valueBindingAuthoringRequirementCount}`],
      ["Policy authoring requirement count", `${readiness.policyAuthoringRequirementCount}`],
      ["Execution lock authoring requirement count", `${readiness.executionLockAuthoringRequirementCount}`],
      ["Archive closeout authoring requirement count", `${readiness.archiveCloseoutAuthoringRequirementCount}`],
      ["Digest mode authoring requirement count", `${readiness.digestModeAuthoringRequirementCount}`],
      ["Ready authoring requirement count", `${readiness.readyAuthoringRequirementCount}`],
      ["Ready authoring blocker count", `${readiness.readyAuthoringBlockerCount}`],
      ["Digest binding authoring blocker count", `${readiness.digestBindingAuthoringBlockerCount}`],
      ["Signature envelope authoring blocker count", `${readiness.signatureEnvelopeAuthoringBlockerCount}`],
      ["Policy authoring blocker count", `${readiness.policyAuthoringBlockerCount}`],
      ["Execution lock authoring blocker count", `${readiness.executionLockAuthoringBlockerCount}`],
      ["Archive closeout authoring blocker count", `${readiness.archiveCloseoutAuthoringBlockerCount}`],
      ["Authoring instruction materialized count", `${readiness.authoringInstructionMaterializedCount}`],
      ["Draft artifact created", `${readiness.draftArtifactCreated}`],
      ["Signed draft text count", `${readiness.signedDraftTextCount}`],
      ["Draft signature payload count", `${readiness.draftSignaturePayloadCount}`],
      ["Approval captured", `${readiness.approvalCaptured}`],
      ["Approval grant present", `${readiness.approvalGrantPresent}`],
      ["Signed approval present", `${readiness.signedApprovalPresent}`],
      ["Source signed approval capture artifact draft review package preflight digest", `${readiness.sourceSignedApprovalCaptureArtifactDraftReviewPackagePreflightDigest}`],
      ["Source signed approval capture artifact draft readiness digest", `${readiness.sourceSignedApprovalCaptureArtifactDraftReadinessDigest}`],
      ["Source signed approval capture artifact draft preflight digest", `${readiness.sourceSignedApprovalCaptureArtifactDraftPreflightDigest}`],
      ["Source signed approval capture artifact preflight digest", `${readiness.sourceSignedApprovalCaptureArtifactPreflightDigest}`],
      ["Source signed approval capture preflight digest", `${readiness.sourceSignedApprovalCapturePreflightDigest}`],
      ["Source signed approval template digest", `${readiness.sourceSignedApprovalTemplateDigest}`],
      ["Source approval packet review digest", `${readiness.sourceApprovalPacketReviewDigest}`],
      ["Passed gates", `${readiness.passedGateCount}/${readiness.gateCount}`],
      ["Imports runtime payload", `${readiness.importsRuntimePayload}`],
      ["Accepts synthetic evidence", `${readiness.acceptsSyntheticEvidence}`],
      ["Contains secret value", `${readiness.containsSecretValue}`],
      ["Signed approval capture artifact draft authoring readiness digest", `${readiness.signedApprovalCaptureArtifactDraftAuthoringReadinessDigest}`],
    ],
    trailingNewline: false,
    sections: [
      {
        heading: "Gates",
        lines: renderEntries(readiness.gates),
        bodyLeadingBlankLine: false,
      },
      {
        heading: "Authoring Requirements",
        lines: trimVerificationTrailingBlankLine(readiness.requirements.flatMap(renderRequirement)),
        bodyLeadingBlankLine: false,
      },
      {
        heading: "Authoring Blockers",
        lines: trimVerificationTrailingBlankLine(readiness.blockers.flatMap(renderBlocker)),
        bodyLeadingBlankLine: false,
      },
      {
        heading: "Blocked Reasons",
        lines: renderVerificationBlockedReasonLines(readiness.blockedReasonCodes),
        bodyLeadingBlankLine: false,
      },
    ],
  });
}

function renderRequirement(
  requirement:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessRequirement,
): string[] {
  return [
    `### ${requirement.order}. ${requirement.nodeVersion} ${requirement.code}`,
    `- Authoring requirement name: ${requirement.authoringRequirementName}`,
    `- Kind: ${requirement.kind}`,
    `- Requirement mode: ${requirement.requirementMode}`,
    `- Source package slot: ${requirement.sourcePackageSlotCode}`,
    `- Source package slot ready: ${requirement.sourcePackageSlotReady}`,
    `- Source package slot kind: ${requirement.sourcePackageSlotKind}`,
    `- Source package slot mode: ${requirement.sourcePackageSlotMode}`,
    `- Source package slot read-only: ${requirement.sourcePackageSlotReadOnly}`,
    `- Source package slot materialized: ${requirement.sourcePackageSlotMaterialized}`,
    `- Source package artifact created: ${requirement.sourcePackageArtifactCreated}`,
    `- Source signed draft text present: ${requirement.sourceSignedDraftTextPresent}`,
    `- Source draft signature payload present: ${requirement.sourceDraftSignaturePayloadPresent}`,
    `- Source approval grant present: ${requirement.sourceApprovalGrantPresent}`,
    `- Source package guard: ${requirement.sourcePackageGuardCode}`,
    `- Source package guard ready: ${requirement.sourcePackageGuardReady}`,
    `- Source package guard kind: ${requirement.sourcePackageGuardKind}`,
    `- Source package guard read-only: ${requirement.sourcePackageGuardReadOnly}`,
    `- Source package guard blocks package materialization: ${requirement.sourcePackageGuardBlocksPackageMaterialization}`,
    `- Source package guard blocks signed draft text: ${requirement.sourcePackageGuardBlocksSignedDraftText}`,
    `- Source package guard blocks signature payload: ${requirement.sourcePackageGuardBlocksSignaturePayload}`,
    `- Source package guard blocks approval grant: ${requirement.sourcePackageGuardBlocksApprovalGrant}`,
    `- Required package slot mode: ${requirement.requiredPackageSlotMode}`,
    `- Required package slot mode covered: ${requirement.requiredPackageSlotModeCovered}`,
    `- Authoring purpose: ${requirement.authoringPurpose}`,
    `- Ready for human signed approval draft artifact authoring requirement: ${requirement.readyForHumanSignedApprovalDraftArtifactAuthoringRequirement}`,
    `- Authoring instruction materialized: ${requirement.authoringInstructionMaterialized}`,
    `- Draft artifact created: ${requirement.draftArtifactCreated}`,
    `- Signed draft text present: ${requirement.signedDraftTextPresent}`,
    `- Draft signature payload present: ${requirement.draftSignaturePayloadPresent}`,
    `- Approval grant present: ${requirement.approvalGrantPresent}`,
    `- Ready for signed approval artifact draft: ${requirement.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${requirement.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${requirement.readyForOperatorValueSupply}`,
    `- Ready for evidence import: ${requirement.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${requirement.readyForRuntimePayload}`,
    `- Writes allowed: ${requirement.writesAllowed}`,
    `- Starts services: ${requirement.startsServices}`,
    `- Mutates sibling state: ${requirement.mutatesSiblingState}`,
    "",
  ];
}

function renderBlocker(
  blocker:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftAuthoringReadinessBlocker,
): string[] {
  return [
    `### ${blocker.order}. ${blocker.nodeVersion} ${blocker.code}`,
    `- Kind: ${blocker.kind}`,
    `- Source authoring requirement: ${blocker.sourceAuthoringRequirementCode}`,
    `- Source authoring requirement ready: ${blocker.sourceAuthoringRequirementReady}`,
    `- Blocker code: ${blocker.blockerCode}`,
    `- Blocker text: ${blocker.blockerText}`,
    `- Rejects missing authoring requirement: ${blocker.rejectsMissingAuthoringRequirement}`,
    `- Blocks authoring instruction materialization: ${blocker.blocksAuthoringInstructionMaterialization}`,
    `- Blocks draft artifact creation: ${blocker.blocksDraftArtifactCreation}`,
    `- Blocks signed draft text: ${blocker.blocksSignedDraftText}`,
    `- Blocks signature payload: ${blocker.blocksSignaturePayload}`,
    `- Blocks approval grant: ${blocker.blocksApprovalGrant}`,
    `- Blocks runtime payload: ${blocker.blocksRuntimePayload}`,
    `- Blocks writes: ${blocker.blocksWrites}`,
    `- Blocks sibling mutation: ${blocker.blocksSiblingMutation}`,
    `- Ready for human signed approval draft artifact authoring blocker: ${blocker.readyForHumanSignedApprovalDraftArtifactAuthoringBlocker}`,
    `- Ready for signed approval artifact draft: ${blocker.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${blocker.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${blocker.readyForOperatorValueSupply}`,
    `- Ready for evidence import: ${blocker.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${blocker.readyForRuntimePayload}`,
    `- Writes allowed: ${blocker.writesAllowed}`,
    `- Starts services: ${blocker.startsServices}`,
    `- Mutates sibling state: ${blocker.mutatesSiblingState}`,
    "",
  ];
}
