import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReadinessLaneTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReadinessTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_VERSIONS = [
  "Node v1112",
  "Node v1113",
  "Node v1114",
  "Node v1115",
  "Node v1116",
  "Node v1117",
  "Node v1118",
  "Node v1119",
  "Node v1120",
  "Node v1121",
  "Node v1122",
  "Node v1123",
  "Node v1124",
  "Node v1125",
  "Node v1126",
  "Node v1127",
  "Node v1128",
  "Node v1129",
  "Node v1130",
  "Node v1131",
  "Node v1132",
  "Node v1133",
  "Node v1134",
  "Node v1135",
  "Node v1136",
] as const;

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_LANES:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReadinessLaneTemplate[]
  = Object.freeze([
    lane("Node v1112", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_REQUEST_MANIFEST",
      "draftArtifactRequestManifest", "identity-readiness-lane", "manual-review",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_REQUEST_ID",
      "ARTIFACT_DRAFT_PREFLIGHT_REQUEST_ID_GUARD", "draftArtifactRequestId",
      "Bind the future manual signed approval draft to a stable request manifest before any artifact exists."),
    lane("Node v1113", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_ARTIFACT_PREFLIGHT_DIGEST_PIN",
      "artifactPreflightDigestPin", "digest-binding-readiness-lane", "digest-pin",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_ARTIFACT_PREFLIGHT_DIGEST",
      "ARTIFACT_DRAFT_PREFLIGHT_ARTIFACT_PREFLIGHT_DIGEST_GUARD",
      "sourceSignedApprovalCaptureArtifactPreflightDigest",
      "Pin the draft readiness package to the v1086 artifact preflight digest."),
    lane("Node v1114", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_TEMPLATE_DIGEST_PIN",
      "templateDigestPin", "digest-binding-readiness-lane", "digest-pin",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_TEMPLATE_DIGEST",
      "ARTIFACT_DRAFT_PREFLIGHT_TEMPLATE_DIGEST_GUARD", "sourceSignedApprovalTemplateDigest",
      "Pin the package to the signed approval template digest that defines human-review wording."),
    lane("Node v1115", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_REVIEW_DIGEST_PIN",
      "approvalPacketReviewDigestPin", "digest-binding-readiness-lane", "digest-pin",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_REVIEW_DIGEST",
      "ARTIFACT_DRAFT_PREFLIGHT_REVIEW_DIGEST_GUARD", "sourceApprovalPacketReviewDigest",
      "Pin the package to the approval packet review digest before manual draft authoring."),
    lane("Node v1116", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_OPERATOR_IDENTITY_REVIEW",
      "operatorIdentityReadiness", "identity-readiness-lane", "manual-review",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_OPERATOR_IDENTITY",
      "ARTIFACT_DRAFT_PREFLIGHT_OPERATOR_IDENTITY_GUARD", "operatorIdentity",
      "Require a human-reviewed operator identity lane without capturing credentials."),
    lane("Node v1117", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_OPERATOR_ROLE_REVIEW",
      "operatorRoleReadiness", "identity-readiness-lane", "manual-review",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_OPERATOR_ROLE",
      "ARTIFACT_DRAFT_PREFLIGHT_OPERATOR_ROLE_GUARD", "operatorRole",
      "Require a human-reviewed operator role lane before draft wording can be prepared."),
    lane("Node v1118", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_WINDOW_ID_REVIEW",
      "captureWindowReadiness", "identity-readiness-lane", "manual-review",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_WINDOW_ID",
      "ARTIFACT_DRAFT_PREFLIGHT_WINDOW_ID_GUARD", "captureWindowId",
      "Bind manual draft review to the planned capture window id without opening the window."),
    lane("Node v1119", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_CHANNEL_POLICY_REVIEW",
      "captureChannelPolicyReadiness", "policy-readiness-lane", "policy-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_CHANNEL_POLICY",
      "ARTIFACT_DRAFT_PREFLIGHT_CHANNEL_POLICY_GUARD", "captureChannelPolicy",
      "Review the capture channel policy while keeping all capture adapters disabled."),
    lane("Node v1120", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SIGNATURE_ALGORITHM_REVIEW",
      "signatureAlgorithmReadiness", "signature-envelope-readiness-lane", "policy-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SIGNATURE_ALGORITHM",
      "ARTIFACT_DRAFT_PREFLIGHT_SIGNATURE_ALGORITHM_GUARD", "signatureAlgorithmPolicy",
      "Review the detached signature algorithm policy before any signature payload is accepted."),
    lane("Node v1121", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_DETACHED_SIGNATURE_REVIEW",
      "detachedSignaturePlaceholderReadiness", "signature-envelope-readiness-lane", "manual-review",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_DETACHED_SIGNATURE_PLACEHOLDER",
      "ARTIFACT_DRAFT_PREFLIGHT_DETACHED_SIGNATURE_PLACEHOLDER_GUARD",
      "detachedSignaturePlaceholder",
      "Keep the signature lane as a placeholder and require later human draft authoring."),
    lane("Node v1122", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SIGNATURE_REDACTION_REVIEW",
      "signatureRedactionReadiness", "signature-envelope-readiness-lane", "policy-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SIGNATURE_REDACTION",
      "ARTIFACT_DRAFT_PREFLIGHT_SIGNATURE_REDACTION_GUARD", "signatureMaterialRedactionPolicy",
      "Prove raw signature material stays outside this package and remains redacted."),
    lane("Node v1123", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_APPROVAL_STATEMENT_DIGEST_PIN",
      "approvalStatementDigestReadiness", "digest-binding-readiness-lane", "digest-pin",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_APPROVAL_STATEMENT_DIGEST",
      "ARTIFACT_DRAFT_PREFLIGHT_APPROVAL_STATEMENT_DIGEST_GUARD", "approvalStatementDigest",
      "Prepare an approval statement digest lane without storing a signed statement."),
    lane("Node v1124", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SOURCE_VERSION_REVIEW",
      "sourceEvidenceVersionReadiness", "source-evidence-readiness-lane", "manual-review",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SOURCE_VERSION",
      "ARTIFACT_DRAFT_PREFLIGHT_SOURCE_VERSION_GUARD", "sourceEvidenceVersion",
      "Review the source evidence version lane that a manual draft would cite."),
    lane("Node v1125", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SOURCE_FILE_REVIEW",
      "sourceEvidenceFileReadiness", "source-evidence-readiness-lane", "manual-review",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SOURCE_FILE",
      "ARTIFACT_DRAFT_PREFLIGHT_SOURCE_FILE_GUARD", "sourceEvidenceFileId",
      "Review the source evidence file lane while keeping imports blocked."),
    lane("Node v1126", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SOURCE_SNIPPET_REVIEW",
      "sourceEvidenceSnippetReadiness", "source-evidence-readiness-lane", "manual-review",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SOURCE_SNIPPET",
      "ARTIFACT_DRAFT_PREFLIGHT_SOURCE_SNIPPET_GUARD", "sourceEvidenceSnippetId",
      "Review the source evidence snippet lane before any runtime payload can be assembled."),
    lane("Node v1127", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_REDACTED_VALUE_DIGEST_PIN",
      "redactedValueDigestReadiness", "value-binding-readiness-lane", "digest-pin",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_REDACTED_VALUE_DIGEST",
      "ARTIFACT_DRAFT_PREFLIGHT_REDACTED_VALUE_DIGEST_GUARD", "redactedValueDigest",
      "Pin a redacted value digest lane while raw values remain absent."),
    lane("Node v1128", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_VALUE_SHAPE_REVIEW",
      "valueShapeReadiness", "value-binding-readiness-lane", "manual-review",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_VALUE_SHAPE",
      "ARTIFACT_DRAFT_PREFLIGHT_VALUE_SHAPE_GUARD", "valueShape",
      "Review value shape metadata without accepting operator-supplied values."),
    lane("Node v1129", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_REDACTION_POLICY_REVIEW",
      "redactionPolicyReadiness", "policy-readiness-lane", "policy-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_REDACTION_POLICY",
      "ARTIFACT_DRAFT_PREFLIGHT_REDACTION_POLICY_GUARD", "redactionPolicy",
      "Keep value and signature redaction policy explicit before manual draft authoring."),
    lane("Node v1130", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_PROVENANCE_POLICY_REVIEW",
      "provenancePolicyReadiness", "policy-readiness-lane", "policy-check",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_PROVENANCE_POLICY",
      "ARTIFACT_DRAFT_PREFLIGHT_PROVENANCE_POLICY_GUARD", "provenancePolicy",
      "Review provenance policy so later approval text can cite immutable source evidence."),
    lane("Node v1131", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_RAW_SECRET_EMBARGO",
      "rawSecretEmbargoReadiness", "execution-lock-readiness-lane", "execution-lock",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_NO_RAW_SECRET_LOCK",
      "ARTIFACT_DRAFT_PREFLIGHT_NO_RAW_SECRET_GUARD", "noRawSecretLock",
      "Carry forward the raw secret embargo into draft readiness."),
    lane("Node v1132", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_APPROVAL_GRANT_EMBARGO",
      "approvalGrantEmbargoReadiness", "execution-lock-readiness-lane", "execution-lock",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_NO_GRANT_LOCK",
      "ARTIFACT_DRAFT_PREFLIGHT_NO_GRANT_GUARD", "noApprovalGrantEmittedLock",
      "Prove no approval grant has been emitted while preparing draft readiness."),
    lane("Node v1133", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_ZERO_VALUE_IMPORT_EMBARGO",
      "zeroValueImportEmbargoReadiness", "execution-lock-readiness-lane", "execution-lock",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_ZERO_VALUE_IMPORT_LOCK",
      "ARTIFACT_DRAFT_PREFLIGHT_ZERO_VALUE_IMPORT_GUARD", "zeroValueImportLock",
      "Keep value submission and evidence import counts at zero."),
    lane("Node v1134", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_WRITE_ROUTE_EMBARGO",
      "writeRouteEmbargoReadiness", "execution-lock-readiness-lane", "execution-lock",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_NO_WRITE_ROUTE_LOCK",
      "ARTIFACT_DRAFT_PREFLIGHT_NO_WRITE_ROUTE_GUARD", "noWriteRouteLock",
      "Keep write routing disabled until a real approval grant exists."),
    lane("Node v1135", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SIBLING_NON_MUTATION_EVIDENCE",
      "siblingNonMutationReadiness", "execution-lock-readiness-lane", "execution-lock",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SIBLING_NON_MUTATION_LOCK",
      "ARTIFACT_DRAFT_PREFLIGHT_SIBLING_NON_MUTATION_GUARD", "siblingNonMutationLock",
      "Require sibling non-mutation evidence before any future manual draft package."),
    lane("Node v1136", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_CLOSEOUT",
      "signedApprovalCaptureArtifactDraftReadinessCloseout", "archive-closeout-readiness-lane",
      "archive-closeout",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_CLOSEOUT",
      "ARTIFACT_DRAFT_PREFLIGHT_CLOSEOUT_GUARD",
      "signedApprovalCaptureArtifactDraftPreflightCloseout",
      "Close the readiness package and limit the next step to a manual draft artifact package."),
  ]);

function lane(
  nodeVersion:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReadinessLaneTemplate[
      "nodeVersion"
    ],
  code: string,
  laneName: string,
  kind:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReadinessLaneTemplate[
      "kind"
    ],
  laneMode:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReadinessLaneTemplate[
      "laneMode"
    ],
  sourceDraftFieldCode: string,
  sourceDraftGuardCode: string,
  requiredSourceFieldName: string,
  readinessPurpose: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReadinessLaneTemplate {
  return {
    nodeVersion,
    code,
    laneName,
    kind,
    laneMode,
    sourceDraftFieldCode,
    sourceDraftGuardCode,
    requiredSourceFieldName,
    readinessPurpose,
  };
}
