import { formatValue, renderEntries, renderMessages } from "./liveProbeReportUtils.js";
import type { ControlledReadOnlyShardPreviewProfile } from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewMarkdown(
  profile: ControlledReadOnlyShardPreviewProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Profile version: ${profile.profileVersion}`,
    `- Preview state: ${profile.previewState}`,
    `- Preview decision: ${profile.previewDecision}`,
    `- Ready: ${profile.readyForControlledReadOnlyShardPreview}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Preview only: ${profile.previewOnly}`,
    `- Live read only: ${profile.liveReadOnly}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Stops Java service: ${profile.stopsJavaService}`,
    `- Stops mini-kv service: ${profile.stopsMiniKvService}`,
    `- Active shard router allowed: ${profile.activeShardRouterAllowed}`,
    `- Write routing allowed: ${profile.writeRoutingAllowed}`,
    `- LOAD/RESTORE/COMPACT allowed: ${profile.loadRestoreCompactAllowed}`,
    `- Preview digest: ${profile.preview.previewDigest}`,
    "",
    "## Java Preview",
    ...renderEntries(profile.preview.java),
    `- Read status: ${profile.reads.java.status}`,
    `- Endpoint: ${profile.reads.java.endpoint}`,
    `- Latency ms: ${formatValue(profile.reads.java.latencyMs)}`,
    "",
    "## mini-kv Preview",
    ...renderEntries(profile.preview.miniKv),
    `- Read status: ${profile.reads.miniKv.status}`,
    `- Command: ${profile.reads.miniKv.command ?? "none"}`,
    `- Latency ms: ${formatValue(profile.reads.miniKv.latencyMs)}`,
    "",
    "## Combined Preview",
    `- Combined shard count: ${formatValue(profile.preview.combinedShardCount)}`,
    `- Combined slot count: ${formatValue(profile.preview.combinedSlotCount)}`,
    `- Both read-only: ${profile.preview.bothReadOnly}`,
    `- Both execution blocked: ${profile.preview.bothExecutionBlocked}`,
    "",
    "## Source Matrix",
    `- Source count: ${profile.preview.sourceMatrix.sourceCount}`,
    `- Ready source count: ${profile.preview.sourceMatrix.readySourceCount}`,
    `- Failed source count: ${profile.preview.sourceMatrix.failedSourceCount}`,
    `- Skipped source count: ${profile.preview.sourceMatrix.skippedSourceCount}`,
    `- Routing modes: ${profile.preview.sourceMatrix.routingModes.join(", ") || "none"}`,
    `- Shard count delta: ${formatValue(profile.preview.sourceMatrix.shardCountDelta)}`,
    `- Slot count delta: ${formatValue(profile.preview.sourceMatrix.slotCountDelta)}`,
    `- All sources ready: ${profile.preview.sourceMatrix.allSourcesReady}`,
    ...profile.preview.sourceMatrix.sources.flatMap((source) => [
      "",
      `### ${source.source}`,
      ...renderEntries(source),
    ]),
    "",
    "## Source Matrix Consumer",
    `- Consumer version: ${profile.preview.sourceMatrixConsumer.consumerVersion}`,
    `- Input source version: ${profile.preview.sourceMatrixConsumer.inputSourceVersion}`,
    `- Decision: ${profile.preview.sourceMatrixConsumer.decision}`,
    `- Ready for controlled read-only consumption: ${profile.preview.sourceMatrixConsumer.readyForControlledReadOnlyConsumption}`,
    `- Required sources: ${profile.preview.sourceMatrixConsumer.requiredSources.join(", ") || "none"}`,
    `- Observed sources: ${profile.preview.sourceMatrixConsumer.observedSources.join(", ") || "none"}`,
    `- Missing sources: ${profile.preview.sourceMatrixConsumer.missingSources.join(", ") || "none"}`,
    `- Gate count: ${profile.preview.sourceMatrixConsumer.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixConsumer.passedGateCount}`,
    `- Blocked reason codes: ${profile.preview.sourceMatrixConsumer.blockedReasonCodes.join(", ") || "none"}`,
    `- Activates routing: ${profile.preview.sourceMatrixConsumer.activatesRouting}`,
    `- Starts services: ${profile.preview.sourceMatrixConsumer.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixConsumer.mutatesSiblingState}`,
    "",
    "### Consumer Gates",
    ...renderEntries(profile.preview.sourceMatrixConsumer.gates),
    "",
    "### Consumer Comparison",
    ...renderEntries(profile.preview.sourceMatrixConsumer.comparison),
    "",
    "## Checks",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Evidence Endpoints",
    ...renderEntries(profile.evidenceEndpoints),
  ].join("\n");
}
