import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactPreflightSealTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactPreflightTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SEALS:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactPreflightSealTemplate[]
  = Object.freeze([
    seal("Node v1062", "ARTIFACT_PREFLIGHT_REQUEST_ID_SEAL", "required-fragment-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_REQUEST_ID", "REJECT_ARTIFACT_REQUEST_ID_MISSING",
      "Reject artifact preflight without a stable artifact request id fragment."),
    seal("Node v1063", "ARTIFACT_PREFLIGHT_CAPTURE_PREFLIGHT_DIGEST_SEAL", "digest-binding-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_CAPTURE_PREFLIGHT_DIGEST",
      "REJECT_CAPTURE_PREFLIGHT_DIGEST_MISSING", "Reject artifact preflight without v1061 digest binding."),
    seal("Node v1064", "ARTIFACT_PREFLIGHT_TEMPLATE_DIGEST_SEAL", "digest-binding-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_TEMPLATE_DIGEST",
      "REJECT_TEMPLATE_DIGEST_MISSING", "Reject artifact preflight without v1036 template digest binding."),
    seal("Node v1065", "ARTIFACT_PREFLIGHT_REVIEW_DIGEST_SEAL", "digest-binding-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_REVIEW_DIGEST",
      "REJECT_REVIEW_DIGEST_MISSING", "Reject artifact preflight without review digest binding."),
    seal("Node v1066", "ARTIFACT_PREFLIGHT_OPERATOR_IDENTITY_SEAL", "required-fragment-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_OPERATOR_IDENTITY",
      "REJECT_OPERATOR_IDENTITY_MISSING", "Reject artifact preflight without operator identity fragment."),
    seal("Node v1067", "ARTIFACT_PREFLIGHT_OPERATOR_ROLE_SEAL", "required-fragment-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_OPERATOR_ROLE",
      "REJECT_OPERATOR_ROLE_MISSING", "Reject artifact preflight without operator role fragment."),
    seal("Node v1068", "ARTIFACT_PREFLIGHT_WINDOW_ID_SEAL", "required-fragment-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_WINDOW_ID",
      "REJECT_CAPTURE_WINDOW_ID_MISSING", "Reject artifact preflight without capture window id fragment."),
    seal("Node v1069", "ARTIFACT_PREFLIGHT_CHANNEL_POLICY_SEAL", "policy-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_CHANNEL_POLICY",
      "REJECT_CAPTURE_CHANNEL_POLICY_MISSING", "Reject artifact preflight without capture channel policy."),
    seal("Node v1070", "ARTIFACT_PREFLIGHT_SIGNATURE_ALGORITHM_SEAL", "signature-envelope-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SIGNATURE_ALGORITHM",
      "REJECT_SIGNATURE_ALGORITHM_MISSING", "Reject artifact preflight without signature algorithm policy."),
    seal("Node v1071", "ARTIFACT_PREFLIGHT_DETACHED_SIGNATURE_PLACEHOLDER_SEAL", "signature-envelope-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_DETACHED_SIGNATURE_PLACEHOLDER",
      "REJECT_DETACHED_SIGNATURE_PLACEHOLDER_MISSING",
      "Reject artifact preflight without detached signature placeholder."),
    seal("Node v1072", "ARTIFACT_PREFLIGHT_SIGNATURE_REDACTION_SEAL", "signature-envelope-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SIGNATURE_REDACTION",
      "REJECT_SIGNATURE_REDACTION_MISSING", "Reject artifact preflight without signature redaction policy."),
    seal("Node v1073", "ARTIFACT_PREFLIGHT_APPROVAL_STATEMENT_DIGEST_SEAL", "digest-binding-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_APPROVAL_STATEMENT_DIGEST",
      "REJECT_APPROVAL_STATEMENT_DIGEST_MISSING", "Reject artifact preflight without approval statement digest."),
    seal("Node v1074", "ARTIFACT_PREFLIGHT_SOURCE_VERSION_SEAL", "required-fragment-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SOURCE_VERSION",
      "REJECT_SOURCE_VERSION_MISSING", "Reject artifact preflight without source evidence version."),
    seal("Node v1075", "ARTIFACT_PREFLIGHT_SOURCE_FILE_SEAL", "required-fragment-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SOURCE_FILE",
      "REJECT_SOURCE_FILE_MISSING", "Reject artifact preflight without source evidence file id."),
    seal("Node v1076", "ARTIFACT_PREFLIGHT_SOURCE_SNIPPET_SEAL", "required-fragment-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SOURCE_SNIPPET",
      "REJECT_SOURCE_SNIPPET_MISSING", "Reject artifact preflight without source evidence snippet id."),
    seal("Node v1077", "ARTIFACT_PREFLIGHT_REDACTED_VALUE_DIGEST_SEAL", "required-fragment-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_REDACTED_VALUE_DIGEST",
      "REJECT_REDACTED_VALUE_DIGEST_MISSING", "Reject artifact preflight without redacted value digest."),
    seal("Node v1078", "ARTIFACT_PREFLIGHT_VALUE_SHAPE_SEAL", "required-fragment-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_VALUE_SHAPE",
      "REJECT_VALUE_SHAPE_MISSING", "Reject artifact preflight without value shape fragment."),
    seal("Node v1079", "ARTIFACT_PREFLIGHT_REDACTION_POLICY_SEAL", "policy-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_REDACTION_POLICY",
      "REJECT_REDACTION_POLICY_MISSING", "Reject artifact preflight without redaction policy."),
    seal("Node v1080", "ARTIFACT_PREFLIGHT_PROVENANCE_POLICY_SEAL", "policy-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_PROVENANCE_POLICY",
      "REJECT_PROVENANCE_POLICY_MISSING", "Reject artifact preflight without provenance policy."),
    seal("Node v1081", "ARTIFACT_PREFLIGHT_NO_RAW_SECRET_SEAL", "no-execution-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_NO_RAW_SECRET_LOCK",
      "REJECT_RAW_SECRET_PRESENT", "Block artifact preflight if raw secret or signature material is present."),
    seal("Node v1082", "ARTIFACT_PREFLIGHT_NO_GRANT_SEAL", "no-execution-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_NO_GRANT_LOCK",
      "REJECT_APPROVAL_GRANT_EMITTED", "Block artifact preflight if an approval grant was emitted."),
    seal("Node v1083", "ARTIFACT_PREFLIGHT_ZERO_VALUE_IMPORT_SEAL", "no-execution-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_ZERO_VALUE_IMPORT_LOCK",
      "REJECT_VALUE_IMPORT_NONZERO", "Block artifact preflight if value submission or import counts are nonzero."),
    seal("Node v1084", "ARTIFACT_PREFLIGHT_NO_WRITE_ROUTE_SEAL", "no-execution-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_NO_WRITE_ROUTE_LOCK",
      "REJECT_WRITE_ROUTE_ENABLED", "Block artifact preflight if write routing is enabled."),
    seal("Node v1085", "ARTIFACT_PREFLIGHT_SIBLING_NON_MUTATION_SEAL", "no-execution-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SIBLING_NON_MUTATION_LOCK",
      "REJECT_SIBLING_MUTATION_ENABLED", "Block artifact preflight if sibling mutation is enabled."),
    seal("Node v1086", "ARTIFACT_PREFLIGHT_CLOSEOUT_SEAL", "closeout-seal",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_CLOSEOUT",
      "REJECT_NEXT_STEP_NOT_ARTIFACT_DRAFT", "Close artifact preflight at signed approval artifact draft readiness."),
  ]);

function seal(
  nodeVersion:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactPreflightSealTemplate[
      "nodeVersion"
    ],
  code: string,
  kind:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactPreflightSealTemplate[
      "kind"
    ],
  sourceArtifactFragmentCode: string,
  rejectionCode: string,
  sealText: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactPreflightSealTemplate {
  return {
    nodeVersion,
    code,
    kind,
    sourceArtifactFragmentCode,
    rejectionCode,
    sealText,
  };
}
