import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplateClauseTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplateTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_TEMPLATE_CLAUSES:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplateClauseTemplate[]
  = Object.freeze([
    clause("Node v1012", "SIGNED_APPROVAL_TEMPLATE_PACKET_ID_REQUIRED", "required-field-clause",
      "SIGNED_APPROVAL_TEMPLATE_PACKET_ID", "REJECT_SIGNED_TEMPLATE_PACKET_ID_MISSING",
      "Reject any signed approval template without a stable signedApprovalPacketId."),
    clause("Node v1013", "SIGNED_APPROVAL_TEMPLATE_OPERATOR_IDENTITY_REQUIRED", "required-field-clause",
      "SIGNED_APPROVAL_TEMPLATE_OPERATOR_IDENTITY", "REJECT_OPERATOR_IDENTITY_MISSING",
      "Reject any signed approval template without an operatorIdentity."),
    clause("Node v1014", "SIGNED_APPROVAL_TEMPLATE_OPERATOR_ROLE_REQUIRED", "required-field-clause",
      "SIGNED_APPROVAL_TEMPLATE_OPERATOR_ROLE", "REJECT_OPERATOR_ROLE_MISSING",
      "Reject any signed approval template without an operatorRole or authority handle."),
    clause("Node v1015", "SIGNED_APPROVAL_TEMPLATE_TIMESTAMP_REQUIRED", "required-field-clause",
      "SIGNED_APPROVAL_TEMPLATE_APPROVAL_TIMESTAMP", "REJECT_APPROVAL_TIMESTAMP_MISSING",
      "Reject any signed approval template without an approvalTimestamp."),
    clause("Node v1016", "SIGNED_APPROVAL_TEMPLATE_REVIEW_DIGEST_BOUND", "evidence-binding-clause",
      "SIGNED_APPROVAL_TEMPLATE_REVIEW_PACKAGE_DIGEST", "REJECT_REVIEW_PACKAGE_DIGEST_MISSING",
      "Bind the template to the v1011 review package digest before capture can be discussed."),
    clause("Node v1017", "SIGNED_APPROVAL_TEMPLATE_DRAFT_DIGEST_BOUND", "evidence-binding-clause",
      "SIGNED_APPROVAL_TEMPLATE_DRAFT_DIGEST", "REJECT_DRAFT_DIGEST_MISSING",
      "Bind the template to the v986 draft digest before capture can be discussed."),
    clause("Node v1018", "SIGNED_APPROVAL_TEMPLATE_SOURCE_VERSION_BOUND", "evidence-binding-clause",
      "SIGNED_APPROVAL_TEMPLATE_SOURCE_EVIDENCE_VERSION", "REJECT_SOURCE_VERSION_MISSING",
      "Reject any template without the sourceEvidenceVersion."),
    clause("Node v1019", "SIGNED_APPROVAL_TEMPLATE_SOURCE_FILE_BOUND", "evidence-binding-clause",
      "SIGNED_APPROVAL_TEMPLATE_SOURCE_EVIDENCE_FILE", "REJECT_SOURCE_FILE_MISSING",
      "Reject any template without a sourceEvidenceFileId."),
    clause("Node v1020", "SIGNED_APPROVAL_TEMPLATE_SOURCE_SNIPPET_BOUND", "evidence-binding-clause",
      "SIGNED_APPROVAL_TEMPLATE_SOURCE_EVIDENCE_SNIPPET", "REJECT_SOURCE_SNIPPET_MISSING",
      "Reject any template without a sourceEvidenceSnippetId."),
    clause("Node v1021", "SIGNED_APPROVAL_TEMPLATE_VALUE_SHAPE_REQUIRED", "required-field-clause",
      "SIGNED_APPROVAL_TEMPLATE_VALUE_SHAPE", "REJECT_VALUE_SHAPE_MISSING",
      "Reject any template without an explicit typed valueShape."),
    clause("Node v1022", "SIGNED_APPROVAL_TEMPLATE_REDACTED_DIGEST_REQUIRED", "required-field-clause",
      "SIGNED_APPROVAL_TEMPLATE_REDACTED_DIGEST", "REJECT_REDACTED_DIGEST_MISSING",
      "Reject any template without a redactedValueDigest; raw values remain prohibited."),
    clause("Node v1023", "SIGNED_APPROVAL_TEMPLATE_REDACTION_POLICY_BOUND", "rejection-clause",
      "SIGNED_APPROVAL_TEMPLATE_REDACTION_POLICY", "REJECT_REDACTION_POLICY_MISSING",
      "Reject templates that do not bind redact-before-persist policy."),
    clause("Node v1024", "SIGNED_APPROVAL_TEMPLATE_PROVENANCE_POLICY_BOUND", "rejection-clause",
      "SIGNED_APPROVAL_TEMPLATE_PROVENANCE_POLICY", "REJECT_PROVENANCE_POLICY_MISSING",
      "Reject templates that do not bind source-evidence-required provenance."),
    clause("Node v1025", "SIGNED_APPROVAL_TEMPLATE_MISSING_VALUE_POLICY_BOUND", "rejection-clause",
      "SIGNED_APPROVAL_TEMPLATE_MISSING_VALUE_POLICY", "REJECT_MISSING_VALUE_POLICY_MISSING",
      "Reject templates that do not fail closed on missing values."),
    clause("Node v1026", "SIGNED_APPROVAL_TEMPLATE_MALFORMED_VALUE_POLICY_BOUND", "rejection-clause",
      "SIGNED_APPROVAL_TEMPLATE_MALFORMED_VALUE_POLICY", "REJECT_MALFORMED_VALUE_POLICY_MISSING",
      "Reject templates that do not reject malformed values."),
    clause("Node v1027", "SIGNED_APPROVAL_TEMPLATE_APPROVAL_POLICY_BOUND", "rejection-clause",
      "SIGNED_APPROVAL_TEMPLATE_APPROVAL_POLICY", "REJECT_APPROVAL_POLICY_MISSING",
      "Reject templates that do not require signed human approval."),
    clause("Node v1028", "SIGNED_APPROVAL_TEMPLATE_PACKET_POLICY_BOUND", "rejection-clause",
      "SIGNED_APPROVAL_TEMPLATE_PACKET_POLICY", "REJECT_PACKET_POLICY_MISSING",
      "Reject templates that accidentally become approval grants instead of templates."),
    clause("Node v1029", "SIGNED_APPROVAL_TEMPLATE_OPERATOR_JUSTIFICATION_REQUIRED", "required-field-clause",
      "SIGNED_APPROVAL_TEMPLATE_OPERATOR_JUSTIFICATION", "REJECT_OPERATOR_JUSTIFICATION_MISSING",
      "Reject templates without human justification tied to source evidence."),
    clause("Node v1030", "SIGNED_APPROVAL_TEMPLATE_JAVA_COVERAGE_BOUND", "evidence-binding-clause",
      "SIGNED_APPROVAL_TEMPLATE_JAVA_EVIDENCE_COVERAGE", "REJECT_JAVA_COVERAGE_MISSING",
      "Reject templates that cannot trace Java evidence coverage."),
    clause("Node v1031", "SIGNED_APPROVAL_TEMPLATE_MINI_KV_COVERAGE_BOUND", "evidence-binding-clause",
      "SIGNED_APPROVAL_TEMPLATE_MINI_KV_EVIDENCE_COVERAGE", "REJECT_MINI_KV_COVERAGE_MISSING",
      "Reject templates that cannot trace mini-kv evidence coverage."),
    clause("Node v1032", "SIGNED_APPROVAL_TEMPLATE_NODE_ENVELOPE_BOUND", "evidence-binding-clause",
      "SIGNED_APPROVAL_TEMPLATE_NODE_ENVELOPE_COVERAGE", "REJECT_NODE_ENVELOPE_COVERAGE_MISSING",
      "Reject templates that cannot trace the Node envelope coverage."),
    clause("Node v1033", "SIGNED_APPROVAL_TEMPLATE_NO_PRIOR_APPROVAL_LOCK", "non-execution-clause",
      "SIGNED_APPROVAL_TEMPLATE_NO_APPROVAL_CAPTURED_LOCK", "REJECT_PRIOR_APPROVAL_PRESENT",
      "Block capture if a prior approval, grant, or signature is already present."),
    clause("Node v1034", "SIGNED_APPROVAL_TEMPLATE_ZERO_VALUE_LOCK", "non-execution-clause",
      "SIGNED_APPROVAL_TEMPLATE_ZERO_VALUE_COUNT_LOCK", "REJECT_VALUE_COUNTS_NONZERO",
      "Block capture if supplied, accepted, or imported value counts are nonzero."),
    clause("Node v1035", "SIGNED_APPROVAL_TEMPLATE_WRITE_SERVICE_LOCK", "non-execution-clause",
      "SIGNED_APPROVAL_TEMPLATE_WRITE_SERVICE_LOCK", "REJECT_WRITE_OR_SERVICE_ENABLED",
      "Block capture if writes, service starts, or sibling mutations are enabled."),
    clause("Node v1036", "SIGNED_APPROVAL_TEMPLATE_CLOSEOUT_ONLY", "closeout-clause",
      "SIGNED_APPROVAL_TEMPLATE_CLOSEOUT", "REJECT_NEXT_STEP_NOT_CAPTURE_PREFLIGHT",
      "Close the template at capture-preflight readiness only; value import remains a later lifecycle."),
  ]);

function clause(
  nodeVersion: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplateClauseTemplate[
    "nodeVersion"
  ],
  code: string,
  kind: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplateClauseTemplate[
    "kind"
  ],
  sourceTemplateFieldCode: string,
  rejectionCode: string,
  clauseText: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplateClauseTemplate {
  return {
    nodeVersion,
    code,
    kind,
    sourceTemplateFieldCode,
    rejectionCode,
    clauseText,
  };
}
