import { renderEntries } from "./liveProbeReportUtils.js";
import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflight,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightGuard,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightSlot,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightTypes.js";

export function renderControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightMarkdown(
  preflight:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflight,
): string {
  return [
    "# Controlled read-only shard preview live read-only window operator evidence value supply signed approval capture artifact draft review package preflight",
    "",
    `- Signed approval capture artifact draft review package preflight version: ${preflight.signedApprovalCaptureArtifactDraftReviewPackagePreflightVersion}`,
    `- Source signed approval capture artifact draft readiness version: ${preflight.sourceSignedApprovalCaptureArtifactDraftReadinessVersion}`,
    `- Artifact draft review package preflight state: ${preflight.artifactDraftReviewPackagePreflightState}`,
    `- Ready for signed approval artifact draft review package preflight: ${preflight.readyForSignedApprovalArtifactDraftReviewPackagePreflight}`,
    `- Ready for manual signed approval draft review package: ${preflight.readyForManualSignedApprovalDraftReviewPackage}`,
    `- Ready for manual signed approval draft review: ${preflight.readyForManualSignedApprovalDraftReview}`,
    `- Ready for signed approval artifact draft: ${preflight.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${preflight.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${preflight.readyForOperatorValueSupply}`,
    `- Ready for operator value submission: ${preflight.readyForOperatorValueSubmission}`,
    `- Ready for evidence import: ${preflight.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${preflight.readyForRuntimePayload}`,
    `- Ready for live execution: ${preflight.readyForLiveExecution}`,
    `- Ready for production execution: ${preflight.readyForProductionExecution}`,
    `- Package slot count: ${preflight.packageSlotCount}`,
    `- Package guard count: ${preflight.packageGuardCount}`,
    `- Identity review package slot count: ${preflight.identityReviewPackageSlotCount}`,
    `- Digest binding review package slot count: ${preflight.digestBindingReviewPackageSlotCount}`,
    `- Signature envelope review package slot count: ${preflight.signatureEnvelopeReviewPackageSlotCount}`,
    `- Source evidence review package slot count: ${preflight.sourceEvidenceReviewPackageSlotCount}`,
    `- Value binding review package slot count: ${preflight.valueBindingReviewPackageSlotCount}`,
    `- Policy review package slot count: ${preflight.policyReviewPackageSlotCount}`,
    `- Execution lock review package slot count: ${preflight.executionLockReviewPackageSlotCount}`,
    `- Archive closeout review package slot count: ${preflight.archiveCloseoutReviewPackageSlotCount}`,
    `- Digest mode review package slot count: ${preflight.digestModeReviewPackageSlotCount}`,
    `- Ready package slot count: ${preflight.readyPackageSlotCount}`,
    `- Ready package guard count: ${preflight.readyPackageGuardCount}`,
    `- Digest binding review package guard count: ${preflight.digestBindingReviewPackageGuardCount}`,
    `- Signature envelope review package guard count: ${preflight.signatureEnvelopeReviewPackageGuardCount}`,
    `- Policy review package guard count: ${preflight.policyReviewPackageGuardCount}`,
    `- Execution lock review package guard count: ${preflight.executionLockReviewPackageGuardCount}`,
    `- Archive closeout review package guard count: ${preflight.archiveCloseoutReviewPackageGuardCount}`,
    `- Package slot materialized count: ${preflight.packageSlotMaterializedCount}`,
    `- Package artifact created: ${preflight.packageArtifactCreated}`,
    `- Signed draft text count: ${preflight.signedDraftTextCount}`,
    `- Draft signature payload count: ${preflight.draftSignaturePayloadCount}`,
    `- Approval captured: ${preflight.approvalCaptured}`,
    `- Approval grant present: ${preflight.approvalGrantPresent}`,
    `- Signed approval present: ${preflight.signedApprovalPresent}`,
    `- Source signed approval capture artifact draft readiness digest: ${preflight.sourceSignedApprovalCaptureArtifactDraftReadinessDigest}`,
    `- Source signed approval capture artifact draft preflight digest: ${preflight.sourceSignedApprovalCaptureArtifactDraftPreflightDigest}`,
    `- Source signed approval capture artifact preflight digest: ${preflight.sourceSignedApprovalCaptureArtifactPreflightDigest}`,
    `- Source signed approval capture preflight digest: ${preflight.sourceSignedApprovalCapturePreflightDigest}`,
    `- Source signed approval template digest: ${preflight.sourceSignedApprovalTemplateDigest}`,
    `- Source approval packet review digest: ${preflight.sourceApprovalPacketReviewDigest}`,
    `- Passed gates: ${preflight.passedGateCount}/${preflight.gateCount}`,
    `- Imports runtime payload: ${preflight.importsRuntimePayload}`,
    `- Accepts synthetic evidence: ${preflight.acceptsSyntheticEvidence}`,
    `- Contains secret value: ${preflight.containsSecretValue}`,
    `- Signed approval capture artifact draft review package preflight digest: ${preflight.signedApprovalCaptureArtifactDraftReviewPackagePreflightDigest}`,
    "",
    "## Gates",
    ...renderEntries(preflight.gates),
    "",
    "## Package Slots",
    ...preflight.slots.flatMap(renderSlot),
    "## Package Guards",
    ...preflight.guards.flatMap(renderGuard),
    "## Blocked Reasons",
    ...(preflight.blockedReasonCodes.length === 0
      ? ["- none"]
      : preflight.blockedReasonCodes.map((reason) => `- ${reason}`)),
  ].join("\n");
}

function renderSlot(
  slot:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightSlot,
): string[] {
  return [
    `### ${slot.order}. ${slot.nodeVersion} ${slot.code}`,
    `- Package slot name: ${slot.packageSlotName}`,
    `- Kind: ${slot.kind}`,
    `- Slot mode: ${slot.slotMode}`,
    `- Source readiness lane: ${slot.sourceReadinessLaneCode}`,
    `- Source readiness lane ready: ${slot.sourceReadinessLaneReady}`,
    `- Source readiness lane kind: ${slot.sourceReadinessLaneKind}`,
    `- Source readiness lane mode: ${slot.sourceReadinessLaneMode}`,
    `- Source readiness lane read-only: ${slot.sourceReadinessLaneReadOnly}`,
    `- Source readiness lane manual review required: ${slot.sourceReadinessLaneManualReviewRequired}`,
    `- Source readiness lane manual draft materialized: ${slot.sourceReadinessLaneManualDraftMaterialized}`,
    `- Source readiness control: ${slot.sourceReadinessControlCode}`,
    `- Source readiness control ready: ${slot.sourceReadinessControlReady}`,
    `- Source readiness control kind: ${slot.sourceReadinessControlKind}`,
    `- Source readiness control read-only: ${slot.sourceReadinessControlReadOnly}`,
    `- Source readiness control blocks auto materialization: ${slot.sourceReadinessControlBlocksAutoMaterialization}`,
    `- Source readiness control blocks signed approval capture: ${slot.sourceReadinessControlBlocksSignedApprovalCapture}`,
    `- Source readiness control blocks runtime payload: ${slot.sourceReadinessControlBlocksRuntimePayload}`,
    `- Required readiness lane mode: ${slot.requiredReadinessLaneMode}`,
    `- Required readiness lane mode covered: ${slot.requiredReadinessLaneModeCovered}`,
    `- Review package purpose: ${slot.reviewPackagePurpose}`,
    `- Ready for manual signed approval draft review package slot: ${slot.readyForManualSignedApprovalDraftReviewPackageSlot}`,
    `- Package slot materialized: ${slot.packageSlotMaterialized}`,
    `- Package artifact created: ${slot.packageArtifactCreated}`,
    `- Signed draft text present: ${slot.signedDraftTextPresent}`,
    `- Draft signature payload present: ${slot.draftSignaturePayloadPresent}`,
    `- Approval grant present: ${slot.approvalGrantPresent}`,
    `- Ready for signed approval artifact draft: ${slot.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${slot.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${slot.readyForOperatorValueSupply}`,
    `- Ready for evidence import: ${slot.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${slot.readyForRuntimePayload}`,
    `- Writes allowed: ${slot.writesAllowed}`,
    `- Starts services: ${slot.startsServices}`,
    `- Mutates sibling state: ${slot.mutatesSiblingState}`,
    "",
  ];
}

function renderGuard(
  guard:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightGuard,
): string[] {
  return [
    `### ${guard.order}. ${guard.nodeVersion} ${guard.code}`,
    `- Kind: ${guard.kind}`,
    `- Source package slot: ${guard.sourcePackageSlotCode}`,
    `- Source package slot ready: ${guard.sourcePackageSlotReady}`,
    `- Blocker code: ${guard.blockerCode}`,
    `- Guard text: ${guard.guardText}`,
    `- Rejects missing review package slot: ${guard.rejectsMissingReviewPackageSlot}`,
    `- Blocks package materialization: ${guard.blocksPackageMaterialization}`,
    `- Blocks signed draft text: ${guard.blocksSignedDraftText}`,
    `- Blocks signature payload: ${guard.blocksSignaturePayload}`,
    `- Blocks approval grant: ${guard.blocksApprovalGrant}`,
    `- Blocks runtime payload: ${guard.blocksRuntimePayload}`,
    `- Blocks writes: ${guard.blocksWrites}`,
    `- Blocks sibling mutation: ${guard.blocksSiblingMutation}`,
    `- Ready for manual signed approval draft review package guard: ${guard.readyForManualSignedApprovalDraftReviewPackageGuard}`,
    `- Ready for signed approval artifact draft: ${guard.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${guard.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${guard.readyForOperatorValueSupply}`,
    `- Ready for evidence import: ${guard.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${guard.readyForRuntimePayload}`,
    `- Writes allowed: ${guard.writesAllowed}`,
    `- Starts services: ${guard.startsServices}`,
    `- Mutates sibling state: ${guard.mutatesSiblingState}`,
    "",
  ];
}
