import { renderEntries, renderProfileEntrySections } from "./liveProbeReportUtils.js";
import type { ControlledReadOnlyShardPreviewProfile } from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewTypes.js";

export function renderControlledReadOnlyShardPreviewHandoffSummarySections(
  profile: ControlledReadOnlyShardPreviewProfile,
): string[] {
  return renderProfileEntrySections([
    {
      heading: "Source Matrix Handoff Notes",
      lines: [
        `- Notes version: ${profile.preview.sourceMatrixHandoffNotes.notesVersion}`,
        `- Input summary export version: ${profile.preview.sourceMatrixHandoffNotes.inputSummaryExportVersion}`,
        `- Handoff state: ${profile.preview.sourceMatrixHandoffNotes.handoffState}`,
        `- Ready for read-only handoff: ${profile.preview.sourceMatrixHandoffNotes.readyForReadOnlyHandoff}`,
        `- Handoff digest: ${profile.preview.sourceMatrixHandoffNotes.handoffDigest.value}`,
        `- Handoff digest scope: ${profile.preview.sourceMatrixHandoffNotes.handoffDigest.scope}`,
        `- Handoff digest covered note count: ${profile.preview.sourceMatrixHandoffNotes.handoffDigest.coveredNoteCount}`,
        `- Note count: ${profile.preview.sourceMatrixHandoffNotes.noteCount}`,
        `- Action required count: ${profile.preview.sourceMatrixHandoffNotes.actionRequiredCount}`,
        `- Requires approval: ${profile.preview.sourceMatrixHandoffNotes.requiresApproval}`,
        `- Requires routing activation: ${profile.preview.sourceMatrixHandoffNotes.requiresRoutingActivation}`,
        `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffNotes.requiresFreshSiblingEvidence}`,
        `- Starts services: ${profile.preview.sourceMatrixHandoffNotes.startsServices}`,
        `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffNotes.mutatesSiblingState}`,
        "",
        "### Handoff Notes",
        ...profile.preview.sourceMatrixHandoffNotes.notes.map((note) =>
          `- ${note.order}. ${note.audience}: ${note.message}`),
      ],
    },
    {
      heading: "Source Matrix Handoff Summary",
      lines: [
        `- Summary version: ${profile.preview.sourceMatrixHandoffSummary.summaryVersion}`,
        `- Input notes version: ${profile.preview.sourceMatrixHandoffSummary.inputNotesVersion}`,
        `- Summary state: ${profile.preview.sourceMatrixHandoffSummary.summaryState}`,
        `- Ready for read-only handoff summary: ${profile.preview.sourceMatrixHandoffSummary.readyForReadOnlyHandoffSummary}`,
        `- Audiences: ${profile.preview.sourceMatrixHandoffSummary.audiences.join(", ") || "none"}`,
        `- Audience count: ${profile.preview.sourceMatrixHandoffSummary.audienceCount}`,
        `- Action required count: ${profile.preview.sourceMatrixHandoffSummary.actionRequiredCount}`,
        `- Handoff digest value: ${profile.preview.sourceMatrixHandoffSummary.handoffDigestValue}`,
        `- Summary digest: ${profile.preview.sourceMatrixHandoffSummary.summaryDigest.value}`,
        `- Summary digest scope: ${profile.preview.sourceMatrixHandoffSummary.summaryDigest.scope}`,
        `- Summary digest covered audience count: ${profile.preview.sourceMatrixHandoffSummary.summaryDigest.coveredAudienceCount}`,
        `- Summary digest covered action required count: ${profile.preview.sourceMatrixHandoffSummary.summaryDigest.coveredActionRequiredCount}`,
        `- Requires approval: ${profile.preview.sourceMatrixHandoffSummary.requiresApproval}`,
        `- Requires routing activation: ${profile.preview.sourceMatrixHandoffSummary.requiresRoutingActivation}`,
        `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffSummary.requiresFreshSiblingEvidence}`,
        `- Starts services: ${profile.preview.sourceMatrixHandoffSummary.startsServices}`,
        `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffSummary.mutatesSiblingState}`,
      ],
    },
    {
      heading: "Source Matrix Handoff Summary Consumer",
      lines: [
        `- Consumer version: ${profile.preview.sourceMatrixHandoffSummaryConsumer.consumerVersion}`,
        `- Input summary version: ${profile.preview.sourceMatrixHandoffSummaryConsumer.inputSummaryVersion}`,
        `- Decision: ${profile.preview.sourceMatrixHandoffSummaryConsumer.decision}`,
        `- Ready for read-only summary consumption: ${profile.preview.sourceMatrixHandoffSummaryConsumer.readyForReadOnlySummaryConsumption}`,
        `- Gate count: ${profile.preview.sourceMatrixHandoffSummaryConsumer.gateCount}`,
        `- Passed gate count: ${profile.preview.sourceMatrixHandoffSummaryConsumer.passedGateCount}`,
        `- Blocked reason codes: ${profile.preview.sourceMatrixHandoffSummaryConsumer.blockedReasonCodes.join(", ") || "none"}`,
        `- Summary digest value: ${profile.preview.sourceMatrixHandoffSummaryConsumer.summaryDigestValue}`,
        `- Summary digest scope: ${profile.preview.sourceMatrixHandoffSummaryConsumer.summaryDigestScope}`,
        `- Covered audience count: ${profile.preview.sourceMatrixHandoffSummaryConsumer.coveredAudienceCount}`,
        `- Action required count: ${profile.preview.sourceMatrixHandoffSummaryConsumer.actionRequiredCount}`,
        `- Requires approval: ${profile.preview.sourceMatrixHandoffSummaryConsumer.requiresApproval}`,
        `- Requires routing activation: ${profile.preview.sourceMatrixHandoffSummaryConsumer.requiresRoutingActivation}`,
        `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffSummaryConsumer.requiresFreshSiblingEvidence}`,
        `- Starts services: ${profile.preview.sourceMatrixHandoffSummaryConsumer.startsServices}`,
        `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffSummaryConsumer.mutatesSiblingState}`,
        "",
        "### Handoff Summary Consumer Gates",
        ...renderEntries(profile.preview.sourceMatrixHandoffSummaryConsumer.gates),
      ],
    },
    {
      heading: "Source Matrix Handoff Summary Consumer Export",
      lines: [
        `- Export version: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportVersion}`,
        `- Input consumer version: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.inputConsumerVersion}`,
        `- Export state: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportState}`,
        `- Ready for read-only summary consumer export: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.readyForReadOnlySummaryConsumerExport}`,
        `- Consumer decision: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.consumerDecision}`,
        `- Summary digest value: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.summaryDigestValue}`,
        `- Export digest: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportDigest.value}`,
        `- Export digest scope: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportDigest.scope}`,
        `- Export digest covered line count: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportDigest.coveredLineCount}`,
        `- Export lines: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportLines.join("; ")}`,
        `- Export line count: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportLineCount}`,
        `- Gate count: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.gateCount}`,
        `- Passed gate count: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.passedGateCount}`,
        `- Blocked reason count: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.blockedReasonCount}`,
        `- Requires approval: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.requiresApproval}`,
        `- Requires routing activation: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.requiresRoutingActivation}`,
        `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.requiresFreshSiblingEvidence}`,
        `- Starts services: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.startsServices}`,
        `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.mutatesSiblingState}`,
      ],
    },
    {
      heading: "Source Matrix Handoff Summary Consumer Receipt",
      lines: [
        `- Receipt version: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptVersion}`,
        `- Input export version: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.inputExportVersion}`,
        `- Receipt state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptState}`,
        `- Ready for read-only summary consumer receipt: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.readyForReadOnlySummaryConsumerReceipt}`,
        `- Export state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.exportState}`,
        `- Export digest value: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.exportDigestValue}`,
        `- Receipt digest: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptDigest.value}`,
        `- Receipt digest scope: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptDigest.scope}`,
        `- Receipt digest covered export line count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptDigest.coveredExportLineCount}`,
        `- Receipt digest covered blocked reason count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptDigest.coveredBlockedReasonCount}`,
        `- Receipt lines: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptLines.join("; ")}`,
        `- Receipt line count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptLineCount}`,
        `- Export line count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.exportLineCount}`,
        `- Blocked reason count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.blockedReasonCount}`,
        `- Requires approval: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.requiresApproval}`,
        `- Requires routing activation: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.requiresRoutingActivation}`,
        `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.requiresFreshSiblingEvidence}`,
        `- Starts services: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.startsServices}`,
        `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.mutatesSiblingState}`,
      ],
    },
    {
      heading: "Source Matrix Handoff Summary Consumer Receipt Archive Snapshot",
      lines: [
        `- Snapshot version: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.snapshotVersion}`,
        `- Input receipt version: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.inputReceiptVersion}`,
        `- Snapshot state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.snapshotState}`,
        `- Ready for read-only summary consumer receipt archive: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.readyForReadOnlySummaryConsumerReceiptArchive}`,
        `- Receipt digest value: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.receiptDigestValue}`,
        `- Snapshot digest: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.snapshotDigest.value}`,
        `- Snapshot digest scope: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.snapshotDigest.scope}`,
        `- Snapshot digest covered section count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.snapshotDigest.coveredSectionCount}`,
        `- Archived sections: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.archivedSections.join(", ")}`,
        `- Archived section count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.archivedSectionCount}`,
        `- Receipt line count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.receiptLineCount}`,
        `- Blocked reason count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.blockedReasonCount}`,
        `- Includes raw credential: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.includesRawCredential}`,
        `- Includes runtime payload: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.includesRuntimePayload}`,
        `- Requires approval: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.requiresApproval}`,
        `- Requires routing activation: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.requiresRoutingActivation}`,
        `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.requiresFreshSiblingEvidence}`,
        `- Starts services: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.startsServices}`,
        `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.mutatesSiblingState}`,
      ],
    },
    {
      heading: "Source Matrix Handoff Summary Consumer Receipt Archive Verification",
      lines: [
        `- Verification version: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.verificationVersion}`,
        `- Input snapshot version: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.inputSnapshotVersion}`,
        `- Verification state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.verificationState}`,
        `- Ready for read-only summary consumer receipt archive verification: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.readyForReadOnlySummaryConsumerReceiptArchiveVerification}`,
        `- Gate count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.gateCount}`,
        `- Passed gate count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.passedGateCount}`,
        `- Blocked reason codes: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.blockedReasonCodes.join(", ") || "none"}`,
        `- Snapshot digest value: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.snapshotDigestValue}`,
        `- Archived section count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.archivedSectionCount}`,
        `- Blocked reason count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.blockedReasonCount}`,
        `- Requires approval: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.requiresApproval}`,
        `- Requires routing activation: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.requiresRoutingActivation}`,
        `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.requiresFreshSiblingEvidence}`,
        `- Starts services: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.startsServices}`,
        `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.mutatesSiblingState}`,
        "",
        "### Handoff Summary Receipt Archive Verification Gates",
        ...renderEntries(profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.gates),
      ],
    },
  ]);
}
