import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  DisabledRuntimeShellImplementationCandidateGateItem,
  ManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellImplementationCandidateGateProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellImplementationCandidateGateTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellImplementationCandidateGateMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellImplementationCandidateGateProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver disabled runtime shell implementation candidate gate",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Candidate gate state: ${profile.candidateGateState}`,
    `- Ready for candidate gate: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellImplementationCandidateGate}`,
    `- Ready for Java v134 + mini-kv v131 echo request: ${profile.readyForParallelJavaV134MiniKvV131EchoRequest}`,
    `- Ready for runtime implementation: ${profile.readyForDisabledRuntimeShellImplementation}`,
    `- Runtime shell implemented: ${profile.runtimeShellImplemented}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v296",
    "",
    ...renderEntries(profile.sourceNodeV296),
    "",
    "## Candidate Gate",
    "",
    ...renderEntries({
      gateVersion: profile.candidateGate.gateVersion,
      gateMode: profile.candidateGate.gateMode,
      sourceSpan: profile.candidateGate.sourceSpan,
      gateDecision: profile.candidateGate.gateDecision,
      gateDigest: profile.candidateGate.gateDigest,
      decisionRationale: profile.candidateGate.decisionRationale,
      requiredGateCount: profile.candidateGate.requiredGateCount,
      documentedGateCount: profile.candidateGate.documentedGateCount,
      reviewEvidenceSatisfiedCount: profile.candidateGate.reviewEvidenceSatisfiedCount,
      runtimePrerequisiteSatisfiedCount: profile.candidateGate.runtimePrerequisiteSatisfiedCount,
      implementationAllowedGateCount: profile.candidateGate.implementationAllowedGateCount,
    }),
    "",
    "## Necessity",
    "",
    ...renderEntries(profile.candidateGate.necessity),
    "",
    "## Required Gates",
    "",
    ...profile.candidateGate.requiredGates.flatMap(renderGate),
    "",
    "## Stop Conditions",
    "",
    ...renderList(profile.candidateGate.stopConditions, "No candidate gate stop conditions."),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No disabled runtime shell implementation candidate gate blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No disabled runtime shell implementation candidate gate warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No disabled runtime shell implementation candidate gate recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...profile.nextActions.map((action) => `- ${action}`),
    "",
  ].join("\n");
}

function renderGate(gate: DisabledRuntimeShellImplementationCandidateGateItem): string[] {
  return [
    `- ${gate.code}: ${gate.title}`,
    `  - owner: ${gate.owner}`,
    `  - requirement: ${gate.requirement}`,
    `  - sourceEvidence: ${gate.sourceEvidence}`,
    `  - reviewEvidenceSatisfied: ${gate.reviewEvidenceSatisfied}`,
    `  - runtimePrerequisiteSatisfied: ${gate.runtimePrerequisiteSatisfied}`,
    `  - implementationAllowed: ${gate.implementationAllowed}`,
    `  - failureClass: ${gate.failureClass}`,
  ];
}
