import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftPreflightFieldTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftPreflightTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_VERSIONS = [
  "Node v1087",
  "Node v1088",
  "Node v1089",
  "Node v1090",
  "Node v1091",
  "Node v1092",
  "Node v1093",
  "Node v1094",
  "Node v1095",
  "Node v1096",
  "Node v1097",
  "Node v1098",
  "Node v1099",
  "Node v1100",
  "Node v1101",
  "Node v1102",
  "Node v1103",
  "Node v1104",
  "Node v1105",
  "Node v1106",
  "Node v1107",
  "Node v1108",
  "Node v1109",
  "Node v1110",
  "Node v1111",
] as const;

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_FIELDS:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftPreflightFieldTemplate[]
  = Object.freeze([
    field("Node v1087", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_REQUEST_ID",
      "draftArtifactRequestId", "identity-draft-field", "manual-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_REQUEST_ID", "captureArtifactPreflightRequestId",
      "ARTIFACT_DRAFT_PREFLIGHT_REQUEST_ID_MISSING", "Stable id for the future manual signed approval draft."),
    field("Node v1088", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_ARTIFACT_PREFLIGHT_DIGEST",
      "sourceSignedApprovalCaptureArtifactPreflightDigest", "digest-binding-draft-field", "digest-reference",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_CAPTURE_PREFLIGHT_DIGEST",
      "sourceSignedApprovalCapturePreflightDigest",
      "ARTIFACT_DRAFT_PREFLIGHT_ARTIFACT_PREFLIGHT_DIGEST_MISSING",
      "Digest binding to the v1086 artifact preflight."),
    field("Node v1089", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_TEMPLATE_DIGEST",
      "sourceSignedApprovalTemplateDigest", "digest-binding-draft-field", "digest-reference",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_TEMPLATE_DIGEST", "sourceSignedApprovalTemplateDigest",
      "ARTIFACT_DRAFT_PREFLIGHT_TEMPLATE_DIGEST_MISSING", "Digest binding to the v1036 template."),
    field("Node v1090", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_REVIEW_DIGEST",
      "sourceApprovalPacketReviewDigest", "digest-binding-draft-field", "digest-reference",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_REVIEW_DIGEST", "sourceApprovalPacketReviewDigest",
      "ARTIFACT_DRAFT_PREFLIGHT_REVIEW_DIGEST_MISSING", "Digest binding to the approval packet review."),
    field("Node v1091", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_OPERATOR_IDENTITY",
      "operatorIdentity", "identity-draft-field", "manual-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_OPERATOR_IDENTITY", "operatorIdentity",
      "ARTIFACT_DRAFT_PREFLIGHT_OPERATOR_IDENTITY_MISSING", "Operator identity field for manual draft review."),
    field("Node v1092", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_OPERATOR_ROLE",
      "operatorRole", "identity-draft-field", "manual-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_OPERATOR_ROLE", "operatorRole",
      "ARTIFACT_DRAFT_PREFLIGHT_OPERATOR_ROLE_MISSING", "Operator role field for manual draft review."),
    field("Node v1093", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_WINDOW_ID",
      "captureWindowId", "identity-draft-field", "manual-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_WINDOW_ID", "captureWindowId",
      "ARTIFACT_DRAFT_PREFLIGHT_WINDOW_ID_MISSING", "Manual capture window id field."),
    field("Node v1094", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_CHANNEL_POLICY",
      "captureChannelPolicy", "policy-draft-field", "policy-code",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_CHANNEL_POLICY", "captureChannelPolicy",
      "ARTIFACT_DRAFT_PREFLIGHT_CHANNEL_POLICY_MISSING", "Capture channel policy field."),
    field("Node v1095", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SIGNATURE_ALGORITHM",
      "signatureAlgorithmPolicy", "signature-envelope-draft-field", "policy-code",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SIGNATURE_ALGORITHM", "signatureAlgorithmPolicy",
      "ARTIFACT_DRAFT_PREFLIGHT_SIGNATURE_ALGORITHM_MISSING", "Signature algorithm policy field."),
    field("Node v1096", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_DETACHED_SIGNATURE_PLACEHOLDER",
      "detachedSignaturePlaceholder", "signature-envelope-draft-field", "detached-signature-placeholder",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_DETACHED_SIGNATURE_PLACEHOLDER",
      "detachedSignaturePlaceholder",
      "ARTIFACT_DRAFT_PREFLIGHT_DETACHED_SIGNATURE_PLACEHOLDER_MISSING",
      "Detached signature placeholder; no signature payload is captured."),
    field("Node v1097", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SIGNATURE_REDACTION",
      "signatureMaterialRedactionPolicy", "signature-envelope-draft-field", "policy-code",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SIGNATURE_REDACTION", "signatureMaterialRedactionPolicy",
      "ARTIFACT_DRAFT_PREFLIGHT_SIGNATURE_REDACTION_MISSING", "Signature material redaction policy field."),
    field("Node v1098", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_APPROVAL_STATEMENT_DIGEST",
      "approvalStatementDigest", "digest-binding-draft-field", "digest-reference",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_APPROVAL_STATEMENT_DIGEST", "approvalStatementDigest",
      "ARTIFACT_DRAFT_PREFLIGHT_APPROVAL_STATEMENT_DIGEST_MISSING",
      "Digest placeholder for the future manual approval statement."),
    field("Node v1099", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SOURCE_VERSION",
      "sourceEvidenceVersion", "source-evidence-draft-field", "manual-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SOURCE_VERSION", "sourceEvidenceVersion",
      "ARTIFACT_DRAFT_PREFLIGHT_SOURCE_VERSION_MISSING", "Source evidence version field."),
    field("Node v1100", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SOURCE_FILE",
      "sourceEvidenceFileId", "source-evidence-draft-field", "manual-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SOURCE_FILE", "sourceEvidenceFileId",
      "ARTIFACT_DRAFT_PREFLIGHT_SOURCE_FILE_MISSING", "Source evidence file id field."),
    field("Node v1101", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SOURCE_SNIPPET",
      "sourceEvidenceSnippetId", "source-evidence-draft-field", "manual-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SOURCE_SNIPPET", "sourceEvidenceSnippetId",
      "ARTIFACT_DRAFT_PREFLIGHT_SOURCE_SNIPPET_MISSING", "Source evidence snippet id field."),
    field("Node v1102", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_REDACTED_VALUE_DIGEST",
      "redactedValueDigest", "value-binding-draft-field", "digest-reference",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_REDACTED_VALUE_DIGEST", "redactedValueDigest",
      "ARTIFACT_DRAFT_PREFLIGHT_REDACTED_VALUE_DIGEST_MISSING", "Redacted value digest field."),
    field("Node v1103", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_VALUE_SHAPE",
      "valueShape", "value-binding-draft-field", "manual-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_VALUE_SHAPE", "valueShape",
      "ARTIFACT_DRAFT_PREFLIGHT_VALUE_SHAPE_MISSING", "Typed value shape field."),
    field("Node v1104", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_REDACTION_POLICY",
      "redactionPolicy", "policy-draft-field", "policy-code",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_REDACTION_POLICY", "redactionPolicy",
      "ARTIFACT_DRAFT_PREFLIGHT_REDACTION_POLICY_MISSING", "Redaction policy field."),
    field("Node v1105", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_PROVENANCE_POLICY",
      "provenancePolicy", "policy-draft-field", "policy-code",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_PROVENANCE_POLICY", "provenancePolicy",
      "ARTIFACT_DRAFT_PREFLIGHT_PROVENANCE_POLICY_MISSING", "Provenance policy field."),
    field("Node v1106", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_NO_RAW_SECRET_LOCK",
      "noRawSecretLock", "execution-lock-draft-field", "boolean-lock",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_NO_RAW_SECRET_LOCK", "noRawSecretLock",
      "ARTIFACT_DRAFT_PREFLIGHT_NO_RAW_SECRET_LOCK_MISSING", "Lock proving raw signature material is absent."),
    field("Node v1107", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_NO_GRANT_LOCK",
      "noApprovalGrantEmittedLock", "execution-lock-draft-field", "boolean-lock",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_NO_GRANT_LOCK", "noApprovalGrantEmittedLock",
      "ARTIFACT_DRAFT_PREFLIGHT_NO_GRANT_LOCK_MISSING", "Lock proving no approval grant was emitted."),
    field("Node v1108", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_ZERO_VALUE_IMPORT_LOCK",
      "zeroValueImportLock", "execution-lock-draft-field", "boolean-lock",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_ZERO_VALUE_IMPORT_LOCK", "zeroValueImportLock",
      "ARTIFACT_DRAFT_PREFLIGHT_ZERO_VALUE_IMPORT_LOCK_MISSING",
      "Lock proving value submission and import remain zero."),
    field("Node v1109", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_NO_WRITE_ROUTE_LOCK",
      "noWriteRouteLock", "execution-lock-draft-field", "boolean-lock",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_NO_WRITE_ROUTE_LOCK", "noWriteRouteLock",
      "ARTIFACT_DRAFT_PREFLIGHT_NO_WRITE_ROUTE_LOCK_MISSING", "Lock proving no write route is enabled."),
    field("Node v1110", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_SIBLING_NON_MUTATION_LOCK",
      "siblingNonMutationLock", "execution-lock-draft-field", "boolean-lock",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SIBLING_NON_MUTATION_LOCK", "siblingNonMutationLock",
      "ARTIFACT_DRAFT_PREFLIGHT_SIBLING_NON_MUTATION_LOCK_MISSING",
      "Lock proving sibling projects remain unchanged."),
    field("Node v1111", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_PREFLIGHT_CLOSEOUT",
      "signedApprovalCaptureArtifactDraftPreflightCloseout", "closeout-draft-field", "manual-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_CLOSEOUT",
      "signedApprovalCaptureArtifactPreflightCloseout",
      "ARTIFACT_DRAFT_PREFLIGHT_CLOSEOUT_MISSING",
      "Closeout limiting the next step to a manual signed approval draft."),
  ]);

function field(
  nodeVersion:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftPreflightFieldTemplate[
      "nodeVersion"
    ],
  code: string,
  fieldName: string,
  kind:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftPreflightFieldTemplate[
      "kind"
    ],
  fieldMode:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftPreflightFieldTemplate[
      "fieldMode"
    ],
  sourceArtifactFragmentCode: string,
  requiredArtifactFragmentName: string,
  draftBlockerCode: string,
  fieldPurpose: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftPreflightFieldTemplate {
  return {
    nodeVersion,
    code,
    fieldName,
    kind,
    fieldMode,
    sourceArtifactFragmentCode,
    requiredArtifactFragmentName,
    draftBlockerCode,
    fieldPurpose,
  };
}
