import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  EndpointHandleAllowlistApprovalClosurePrerequisite,
  ManagedAuditManualSandboxConnectionCredentialResolverEndpointHandleAllowlistApprovalPrerequisiteClosureReviewProfile,
  SourceNodeV321EndpointHandleAllowlistApprovalContractUpstreamEchoVerificationReference,
} from "./managedAuditManualSandboxConnectionCredentialResolverEndpointHandleAllowlistApprovalPrerequisiteClosureReviewTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverEndpointHandleAllowlistApprovalPrerequisiteClosureReviewMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverEndpointHandleAllowlistApprovalPrerequisiteClosureReviewProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver endpoint handle allowlist approval prerequisite closure review",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Review state: ${profile.reviewState}`,
    `- Prerequisite closure decision: ${profile.prerequisiteClosureDecision}`,
    `- Ready for closure review: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverEndpointHandleAllowlistApprovalPrerequisiteClosureReview}`,
    `- Active Node review version: ${profile.activeNodeReviewVersion}`,
    `- Ready for no-network safety fixture contract intake: ${profile.readyForNoNetworkSafetyFixtureContractIntake}`,
    `- New Java + mini-kv echo requested: ${profile.newJavaMiniKvEchoRequested}`,
    `- Runtime shell implemented: ${profile.runtimeShellImplemented}`,
    `- Runtime shell invocation allowed: ${profile.runtimeShellInvocationAllowed}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    "",
    "## Source Node v321",
    "",
    ...renderSourceNodeV321(profile.sourceNodeV321),
    "",
    "## Closure Review",
    "",
    ...renderEntries({
      reviewDigest: profile.closureReview.reviewDigest,
      reviewMode: profile.closureReview.reviewMode,
      sourceSpan: profile.closureReview.sourceSpan,
      sourceVerificationDigest: profile.closureReview.sourceVerificationDigest,
      completedPrerequisiteCount: profile.closureReview.completedPrerequisiteCount,
      remainingPrerequisiteCount: profile.closureReview.remainingPrerequisiteCount,
      originalPrerequisiteCount: profile.closureReview.originalPrerequisiteCount,
      movedPrerequisiteId: profile.closureReview.movedPrerequisiteId,
      movedFrom: profile.closureReview.movedFrom,
      movedTo: profile.closureReview.movedTo,
      nextConcretePrerequisiteId: profile.closureReview.nextConcretePrerequisiteId,
      nextConcretePrerequisiteContractRequired: profile.closureReview.nextConcretePrerequisiteContractRequired,
      nextNodeVersionSuggested: profile.closureReview.nextNodeVersionSuggested,
      nextJavaVersionRequested: profile.closureReview.nextJavaVersionRequested,
      nextMiniKvVersionRequested: profile.closureReview.nextMiniKvVersionRequested,
      chainContinuationAllowed: profile.closureReview.chainContinuationAllowed,
      runtimeShellStillBlocked: profile.closureReview.runtimeShellStillBlocked,
      closureReason: profile.closureReview.closureReason,
    }),
    "",
    "### Completed Prerequisites",
    "",
    ...renderPrerequisites(profile.closureReview.completedPrerequisites),
    "",
    "### Remaining Prerequisites",
    "",
    ...renderPrerequisites(profile.closureReview.remainingPrerequisites),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No endpoint handle allowlist prerequisite closure review blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No endpoint handle allowlist prerequisite closure review warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No endpoint handle allowlist prerequisite closure review recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderSourceNodeV321(
  reference: SourceNodeV321EndpointHandleAllowlistApprovalContractUpstreamEchoVerificationReference,
): string[] {
  return renderEntries({
    sourceVersion: reference.sourceVersion,
    profileVersion: reference.profileVersion,
    verificationState: reference.verificationState,
    readyForEndpointHandleAllowlistApprovalContractUpstreamEchoVerification:
      reference.readyForEndpointHandleAllowlistApprovalContractUpstreamEchoVerification,
    readOnlyUpstreamEchoVerification: reference.readOnlyUpstreamEchoVerification,
    verificationDigest: reference.verificationDigest,
    sourceSpan: reference.sourceSpan,
    sourceNodeV320Ready: reference.sourceNodeV320Ready,
    javaV147EchoReady: reference.javaV147EchoReady,
    miniKvV140ReceiptReady: reference.miniKvV140ReceiptReady,
    upstreamEchoAligned: reference.upstreamEchoAligned,
    endpointHandleAllowlistContractAligned: reference.endpointHandleAllowlistContractAligned,
    sideEffectBoundariesAligned: reference.sideEffectBoundariesAligned,
    implementationStillBlocked: reference.implementationStillBlocked,
    remainingPrerequisitesAfterV321: reference.remainingPrerequisitesAfterV321,
    contractDigest: reference.contractDigest,
    requiredFieldCount: reference.requiredFieldCount,
    prohibitedFieldCount: reference.prohibitedFieldCount,
    rejectionReasonCount: reference.rejectionReasonCount,
    noGoBoundaryCount: reference.noGoBoundaryCount,
    upstreamEchoRequestCount: reference.upstreamEchoRequestCount,
    sourceProductionBlockerCount: reference.sourceProductionBlockerCount,
  });
}

function renderPrerequisites(prerequisites: EndpointHandleAllowlistApprovalClosurePrerequisite[]): string[] {
  return renderList(
    prerequisites.map((prerequisite) =>
      `${prerequisite.id}: ${prerequisite.closureState}; requiredBeforeRuntimeShell=${prerequisite.requiredBeforeRuntimeShell}; opensRuntimeShell=${prerequisite.opensRuntimeShell}; evidence=${prerequisite.evidence}`),
    "No prerequisites.",
  );
}
