import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionPacketContributionReviewProfile,
  RuntimeExecutionPacketReviewRow,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionPacketContributionReviewTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionPacketContributionReviewMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionPacketContributionReviewProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Contribution review state: ${profile.contributionReviewState}`,
    `- Contribution review decision: ${profile.contributionReviewDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for Node v398 runtime execution packet approval gate review: ${profile.readyForNodeV398RuntimeExecutionPacketApprovalGateReview}`,
    `- Ready for runtime execution packet: ${profile.readyForRuntimeExecutionPacket}`,
    `- Ready for runtime live-read gate: ${profile.readyForRuntimeLiveReadGate}`,
    `- Runtime execution artifacts complete: ${profile.runtimeExecutionArtifactsComplete}`,
    `- Present runtime execution artifact count: ${profile.presentRuntimeExecutionArtifactCount}`,
    `- Missing runtime execution artifact count: ${profile.missingRuntimeExecutionArtifactCount}`,
    `- Runtime execution packet present: ${profile.runtimeExecutionPacketPresent}`,
    `- Runtime execution packet executable: ${profile.runtimeExecutionPacketExecutable}`,
    `- Runtime gate approval present: ${profile.runtimeGateApprovalPresent}`,
    `- Concrete loopback ports assigned: ${profile.concreteLoopbackPortsAssigned}`,
    `- Execution attempted: ${profile.executionAttempted}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Active shard prototype enabled: ${profile.activeShardPrototypeEnabled}`,
    "",
    "## Source Node v396",
    "",
    ...renderEntries(profile.sourceNodeV396),
    "",
    "## Java v163 Runtime Execution Packet Contribution",
    "",
    ...renderEntries(profile.javaV163RuntimeExecutionPacketContribution),
    "",
    "## mini-kv v154 Runtime Execution Candidate",
    "",
    ...renderEntries(profile.miniKvV154RuntimeExecutionCandidate),
    "",
    "## Runtime Execution Packet Review Rows",
    "",
    ...profile.reviewRows.flatMap(renderReviewRow),
    "",
    "## Contribution Review",
    "",
    ...renderEntries(profile.contributionReview),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderReviewRow(row: RuntimeExecutionPacketReviewRow): string[] {
  return [
    `- ${row.key}`,
    `  - javaContribution: ${row.javaContribution}`,
    `  - miniKvContribution: ${row.miniKvContribution}`,
    `  - nodeOrOperatorGap: ${row.nodeOrOperatorGap}`,
    `  - crossProjectAccepted: ${row.crossProjectAccepted}`,
  ];
}
