import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionSandboxEndpointCredentialResolverTestOnlyShellUpstreamEchoVerificationProfile,
} from "./managedAuditManualSandboxConnectionSandboxEndpointCredentialResolverTestOnlyShellUpstreamEchoVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionSandboxEndpointCredentialResolverTestOnlyShellUpstreamEchoVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionSandboxEndpointCredentialResolverTestOnlyShellUpstreamEchoVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection sandbox endpoint credential resolver test-only shell upstream echo verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Verification state: ${profile.verificationState}`,
    `- Ready for test-only shell upstream echo verification: ${profile.readyForManagedAuditManualSandboxConnectionSandboxEndpointCredentialResolverTestOnlyShellUpstreamEchoVerification}`,
    `- Ready for sandbox adapter connection: ${profile.readyForManagedAuditSandboxAdapterConnection}`,
    "",
    "## Source Node v264",
    "",
    ...renderEntries({
      sourceVersion: profile.sourceNodeV264.sourceVersion,
      profileVersion: profile.sourceNodeV264.profileVersion,
      shellContractState: profile.sourceNodeV264.shellContractState,
      readyForTestOnlyShellContract: profile.sourceNodeV264.readyForTestOnlyShellContract,
      shellMode: profile.sourceNodeV264.shellMode,
      resolverKind: profile.sourceNodeV264.resolverKind,
      requestShapeFieldCount: profile.sourceNodeV264.requestShapeFieldCount,
      responseShapeFieldCount: profile.sourceNodeV264.responseShapeFieldCount,
      failureMappingCount: profile.sourceNodeV264.failureMappingCount,
      guardConditionCount: profile.sourceNodeV264.guardConditionCount,
      readyForNodeV265: profile.sourceNodeV264.readyForNodeV265TestOnlyShellUpstreamEchoVerification,
    }),
    "",
    "## Java v107 Echo",
    "",
    ...renderEntries({
      sourceVersion: profile.upstreamEchoes.javaV107.sourceVersion,
      responseSchemaVersion: profile.upstreamEchoes.javaV107.responseSchemaVersion,
      markerField: profile.upstreamEchoes.javaV107.markerField,
      consumedNodeVersion: profile.upstreamEchoes.javaV107.consumedNodeVersion,
      nextNodeConsumerVersion: profile.upstreamEchoes.javaV107.nextNodeConsumerVersion,
      shellMode: profile.upstreamEchoes.javaV107.shellMode,
      resolverKind: profile.upstreamEchoes.javaV107.resolverKind,
      requestShapeFieldCount: profile.upstreamEchoes.javaV107.requestShapeFieldCount,
      responseShapeFieldCount: profile.upstreamEchoes.javaV107.responseShapeFieldCount,
      failureMappingCount: profile.upstreamEchoes.javaV107.failureMappingCount,
      guardConditionCount: profile.upstreamEchoes.javaV107.guardConditionCount,
      readyForNodeV265: profile.upstreamEchoes.javaV107.readyForNodeV265SandboxEndpointCredentialResolverTestOnlyShellUpstreamEchoVerification,
    }),
    "",
    "## mini-kv v116 Non-Participation",
    "",
    ...renderEntries({
      sourceVersion: profile.upstreamEchoes.miniKvV116.sourceVersion,
      receiptVersion: profile.upstreamEchoes.miniKvV116.receiptVersion,
      releaseVersion: profile.upstreamEchoes.miniKvV116.releaseVersion,
      consumerHint: profile.upstreamEchoes.miniKvV116.consumerHint,
      receiptDigest: profile.upstreamEchoes.miniKvV116.receiptDigest,
      sourceContractProfileVersion: profile.upstreamEchoes.miniKvV116.sourceContractProfileVersion,
      sourceContractState: profile.upstreamEchoes.miniKvV116.sourceContractState,
      sourceShellMode: profile.upstreamEchoes.miniKvV116.sourceShellMode,
      sourceResolverKind: profile.upstreamEchoes.miniKvV116.sourceResolverKind,
      readyForNodeV265Alignment: profile.upstreamEchoes.miniKvV116.readyForNodeV265Alignment,
    }),
    "",
    "## Java v109 Optimization Context",
    "",
    ...renderEntries(profile.optimizationContext.javaV109),
    "",
    "## Echo Verification",
    "",
    ...renderEntries(profile.echoVerification),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No test-only resolver shell upstream echo verification blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No test-only resolver shell upstream echo verification warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No test-only resolver shell upstream echo verification recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
