import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverShardReadinessCompatibilityReportProfile,
  ShardReadinessCompatibilityFieldCheck,
  ShardReadinessCompatibilityProjectReport,
} from "./managedAuditManualSandboxConnectionCredentialResolverShardReadinessCompatibilityReportTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverShardReadinessCompatibilityReportMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverShardReadinessCompatibilityReportProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver shard readiness compatibility report",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Compatibility state: ${profile.compatibilityState}`,
    `- Compatibility decision: ${profile.compatibilityDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source static Node version: ${profile.sourceStaticNodeVersion}`,
    `- Source archive Node version: ${profile.sourceArchiveNodeVersion}`,
    `- Ready for Node v374 minimal shard readiness regular gate: ${profile.readyForNodeV374MinimalShardReadinessRegularGate}`,
    `- Compatibility report only: ${profile.compatibilityReportOnly}`,
    `- Reruns live read: ${profile.rerunsLiveRead}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Stops Java service: ${profile.stopsJavaService}`,
    `- Stops mini-kv service: ${profile.stopsMiniKvService}`,
    `- Mutates Java state: ${profile.mutatesJavaState}`,
    `- Mutates mini-kv state: ${profile.mutatesMiniKvState}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v370",
    "",
    ...renderEntries(profile.sourceNodeV370),
    "",
    "## Source Node v372",
    "",
    ...renderEntries(profile.sourceNodeV372),
    "",
    "## Project Reports",
    "",
    ...profile.projectReports.flatMap(renderProjectReport),
    "",
    "## Field Checks",
    "",
    ...profile.fieldChecks.map(renderFieldCheck),
    "",
    "## Compatibility Report",
    "",
    ...renderEntries(profile.compatibilityReport),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderProjectReport(report: ShardReadinessCompatibilityProjectReport): string[] {
  return [
    `- ${report.project}:`,
    `  - staticSourceVersion: ${report.staticSourceVersion}`,
    `  - liveSourceVersion: ${report.liveSourceVersion}`,
    `  - staticReady: ${report.staticReady}`,
    `  - liveReady: ${report.liveReady}`,
    `  - readOnlySafe: ${report.readOnlySafe}`,
    `  - executionBlocked: ${report.executionBlocked}`,
    `  - activeShardingEnabled: ${report.activeShardingEnabled}`,
    `  - fieldCount: ${report.fieldCount}`,
    `  - matchedFieldCount: ${report.matchedFieldCount}`,
    `  - mismatchedFields: ${report.mismatchedFields.length === 0 ? "none" : report.mismatchedFields.join(", ")}`,
    `  - compatibleForRegularGate: ${report.compatibleForRegularGate}`,
  ];
}

function renderFieldCheck(check: ShardReadinessCompatibilityFieldCheck): string {
  return `- ${check.project}.${check.field}: static=${String(check.staticValue)}; live=${String(check.liveValue)}; matches=${check.matches}`;
}
