import { renderEntries, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyDraftCandidateProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyDraftCandidateTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyDraftCandidateMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyDraftCandidateProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver disabled runtime shell design draft body draft candidate",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Draft candidate state: ${profile.draftCandidateState}`,
    `- Draft candidate decision: ${profile.draftCandidateDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for v343 body draft candidate: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyDraftCandidate}`,
    `- Ready for Node v344 archive verification: ${profile.readyForNodeV344DisabledRuntimeShellDesignDraftBodyDraftCandidateArchiveVerification}`,
    `- Ready for disabled runtime shell design draft: ${profile.readyForDisabledRuntimeShellDesignDraft}`,
    `- Ready for runtime shell implementation: ${profile.readyForRuntimeShellImplementation}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Credential value read: ${profile.credentialValueRead}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    `- HTTP request sent: ${profile.httpRequestSent}`,
    `- TCP connection attempted: ${profile.tcpConnectionAttempted}`,
    `- Java SQL execution allowed: ${profile.javaSqlExecutionAllowed}`,
    `- mini-kv write command allowed: ${profile.miniKvWriteCommandAllowed}`,
    `- Automatic upstream start: ${profile.automaticUpstreamStart}`,
    "",
    "## Source Node v342",
    "",
    ...renderEntries({
      archiveVerificationState: profile.sourceNodeV342.archiveVerificationState,
      archiveVerificationDecision: profile.sourceNodeV342.archiveVerificationDecision,
      readyForArchiveVerification: profile.sourceNodeV342.readyForArchiveVerification,
      readyForNodeV343DisabledRuntimeShellDesignDraftBodyDraftCandidate:
        profile.sourceNodeV342.readyForNodeV343DisabledRuntimeShellDesignDraftBodyDraftCandidate,
      archiveVerificationDigest: profile.sourceNodeV342.archiveVerificationDigest,
      sourcePlanDigest: profile.sourceNodeV342.sourcePlanDigest,
      sourceChecks: `${profile.sourceNodeV342.sourcePassedCheckCount}/${profile.sourceNodeV342.sourceCheckCount}`,
      sourceArchiveFiles:
        `${profile.sourceNodeV342.sourcePresentArchiveFileCount}/${profile.sourceNodeV342.sourceArchiveFileCount}`,
      sourceProductionBlockers: profile.sourceNodeV342.sourceProductionBlockerCount,
    }),
    "",
    "## Necessity Proof",
    "",
    ...renderEntries(profile.necessityProof),
    "",
    "## Draft Candidate",
    "",
    ...renderEntries(profile.draftCandidate),
    "",
    "## Body Sections",
    "",
    ...profile.bodySections.map((entry) => `- ${entry.id}: ${entry.title}; ${entry.body}`),
    "",
    "## Evidence Citations",
    "",
    ...profile.evidenceCitations.map((entry) =>
      `- ${entry.id}: ${entry.sourceVersion}; ${entry.citationRole}; cited=${entry.citedByDraftCandidate}`),
    "",
    "## Safety Guards",
    "",
    ...profile.safetyGuards.map((entry) => `- ${entry.id}: enforced=${entry.enforced}`),
    "",
    "## Stop Conditions",
    "",
    ...profile.stopConditions.map((entry) => `- ${entry.code}: action=${entry.action}`),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    `- Checks: ${profile.summary.passedCheckCount}/${profile.summary.checkCount}`,
    `- Source Node v342 checks: ${profile.summary.sourceNodeV342PassedCheckCount}/${profile.summary.sourceNodeV342CheckCount}`,
    `- Source archive files: ${profile.summary.sourcePresentArchiveFileCount}/${profile.summary.sourceArchiveFileCount}`,
    `- Source production blockers: ${profile.summary.sourceProductionBlockerCount}`,
    `- Body sections: ${profile.summary.sectionCount}`,
    `- Evidence citations: ${profile.summary.evidenceCitationCount}`,
    `- Safety guards: ${profile.summary.safetyGuardCount}`,
    `- Stop conditions: ${profile.summary.stopConditionCount}`,
    `- Production blockers: ${profile.summary.productionBlockerCount}`,
    `- Warnings: ${profile.summary.warningCount}`,
    `- Recommendations: ${profile.summary.recommendationCount}`,
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...profile.nextActions.map((item) => `- ${item}`),
    "",
  ].join("\n");
}
