import { renderEntries } from "./liveProbeReportUtils.js";
import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraftSlot,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraftTypes.js";
import {
  renderVerificationBlockedReasonLines,
  renderVerificationReportMarkdown,
  renderVerificationResolvedEvidenceFileDetailLines,
  trimVerificationTrailingBlankLine,
} from "./verificationReportBuilder.js";

export function renderControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraftMarkdown(
  draft: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraft,
): string {
  return renderVerificationReportMarkdown({
    title: "Controlled read-only shard preview live read-only window operator evidence value supply approval packet draft",
    meta: [
      ["Approval packet draft version", draft.approvalPacketDraftVersion],
      ["Source value supply envelope version", draft.sourceValueSupplyEnvelopeVersion],
      ["Java value supply evidence version", draft.javaValueSupplyEvidenceVersion],
      ["mini-kv value supply evidence version", draft.miniKvValueSupplyEvidenceVersion],
      ["Draft state", draft.draftState],
      ["Ready for value supply approval packet draft", draft.readyForValueSupplyApprovalPacketDraft],
      ["Ready for operator value supply", draft.readyForOperatorValueSupply],
      ["Ready for operator value submission", draft.readyForOperatorValueSubmission],
      ["Ready for evidence import", draft.readyForEvidenceImport],
      ["Ready for manual evidence entry", draft.readyForManualEvidenceEntry],
      ["Ready for runtime payload", draft.readyForRuntimePayload],
      ["Ready for live execution", draft.readyForLiveExecution],
      ["Ready for production execution", draft.readyForProductionExecution],
      ["Draft slot count", draft.draftSlotCount],
      ["Java evidence slot count", draft.javaEvidenceSlotCount],
      ["mini-kv evidence slot count", draft.miniKvEvidenceSlotCount],
      ["Node value supply envelope slot count", draft.nodeValueSupplyEnvelopeSlotCount],
      ["Evidence files present", `${draft.presentFileCount}/${draft.fileCount}`],
      ["Evidence snippets matched", `${draft.matchedSnippetCount}/${draft.snippetCount}`],
      ["Historical fixture resolved file count", draft.historicalFixtureResolvedFileCount],
      ["Approval field count", draft.approvalFieldCount],
      ["Review record field count", draft.reviewRecordFieldCount],
      ["Supplied value count", draft.suppliedValueCount],
      ["Accepted value count", draft.acceptedValueCount],
      ["Imported value count", draft.importedValueCount],
      ["Approval captured", draft.approvalCaptured],
      ["Approval grant present", draft.approvalGrantPresent],
      ["Signed approval present", draft.signedApprovalPresent],
      ["Operator identity present", draft.operatorIdentityPresent],
      ["Approval timestamp present", draft.approvalTimestampPresent],
      ["Passed gates", `${draft.passedGateCount}/${draft.gateCount}`],
      ["Imports runtime payload", draft.importsRuntimePayload],
      ["Accepts synthetic evidence", draft.acceptsSyntheticEvidence],
      ["Contains secret value", draft.containsSecretValue],
      ["Approval packet draft digest", draft.approvalPacketDraftDigest],
    ],
    trailingNewline: false,
    sections: [
      { heading: "Gates", lines: renderEntries(draft.gates), bodyLeadingBlankLine: false },
      {
        heading: "Evidence Files",
        lines: renderVerificationResolvedEvidenceFileDetailLines(Object.values(draft.files)),
        bodyLeadingBlankLine: false,
      },
      {
        heading: "Snippets",
        lines: draft.snippets.map((snippet) =>
          `- ${snippet.id}: matched=${snippet.matched}, resolvedPath=${snippet.resolvedPath}`),
        bodyLeadingBlankLine: false,
      },
      {
        heading: "Slots",
        lines: trimVerificationTrailingBlankLine(draft.slots.flatMap(renderSlot)),
        bodyLeadingBlankLine: false,
      },
      {
        heading: "Blocked Reasons",
        lines: renderVerificationBlockedReasonLines(draft.blockedReasonCodes),
        bodyLeadingBlankLine: false,
      },
    ],
  });
}

function renderSlot(
  slot: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketDraftSlot,
): string[] {
  return [
    `### ${slot.order}. ${slot.nodeVersion} ${slot.code}`,
    `- Kind: ${slot.kind}`,
    `- Project: ${slot.project}`,
    `- Source value supply envelope slot: ${slot.sourceValueSupplyEnvelopeSlotCode}`,
    `- Source value supply envelope node version: ${slot.sourceValueSupplyEnvelopeNodeVersion}`,
    `- Source value supply envelope slot ready: ${slot.sourceValueSupplyEnvelopeSlotReady}`,
    `- Evidence file id: ${slot.evidenceFileId}`,
    `- Evidence snippet id: ${slot.evidenceSnippetId}`,
    `- Evidence file present: ${slot.evidenceFilePresent}`,
    `- Evidence snippet matched: ${slot.evidenceSnippetMatched}`,
    `- Evidence resolved from historical fixture: ${slot.evidenceResolvedFromHistoricalFixture}`,
    `- Evidence expectation: ${slot.evidenceExpectation}`,
    `- Value supply evidence version: ${slot.valueSupplyEvidenceVersion}`,
    `- Approval field names: ${slot.approvalFieldNames.join(", ")}`,
    `- Required review record fields: ${slot.requiredReviewRecordFields.join(", ")}`,
    `- Approval policy: ${slot.policy.approvalPolicy}`,
    `- Packet policy: ${slot.policy.packetPolicy}`,
    `- Missing value policy: ${slot.policy.missingValuePolicy}`,
    `- Malformed value policy: ${slot.policy.malformedValuePolicy}`,
    `- Redaction policy: ${slot.policy.redactionPolicy}`,
    `- Provenance policy: ${slot.policy.provenancePolicy}`,
    `- Approval captured: ${slot.approvalCaptured}`,
    `- Approval grant present: ${slot.approvalGrantPresent}`,
    `- Signed approval present: ${slot.signedApprovalPresent}`,
    `- Operator identity present: ${slot.operatorIdentityPresent}`,
    `- Approval timestamp present: ${slot.approvalTimestampPresent}`,
    `- Supplied value count: ${slot.suppliedValueCount}`,
    `- Accepted value count: ${slot.acceptedValueCount}`,
    `- Imported value count: ${slot.importedValueCount}`,
    `- Ready for value supply approval packet draft: ${slot.readyForValueSupplyApprovalPacketDraft}`,
    `- Ready for operator value supply: ${slot.readyForOperatorValueSupply}`,
    `- Ready for operator value submission: ${slot.readyForOperatorValueSubmission}`,
    `- Ready for evidence import: ${slot.readyForEvidenceImport}`,
    `- Ready for manual evidence entry: ${slot.readyForManualEvidenceEntry}`,
    `- Ready for runtime payload: ${slot.readyForRuntimePayload}`,
    `- Ready for live execution: ${slot.readyForLiveExecution}`,
    `- Ready for production execution: ${slot.readyForProductionExecution}`,
    `- Imports runtime payload: ${slot.importsRuntimePayload}`,
    `- Accepts synthetic evidence: ${slot.acceptsSyntheticEvidence}`,
    `- Contains secret value: ${slot.containsSecretValue}`,
    `- Writes allowed: ${slot.writesAllowed}`,
    `- Automatic service start: ${slot.automaticServiceStart}`,
    `- Starts services: ${slot.startsServices}`,
    `- Mutates sibling state: ${slot.mutatesSiblingState}`,
    "",
  ];
}
