import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvOperatorServiceLifecycleEvidenceIntakeProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvOperatorServiceLifecycleEvidenceIntakeTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvOperatorServiceLifecycleEvidenceIntakeMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvOperatorServiceLifecycleEvidenceIntakeProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Intake state: ${profile.intakeState}`,
    `- Intake decision: ${profile.intakeDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for Node v387 archive verification: ${profile.readyForNodeV387ArchiveVerification}`,
    `- Ready for runtime live-read gate: ${profile.readyForRuntimeLiveReadGate}`,
    `- Evidence intake only: ${profile.evidenceIntakeOnly}`,
    `- Live read gate allowed: ${profile.liveReadGateAllowed}`,
    `- Runtime probe allowed: ${profile.runtimeProbeAllowed}`,
    `- Reruns live read: ${profile.rerunsLiveRead}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Stops Java service: ${profile.stopsJavaService}`,
    `- Stops mini-kv service: ${profile.stopsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Active shard prototype enabled: ${profile.activeShardPrototypeEnabled}`,
    "",
    "## Source Node v385",
    "",
    ...renderEntries(profile.sourceNodeV385),
    "",
    "## Java v160 Operator Service Lifecycle",
    "",
    ...renderEntries(profile.javaOperatorServiceLifecycle),
    "",
    "## mini-kv v151 Operator Service Lifecycle Template",
    "",
    ...renderEntries(profile.miniKvOperatorServiceLifecycleTemplate),
    "",
    "## mini-kv v150 Frozen Live Read Gate Plan",
    "",
    ...renderEntries(profile.miniKvFrozenLiveReadGatePlan),
    "",
    "## Evidence Files",
    "",
    ...[
      profile.javaOperatorServiceLifecycleFile,
      profile.miniKvOperatorServiceLifecycleTemplateFile,
      profile.miniKvFrozenLiveReadGatePlanFile,
    ].map((file) =>
      `- ${file.id}: exists=${file.exists}; fallback=${file.usedHistoricalFallback}; bytes=${file.byteLength}; digest=${file.digest}; resolved=${file.resolvedPath}`),
    "",
    "## Intake",
    "",
    ...renderEntries(profile.intake),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
