import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageComparedEvidenceEvaluationPreflightGuardTemplate,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageComparedEvidenceEvaluationPreflightRuleTemplate,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageComparedEvidenceEvaluationPreflightVersion,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageComparedEvidenceEvaluationPreflightTypes.js";

const ALL_INTAKE_SLOT_KINDS = [
  "source-acceptance-precheck-evidence-slot",
  "manual-submission-reference-evidence-slot",
  "offline-comparison-result-evidence-slot",
  "identity-binding-evidence-slot",
  "digest-match-summary-evidence-slot",
  "detached-signature-envelope-observation-evidence-slot",
  "source-evidence-handle-evidence-slot",
  "policy-execution-lock-evidence-slot",
  "approval-grant-separation-evidence-slot",
  "archive-closeout-evidence-slot",
] as const;

const ALL_INTAKE_GUARD_KINDS = [
  "source-acceptance-precheck-evidence-guard",
  "manual-submission-reference-evidence-guard",
  "offline-comparison-result-evidence-guard",
  "identity-binding-evidence-guard",
  "digest-match-summary-evidence-guard",
  "detached-signature-envelope-observation-evidence-guard",
  "source-evidence-handle-evidence-guard",
  "policy-execution-lock-evidence-guard",
  "approval-grant-separation-evidence-guard",
  "archive-closeout-evidence-guard",
] as const;

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_PREFLIGHT_VERSIONS:
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageComparedEvidenceEvaluationPreflightVersion[] = [
    "Node v1332",
    "Node v1333",
    "Node v1334",
    "Node v1335",
    "Node v1336",
    "Node v1337",
    "Node v1338",
    "Node v1339",
    "Node v1340",
    "Node v1341",
    "Node v1342",
    "Node v1343",
    "Node v1344",
    "Node v1345",
    "Node v1346",
    "Node v1347",
    "Node v1348",
    "Node v1349",
    "Node v1350",
    "Node v1351",
  ];

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_PREFLIGHT_RULES:
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageComparedEvidenceEvaluationPreflightRuleTemplate[] = [
    {
      nodeVersion: "Node v1332",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_SOURCE_INTAKE_RULE",
      ruleName: "Source intake readiness evaluation",
      kind: "source-intake-readiness-evaluation-rule",
      sourceSlotKinds: [...ALL_INTAKE_SLOT_KINDS],
      sourceGuardKinds: [...ALL_INTAKE_GUARD_KINDS],
      expectedCandidateField: "sourceIntakeDigest",
      evaluationQuestion: "Does a real candidate cite the v1331 intake digest and inherit every source slot guard?",
    },
    {
      nodeVersion: "Node v1333",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_ARTIFACT_SHAPE_RULE",
      ruleName: "Evidence artifact shape evaluation",
      kind: "evidence-artifact-shape-evaluation-rule",
      sourceSlotKinds: ["source-acceptance-precheck-evidence-slot"],
      sourceGuardKinds: ["source-acceptance-precheck-evidence-guard"],
      expectedCandidateField: "artifactShape",
      evaluationQuestion: "Does the candidate expose the required immutable evidence fields without executable payloads?",
    },
    {
      nodeVersion: "Node v1334",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_OPERATOR_PROVENANCE_RULE",
      ruleName: "Operator provenance evaluation",
      kind: "operator-provenance-evaluation-rule",
      sourceSlotKinds: ["manual-submission-reference-evidence-slot", "identity-binding-evidence-slot"],
      sourceGuardKinds: ["manual-submission-reference-evidence-guard", "identity-binding-evidence-guard"],
      expectedCandidateField: "operatorProvenance",
      evaluationQuestion: "Does the candidate bind the operator source, request identity, and correlation metadata?",
    },
    {
      nodeVersion: "Node v1335",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_MANUAL_SUBMISSION_REFERENCE_RULE",
      ruleName: "Manual submission reference evaluation",
      kind: "manual-submission-reference-evaluation-rule",
      sourceSlotKinds: ["manual-submission-reference-evidence-slot"],
      sourceGuardKinds: ["manual-submission-reference-evidence-guard"],
      expectedCandidateField: "manualSubmissionReference",
      evaluationQuestion: "Does the candidate cite the submitted draft text package source without creating it in Node?",
    },
    {
      nodeVersion: "Node v1336",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_OFFLINE_COMPARISON_RESULT_RULE",
      ruleName: "Offline comparison result evaluation",
      kind: "offline-comparison-result-evaluation-rule",
      sourceSlotKinds: ["offline-comparison-result-evidence-slot"],
      sourceGuardKinds: ["offline-comparison-result-evidence-guard"],
      expectedCandidateField: "offlineComparisonResult",
      evaluationQuestion: "Does the candidate state the manual comparison result without treating it as acceptance?",
    },
    {
      nodeVersion: "Node v1337",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_IDENTITY_BINDING_RULE",
      ruleName: "Identity binding evaluation",
      kind: "identity-binding-evaluation-rule",
      sourceSlotKinds: ["identity-binding-evidence-slot"],
      sourceGuardKinds: ["identity-binding-evidence-guard"],
      expectedCandidateField: "identityBinding",
      evaluationQuestion: "Does the candidate bind request, operator, correlation, and artifact identity consistently?",
    },
    {
      nodeVersion: "Node v1338",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_DIGEST_LINEAGE_RULE",
      ruleName: "Digest lineage evaluation",
      kind: "digest-lineage-evaluation-rule",
      sourceSlotKinds: ["digest-match-summary-evidence-slot"],
      sourceGuardKinds: ["digest-match-summary-evidence-guard"],
      expectedCandidateField: "digestLineage",
      evaluationQuestion: "Does the candidate bind review, submission, comparison, acceptance precheck, and intake digests?",
    },
    {
      nodeVersion: "Node v1339",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_SIGNATURE_ENVELOPE_RULE",
      ruleName: "Signature envelope metadata evaluation",
      kind: "signature-envelope-metadata-evaluation-rule",
      sourceSlotKinds: ["detached-signature-envelope-observation-evidence-slot"],
      sourceGuardKinds: ["detached-signature-envelope-observation-evidence-guard"],
      expectedCandidateField: "signatureEnvelopeMetadata",
      evaluationQuestion: "Does the candidate only describe signature envelope metadata while keeping payload import disabled?",
    },
    {
      nodeVersion: "Node v1340",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_SOURCE_EVIDENCE_HANDLE_RULE",
      ruleName: "Source evidence handle evaluation",
      kind: "source-evidence-handle-evaluation-rule",
      sourceSlotKinds: ["source-evidence-handle-evidence-slot"],
      sourceGuardKinds: ["source-evidence-handle-evidence-guard"],
      expectedCandidateField: "sourceEvidenceHandles",
      evaluationQuestion: "Does the candidate cite existing Java and mini-kv evidence handles without reading fresh payloads?",
    },
    {
      nodeVersion: "Node v1341",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_OPERATOR_VALUE_HANDLE_RULE",
      ruleName: "Operator value handle evaluation",
      kind: "operator-value-handle-evaluation-rule",
      sourceSlotKinds: ["source-evidence-handle-evidence-slot"],
      sourceGuardKinds: ["source-evidence-handle-evidence-guard"],
      expectedCandidateField: "operatorValueHandles",
      evaluationQuestion: "Does the candidate cite operator value handles without exposing secret values?",
    },
    {
      nodeVersion: "Node v1342",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_POLICY_ASSERTION_RULE",
      ruleName: "Policy assertion evaluation",
      kind: "policy-assertion-evaluation-rule",
      sourceSlotKinds: ["policy-execution-lock-evidence-slot"],
      sourceGuardKinds: ["policy-execution-lock-evidence-guard"],
      expectedCandidateField: "policyAssertions",
      evaluationQuestion: "Does the candidate preserve policy assertions from the intake contract?",
    },
    {
      nodeVersion: "Node v1343",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_EXECUTION_LOCK_RULE",
      ruleName: "Execution lock evaluation",
      kind: "execution-lock-evaluation-rule",
      sourceSlotKinds: ["policy-execution-lock-evidence-slot"],
      sourceGuardKinds: ["policy-execution-lock-evidence-guard"],
      expectedCandidateField: "executionLocks",
      evaluationQuestion: "Does the candidate preserve no-runtime, no-write, no-sibling-mutation, no-live, and no-production locks?",
    },
    {
      nodeVersion: "Node v1344",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_APPROVAL_GRANT_SEPARATION_RULE",
      ruleName: "Approval grant separation evaluation",
      kind: "approval-grant-separation-evaluation-rule",
      sourceSlotKinds: ["approval-grant-separation-evidence-slot"],
      sourceGuardKinds: ["approval-grant-separation-evidence-guard"],
      expectedCandidateField: "approvalGrantSeparation",
      evaluationQuestion: "Does the candidate prove comparison is not approval and cannot capture an approval grant?",
    },
    {
      nodeVersion: "Node v1345",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_ARCHIVE_REFERENCE_RULE",
      ruleName: "Archive reference evaluation",
      kind: "archive-reference-evaluation-rule",
      sourceSlotKinds: ["archive-closeout-evidence-slot"],
      sourceGuardKinds: ["archive-closeout-evidence-guard"],
      expectedCandidateField: "archiveReferences",
      evaluationQuestion: "Does the candidate cite durable archive references for every compared evidence field?",
    },
    {
      nodeVersion: "Node v1346",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_SECRET_VALUE_EXCLUSION_RULE",
      ruleName: "Secret value exclusion evaluation",
      kind: "secret-value-exclusion-evaluation-rule",
      sourceSlotKinds: ["source-evidence-handle-evidence-slot", "policy-execution-lock-evidence-slot"],
      sourceGuardKinds: ["source-evidence-handle-evidence-guard", "policy-execution-lock-evidence-guard"],
      expectedCandidateField: "secretValueExclusion",
      evaluationQuestion: "Does the candidate prove it contains no credential, secret, or raw operator value material?",
    },
    {
      nodeVersion: "Node v1347",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_SYNTHETIC_EVIDENCE_EXCLUSION_RULE",
      ruleName: "Synthetic evidence exclusion evaluation",
      kind: "synthetic-evidence-exclusion-evaluation-rule",
      sourceSlotKinds: [...ALL_INTAKE_SLOT_KINDS],
      sourceGuardKinds: [...ALL_INTAKE_GUARD_KINDS],
      expectedCandidateField: "syntheticEvidenceExclusion",
      evaluationQuestion: "Does the candidate prove evidence came from real manual comparison rather than generated fixture data?",
    },
    {
      nodeVersion: "Node v1348",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_RUNTIME_PAYLOAD_EXCLUSION_RULE",
      ruleName: "Runtime payload exclusion evaluation",
      kind: "runtime-payload-exclusion-evaluation-rule",
      sourceSlotKinds: ["policy-execution-lock-evidence-slot"],
      sourceGuardKinds: ["policy-execution-lock-evidence-guard"],
      expectedCandidateField: "runtimePayloadExclusion",
      evaluationQuestion: "Does the candidate prove it imports no runtime payload and starts no service?",
    },
    {
      nodeVersion: "Node v1349",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_WRITE_AND_SIBLING_MUTATION_EXCLUSION_RULE",
      ruleName: "Write and sibling mutation exclusion evaluation",
      kind: "write-and-sibling-mutation-exclusion-evaluation-rule",
      sourceSlotKinds: ["policy-execution-lock-evidence-slot"],
      sourceGuardKinds: ["policy-execution-lock-evidence-guard"],
      expectedCandidateField: "writeAndSiblingMutationExclusion",
      evaluationQuestion: "Does the candidate prove it cannot write, route writes, or mutate sibling state?",
    },
    {
      nodeVersion: "Node v1350",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_REVIEWER_TRACEABILITY_RULE",
      ruleName: "Reviewer traceability evaluation",
      kind: "reviewer-traceability-evaluation-rule",
      sourceSlotKinds: ["identity-binding-evidence-slot", "archive-closeout-evidence-slot"],
      sourceGuardKinds: ["identity-binding-evidence-guard", "archive-closeout-evidence-guard"],
      expectedCandidateField: "reviewerTraceability",
      evaluationQuestion: "Does the candidate show who reviewed the compared evidence and where the review is archived?",
    },
    {
      nodeVersion: "Node v1351",
      code: "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_CLOSEOUT_RULE",
      ruleName: "Evaluation closeout rule",
      kind: "evaluation-closeout-evaluation-rule",
      sourceSlotKinds: [...ALL_INTAKE_SLOT_KINDS],
      sourceGuardKinds: [...ALL_INTAKE_GUARD_KINDS],
      expectedCandidateField: "evaluationCloseout",
      evaluationQuestion: "Does the candidate close the evaluation without accepting comparison as approval or execution authority?",
    },
  ];

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_PREFLIGHT_GUARDS:
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageComparedEvidenceEvaluationPreflightGuardTemplate[] =
    CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_TEXT_PACKAGE_COMPARED_EVIDENCE_EVALUATION_PREFLIGHT_RULES.map((rule) => ({
      nodeVersion: rule.nodeVersion,
      code: `${rule.code}_GUARD`,
      kind: rule.kind.replace("-rule", "-guard") as
        ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageComparedEvidenceEvaluationPreflightGuardTemplate["kind"],
      sourceRuleCode: rule.code,
      guardCode: `${rule.expectedCandidateField}.missing-or-synthetic-candidate-blocked`,
      guardText:
        `Require a real compared evidence candidate field ${rule.expectedCandidateField}; keep acceptance, approval grant, signed approval, runtime payload, writes, and sibling mutation blocked until a real candidate satisfies the rule.`,
    }));
