import type {
  ControlledReadOnlyShardPreviewSourceMatrixConsumptionPlan,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewConsumptionPlanTypes.js";
import type {
  ControlledReadOnlyShardPreviewObservationPreview,
  ControlledReadOnlyShardPreviewSourceMatrix,
  ControlledReadOnlyShardPreviewSourceMatrixConsumer,
  ControlledReadOnlyShardPreviewSourceMatrixDriftSummary,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewSourceMatrixTypes.js";
import type {
  ControlledReadOnlyShardPreviewChecks,
  ControlledReadOnlyShardPreviewMessage,
  ControlledReadOnlyShardPreviewObservation,
  ControlledReadOnlyShardPreviewSummary,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewSupportTypes.js";
import type {
  ControlledReadOnlyShardPreviewSourceMatrixReviewChecklist,
  ControlledReadOnlyShardPreviewSourceMatrixReviewDigest,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewReviewDecisionTypes.js";
import type {
  ControlledReadOnlyShardPreviewSourceMatrixArchiveSnapshot,
  ControlledReadOnlyShardPreviewSourceMatrixArchiveSnapshotSummaryExport,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewArchiveTypes.js";
import type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffNotes,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummary,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewHandoffTypes.js";
import type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumer,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerExport,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerReceipt,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewHandoffConsumerTypes.js";
import type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerReceiptArchiveVerification,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewHandoffReceiptArchiveTypes.js";
import type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverage,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageVerification,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewRouteCoverageTypes.js";
import type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSnapshot,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveVerification,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewRouteCoverageArchiveTypes.js";
import type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSummary,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSummaryReceipt,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewRouteCoverageArchiveSummaryTypes.js";
import type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewRouteCoverageArchiveReceiptTypes.js";
import type {
  ControlledReadOnlyShardPreviewExecutionGapMatrix,
  ControlledReadOnlyShardPreviewLiveReadOnlyPacketCandidate,
  ControlledReadOnlyShardPreviewLiveReadOnlyPacketCandidateVerification,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewExecutionReadinessTypes.js";

export type {
  ControlledReadOnlyShardPreviewObservationPreview,
  ControlledReadOnlyShardPreviewSource,
  ControlledReadOnlyShardPreviewSourceMatrix,
  ControlledReadOnlyShardPreviewSourceMatrixConsumer,
  ControlledReadOnlyShardPreviewSourceMatrixConsumerComparison,
  ControlledReadOnlyShardPreviewSourceMatrixConsumerGates,
  ControlledReadOnlyShardPreviewSourceMatrixDriftDimension,
  ControlledReadOnlyShardPreviewSourceMatrixDriftFinding,
  ControlledReadOnlyShardPreviewSourceMatrixDriftSummary,
  ControlledReadOnlyShardPreviewSourceMatrixEntry,
  PreviewProject,
  PreviewStatus,
  PreviewTransport,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewSourceMatrixTypes.js";

export type {
  ControlledReadOnlyShardPreviewChecks,
  ControlledReadOnlyShardPreviewMessage,
  ControlledReadOnlyShardPreviewObservation,
  ControlledReadOnlyShardPreviewSummary,
  PreviewMessageSource,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewSupportTypes.js";

export type {
  ControlledReadOnlyShardPreviewSourceMatrixConsumptionPlan,
  ControlledReadOnlyShardPreviewSourceMatrixConsumptionPlanStep,
  ControlledReadOnlyShardPreviewSourceMatrixConsumptionPlanStepCode,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewConsumptionPlanTypes.js";

export type {
  ControlledReadOnlyShardPreviewSourceMatrixReviewChecklist,
  ControlledReadOnlyShardPreviewSourceMatrixReviewChecklistItem,
  ControlledReadOnlyShardPreviewSourceMatrixReviewDigest,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewReviewDecisionTypes.js";

export type {
  ControlledReadOnlyShardPreviewSourceMatrixArchiveSnapshot,
  ControlledReadOnlyShardPreviewSourceMatrixArchiveSnapshotSummaryExport,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewArchiveTypes.js";

export type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffAudience,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffNote,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffNotes,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummary,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewHandoffTypes.js";

export type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumer,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerExport,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerGates,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerReceipt,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewHandoffConsumerTypes.js";

export type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerReceiptArchiveVerification,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerReceiptArchiveVerificationGates,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewHandoffReceiptArchiveTypes.js";

export type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverage,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageVerification,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageVerificationGates,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewRouteCoverageTypes.js";

export type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSnapshot,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveVerification,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveVerificationGates,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewRouteCoverageArchiveTypes.js";

export type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSummary,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSummaryReceipt,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewRouteCoverageArchiveSummaryTypes.js";

export type {
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification,
  ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerificationGates,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewRouteCoverageArchiveReceiptTypes.js";

export type {
  ControlledReadOnlyShardPreviewExecutionGapMatrix,
  ControlledReadOnlyShardPreviewExecutionReadinessGate,
  ControlledReadOnlyShardPreviewExecutionReadinessGateState,
  ControlledReadOnlyShardPreviewExecutionReadinessScope,
  ControlledReadOnlyShardPreviewLiveReadOnlyPacketCandidate,
  ControlledReadOnlyShardPreviewLiveReadOnlyPacketCandidateChecks,
  ControlledReadOnlyShardPreviewLiveReadOnlyPacketCandidateVerification,
  ControlledReadOnlyShardPreviewLiveReadOnlyPacketCandidateVerificationGates,
  ControlledReadOnlyShardPreviewLiveReadOnlyPacketProcessStep,
  ControlledReadOnlyShardPreviewLiveReadOnlyPacketTarget,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewExecutionReadinessTypes.js";

export interface ControlledReadOnlyShardPreviewProfile {
  service: "orderops-node";
  title: string;
  generatedAt: string;
  profileVersion: "managed-audit-manual-sandbox-connection-credential-resolver-controlled-read-only-shard-preview.v1";
  previewState: "controlled-read-only-shard-preview-ready" | "blocked";
  previewDecision: "preview-java-and-mini-kv-shard-readiness" | "blocked";
  readyForControlledReadOnlyShardPreview: boolean;
  activeNodeVersion: "Node v638";
  sourceNodeVersion: "Node v637";
  consumesNodeV580MaturityRunCloseout: true;
  previewOnly: true;
  liveReadOnly: true;
  executionAllowed: false;
  startsJavaService: false;
  startsMiniKvService: false;
  stopsJavaService: false;
  stopsMiniKvService: false;
  mutatesJavaState: false;
  mutatesMiniKvState: false;
  activeShardRouterAllowed: false;
  writeRoutingAllowed: false;
  loadRestoreCompactAllowed: false;
  connectsManagedAudit: false;
  credentialValueRead: false;
  rawEndpointUrlParsed: false;
  reads: {
    java: ControlledReadOnlyShardPreviewObservation;
    miniKv: ControlledReadOnlyShardPreviewObservation;
  };
  preview: {
    java: ControlledReadOnlyShardPreviewObservationPreview;
    miniKv: ControlledReadOnlyShardPreviewObservationPreview;
    combinedSlotCount: number | null;
    combinedShardCount: number | null;
    bothReadOnly: boolean;
    bothExecutionBlocked: boolean;
    sourceMatrix: ControlledReadOnlyShardPreviewSourceMatrix;
    sourceMatrixConsumer: ControlledReadOnlyShardPreviewSourceMatrixConsumer;
    sourceMatrixDriftSummary: ControlledReadOnlyShardPreviewSourceMatrixDriftSummary;
    sourceMatrixConsumptionPlan: ControlledReadOnlyShardPreviewSourceMatrixConsumptionPlan;
    sourceMatrixReviewChecklist: ControlledReadOnlyShardPreviewSourceMatrixReviewChecklist;
    sourceMatrixReviewDigest: ControlledReadOnlyShardPreviewSourceMatrixReviewDigest;
    sourceMatrixArchiveSnapshot: ControlledReadOnlyShardPreviewSourceMatrixArchiveSnapshot;
    sourceMatrixArchiveSnapshotSummaryExport: ControlledReadOnlyShardPreviewSourceMatrixArchiveSnapshotSummaryExport;
    sourceMatrixHandoffNotes: ControlledReadOnlyShardPreviewSourceMatrixHandoffNotes;
    sourceMatrixHandoffSummary: ControlledReadOnlyShardPreviewSourceMatrixHandoffSummary;
    sourceMatrixHandoffSummaryConsumer: ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumer;
    sourceMatrixHandoffSummaryConsumerExport: ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerExport;
    sourceMatrixHandoffSummaryConsumerReceipt: ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerReceipt;
    sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot:
      ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot;
    sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification:
      ControlledReadOnlyShardPreviewSourceMatrixHandoffSummaryConsumerReceiptArchiveVerification;
    sourceMatrixHandoffRouteCoverage: ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverage;
    sourceMatrixHandoffRouteCoverageVerification:
      ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageVerification;
    sourceMatrixHandoffRouteCoverageArchiveSnapshot:
      ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSnapshot;
    sourceMatrixHandoffRouteCoverageArchiveVerification:
      ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveVerification;
    sourceMatrixHandoffRouteCoverageArchiveSummary:
      ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSummary;
    sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt:
      ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSummaryReceipt;
    sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot:
      ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot;
    sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification:
      ControlledReadOnlyShardPreviewSourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification;
    executionGapMatrix: ControlledReadOnlyShardPreviewExecutionGapMatrix;
    liveReadOnlyPacketCandidate: ControlledReadOnlyShardPreviewLiveReadOnlyPacketCandidate;
    liveReadOnlyPacketCandidateVerification: ControlledReadOnlyShardPreviewLiveReadOnlyPacketCandidateVerification;
    previewDigest: string;
  };
  checks: ControlledReadOnlyShardPreviewChecks;
  summary: ControlledReadOnlyShardPreviewSummary;
  productionBlockers: ControlledReadOnlyShardPreviewMessage[];
  warnings: ControlledReadOnlyShardPreviewMessage[];
  recommendations: ControlledReadOnlyShardPreviewMessage[];
  evidenceEndpoints: {
    controlledReadOnlyShardPreviewJson: string;
    controlledReadOnlyShardPreviewMarkdown: string;
    javaShardReadinessEndpoint: string;
    miniKvShardJsonCommand: "SHARDJSON";
    sourceNodeV580ArchiveIndex: "e/README.md";
    nextNodeVersion: "Node v639";
  };
  nextActions: string[];
}
