import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  CredentialHandleApprovalClosurePrerequisite,
  ManagedAuditManualSandboxConnectionCredentialResolverCredentialHandleApprovalPrerequisiteClosureReviewProfile,
  SourceNodeV318CredentialHandleApprovalContractUpstreamEchoVerificationReference,
} from "./managedAuditManualSandboxConnectionCredentialResolverCredentialHandleApprovalPrerequisiteClosureReviewTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverCredentialHandleApprovalPrerequisiteClosureReviewMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverCredentialHandleApprovalPrerequisiteClosureReviewProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver credential handle approval prerequisite closure review",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Review state: ${profile.reviewState}`,
    `- Prerequisite closure decision: ${profile.prerequisiteClosureDecision}`,
    `- Ready for closure review: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverCredentialHandleApprovalPrerequisiteClosureReview}`,
    `- Active Node review version: ${profile.activeNodeReviewVersion}`,
    `- Ready for endpoint handle allowlist contract intake: ${profile.readyForEndpointHandleAllowlistContractIntake}`,
    `- New Java + mini-kv echo requested: ${profile.newJavaMiniKvEchoRequested}`,
    `- Runtime shell implemented: ${profile.runtimeShellImplemented}`,
    `- Runtime shell invocation allowed: ${profile.runtimeShellInvocationAllowed}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v318",
    "",
    ...renderSourceNodeV318(profile.sourceNodeV318),
    "",
    "## Closure Review",
    "",
    ...renderEntries({
      reviewDigest: profile.closureReview.reviewDigest,
      reviewMode: profile.closureReview.reviewMode,
      sourceSpan: profile.closureReview.sourceSpan,
      sourceVerificationDigest: profile.closureReview.sourceVerificationDigest,
      completedPrerequisiteCount: profile.closureReview.completedPrerequisiteCount,
      remainingPrerequisiteCount: profile.closureReview.remainingPrerequisiteCount,
      originalPrerequisiteCount: profile.closureReview.originalPrerequisiteCount,
      movedPrerequisiteId: profile.closureReview.movedPrerequisiteId,
      movedFrom: profile.closureReview.movedFrom,
      movedTo: profile.closureReview.movedTo,
      nextConcretePrerequisiteId: profile.closureReview.nextConcretePrerequisiteId,
      nextConcretePrerequisiteContractRequired: profile.closureReview.nextConcretePrerequisiteContractRequired,
      nextNodeVersionSuggested: profile.closureReview.nextNodeVersionSuggested,
      nextJavaVersionRequested: profile.closureReview.nextJavaVersionRequested,
      nextMiniKvVersionRequested: profile.closureReview.nextMiniKvVersionRequested,
      chainContinuationAllowed: profile.closureReview.chainContinuationAllowed,
      runtimeShellStillBlocked: profile.closureReview.runtimeShellStillBlocked,
      closureReason: profile.closureReview.closureReason,
    }),
    "",
    "### Completed Prerequisites",
    "",
    ...renderPrerequisites(profile.closureReview.completedPrerequisites),
    "",
    "### Remaining Prerequisites",
    "",
    ...renderPrerequisites(profile.closureReview.remainingPrerequisites),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No credential handle approval prerequisite closure review blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No credential handle approval prerequisite closure review warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No credential handle approval prerequisite closure review recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderSourceNodeV318(
  reference: SourceNodeV318CredentialHandleApprovalContractUpstreamEchoVerificationReference,
): string[] {
  return renderEntries({
    sourceVersion: reference.sourceVersion,
    profileVersion: reference.profileVersion,
    verificationState: reference.verificationState,
    readyForCredentialHandleApprovalContractUpstreamEchoVerification:
      reference.readyForCredentialHandleApprovalContractUpstreamEchoVerification,
    readOnlyUpstreamEchoVerification: reference.readOnlyUpstreamEchoVerification,
    verificationDigest: reference.verificationDigest,
    sourceSpan: reference.sourceSpan,
    upstreamEchoAligned: reference.upstreamEchoAligned,
    credentialHandleContractAligned: reference.credentialHandleContractAligned,
    sideEffectBoundariesAligned: reference.sideEffectBoundariesAligned,
    implementationStillBlocked: reference.implementationStillBlocked,
    contractDigest: reference.contractDigest,
    requiredFieldCount: reference.requiredFieldCount,
    prohibitedFieldCount: reference.prohibitedFieldCount,
    rejectionReasonCount: reference.rejectionReasonCount,
    noGoBoundaryCount: reference.noGoBoundaryCount,
    upstreamEchoRequestCount: reference.upstreamEchoRequestCount,
    sourceProductionBlockerCount: reference.sourceProductionBlockerCount,
  });
}

function renderPrerequisites(prerequisites: CredentialHandleApprovalClosurePrerequisite[]): string[] {
  return renderList(
    prerequisites.map((prerequisite) =>
      `${prerequisite.id}: ${prerequisite.closureState}; requiredBeforeRuntimeShell=${prerequisite.requiredBeforeRuntimeShell}; opensRuntimeShell=${prerequisite.opensRuntimeShell}; evidence=${prerequisite.evidence}`),
    "No prerequisites.",
  );
}
