import type {
  ManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftCandidateReviewProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftCandidateReviewTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftCandidateReviewMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftCandidateReviewProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver disabled runtime shell design draft candidate review",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Candidate review state: ${profile.candidateReviewState}`,
    `- Candidate review decision: ${profile.candidateReviewDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for v331 candidate review: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftCandidateReview}`,
    `- Ready for Node v332 archive verification: ${profile.readyForNodeV332ArchiveVerification}`,
    `- Ready for disabled runtime shell design draft: ${profile.readyForDisabledRuntimeShellDesignDraft}`,
    `- Ready for disabled runtime shell design draft outline: ${profile.readyForDisabledRuntimeShellDesignDraftOutline}`,
    `- Ready for runtime shell implementation: ${profile.readyForRuntimeShellImplementation}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Credential value read: ${profile.credentialValueRead}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    `- HTTP request sent: ${profile.httpRequestSent}`,
    `- TCP connection attempted: ${profile.tcpConnectionAttempted}`,
    `- Java SQL execution allowed: ${profile.javaSqlExecutionAllowed}`,
    `- mini-kv write command allowed: ${profile.miniKvWriteCommandAllowed}`,
    `- Automatic upstream start: ${profile.automaticUpstreamStart}`,
    "",
    "## Source Node v330",
    "",
    `- Review state: ${profile.sourceNodeV330.reviewState}`,
    `- Upstream alignment decision: ${profile.sourceNodeV330.upstreamAlignmentDecision}`,
    `- Ready for source review: ${profile.sourceNodeV330.readyForCandidateGateUpstreamHardeningReview}`,
    `- Ready for next candidate: ${profile.sourceNodeV330.readyForNextNodeDisabledRuntimeShellDesignDraftCandidate}`,
    `- Source digest: ${profile.sourceNodeV330.hardeningReviewDigest}`,
    `- Source checks: ${profile.sourceNodeV330.sourcePassedCheckCount}/${profile.sourceNodeV330.sourceCheckCount}`,
    `- Source production blockers: ${profile.sourceNodeV330.sourceProductionBlockerCount}`,
    "",
    "## Necessity Proof",
    "",
    `- Blocker resolved: ${profile.necessityProof.blockerResolved}`,
    `- Consumer: ${profile.necessityProof.consumer}`,
    `- Why v330 cannot be reused: ${profile.necessityProof.whyV330CannotBeReused}`,
    `- Why old design review cannot be reused: ${profile.necessityProof.whyExistingDesignReviewCannotBeReused}`,
    `- Stop condition: ${profile.necessityProof.stopCondition}`,
    `- Proof complete: ${profile.necessityProof.proofComplete}`,
    "",
    "## Candidate Review",
    "",
    `- Review digest: ${profile.candidateReview.reviewDigest}`,
    `- Record mode: ${profile.candidateReview.recordMode}`,
    `- Decision: ${profile.candidateReview.decision}`,
    `- Candidate scope: ${profile.candidateReview.candidateScope}`,
    `- Requires archive verification before design draft: ${profile.candidateReview.requiresArchiveVerificationBeforeDesignDraft}`,
    `- Requests Java/mini-kv echo: ${profile.candidateReview.requestsJavaMiniKvEcho}`,
    `- Ready for Node v332 archive verification: ${profile.candidateReview.readyForNodeV332ArchiveVerification}`,
    `- Allows design draft now: ${profile.candidateReview.allowsDisabledRuntimeShellDesignDraftNow}`,
    `- Allows design draft outline: ${profile.candidateReview.allowsDisabledRuntimeShellDesignDraftOutline}`,
    `- Allows runtime implementation: ${profile.candidateReview.allowsRuntimeShellImplementation}`,
    `- Allows credential value read: ${profile.candidateReview.allowsCredentialValueRead}`,
    `- Allows raw endpoint URL parse: ${profile.candidateReview.allowsRawEndpointUrlParse}`,
    `- Allows external request: ${profile.candidateReview.allowsExternalRequest}`,
    `- Allows mini-kv write/admin command: ${profile.candidateReview.allowsMiniKvWriteOrAdminCommand}`,
    `- Next Node version suggested: ${profile.candidateReview.nextNodeVersionSuggested}`,
    "",
    "## Review Questions",
    "",
    ...profile.reviewQuestions.map((entry) => `- ${entry.id}: ${entry.question} Answer=${entry.answer}`),
    "",
    "## Stop Conditions",
    "",
    ...profile.stopConditions.map((entry) => `- ${entry.code}: ${entry.condition}; action=${entry.action}`),
    "",
    "## Checks",
    "",
    ...Object.entries(profile.checks).map(([key, value]) => `- ${key}: ${value}`),
    "",
    "## Summary",
    "",
    `- Checks: ${profile.summary.passedCheckCount}/${profile.summary.checkCount}`,
    `- Source Node v330 checks: ${profile.summary.sourceNodeV330PassedCheckCount}/${profile.summary.sourceNodeV330CheckCount}`,
    `- Source production blockers: ${profile.summary.sourceProductionBlockerCount}`,
    `- Review questions: ${profile.summary.answeredReviewQuestionCount}/${profile.summary.reviewQuestionCount}`,
    `- Stop conditions: ${profile.summary.stopConditionCount}`,
    `- Production blockers: ${profile.summary.productionBlockerCount}`,
    `- Warnings: ${profile.summary.warningCount}`,
    `- Recommendations: ${profile.summary.recommendationCount}`,
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...profile.nextActions.map((action) => `- ${action}`),
    "",
  ].join("\n");
}

function renderMessages(
  messages: readonly { code: string; severity: string; source: string; message: string }[],
  emptyMessage: string,
): string[] {
  if (messages.length === 0) {
    return [`- ${emptyMessage}`];
  }
  return messages.map((message) => `- [${message.severity}] ${message.code} (${message.source}): ${message.message}`);
}
