import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvShardReadinessEvidenceConsumptionProfile,
  ShardReadinessEvidenceAssessment,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvShardReadinessEvidenceConsumptionTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvShardReadinessEvidenceConsumptionMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvShardReadinessEvidenceConsumptionProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver Java/mini-kv shard readiness evidence consumption",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Evidence consumption state: ${profile.evidenceConsumptionState}`,
    `- Evidence consumption decision: ${profile.evidenceConsumptionDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for Node v377 archive verification: ${profile.readyForNodeV377ShardReadinessEvidenceConsumptionArchiveVerification}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Stops Java service: ${profile.stopsJavaService}`,
    `- Stops mini-kv service: ${profile.stopsMiniKvService}`,
    `- Mutates Java state: ${profile.mutatesJavaState}`,
    `- Mutates mini-kv state: ${profile.mutatesMiniKvState}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v375",
    "",
    ...renderEntries(profile.sourceNodeV375),
    "",
    "## Java v154 Shard Readiness",
    "",
    ...renderShardReadiness(profile.javaShardReadiness),
    "",
    "## mini-kv v145 Shard Readiness",
    "",
    ...renderShardReadiness(profile.miniKvShardReadiness),
    "",
    "## Evidence Consumption",
    "",
    ...renderEntries(profile.evidenceConsumption),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderShardReadiness(assessment: ShardReadinessEvidenceAssessment): string[] {
  return [
    `- Project: ${assessment.project}`,
    `- Source version: ${assessment.sourceVersion}`,
    `- Ready for Node consumption: ${assessment.readyForNodeConsumption}`,
    `- Required fields: ${assessment.presentRequiredFieldCount}/${assessment.requiredFieldCount}`,
    `- Missing fields: ${assessment.missingRequiredFields.length === 0 ? "none" : assessment.missingRequiredFields.join(", ")}`,
    `- Read only safe: ${assessment.readOnlySafe}`,
    `- Execution blocked: ${assessment.executionBlocked}`,
    `- Status accepted: ${assessment.statusAccepted}`,
    `- Hardening explains fields: ${assessment.hardeningExplainsFields}`,
    `- Source core linked: ${assessment.sourceCoreLinked}`,
    `- Boundary safe: ${assessment.boundarySafe}`,
    `- Preserves archived Node evidence: ${assessment.preservesArchivedNodeEvidence}`,
    `- Hardening file: ${assessment.hardeningFile.configuredPath}`,
    `- Resolved hardening path: ${assessment.hardeningFile.resolvedPath}`,
    `- Used historical fallback: ${assessment.hardeningFile.usedHistoricalFallback}`,
    `- Source core file: ${assessment.sourceCoreFile?.configuredPath ?? "not-applicable"}`,
    "- Evidence:",
    ...renderEntries(assessment.evidence).map((line) => `  ${line}`),
  ];
}
