import { formatValue, renderEntries, renderMessages } from "./liveProbeReportUtils.js";
import type { ControlledReadOnlyShardPreviewProfile } from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewMarkdown(
  profile: ControlledReadOnlyShardPreviewProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Profile version: ${profile.profileVersion}`,
    `- Preview state: ${profile.previewState}`,
    `- Preview decision: ${profile.previewDecision}`,
    `- Ready: ${profile.readyForControlledReadOnlyShardPreview}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Preview only: ${profile.previewOnly}`,
    `- Live read only: ${profile.liveReadOnly}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Stops Java service: ${profile.stopsJavaService}`,
    `- Stops mini-kv service: ${profile.stopsMiniKvService}`,
    `- Active shard router allowed: ${profile.activeShardRouterAllowed}`,
    `- Write routing allowed: ${profile.writeRoutingAllowed}`,
    `- LOAD/RESTORE/COMPACT allowed: ${profile.loadRestoreCompactAllowed}`,
    `- Preview digest: ${profile.preview.previewDigest}`,
    "",
    "## Java Preview",
    ...renderEntries(profile.preview.java),
    `- Read status: ${profile.reads.java.status}`,
    `- Endpoint: ${profile.reads.java.endpoint}`,
    `- Latency ms: ${formatValue(profile.reads.java.latencyMs)}`,
    "",
    "## mini-kv Preview",
    ...renderEntries(profile.preview.miniKv),
    `- Read status: ${profile.reads.miniKv.status}`,
    `- Command: ${profile.reads.miniKv.command ?? "none"}`,
    `- Latency ms: ${formatValue(profile.reads.miniKv.latencyMs)}`,
    "",
    "## Combined Preview",
    `- Combined shard count: ${formatValue(profile.preview.combinedShardCount)}`,
    `- Combined slot count: ${formatValue(profile.preview.combinedSlotCount)}`,
    `- Both read-only: ${profile.preview.bothReadOnly}`,
    `- Both execution blocked: ${profile.preview.bothExecutionBlocked}`,
    "",
    "## Source Matrix",
    `- Source count: ${profile.preview.sourceMatrix.sourceCount}`,
    `- Ready source count: ${profile.preview.sourceMatrix.readySourceCount}`,
    `- Failed source count: ${profile.preview.sourceMatrix.failedSourceCount}`,
    `- Skipped source count: ${profile.preview.sourceMatrix.skippedSourceCount}`,
    `- Routing modes: ${profile.preview.sourceMatrix.routingModes.join(", ") || "none"}`,
    `- Shard count delta: ${formatValue(profile.preview.sourceMatrix.shardCountDelta)}`,
    `- Slot count delta: ${formatValue(profile.preview.sourceMatrix.slotCountDelta)}`,
    `- All sources ready: ${profile.preview.sourceMatrix.allSourcesReady}`,
    ...profile.preview.sourceMatrix.sources.flatMap((source) => [
      "",
      `### ${source.source}`,
      ...renderEntries(source),
    ]),
    "",
    "## Source Matrix Consumer",
    `- Consumer version: ${profile.preview.sourceMatrixConsumer.consumerVersion}`,
    `- Input source version: ${profile.preview.sourceMatrixConsumer.inputSourceVersion}`,
    `- Decision: ${profile.preview.sourceMatrixConsumer.decision}`,
    `- Ready for controlled read-only consumption: ${profile.preview.sourceMatrixConsumer.readyForControlledReadOnlyConsumption}`,
    `- Required sources: ${profile.preview.sourceMatrixConsumer.requiredSources.join(", ") || "none"}`,
    `- Observed sources: ${profile.preview.sourceMatrixConsumer.observedSources.join(", ") || "none"}`,
    `- Missing sources: ${profile.preview.sourceMatrixConsumer.missingSources.join(", ") || "none"}`,
    `- Gate count: ${profile.preview.sourceMatrixConsumer.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixConsumer.passedGateCount}`,
    `- Blocked reason codes: ${profile.preview.sourceMatrixConsumer.blockedReasonCodes.join(", ") || "none"}`,
    `- Activates routing: ${profile.preview.sourceMatrixConsumer.activatesRouting}`,
    `- Starts services: ${profile.preview.sourceMatrixConsumer.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixConsumer.mutatesSiblingState}`,
    "",
    "### Consumer Gates",
    ...renderEntries(profile.preview.sourceMatrixConsumer.gates),
    "",
    "### Consumer Comparison",
    ...renderEntries(profile.preview.sourceMatrixConsumer.comparison),
    "",
    "## Source Matrix Drift Summary",
    `- Summary version: ${profile.preview.sourceMatrixDriftSummary.summaryVersion}`,
    `- Input consumer version: ${profile.preview.sourceMatrixDriftSummary.inputConsumerVersion}`,
    `- Drift state: ${profile.preview.sourceMatrixDriftSummary.driftState}`,
    `- Ready for controlled drift review: ${profile.preview.sourceMatrixDriftSummary.readyForControlledDriftReview}`,
    `- Finding count: ${profile.preview.sourceMatrixDriftSummary.findingCount}`,
    `- Drift finding count: ${profile.preview.sourceMatrixDriftSummary.driftFindingCount}`,
    `- Blocking finding count: ${profile.preview.sourceMatrixDriftSummary.blockingFindingCount}`,
    `- Comparable finding count: ${profile.preview.sourceMatrixDriftSummary.comparableFindingCount}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixDriftSummary.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixDriftSummary.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixDriftSummary.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixDriftSummary.mutatesSiblingState}`,
    "",
    "### Drift Findings",
    ...profile.preview.sourceMatrixDriftSummary.findings.map((finding) =>
      `- ${finding.dimension}: ${finding.status} (${finding.severity}) - ${finding.message}`),
    "",
    "## Source Matrix Review Checklist",
    `- Checklist version: ${profile.preview.sourceMatrixReviewChecklist.checklistVersion}`,
    `- Input drift summary version: ${profile.preview.sourceMatrixReviewChecklist.inputDriftSummaryVersion}`,
    `- Checklist state: ${profile.preview.sourceMatrixReviewChecklist.checklistState}`,
    `- Ready for operator review: ${profile.preview.sourceMatrixReviewChecklist.readyForOperatorReview}`,
    `- Item count: ${profile.preview.sourceMatrixReviewChecklist.itemCount}`,
    `- Ready item count: ${profile.preview.sourceMatrixReviewChecklist.readyItemCount}`,
    `- Review item count: ${profile.preview.sourceMatrixReviewChecklist.reviewItemCount}`,
    `- Blocked item count: ${profile.preview.sourceMatrixReviewChecklist.blockedItemCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixReviewChecklist.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixReviewChecklist.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixReviewChecklist.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixReviewChecklist.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixReviewChecklist.mutatesSiblingState}`,
    "",
    "### Checklist Items",
    ...profile.preview.sourceMatrixReviewChecklist.items.map((item) =>
      `- ${item.order}. ${item.check}: ${item.status} (${item.severity}) - ${item.operatorAction}`),
    "",
    "## Source Matrix Review Digest",
    `- Digest version: ${profile.preview.sourceMatrixReviewDigest.digestVersion}`,
    `- Input checklist version: ${profile.preview.sourceMatrixReviewDigest.inputChecklistVersion}`,
    `- Algorithm: ${profile.preview.sourceMatrixReviewDigest.algorithm}`,
    `- Value: ${profile.preview.sourceMatrixReviewDigest.value}`,
    `- Covered fields: ${profile.preview.sourceMatrixReviewDigest.coveredFields.join(", ")}`,
    `- Ready for controlled review archive: ${profile.preview.sourceMatrixReviewDigest.readyForControlledReviewArchive}`,
    `- Checklist state: ${profile.preview.sourceMatrixReviewDigest.checklistState}`,
    `- Item count: ${profile.preview.sourceMatrixReviewDigest.itemCount}`,
    `- Blocked item count: ${profile.preview.sourceMatrixReviewDigest.blockedItemCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixReviewDigest.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixReviewDigest.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixReviewDigest.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixReviewDigest.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixReviewDigest.mutatesSiblingState}`,
    "",
    "## Source Matrix Archive Snapshot",
    `- Snapshot version: ${profile.preview.sourceMatrixArchiveSnapshot.snapshotVersion}`,
    `- Input review digest version: ${profile.preview.sourceMatrixArchiveSnapshot.inputReviewDigestVersion}`,
    `- Archive state: ${profile.preview.sourceMatrixArchiveSnapshot.archiveState}`,
    `- Ready for controlled review archive: ${profile.preview.sourceMatrixArchiveSnapshot.readyForControlledReviewArchive}`,
    `- Digest value: ${profile.preview.sourceMatrixArchiveSnapshot.digestValue}`,
    `- Archived sections: ${profile.preview.sourceMatrixArchiveSnapshot.archivedSections.join(", ")}`,
    `- Archived section count: ${profile.preview.sourceMatrixArchiveSnapshot.archivedSectionCount}`,
    `- Checklist state: ${profile.preview.sourceMatrixArchiveSnapshot.checklistState}`,
    `- Item count: ${profile.preview.sourceMatrixArchiveSnapshot.itemCount}`,
    `- Blocked item count: ${profile.preview.sourceMatrixArchiveSnapshot.blockedItemCount}`,
    `- Includes raw credential: ${profile.preview.sourceMatrixArchiveSnapshot.includesRawCredential}`,
    `- Includes runtime payload: ${profile.preview.sourceMatrixArchiveSnapshot.includesRuntimePayload}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixArchiveSnapshot.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixArchiveSnapshot.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixArchiveSnapshot.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixArchiveSnapshot.mutatesSiblingState}`,
    "",
    "## Source Matrix Archive Snapshot Summary Export",
    `- Export version: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.exportVersion}`,
    `- Input archive snapshot version: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.inputArchiveSnapshotVersion}`,
    `- Export state: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.exportState}`,
    `- Ready for summary export: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.readyForSummaryExport}`,
    `- Digest value: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.digestValue}`,
    `- Summary digest: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.summaryDigest.value}`,
    `- Summary digest scope: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.summaryDigest.scope}`,
    `- Summary digest covered line count: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.summaryDigest.coveredLineCount}`,
    `- Summary lines: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.summaryLines.join("; ")}`,
    `- Summary line count: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.summaryLineCount}`,
    `- Archived section count: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.archivedSectionCount}`,
    `- Blocked item count: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.blockedItemCount}`,
    `- Includes raw credential: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.includesRawCredential}`,
    `- Includes runtime payload: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.includesRuntimePayload}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Notes",
    `- Notes version: ${profile.preview.sourceMatrixHandoffNotes.notesVersion}`,
    `- Input summary export version: ${profile.preview.sourceMatrixHandoffNotes.inputSummaryExportVersion}`,
    `- Handoff state: ${profile.preview.sourceMatrixHandoffNotes.handoffState}`,
    `- Ready for read-only handoff: ${profile.preview.sourceMatrixHandoffNotes.readyForReadOnlyHandoff}`,
    `- Handoff digest: ${profile.preview.sourceMatrixHandoffNotes.handoffDigest.value}`,
    `- Handoff digest scope: ${profile.preview.sourceMatrixHandoffNotes.handoffDigest.scope}`,
    `- Handoff digest covered note count: ${profile.preview.sourceMatrixHandoffNotes.handoffDigest.coveredNoteCount}`,
    `- Note count: ${profile.preview.sourceMatrixHandoffNotes.noteCount}`,
    `- Action required count: ${profile.preview.sourceMatrixHandoffNotes.actionRequiredCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffNotes.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffNotes.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffNotes.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffNotes.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffNotes.mutatesSiblingState}`,
    "",
    "### Handoff Notes",
    ...profile.preview.sourceMatrixHandoffNotes.notes.map((note) =>
      `- ${note.order}. ${note.audience}: ${note.message}`),
    "",
    "## Source Matrix Handoff Summary",
    `- Summary version: ${profile.preview.sourceMatrixHandoffSummary.summaryVersion}`,
    `- Input notes version: ${profile.preview.sourceMatrixHandoffSummary.inputNotesVersion}`,
    `- Summary state: ${profile.preview.sourceMatrixHandoffSummary.summaryState}`,
    `- Ready for read-only handoff summary: ${profile.preview.sourceMatrixHandoffSummary.readyForReadOnlyHandoffSummary}`,
    `- Audiences: ${profile.preview.sourceMatrixHandoffSummary.audiences.join(", ") || "none"}`,
    `- Audience count: ${profile.preview.sourceMatrixHandoffSummary.audienceCount}`,
    `- Action required count: ${profile.preview.sourceMatrixHandoffSummary.actionRequiredCount}`,
    `- Handoff digest value: ${profile.preview.sourceMatrixHandoffSummary.handoffDigestValue}`,
    `- Summary digest: ${profile.preview.sourceMatrixHandoffSummary.summaryDigest.value}`,
    `- Summary digest scope: ${profile.preview.sourceMatrixHandoffSummary.summaryDigest.scope}`,
    `- Summary digest covered audience count: ${profile.preview.sourceMatrixHandoffSummary.summaryDigest.coveredAudienceCount}`,
    `- Summary digest covered action required count: ${profile.preview.sourceMatrixHandoffSummary.summaryDigest.coveredActionRequiredCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffSummary.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffSummary.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffSummary.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffSummary.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffSummary.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Summary Consumer",
    `- Consumer version: ${profile.preview.sourceMatrixHandoffSummaryConsumer.consumerVersion}`,
    `- Input summary version: ${profile.preview.sourceMatrixHandoffSummaryConsumer.inputSummaryVersion}`,
    `- Decision: ${profile.preview.sourceMatrixHandoffSummaryConsumer.decision}`,
    `- Ready for read-only summary consumption: ${profile.preview.sourceMatrixHandoffSummaryConsumer.readyForReadOnlySummaryConsumption}`,
    `- Gate count: ${profile.preview.sourceMatrixHandoffSummaryConsumer.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixHandoffSummaryConsumer.passedGateCount}`,
    `- Blocked reason codes: ${profile.preview.sourceMatrixHandoffSummaryConsumer.blockedReasonCodes.join(", ") || "none"}`,
    `- Summary digest value: ${profile.preview.sourceMatrixHandoffSummaryConsumer.summaryDigestValue}`,
    `- Summary digest scope: ${profile.preview.sourceMatrixHandoffSummaryConsumer.summaryDigestScope}`,
    `- Covered audience count: ${profile.preview.sourceMatrixHandoffSummaryConsumer.coveredAudienceCount}`,
    `- Action required count: ${profile.preview.sourceMatrixHandoffSummaryConsumer.actionRequiredCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffSummaryConsumer.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffSummaryConsumer.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffSummaryConsumer.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffSummaryConsumer.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffSummaryConsumer.mutatesSiblingState}`,
    "",
    "### Handoff Summary Consumer Gates",
    ...renderEntries(profile.preview.sourceMatrixHandoffSummaryConsumer.gates),
    "",
    "## Source Matrix Handoff Summary Consumer Export",
    `- Export version: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportVersion}`,
    `- Input consumer version: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.inputConsumerVersion}`,
    `- Export state: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportState}`,
    `- Ready for read-only summary consumer export: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.readyForReadOnlySummaryConsumerExport}`,
    `- Consumer decision: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.consumerDecision}`,
    `- Summary digest value: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.summaryDigestValue}`,
    `- Export digest: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportDigest.value}`,
    `- Export digest scope: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportDigest.scope}`,
    `- Export digest covered line count: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportDigest.coveredLineCount}`,
    `- Export lines: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportLines.join("; ")}`,
    `- Export line count: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.exportLineCount}`,
    `- Gate count: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.passedGateCount}`,
    `- Blocked reason count: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.blockedReasonCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffSummaryConsumerExport.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Summary Consumer Receipt",
    `- Receipt version: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptVersion}`,
    `- Input export version: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.inputExportVersion}`,
    `- Receipt state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptState}`,
    `- Ready for read-only summary consumer receipt: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.readyForReadOnlySummaryConsumerReceipt}`,
    `- Export state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.exportState}`,
    `- Export digest value: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.exportDigestValue}`,
    `- Receipt digest: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptDigest.value}`,
    `- Receipt digest scope: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptDigest.scope}`,
    `- Receipt digest covered export line count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptDigest.coveredExportLineCount}`,
    `- Receipt digest covered blocked reason count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptDigest.coveredBlockedReasonCount}`,
    `- Receipt lines: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptLines.join("; ")}`,
    `- Receipt line count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.receiptLineCount}`,
    `- Export line count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.exportLineCount}`,
    `- Blocked reason count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.blockedReasonCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceipt.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Summary Consumer Receipt Archive Snapshot",
    `- Snapshot version: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.snapshotVersion}`,
    `- Input receipt version: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.inputReceiptVersion}`,
    `- Snapshot state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.snapshotState}`,
    `- Ready for read-only summary consumer receipt archive: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.readyForReadOnlySummaryConsumerReceiptArchive}`,
    `- Receipt digest value: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.receiptDigestValue}`,
    `- Snapshot digest: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.snapshotDigest.value}`,
    `- Snapshot digest scope: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.snapshotDigest.scope}`,
    `- Snapshot digest covered section count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.snapshotDigest.coveredSectionCount}`,
    `- Archived sections: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.archivedSections.join(", ")}`,
    `- Archived section count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.archivedSectionCount}`,
    `- Receipt line count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.receiptLineCount}`,
    `- Blocked reason count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.blockedReasonCount}`,
    `- Includes raw credential: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.includesRawCredential}`,
    `- Includes runtime payload: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.includesRuntimePayload}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveSnapshot.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Summary Consumer Receipt Archive Verification",
    `- Verification version: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.verificationVersion}`,
    `- Input snapshot version: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.inputSnapshotVersion}`,
    `- Verification state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.verificationState}`,
    `- Ready for read-only summary consumer receipt archive verification: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.readyForReadOnlySummaryConsumerReceiptArchiveVerification}`,
    `- Gate count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.passedGateCount}`,
    `- Blocked reason codes: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.blockedReasonCodes.join(", ") || "none"}`,
    `- Snapshot digest value: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.snapshotDigestValue}`,
    `- Archived section count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.archivedSectionCount}`,
    `- Blocked reason count: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.blockedReasonCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.mutatesSiblingState}`,
    "",
    "### Handoff Summary Receipt Archive Verification Gates",
    ...renderEntries(profile.preview.sourceMatrixHandoffSummaryConsumerReceiptArchiveVerification.gates),
    "",
    "## Source Matrix Handoff Route Coverage",
    `- Coverage version: ${profile.preview.sourceMatrixHandoffRouteCoverage.coverageVersion}`,
    `- Input verification version: ${profile.preview.sourceMatrixHandoffRouteCoverage.inputVerificationVersion}`,
    `- Coverage state: ${profile.preview.sourceMatrixHandoffRouteCoverage.coverageState}`,
    `- Ready for read-only handoff route coverage: ${profile.preview.sourceMatrixHandoffRouteCoverage.readyForReadOnlyHandoffRouteCoverage}`,
    `- Route surface: ${profile.preview.sourceMatrixHandoffRouteCoverage.routeSurface}`,
    `- Verification state: ${profile.preview.sourceMatrixHandoffRouteCoverage.verificationState}`,
    `- Covered sections: ${profile.preview.sourceMatrixHandoffRouteCoverage.coveredSections.join(", ")}`,
    `- Covered section count: ${profile.preview.sourceMatrixHandoffRouteCoverage.coveredSectionCount}`,
    `- Coverage digest: ${profile.preview.sourceMatrixHandoffRouteCoverage.coverageDigest.value}`,
    `- Coverage digest scope: ${profile.preview.sourceMatrixHandoffRouteCoverage.coverageDigest.scope}`,
    `- Coverage digest covered section count: ${profile.preview.sourceMatrixHandoffRouteCoverage.coverageDigest.coveredSectionCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverage.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverage.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverage.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverage.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverage.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Route Coverage Verification",
    `- Verification version: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.verificationVersion}`,
    `- Input coverage version: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.inputCoverageVersion}`,
    `- Verification state: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.verificationState}`,
    `- Ready for read-only handoff route coverage verification: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.readyForReadOnlyHandoffRouteCoverageVerification}`,
    `- Gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.passedGateCount}`,
    `- Blocked reason codes: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.blockedReasonCodes.join(", ") || "none"}`,
    `- Coverage digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.coverageDigestValue}`,
    `- Covered section count: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.coveredSectionCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.mutatesSiblingState}`,
    "",
    "### Handoff Route Coverage Verification Gates",
    ...renderEntries(profile.preview.sourceMatrixHandoffRouteCoverageVerification.gates),
    "",
    "## Source Matrix Handoff Route Coverage Archive Snapshot",
    `- Snapshot version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.snapshotVersion}`,
    `- Input verification version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.inputVerificationVersion}`,
    `- Snapshot state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.snapshotState}`,
    `- Ready for read-only handoff route coverage archive: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.readyForReadOnlyHandoffRouteCoverageArchive}`,
    `- Coverage digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.coverageDigestValue}`,
    `- Snapshot digest: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.snapshotDigest.value}`,
    `- Snapshot digest scope: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.snapshotDigest.scope}`,
    `- Snapshot digest covered section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.snapshotDigest.coveredSectionCount}`,
    `- Archived sections: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.archivedSections.join(", ")}`,
    `- Archived section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.archivedSectionCount}`,
    `- Verification gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.verificationGateCount}`,
    `- Verification passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.verificationPassedGateCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Route Coverage Archive Verification",
    `- Verification version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.verificationVersion}`,
    `- Input snapshot version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.inputSnapshotVersion}`,
    `- Verification state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.verificationState}`,
    `- Ready for read-only handoff route coverage archive verification: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.readyForReadOnlyHandoffRouteCoverageArchiveVerification}`,
    `- Gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.passedGateCount}`,
    `- Blocked reason codes: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.blockedReasonCodes.join(", ") || "none"}`,
    `- Snapshot digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.snapshotDigestValue}`,
    `- Archived section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.archivedSectionCount}`,
    `- Verification gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.verificationGateCount}`,
    `- Verification passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.verificationPassedGateCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.mutatesSiblingState}`,
    "",
    "### Handoff Route Coverage Archive Verification Gates",
    ...renderEntries(profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.gates),
    "",
    "## Source Matrix Handoff Route Coverage Archive Summary",
    `- Summary version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryVersion}`,
    `- Input verification version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.inputVerificationVersion}`,
    `- Summary state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryState}`,
    `- Ready for read-only handoff route coverage archive summary: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.readyForReadOnlyHandoffRouteCoverageArchiveSummary}`,
    `- Verification state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.verificationState}`,
    `- Snapshot digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.snapshotDigestValue}`,
    `- Summary digest: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryDigest.value}`,
    `- Summary digest scope: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryDigest.scope}`,
    `- Summary digest covered line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryDigest.coveredLineCount}`,
    `- Summary lines: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryLines.join("; ")}`,
    `- Summary line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryLineCount}`,
    `- Gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.passedGateCount}`,
    `- Archived section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.archivedSectionCount}`,
    `- Blocked reason count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.blockedReasonCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Route Coverage Archive Summary Receipt",
    `- Receipt version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptVersion}`,
    `- Input summary version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.inputSummaryVersion}`,
    `- Receipt state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptState}`,
    `- Ready for read-only handoff route coverage archive summary receipt: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.readyForReadOnlyHandoffRouteCoverageArchiveSummaryReceipt}`,
    `- Summary state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.summaryState}`,
    `- Summary digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.summaryDigestValue}`,
    `- Receipt digest: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptDigest.value}`,
    `- Receipt digest scope: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptDigest.scope}`,
    `- Receipt digest covered summary line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptDigest.coveredSummaryLineCount}`,
    `- Receipt digest covered blocked reason count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptDigest.coveredBlockedReasonCount}`,
    `- Receipt lines: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptLines.join("; ")}`,
    `- Receipt line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptLineCount}`,
    `- Summary line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.summaryLineCount}`,
    `- Gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.passedGateCount}`,
    `- Blocked reason count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.blockedReasonCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Route Coverage Archive Summary Receipt Archive Snapshot",
    `- Snapshot version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.snapshotVersion}`,
    `- Input receipt version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.inputReceiptVersion}`,
    `- Snapshot state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.snapshotState}`,
    `- Ready for read-only handoff route coverage archive summary receipt archive: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.readyForReadOnlyHandoffRouteCoverageArchiveSummaryReceiptArchive}`,
    `- Receipt digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.receiptDigestValue}`,
    `- Snapshot digest: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.snapshotDigest.value}`,
    `- Snapshot digest scope: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.snapshotDigest.scope}`,
    `- Snapshot digest covered section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.snapshotDigest.coveredSectionCount}`,
    `- Archived sections: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.archivedSections.join(", ")}`,
    `- Archived section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.archivedSectionCount}`,
    `- Receipt line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.receiptLineCount}`,
    `- Summary line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.summaryLineCount}`,
    `- Blocked reason count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.blockedReasonCount}`,
    `- Includes raw credential: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.includesRawCredential}`,
    `- Includes runtime payload: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.includesRuntimePayload}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Route Coverage Archive Summary Receipt Archive Verification",
    `- Verification version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.verificationVersion}`,
    `- Input snapshot version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.inputSnapshotVersion}`,
    `- Verification state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.verificationState}`,
    `- Ready for read-only handoff route coverage archive summary receipt archive verification: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.readyForReadOnlyHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification}`,
    `- Gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.passedGateCount}`,
    `- Blocked reason codes: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.blockedReasonCodes.join(", ") || "none"}`,
    `- Snapshot digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.snapshotDigestValue}`,
    `- Archived section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.archivedSectionCount}`,
    `- Receipt line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.receiptLineCount}`,
    `- Summary line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.summaryLineCount}`,
    `- Blocked reason count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.blockedReasonCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.mutatesSiblingState}`,
    "",
    "### Handoff Route Coverage Archive Summary Receipt Archive Verification Gates",
    ...renderEntries(profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.gates),
    "",
    "## Checks",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Evidence Endpoints",
    ...renderEntries(profile.evidenceEndpoints),
  ].join("\n");
}
