import { formatValue, renderEntries } from "./liveProbeReportUtils.js";
import type { ControlledReadOnlyShardPreviewProfile } from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewTypes.js";

export function renderControlledReadOnlyShardPreviewSourceMatrixSections(
  profile: ControlledReadOnlyShardPreviewProfile,
): string[] {
  return [
    "## Source Matrix",
    `- Source count: ${profile.preview.sourceMatrix.sourceCount}`,
    `- Ready source count: ${profile.preview.sourceMatrix.readySourceCount}`,
    `- Failed source count: ${profile.preview.sourceMatrix.failedSourceCount}`,
    `- Skipped source count: ${profile.preview.sourceMatrix.skippedSourceCount}`,
    `- Routing modes: ${profile.preview.sourceMatrix.routingModes.join(", ") || "none"}`,
    `- Shard count delta: ${formatValue(profile.preview.sourceMatrix.shardCountDelta)}`,
    `- Slot count delta: ${formatValue(profile.preview.sourceMatrix.slotCountDelta)}`,
    `- All sources ready: ${profile.preview.sourceMatrix.allSourcesReady}`,
    ...profile.preview.sourceMatrix.sources.flatMap((source) => [
      "",
      `### ${source.source}`,
      ...renderEntries(source),
    ]),
    "",
    "## Source Matrix Consumer",
    `- Consumer version: ${profile.preview.sourceMatrixConsumer.consumerVersion}`,
    `- Input source version: ${profile.preview.sourceMatrixConsumer.inputSourceVersion}`,
    `- Decision: ${profile.preview.sourceMatrixConsumer.decision}`,
    `- Ready for controlled read-only consumption: ${profile.preview.sourceMatrixConsumer.readyForControlledReadOnlyConsumption}`,
    `- Required sources: ${profile.preview.sourceMatrixConsumer.requiredSources.join(", ") || "none"}`,
    `- Observed sources: ${profile.preview.sourceMatrixConsumer.observedSources.join(", ") || "none"}`,
    `- Missing sources: ${profile.preview.sourceMatrixConsumer.missingSources.join(", ") || "none"}`,
    `- Gate count: ${profile.preview.sourceMatrixConsumer.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixConsumer.passedGateCount}`,
    `- Blocked reason codes: ${profile.preview.sourceMatrixConsumer.blockedReasonCodes.join(", ") || "none"}`,
    `- Activates routing: ${profile.preview.sourceMatrixConsumer.activatesRouting}`,
    `- Starts services: ${profile.preview.sourceMatrixConsumer.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixConsumer.mutatesSiblingState}`,
    "",
    "### Consumer Gates",
    ...renderEntries(profile.preview.sourceMatrixConsumer.gates),
    "",
    "### Consumer Comparison",
    ...renderEntries(profile.preview.sourceMatrixConsumer.comparison),
    "",
    "## Source Matrix Drift Summary",
    `- Summary version: ${profile.preview.sourceMatrixDriftSummary.summaryVersion}`,
    `- Input consumer version: ${profile.preview.sourceMatrixDriftSummary.inputConsumerVersion}`,
    `- Drift state: ${profile.preview.sourceMatrixDriftSummary.driftState}`,
    `- Ready for controlled drift review: ${profile.preview.sourceMatrixDriftSummary.readyForControlledDriftReview}`,
    `- Finding count: ${profile.preview.sourceMatrixDriftSummary.findingCount}`,
    `- Drift finding count: ${profile.preview.sourceMatrixDriftSummary.driftFindingCount}`,
    `- Blocking finding count: ${profile.preview.sourceMatrixDriftSummary.blockingFindingCount}`,
    `- Comparable finding count: ${profile.preview.sourceMatrixDriftSummary.comparableFindingCount}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixDriftSummary.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixDriftSummary.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixDriftSummary.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixDriftSummary.mutatesSiblingState}`,
    "",
    "### Drift Findings",
    ...profile.preview.sourceMatrixDriftSummary.findings.map((finding) =>
      `- ${finding.dimension}: ${finding.status} (${finding.severity}) - ${finding.message}`),
    "",
    "## Source Matrix Consumption Plan",
    `- Plan version: ${profile.preview.sourceMatrixConsumptionPlan.planVersion}`,
    `- Input consumer version: ${profile.preview.sourceMatrixConsumptionPlan.inputConsumerVersion}`,
    `- Input drift summary version: ${profile.preview.sourceMatrixConsumptionPlan.inputDriftSummaryVersion}`,
    `- Plan state: ${profile.preview.sourceMatrixConsumptionPlan.planState}`,
    `- Ready for read-only consumption plan: ${profile.preview.sourceMatrixConsumptionPlan.readyForReadOnlyConsumptionPlan}`,
    `- Review mode: ${profile.preview.sourceMatrixConsumptionPlan.reviewMode}`,
    `- Observed sources: ${profile.preview.sourceMatrixConsumptionPlan.observedSources.join(", ") || "none"}`,
    `- Missing sources: ${profile.preview.sourceMatrixConsumptionPlan.missingSources.join(", ") || "none"}`,
    `- Routing modes: ${profile.preview.sourceMatrixConsumptionPlan.routingModes.join(", ") || "none"}`,
    `- Blocked reason codes: ${profile.preview.sourceMatrixConsumptionPlan.blockedReasonCodes.join(", ") || "none"}`,
    `- Drift finding count: ${profile.preview.sourceMatrixConsumptionPlan.driftFindingCount}`,
    `- Blocking finding count: ${profile.preview.sourceMatrixConsumptionPlan.blockingFindingCount}`,
    `- Plan digest: ${profile.preview.sourceMatrixConsumptionPlan.planDigest.value}`,
    `- Plan digest scope: ${profile.preview.sourceMatrixConsumptionPlan.planDigest.scope}`,
    `- Plan digest covered step count: ${profile.preview.sourceMatrixConsumptionPlan.planDigest.coveredStepCount}`,
    `- Ready step count: ${profile.preview.sourceMatrixConsumptionPlan.stepStatusSummary.readyStepCount}`,
    `- Review step count: ${profile.preview.sourceMatrixConsumptionPlan.stepStatusSummary.reviewStepCount}`,
    `- Blocked step count: ${profile.preview.sourceMatrixConsumptionPlan.stepStatusSummary.blockedStepCount}`,
    `- Routing activation allowed step count: ${profile.preview.sourceMatrixConsumptionPlan.stepSafetySummary.routingActivationAllowedStepCount}`,
    `- Writes allowed step count: ${profile.preview.sourceMatrixConsumptionPlan.stepSafetySummary.writesAllowedStepCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixConsumptionPlan.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixConsumptionPlan.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixConsumptionPlan.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixConsumptionPlan.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixConsumptionPlan.mutatesSiblingState}`,
    "",
    "### Consumption Plan Steps",
    ...profile.preview.sourceMatrixConsumptionPlan.planSteps.map((step) => `- ${step}`),
    "",
    "### Consumption Plan Step Records",
    ...profile.preview.sourceMatrixConsumptionPlan.planStepRecords.map((step) =>
      `- ${step.order}. ${step.code}: ${step.status}; ${step.evidence}; routingActivationAllowed=${step.routingActivationAllowed}; writesAllowed=${step.writesAllowed}`),
    "",
    "## Source Matrix Review Checklist",
    `- Checklist version: ${profile.preview.sourceMatrixReviewChecklist.checklistVersion}`,
    `- Input drift summary version: ${profile.preview.sourceMatrixReviewChecklist.inputDriftSummaryVersion}`,
    `- Checklist state: ${profile.preview.sourceMatrixReviewChecklist.checklistState}`,
    `- Ready for operator review: ${profile.preview.sourceMatrixReviewChecklist.readyForOperatorReview}`,
    `- Item count: ${profile.preview.sourceMatrixReviewChecklist.itemCount}`,
    `- Ready item count: ${profile.preview.sourceMatrixReviewChecklist.readyItemCount}`,
    `- Review item count: ${profile.preview.sourceMatrixReviewChecklist.reviewItemCount}`,
    `- Blocked item count: ${profile.preview.sourceMatrixReviewChecklist.blockedItemCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixReviewChecklist.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixReviewChecklist.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixReviewChecklist.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixReviewChecklist.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixReviewChecklist.mutatesSiblingState}`,
    "",
    "### Checklist Items",
    ...profile.preview.sourceMatrixReviewChecklist.items.map((item) =>
      `- ${item.order}. ${item.check}: ${item.status} (${item.severity}) - ${item.operatorAction}`),
    "",
    "## Source Matrix Review Digest",
    `- Digest version: ${profile.preview.sourceMatrixReviewDigest.digestVersion}`,
    `- Input checklist version: ${profile.preview.sourceMatrixReviewDigest.inputChecklistVersion}`,
    `- Algorithm: ${profile.preview.sourceMatrixReviewDigest.algorithm}`,
    `- Value: ${profile.preview.sourceMatrixReviewDigest.value}`,
    `- Covered fields: ${profile.preview.sourceMatrixReviewDigest.coveredFields.join(", ")}`,
    `- Ready for controlled review archive: ${profile.preview.sourceMatrixReviewDigest.readyForControlledReviewArchive}`,
    `- Checklist state: ${profile.preview.sourceMatrixReviewDigest.checklistState}`,
    `- Item count: ${profile.preview.sourceMatrixReviewDigest.itemCount}`,
    `- Blocked item count: ${profile.preview.sourceMatrixReviewDigest.blockedItemCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixReviewDigest.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixReviewDigest.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixReviewDigest.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixReviewDigest.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixReviewDigest.mutatesSiblingState}`,
    "",
    "## Source Matrix Archive Snapshot",
    `- Snapshot version: ${profile.preview.sourceMatrixArchiveSnapshot.snapshotVersion}`,
    `- Input review digest version: ${profile.preview.sourceMatrixArchiveSnapshot.inputReviewDigestVersion}`,
    `- Archive state: ${profile.preview.sourceMatrixArchiveSnapshot.archiveState}`,
    `- Ready for controlled review archive: ${profile.preview.sourceMatrixArchiveSnapshot.readyForControlledReviewArchive}`,
    `- Digest value: ${profile.preview.sourceMatrixArchiveSnapshot.digestValue}`,
    `- Archived sections: ${profile.preview.sourceMatrixArchiveSnapshot.archivedSections.join(", ")}`,
    `- Archived section count: ${profile.preview.sourceMatrixArchiveSnapshot.archivedSectionCount}`,
    `- Checklist state: ${profile.preview.sourceMatrixArchiveSnapshot.checklistState}`,
    `- Item count: ${profile.preview.sourceMatrixArchiveSnapshot.itemCount}`,
    `- Blocked item count: ${profile.preview.sourceMatrixArchiveSnapshot.blockedItemCount}`,
    `- Includes raw credential: ${profile.preview.sourceMatrixArchiveSnapshot.includesRawCredential}`,
    `- Includes runtime payload: ${profile.preview.sourceMatrixArchiveSnapshot.includesRuntimePayload}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixArchiveSnapshot.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixArchiveSnapshot.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixArchiveSnapshot.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixArchiveSnapshot.mutatesSiblingState}`,
    "",
    "## Source Matrix Archive Snapshot Summary Export",
    `- Export version: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.exportVersion}`,
    `- Input archive snapshot version: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.inputArchiveSnapshotVersion}`,
    `- Export state: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.exportState}`,
    `- Ready for summary export: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.readyForSummaryExport}`,
    `- Digest value: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.digestValue}`,
    `- Summary digest: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.summaryDigest.value}`,
    `- Summary digest scope: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.summaryDigest.scope}`,
    `- Summary digest covered line count: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.summaryDigest.coveredLineCount}`,
    `- Summary lines: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.summaryLines.join("; ")}`,
    `- Summary line count: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.summaryLineCount}`,
    `- Archived section count: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.archivedSectionCount}`,
    `- Blocked item count: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.blockedItemCount}`,
    `- Includes raw credential: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.includesRawCredential}`,
    `- Includes runtime payload: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.includesRuntimePayload}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixArchiveSnapshotSummaryExport.mutatesSiblingState}`,
    "",
  ];
}
