import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverDisabledCandidateUpstreamEchoVerificationProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverDisabledCandidateUpstreamEchoVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverDisabledCandidateUpstreamEchoVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverDisabledCandidateUpstreamEchoVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver disabled candidate upstream echo verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Verification state: ${profile.verificationState}`,
    `- Ready for disabled candidate upstream echo verification: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverDisabledCandidateUpstreamEchoVerification}`,
    `- Read-only upstream echo verification: ${profile.readOnlyUpstreamEchoVerification}`,
    `- Disabled candidate echo verification only: ${profile.disabledCandidateEchoVerificationOnly}`,
    `- Real resolver implementation allowed: ${profile.realResolverImplementationAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v273",
    "",
    ...renderEntries(profile.sourceNodeV273),
    "",
    "## Java v113 Echo Receipt",
    "",
    ...renderEntries(profile.upstreamEchoes.javaV113),
    "",
    "## mini-kv v120 Non-Participation Receipt",
    "",
    ...renderEntries(profile.upstreamEchoes.miniKvV120),
    "",
    "## Echo Verification",
    "",
    ...renderEntries(profile.echoVerification),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No disabled candidate upstream echo blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No disabled candidate upstream echo warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No disabled candidate upstream echo recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
