import { formatValue, renderEntries, renderMessages } from "./liveProbeReportUtils.js";
import { renderControlledReadOnlyShardPreviewHandoffSummarySections } from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewHandoffSummaryRenderer.js";
import { renderControlledReadOnlyShardPreviewHandoffRouteCoverageSections } from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewRouteCoverageRenderer.js";
import { renderControlledReadOnlyShardPreviewSourceMatrixSections } from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewSourceMatrixRenderer.js";
import type { ControlledReadOnlyShardPreviewProfile } from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewMarkdown(
  profile: ControlledReadOnlyShardPreviewProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Profile version: ${profile.profileVersion}`,
    `- Preview state: ${profile.previewState}`,
    `- Preview decision: ${profile.previewDecision}`,
    `- Ready: ${profile.readyForControlledReadOnlyShardPreview}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Preview only: ${profile.previewOnly}`,
    `- Live read only: ${profile.liveReadOnly}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Stops Java service: ${profile.stopsJavaService}`,
    `- Stops mini-kv service: ${profile.stopsMiniKvService}`,
    `- Active shard router allowed: ${profile.activeShardRouterAllowed}`,
    `- Write routing allowed: ${profile.writeRoutingAllowed}`,
    `- LOAD/RESTORE/COMPACT allowed: ${profile.loadRestoreCompactAllowed}`,
    `- Preview digest: ${profile.preview.previewDigest}`,
    "",
    "## Java Preview",
    ...renderEntries(profile.preview.java),
    `- Read status: ${profile.reads.java.status}`,
    `- Endpoint: ${profile.reads.java.endpoint}`,
    `- Latency ms: ${formatValue(profile.reads.java.latencyMs)}`,
    "",
    "## mini-kv Preview",
    ...renderEntries(profile.preview.miniKv),
    `- Read status: ${profile.reads.miniKv.status}`,
    `- Command: ${profile.reads.miniKv.command ?? "none"}`,
    `- Latency ms: ${formatValue(profile.reads.miniKv.latencyMs)}`,
    "",
    "## Combined Preview",
    `- Combined shard count: ${formatValue(profile.preview.combinedShardCount)}`,
    `- Combined slot count: ${formatValue(profile.preview.combinedSlotCount)}`,
    `- Both read-only: ${profile.preview.bothReadOnly}`,
    `- Both execution blocked: ${profile.preview.bothExecutionBlocked}`,
    "",
    ...renderControlledReadOnlyShardPreviewSourceMatrixSections(profile),
    ...renderControlledReadOnlyShardPreviewHandoffSummarySections(profile),
    ...renderControlledReadOnlyShardPreviewHandoffRouteCoverageSections(profile),
    "## Execution Gap Matrix",
    ...renderEntries({
      matrixVersion: profile.preview.executionGapMatrix.matrixVersion,
      matrixState: profile.preview.executionGapMatrix.matrixState,
      readyForLiveReadOnlyPacketPlanning:
        profile.preview.executionGapMatrix.readyForLiveReadOnlyPacketPlanning,
      readyForLiveReadOnlyExecution: profile.preview.executionGapMatrix.readyForLiveReadOnlyExecution,
      readyForProductionExecution: profile.preview.executionGapMatrix.readyForProductionExecution,
      gateCount: profile.preview.executionGapMatrix.gateCount,
      actionRequiredGateCount: profile.preview.executionGapMatrix.actionRequiredGateCount,
      productionExecutionBlockerCount: profile.preview.executionGapMatrix.productionExecutionBlockerCount,
    }),
    "",
    "## Live Read-Only Packet Candidate",
    ...renderEntries({
      candidateVersion: profile.preview.liveReadOnlyPacketCandidate.candidateVersion,
      candidateState: profile.preview.liveReadOnlyPacketCandidate.candidateState,
      readyForManualLiveReadOnlyWindow:
        profile.preview.liveReadOnlyPacketCandidate.readyForManualLiveReadOnlyWindow,
      processStepCount: profile.preview.liveReadOnlyPacketCandidate.processStepCount,
      readTargetCount: profile.preview.liveReadOnlyPacketCandidate.readTargetCount,
      candidateDigest: profile.preview.liveReadOnlyPacketCandidate.candidateDigest,
    }),
    "",
    "## Live Read-Only Packet Candidate Verification",
    ...renderEntries({
      verificationVersion: profile.preview.liveReadOnlyPacketCandidateVerification.verificationVersion,
      verificationState: profile.preview.liveReadOnlyPacketCandidateVerification.verificationState,
      readyForManualLiveReadOnlyWindow:
        profile.preview.liveReadOnlyPacketCandidateVerification.readyForManualLiveReadOnlyWindow,
      passedGateCount: profile.preview.liveReadOnlyPacketCandidateVerification.passedGateCount,
      gateCount: profile.preview.liveReadOnlyPacketCandidateVerification.gateCount,
      nextAction: profile.preview.liveReadOnlyPacketCandidateVerification.nextAction,
    }),
    "",
    "## Live Read-Only Window Stage Ledger",
    ...renderEntries({
      ledgerVersion: profile.preview.liveReadOnlyWindowStageLedger.ledgerVersion,
      ledgerState: profile.preview.liveReadOnlyWindowStageLedger.ledgerState,
      readyForManualLiveReadOnlyWindow:
        profile.preview.liveReadOnlyWindowStageLedger.readyForManualLiveReadOnlyWindow,
      stageCount: profile.preview.liveReadOnlyWindowStageLedger.stageCount,
      readyStageCount: profile.preview.liveReadOnlyWindowStageLedger.readyStageCount,
      cleanupRequiredStageCount: profile.preview.liveReadOnlyWindowStageLedger.cleanupRequiredStageCount,
      ledgerDigest: profile.preview.liveReadOnlyWindowStageLedger.ledgerDigest,
    }),
    "",
    "## Checks",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Evidence Endpoints",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    ...profile.nextActions.map((action) => `- ${action}`),
  ].join("\n");
}
