import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightSlotTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_VERSIONS = [
  "Node v1137",
  "Node v1138",
  "Node v1139",
  "Node v1140",
  "Node v1141",
  "Node v1142",
  "Node v1143",
  "Node v1144",
  "Node v1145",
  "Node v1146",
  "Node v1147",
  "Node v1148",
  "Node v1149",
  "Node v1150",
  "Node v1151",
  "Node v1152",
  "Node v1153",
  "Node v1154",
  "Node v1155",
  "Node v1156",
  "Node v1157",
  "Node v1158",
  "Node v1159",
  "Node v1160",
  "Node v1161",
] as const;

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SLOTS:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightSlotTemplate[]
  = Object.freeze([
    slot("Node v1137", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REQUEST_MANIFEST_SLOT",
      "reviewPackageRequestManifest", "identity-review-package-slot", "manual-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_REQUEST_MANIFEST",
      "ARTIFACT_DRAFT_READINESS_REQUEST_MANIFEST_CONTROL", "manual-review",
      "Carry the draft request manifest into a review package slot without creating an artifact."),
    slot("Node v1138", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_ARTIFACT_PREFLIGHT_DIGEST_SLOT",
      "artifactPreflightDigestPackageSlot", "digest-binding-review-package-slot",
      "digest-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_ARTIFACT_PREFLIGHT_DIGEST_PIN",
      "ARTIFACT_DRAFT_READINESS_ARTIFACT_PREFLIGHT_DIGEST_CONTROL", "digest-pin",
      "Carry the artifact preflight digest pin into the review package preflight."),
    slot("Node v1139", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_TEMPLATE_DIGEST_SLOT",
      "templateDigestPackageSlot", "digest-binding-review-package-slot", "digest-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_TEMPLATE_DIGEST_PIN",
      "ARTIFACT_DRAFT_READINESS_TEMPLATE_DIGEST_CONTROL", "digest-pin",
      "Carry the template digest pin that defines manual approval wording."),
    slot("Node v1140", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REVIEW_DIGEST_SLOT",
      "approvalPacketReviewDigestPackageSlot", "digest-binding-review-package-slot",
      "digest-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_REVIEW_DIGEST_PIN",
      "ARTIFACT_DRAFT_READINESS_REVIEW_DIGEST_CONTROL", "digest-pin",
      "Carry the approval packet review digest into the future manual draft package."),
    slot("Node v1141", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_OPERATOR_IDENTITY_SLOT",
      "operatorIdentityPackageSlot", "identity-review-package-slot", "manual-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_OPERATOR_IDENTITY_REVIEW",
      "ARTIFACT_DRAFT_READINESS_OPERATOR_IDENTITY_CONTROL", "manual-review",
      "Expose the reviewed operator identity as package metadata without credential capture."),
    slot("Node v1142", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_OPERATOR_ROLE_SLOT",
      "operatorRolePackageSlot", "identity-review-package-slot", "manual-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_OPERATOR_ROLE_REVIEW",
      "ARTIFACT_DRAFT_READINESS_OPERATOR_ROLE_CONTROL", "manual-review",
      "Expose the reviewed operator role as package metadata before draft authoring."),
    slot("Node v1143", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_WINDOW_ID_SLOT",
      "captureWindowPackageSlot", "identity-review-package-slot", "manual-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_WINDOW_ID_REVIEW",
      "ARTIFACT_DRAFT_READINESS_WINDOW_ID_CONTROL", "manual-review",
      "Bind the review package to the capture window id without opening that window."),
    slot("Node v1144", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_CHANNEL_POLICY_SLOT",
      "captureChannelPolicyPackageSlot", "policy-review-package-slot", "policy-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_CHANNEL_POLICY_REVIEW",
      "ARTIFACT_DRAFT_READINESS_CHANNEL_POLICY_CONTROL", "policy-check",
      "Carry capture channel policy into a read-only package slot."),
    slot("Node v1145", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIGNATURE_ALGORITHM_SLOT",
      "signatureAlgorithmPackageSlot", "signature-envelope-review-package-slot",
      "policy-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SIGNATURE_ALGORITHM_REVIEW",
      "ARTIFACT_DRAFT_READINESS_SIGNATURE_ALGORITHM_CONTROL", "policy-check",
      "Prepare signature algorithm policy for human review while signatures remain absent."),
    slot("Node v1146", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_DETACHED_SIGNATURE_SLOT",
      "detachedSignaturePlaceholderPackageSlot", "signature-envelope-review-package-slot",
      "manual-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_DETACHED_SIGNATURE_REVIEW",
      "ARTIFACT_DRAFT_READINESS_DETACHED_SIGNATURE_CONTROL", "manual-review",
      "Keep the detached signature lane as a placeholder for out-of-band human authoring."),
    slot("Node v1147", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIGNATURE_REDACTION_SLOT",
      "signatureRedactionPackageSlot", "signature-envelope-review-package-slot",
      "policy-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SIGNATURE_REDACTION_REVIEW",
      "ARTIFACT_DRAFT_READINESS_SIGNATURE_REDACTION_CONTROL", "policy-check",
      "Carry signature redaction policy while raw signature material remains absent."),
    slot("Node v1148", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_APPROVAL_STATEMENT_DIGEST_SLOT",
      "approvalStatementDigestPackageSlot", "digest-binding-review-package-slot",
      "digest-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_APPROVAL_STATEMENT_DIGEST_PIN",
      "ARTIFACT_DRAFT_READINESS_APPROVAL_STATEMENT_DIGEST_CONTROL", "digest-pin",
      "Carry the approval statement digest without storing signed statement text."),
    slot("Node v1149", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_VERSION_SLOT",
      "sourceEvidenceVersionPackageSlot", "source-evidence-review-package-slot",
      "manual-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SOURCE_VERSION_REVIEW",
      "ARTIFACT_DRAFT_READINESS_SOURCE_VERSION_CONTROL", "manual-review",
      "Expose the source evidence version the later manual draft must cite."),
    slot("Node v1150", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_FILE_SLOT",
      "sourceEvidenceFilePackageSlot", "source-evidence-review-package-slot",
      "manual-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SOURCE_FILE_REVIEW",
      "ARTIFACT_DRAFT_READINESS_SOURCE_FILE_CONTROL", "manual-review",
      "Expose the source evidence file id while keeping evidence imports blocked."),
    slot("Node v1151", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_SNIPPET_SLOT",
      "sourceEvidenceSnippetPackageSlot", "source-evidence-review-package-slot",
      "manual-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SOURCE_SNIPPET_REVIEW",
      "ARTIFACT_DRAFT_READINESS_SOURCE_SNIPPET_CONTROL", "manual-review",
      "Expose the source snippet id without assembling runtime payloads."),
    slot("Node v1152", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REDACTED_VALUE_DIGEST_SLOT",
      "redactedValueDigestPackageSlot", "value-binding-review-package-slot",
      "digest-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_REDACTED_VALUE_DIGEST_PIN",
      "ARTIFACT_DRAFT_READINESS_REDACTED_VALUE_DIGEST_CONTROL", "digest-pin",
      "Carry the redacted value digest while raw operator values remain absent."),
    slot("Node v1153", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_VALUE_SHAPE_SLOT",
      "valueShapePackageSlot", "value-binding-review-package-slot", "manual-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_VALUE_SHAPE_REVIEW",
      "ARTIFACT_DRAFT_READINESS_VALUE_SHAPE_CONTROL", "manual-review",
      "Expose value shape metadata without accepting operator-supplied values."),
    slot("Node v1154", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REDACTION_POLICY_SLOT",
      "redactionPolicyPackageSlot", "policy-review-package-slot", "policy-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_REDACTION_POLICY_REVIEW",
      "ARTIFACT_DRAFT_READINESS_REDACTION_POLICY_CONTROL", "policy-check",
      "Carry redaction policy into the review package preflight."),
    slot("Node v1155", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_PROVENANCE_POLICY_SLOT",
      "provenancePolicyPackageSlot", "policy-review-package-slot", "policy-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_PROVENANCE_POLICY_REVIEW",
      "ARTIFACT_DRAFT_READINESS_PROVENANCE_POLICY_CONTROL", "policy-check",
      "Carry provenance policy so later draft text can cite immutable evidence."),
    slot("Node v1156", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_RAW_SECRET_EMBARGO_SLOT",
      "rawSecretEmbargoPackageSlot", "execution-lock-review-package-slot",
      "execution-lock-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_RAW_SECRET_EMBARGO",
      "ARTIFACT_DRAFT_READINESS_RAW_SECRET_EMBARGO_CONTROL", "execution-lock",
      "Carry the raw secret embargo into the review package preflight."),
    slot("Node v1157", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_APPROVAL_GRANT_EMBARGO_SLOT",
      "approvalGrantEmbargoPackageSlot", "execution-lock-review-package-slot",
      "execution-lock-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_APPROVAL_GRANT_EMBARGO",
      "ARTIFACT_DRAFT_READINESS_APPROVAL_GRANT_EMBARGO_CONTROL", "execution-lock",
      "Carry the approval grant embargo while no grant exists."),
    slot("Node v1158", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_ZERO_VALUE_IMPORT_EMBARGO_SLOT",
      "zeroValueImportEmbargoPackageSlot", "execution-lock-review-package-slot",
      "execution-lock-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_ZERO_VALUE_IMPORT_EMBARGO",
      "ARTIFACT_DRAFT_READINESS_ZERO_VALUE_IMPORT_EMBARGO_CONTROL", "execution-lock",
      "Carry zero value import evidence while submissions remain blocked."),
    slot("Node v1159", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_WRITE_ROUTE_EMBARGO_SLOT",
      "writeRouteEmbargoPackageSlot", "execution-lock-review-package-slot",
      "execution-lock-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_WRITE_ROUTE_EMBARGO",
      "ARTIFACT_DRAFT_READINESS_WRITE_ROUTE_EMBARGO_CONTROL", "execution-lock",
      "Carry the write route embargo until a real approval grant exists."),
    slot("Node v1160", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIBLING_NON_MUTATION_SLOT",
      "siblingNonMutationPackageSlot", "execution-lock-review-package-slot",
      "execution-lock-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_SIBLING_NON_MUTATION_EVIDENCE",
      "ARTIFACT_DRAFT_READINESS_SIBLING_NON_MUTATION_CONTROL", "execution-lock",
      "Carry sibling non-mutation evidence into the review package."),
    slot("Node v1161", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_CLOSEOUT_SLOT",
      "signedApprovalCaptureArtifactDraftReviewPackagePreflightCloseout",
      "archive-closeout-review-package-slot", "archive-closeout-review-package-entry",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_READINESS_CLOSEOUT",
      "ARTIFACT_DRAFT_READINESS_CLOSEOUT_CONTROL", "archive-closeout",
      "Close the review package preflight and require separate human draft artifact authoring."),
  ]);

function slot(
  nodeVersion:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightSlotTemplate[
      "nodeVersion"
    ],
  code: string,
  packageSlotName: string,
  kind:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightSlotTemplate[
      "kind"
    ],
  slotMode:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightSlotTemplate[
      "slotMode"
    ],
  sourceReadinessLaneCode: string,
  sourceReadinessControlCode: string,
  requiredReadinessLaneMode:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightSlotTemplate[
      "requiredReadinessLaneMode"
    ],
  reviewPackagePurpose: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightSlotTemplate {
  return {
    nodeVersion,
    code,
    packageSlotName,
    kind,
    slotMode,
    sourceReadinessLaneCode,
    sourceReadinessControlCode,
    requiredReadinessLaneMode,
    reviewPackagePurpose,
  };
}
