import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverPreImplementationPlanIntakeProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverPreImplementationPlanIntakeTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverPreImplementationPlanIntakeMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverPreImplementationPlanIntakeProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver pre-implementation plan intake",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Plan intake state: ${profile.planIntakeState}`,
    `- Ready for pre-implementation plan intake: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverPreImplementationPlanIntake}`,
    `- Plan intake only: ${profile.planIntakeOnly}`,
    `- Real resolver implementation allowed: ${profile.realResolverImplementationAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v269",
    "",
    ...renderEntries(profile.sourceNodeV269),
    "",
    "## Pre-Implementation Plan",
    "",
    ...renderEntries({
      planVersion: profile.preImplementationPlan.planVersion,
      planMode: profile.preImplementationPlan.planMode,
      sourceSpan: profile.preImplementationPlan.sourceSpan,
      planDigest: profile.preImplementationPlan.planDigest,
      boundaryCount: profile.preImplementationPlan.boundaryCount,
      definedBoundaryCount: profile.preImplementationPlan.definedBoundaryCount,
      allRequiredBoundariesDefined: profile.preImplementationPlan.allRequiredBoundariesDefined,
      realResolverImplementationAllowed: profile.preImplementationPlan.realResolverImplementationAllowed,
      secretProviderRuntimeAllowed: profile.preImplementationPlan.secretProviderRuntimeAllowed,
      credentialValueReadAllowed: profile.preImplementationPlan.credentialValueReadAllowed,
      rawEndpointUrlParseAllowed: profile.preImplementationPlan.rawEndpointUrlParseAllowed,
      externalRequestAllowed: profile.preImplementationPlan.externalRequestAllowed,
      schemaMigrationAllowed: profile.preImplementationPlan.schemaMigrationAllowed,
      approvalLedgerWriteAllowed: profile.preImplementationPlan.approvalLedgerWriteAllowed,
      automaticUpstreamStartAllowed: profile.preImplementationPlan.automaticUpstreamStartAllowed,
    }),
    "",
    "## Boundaries",
    "",
    ...profile.preImplementationPlan.boundaries.map((boundary) =>
      `- ${boundary.code}: ${boundary.status}; requirement=${boundary.requirementFromV268}; owner=${boundary.owner}; evidence=${boundary.verificationEvidence}`),
    "",
    "## Plan Intake",
    "",
    ...renderEntries(profile.planIntake),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No credential resolver pre-implementation plan intake blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No credential resolver pre-implementation plan intake warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No credential resolver pre-implementation plan intake recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
