import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverProductionReadinessDecisionGateProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverProductionReadinessDecisionGateTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverProductionReadinessDecisionGateMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverProductionReadinessDecisionGateProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver production readiness decision gate",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Decision gate state: ${profile.decisionGateState}`,
    `- Readiness decision: ${profile.readinessDecision}`,
    `- Ready for pre-implementation plan: ${profile.readyForCredentialResolverPreImplementationPlan}`,
    `- Real resolver implementation allowed: ${profile.realResolverImplementationAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v267",
    "",
    ...renderEntries(profile.sourceNodeV267),
    "",
    "## Pre-Implementation Requirements",
    "",
    ...renderEntries(profile.preImplementationRequirements),
    "",
    "## Production Readiness Decision",
    "",
    ...renderEntries(profile.productionReadinessDecision),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No credential resolver production readiness blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No credential resolver production readiness warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No credential resolver production readiness recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
