import { renderEntries } from "./liveProbeReportUtils.js";
import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageSubmissionPreflight,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageSubmissionPreflightComparisonControl,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageSubmissionPreflightSlot,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageSubmissionPreflightTypes.js";

export function renderControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageSubmissionPreflightMarkdown(
  preflight:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageSubmissionPreflight,
): string {
  return [
    "# Controlled read-only shard preview live read-only window operator evidence value supply signed approval capture artifact draft text package submission preflight",
    "",
    `- Signed approval capture artifact draft text package submission preflight version: ${preflight.signedApprovalCaptureArtifactDraftTextPackageSubmissionPreflightVersion}`,
    `- Source signed approval capture artifact draft text package review preflight version: ${preflight.sourceSignedApprovalCaptureArtifactDraftTextPackageReviewPreflightVersion}`,
    `- Artifact draft text package submission preflight state: ${preflight.artifactDraftTextPackageSubmissionPreflightState}`,
    `- Ready for signed approval artifact draft text package submission preflight: ${preflight.readyForSignedApprovalArtifactDraftTextPackageSubmissionPreflight}`,
    `- Ready for manual signed approval draft text package submission: ${preflight.readyForManualSignedApprovalDraftTextPackageSubmission}`,
    `- Ready for offline signed approval draft text package comparison: ${preflight.readyForOfflineSignedApprovalDraftTextPackageComparison}`,
    `- Ready for offline signed approval draft text package review: ${preflight.readyForOfflineSignedApprovalDraftTextPackageReview}`,
    `- Ready for signed approval artifact draft: ${preflight.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${preflight.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${preflight.readyForOperatorValueSupply}`,
    `- Ready for operator value submission: ${preflight.readyForOperatorValueSubmission}`,
    `- Ready for evidence import: ${preflight.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${preflight.readyForRuntimePayload}`,
    `- Ready for live execution: ${preflight.readyForLiveExecution}`,
    `- Ready for production execution: ${preflight.readyForProductionExecution}`,
    `- Submission slot count: ${preflight.submissionSlotCount}`,
    `- Comparison control count: ${preflight.comparisonControlCount}`,
    `- Identity submission slot count: ${preflight.identitySubmissionSlotCount}`,
    `- Digest binding submission slot count: ${preflight.digestBindingSubmissionSlotCount}`,
    `- Signature envelope submission slot count: ${preflight.signatureEnvelopeSubmissionSlotCount}`,
    `- Source evidence submission slot count: ${preflight.sourceEvidenceSubmissionSlotCount}`,
    `- Value binding submission slot count: ${preflight.valueBindingSubmissionSlotCount}`,
    `- Policy submission slot count: ${preflight.policySubmissionSlotCount}`,
    `- Execution lock submission slot count: ${preflight.executionLockSubmissionSlotCount}`,
    `- Archive closeout submission slot count: ${preflight.archiveCloseoutSubmissionSlotCount}`,
    `- Digest mode submission slot count: ${preflight.digestModeSubmissionSlotCount}`,
    `- Ready submission slot count: ${preflight.readySubmissionSlotCount}`,
    `- Ready comparison control count: ${preflight.readyComparisonControlCount}`,
    `- Digest binding comparison control count: ${preflight.digestBindingComparisonControlCount}`,
    `- Signature envelope comparison control count: ${preflight.signatureEnvelopeComparisonControlCount}`,
    `- Policy comparison control count: ${preflight.policyComparisonControlCount}`,
    `- Execution lock comparison control count: ${preflight.executionLockComparisonControlCount}`,
    `- Archive closeout comparison control count: ${preflight.archiveCloseoutComparisonControlCount}`,
    `- Expected draft text package submission slot count: ${preflight.expectedDraftTextPackageSubmissionSlotCount}`,
    `- Actual draft text package submission count: ${preflight.actualDraftTextPackageSubmissionCount}`,
    `- Submitted draft text package count: ${preflight.submittedDraftTextPackageCount}`,
    `- Compared draft text package count: ${preflight.comparedDraftTextPackageCount}`,
    `- Accepted draft text package count: ${preflight.acceptedDraftTextPackageCount}`,
    `- Rejected draft text package count: ${preflight.rejectedDraftTextPackageCount}`,
    `- Signed draft text count: ${preflight.signedDraftTextCount}`,
    `- Draft signature payload count: ${preflight.draftSignaturePayloadCount}`,
    `- Approval captured: ${preflight.approvalCaptured}`,
    `- Approval grant present: ${preflight.approvalGrantPresent}`,
    `- Signed approval present: ${preflight.signedApprovalPresent}`,
    `- Source signed approval capture artifact draft text package review preflight digest: ${preflight.sourceSignedApprovalCaptureArtifactDraftTextPackageReviewPreflightDigest}`,
    `- Source signed approval capture artifact draft text package intake digest: ${preflight.sourceSignedApprovalCaptureArtifactDraftTextPackageIntakeDigest}`,
    `- Source signed approval capture artifact draft instruction preflight digest: ${preflight.sourceSignedApprovalCaptureArtifactDraftInstructionPreflightDigest}`,
    `- Source signed approval capture artifact draft authoring readiness digest: ${preflight.sourceSignedApprovalCaptureArtifactDraftAuthoringReadinessDigest}`,
    `- Source signed approval capture artifact draft review package preflight digest: ${preflight.sourceSignedApprovalCaptureArtifactDraftReviewPackagePreflightDigest}`,
    `- Source signed approval capture artifact draft readiness digest: ${preflight.sourceSignedApprovalCaptureArtifactDraftReadinessDigest}`,
    `- Source signed approval capture artifact draft preflight digest: ${preflight.sourceSignedApprovalCaptureArtifactDraftPreflightDigest}`,
    `- Source signed approval capture artifact preflight digest: ${preflight.sourceSignedApprovalCaptureArtifactPreflightDigest}`,
    `- Source signed approval capture preflight digest: ${preflight.sourceSignedApprovalCapturePreflightDigest}`,
    `- Source signed approval template digest: ${preflight.sourceSignedApprovalTemplateDigest}`,
    `- Source approval packet review digest: ${preflight.sourceApprovalPacketReviewDigest}`,
    `- Passed gates: ${preflight.passedGateCount}/${preflight.gateCount}`,
    `- Imports runtime payload: ${preflight.importsRuntimePayload}`,
    `- Accepts synthetic evidence: ${preflight.acceptsSyntheticEvidence}`,
    `- Contains secret value: ${preflight.containsSecretValue}`,
    `- Signed approval capture artifact draft text package submission preflight digest: ${preflight.signedApprovalCaptureArtifactDraftTextPackageSubmissionPreflightDigest}`,
    "",
    "## Gates",
    ...renderEntries(preflight.gates),
    "",
    "## Submission Slots",
    ...preflight.slots.flatMap(renderSlot),
    "## Comparison Controls",
    ...preflight.controls.flatMap(renderControl),
    "## Blocked Reasons",
    ...(preflight.blockedReasonCodes.length === 0
      ? ["- none"]
      : preflight.blockedReasonCodes.map((reason) => `- ${reason}`)),
  ].join("\n");
}

function renderSlot(
  slot:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageSubmissionPreflightSlot,
): string[] {
  return [
    `### ${slot.order}. ${slot.nodeVersion} ${slot.code}`,
    `- Submission slot name: ${slot.submissionSlotName}`,
    `- Kind: ${slot.kind}`,
    `- Slot mode: ${slot.slotMode}`,
    `- Source review criterion: ${slot.sourceReviewCriterionCode}`,
    `- Source review criterion ready: ${slot.sourceReviewCriterionReady}`,
    `- Source review criterion kind: ${slot.sourceReviewCriterionKind}`,
    `- Source review criterion mode: ${slot.sourceReviewCriterionMode}`,
    `- Source review criterion read-only: ${slot.sourceReviewCriterionReadOnly}`,
    `- Source review criterion materialized: ${slot.sourceReviewCriterionMaterialized}`,
    `- Source draft text package reviewed: ${slot.sourceDraftTextPackageReviewed}`,
    `- Source draft text package approved: ${slot.sourceDraftTextPackageApproved}`,
    `- Source draft text package rejected: ${slot.sourceDraftTextPackageRejected}`,
    `- Source signed draft text present: ${slot.sourceSignedDraftTextPresent}`,
    `- Source draft signature payload present: ${slot.sourceDraftSignaturePayloadPresent}`,
    `- Source approval grant present: ${slot.sourceApprovalGrantPresent}`,
    `- Source review control: ${slot.sourceReviewControlCode}`,
    `- Source review control ready: ${slot.sourceReviewControlReady}`,
    `- Source review control kind: ${slot.sourceReviewControlKind}`,
    `- Source review control read-only: ${slot.sourceReviewControlReadOnly}`,
    `- Source review control blocks draft text package review: ${slot.sourceReviewControlBlocksDraftTextPackageReview}`,
    `- Source review control blocks draft text package approval: ${slot.sourceReviewControlBlocksDraftTextPackageApproval}`,
    `- Source review control blocks signed draft text: ${slot.sourceReviewControlBlocksSignedDraftText}`,
    `- Source review control blocks signature payload: ${slot.sourceReviewControlBlocksSignaturePayload}`,
    `- Source review control blocks approval grant: ${slot.sourceReviewControlBlocksApprovalGrant}`,
    `- Source review control blocks runtime payload: ${slot.sourceReviewControlBlocksRuntimePayload}`,
    `- Source review control blocks writes: ${slot.sourceReviewControlBlocksWrites}`,
    `- Source review control blocks sibling mutation: ${slot.sourceReviewControlBlocksSiblingMutation}`,
    `- Expected shape: ${slot.expectedShape}`,
    `- Submission requirement: ${slot.submissionRequirement}`,
    `- Comparison question: ${slot.comparisonQuestion}`,
    `- Ready for manual signed approval draft text package submission slot: ${slot.readyForManualSignedApprovalDraftTextPackageSubmissionSlot}`,
    `- Submission slot materialized: ${slot.submissionSlotMaterialized}`,
    `- Draft text package submitted: ${slot.draftTextPackageSubmitted}`,
    `- Draft text package compared: ${slot.draftTextPackageCompared}`,
    `- Draft text package accepted: ${slot.draftTextPackageAccepted}`,
    `- Draft text package rejected: ${slot.draftTextPackageRejected}`,
    `- Signed draft text present: ${slot.signedDraftTextPresent}`,
    `- Draft signature payload present: ${slot.draftSignaturePayloadPresent}`,
    `- Approval grant present: ${slot.approvalGrantPresent}`,
    `- Writes allowed: ${slot.writesAllowed}`,
    `- Starts services: ${slot.startsServices}`,
    `- Mutates sibling state: ${slot.mutatesSiblingState}`,
    "",
  ];
}

function renderControl(
  control:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageSubmissionPreflightComparisonControl,
): string[] {
  return [
    `### ${control.order}. ${control.nodeVersion} ${control.code}`,
    `- Kind: ${control.kind}`,
    `- Source submission slot: ${control.sourceSubmissionSlotCode}`,
    `- Source submission slot ready: ${control.sourceSubmissionSlotReady}`,
    `- Source review control kind: ${control.sourceReviewControlKind}`,
    `- Guard code: ${control.guardCode}`,
    `- Guard text: ${control.guardText}`,
    `- Rejects unsubmitted slot: ${control.rejectsUnsubmittedSlot}`,
    `- Blocks draft text package submission: ${control.blocksDraftTextPackageSubmission}`,
    `- Blocks draft text package comparison: ${control.blocksDraftTextPackageComparison}`,
    `- Blocks draft text package acceptance: ${control.blocksDraftTextPackageAcceptance}`,
    `- Blocks signed draft text: ${control.blocksSignedDraftText}`,
    `- Blocks signature payload: ${control.blocksSignaturePayload}`,
    `- Blocks approval grant: ${control.blocksApprovalGrant}`,
    `- Blocks runtime payload: ${control.blocksRuntimePayload}`,
    `- Blocks writes: ${control.blocksWrites}`,
    `- Blocks sibling mutation: ${control.blocksSiblingMutation}`,
    `- Ready for manual signed approval draft text package comparison control: ${control.readyForManualSignedApprovalDraftTextPackageComparisonControl}`,
    `- Writes allowed: ${control.writesAllowed}`,
    `- Starts services: ${control.startsServices}`,
    `- Mutates sibling state: ${control.mutatesSiblingState}`,
    "",
  ];
}
