import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessContractProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessContractTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessContractMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessContractProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver disabled fake harness contract",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Contract state: ${profile.contractState}`,
    `- Ready for disabled fake harness contract: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessContract}`,
    `- Ready for Java v122 + mini-kv v127 echo: ${profile.readyForJavaV122MiniKvV127ParallelEcho}`,
    `- Fake harness runtime enabled: ${profile.fakeHarnessRuntimeEnabled}`,
    `- Runtime invocation allowed: ${profile.disabledFakeHarnessContract.runtimeInvocationAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v287",
    "",
    ...renderEntries(profile.sourceNodeV287),
    "",
    "## Disabled Fake Harness Contract",
    "",
    ...renderEntries({
      contractDigest: profile.disabledFakeHarnessContract.contractDigest,
      contractMode: profile.disabledFakeHarnessContract.contractMode,
      sourceSpan: profile.disabledFakeHarnessContract.sourceSpan,
      contractName: profile.disabledFakeHarnessContract.contractName,
      runtimeToggleName: profile.disabledFakeHarnessContract.runtimeToggleName,
      defaultRuntimeToggleValue: profile.disabledFakeHarnessContract.defaultRuntimeToggleValue,
      invocationState: profile.disabledFakeHarnessContract.invocationState,
      runtimeImplementationPresent: profile.disabledFakeHarnessContract.runtimeImplementationPresent,
      runtimeInvocationAllowed: profile.disabledFakeHarnessContract.runtimeInvocationAllowed,
    }),
    "",
    "## Required Inputs",
    "",
    ...renderList(profile.disabledFakeHarnessContract.requiredInputs, "No required inputs."),
    "",
    "## Allowed Outputs",
    "",
    ...renderList(profile.disabledFakeHarnessContract.allowedOutputs, "No allowed outputs."),
    "",
    "## Prohibited Inputs",
    "",
    ...renderList(profile.disabledFakeHarnessContract.prohibitedInputs, "No prohibited inputs."),
    "",
    "## Required Artifacts",
    "",
    ...renderList(profile.disabledFakeHarnessContract.requiredArtifacts, "No required artifacts."),
    "",
    "## Contract Assertions",
    "",
    ...renderList(profile.disabledFakeHarnessContract.contractAssertions, "No contract assertions."),
    "",
    "## Prohibited Actions",
    "",
    ...renderList(profile.disabledFakeHarnessContract.prohibitedActions, "No prohibited actions."),
    "",
    "## Boundary Summary",
    "",
    ...renderEntries({
      credentialHandleOnly: profile.disabledFakeHarnessContract.credentialBoundary.credentialHandleOnly,
      credentialValueRead: profile.disabledFakeHarnessContract.credentialBoundary.credentialValueRead,
      credentialValueProvided: profile.disabledFakeHarnessContract.credentialBoundary.credentialValueProvided,
      endpointHandleOnly: profile.disabledFakeHarnessContract.endpointBoundary.endpointHandleOnly,
      rawEndpointUrlParsed: profile.disabledFakeHarnessContract.endpointBoundary.rawEndpointUrlParsed,
      rawEndpointUrlRendered: profile.disabledFakeHarnessContract.endpointBoundary.rawEndpointUrlRendered,
      realSecretProviderInstantiated:
        profile.disabledFakeHarnessContract.providerClientBoundary.realSecretProviderInstantiated,
      realResolverClientInstantiated:
        profile.disabledFakeHarnessContract.providerClientBoundary.realResolverClientInstantiated,
      fakeSecretProviderInstantiated:
        profile.disabledFakeHarnessContract.providerClientBoundary.fakeSecretProviderInstantiated,
      fakeResolverClientInstantiated:
        profile.disabledFakeHarnessContract.providerClientBoundary.fakeResolverClientInstantiated,
      externalRequestSent: profile.disabledFakeHarnessContract.networkBoundary.externalRequestSent,
      connectsManagedAudit: profile.disabledFakeHarnessContract.networkBoundary.connectsManagedAudit,
      executionAllowed: profile.disabledFakeHarnessContract.writeBoundary.executionAllowed,
      schemaMigrationExecuted: profile.disabledFakeHarnessContract.writeBoundary.schemaMigrationExecuted,
      approvalLedgerWritten: profile.disabledFakeHarnessContract.writeBoundary.approvalLedgerWritten,
      automaticUpstreamStart: profile.disabledFakeHarnessContract.autoStartBoundary.automaticUpstreamStart,
    }),
    "",
    "## Upstream Echo Requirement",
    "",
    ...renderEntries(profile.upstreamEchoRequirement),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No disabled fake harness contract blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No disabled fake harness contract warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No disabled fake harness contract recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
