import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvDeclaredOperatorLifecycleRuntimeLiveReadGatePlanProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvDeclaredOperatorLifecycleRuntimeLiveReadGatePlanTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvDeclaredOperatorLifecycleRuntimeLiveReadGatePlanMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvDeclaredOperatorLifecycleRuntimeLiveReadGatePlanProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Plan state: ${profile.planState}`,
    `- Plan decision: ${profile.planDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for Node v391 archive verification: ${profile.readyForNodeV391ArchiveVerification}`,
    `- Ready for runtime live-read gate: ${profile.readyForRuntimeLiveReadGate}`,
    `- Runtime gate plan only: ${profile.runtimeGatePlanOnly}`,
    `- Operator approval record required: ${profile.operatorApprovalRecordRequired}`,
    `- Concrete loopback ports required: ${profile.concreteLoopbackPortsRequired}`,
    `- GET-only smoke command required: ${profile.getOnlySmokeCommandRequired}`,
    `- Cleanup proof required: ${profile.cleanupProofRequired}`,
    `- Runtime gate approval present: ${profile.runtimeGateApprovalPresent}`,
    `- Concrete loopback ports assigned: ${profile.concreteLoopbackPortsAssigned}`,
    `- Live read gate allowed: ${profile.liveReadGateAllowed}`,
    `- Runtime probe allowed: ${profile.runtimeProbeAllowed}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Stops Java service: ${profile.stopsJavaService}`,
    `- Stops mini-kv service: ${profile.stopsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Active shard prototype enabled: ${profile.activeShardPrototypeEnabled}`,
    "",
    "## Source Node v389",
    "",
    ...renderEntries(profile.sourceNodeV389),
    "",
    "## Source Node v389 Replay",
    "",
    ...renderEntries(profile.sourceNodeV389Replay),
    "",
    "## Source Node v388 Replay",
    "",
    ...renderEntries(profile.sourceNodeV388Replay),
    "",
    "## Runtime Live Read Gate Plan",
    "",
    ...renderEntries(profile.runtimeGatePlan),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
