import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionSandboxEndpointHandlePreflightReviewProfile,
} from "./managedAuditManualSandboxConnectionSandboxEndpointHandlePreflightReviewTypes.js";

export function renderManagedAuditManualSandboxConnectionSandboxEndpointHandlePreflightReviewMarkdown(
  profile: ManagedAuditManualSandboxConnectionSandboxEndpointHandlePreflightReviewProfile,
): string {
  return [
    "# Managed audit manual sandbox connection sandbox endpoint handle preflight review",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Review state: ${profile.reviewState}`,
    `- Ready for endpoint handle preflight review: ${profile.readyForManagedAuditManualSandboxConnectionSandboxEndpointHandlePreflightReview}`,
    `- Ready for sandbox adapter connection: ${profile.readyForManagedAuditSandboxAdapterConnection}`,
    "",
    "## Source Node v257",
    "",
    ...renderEntries(profile.sourceNodeV257),
    "",
    "## Preflight Review",
    "",
    ...renderEntries(profile.preflightReview),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No sandbox endpoint handle preflight review blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No sandbox endpoint handle preflight review warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No sandbox endpoint handle preflight review recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
