import { renderEntries } from "./liveProbeReportUtils.js";
import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageReviewPreflight,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageReviewPreflightControl,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageReviewPreflightCriterion,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageReviewPreflightTypes.js";
import {
  renderVerificationBlockedReasonLines,
  renderVerificationReportMarkdown,
  trimVerificationTrailingBlankLine,
} from "./verificationReportBuilder.js";

export function renderControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageReviewPreflightMarkdown(
  preflight:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageReviewPreflight,
): string {
  return renderVerificationReportMarkdown({
    title: "Controlled read-only shard preview live read-only window operator evidence value supply signed approval capture artifact draft text package review preflight",
    meta: [
      ["Signed approval capture artifact draft text package review preflight version", `${preflight.signedApprovalCaptureArtifactDraftTextPackageReviewPreflightVersion}`],
      ["Source signed approval capture artifact draft text package intake version", `${preflight.sourceSignedApprovalCaptureArtifactDraftTextPackageIntakeVersion}`],
      ["Artifact draft text package review preflight state", `${preflight.artifactDraftTextPackageReviewPreflightState}`],
      ["Ready for signed approval artifact draft text package review preflight", `${preflight.readyForSignedApprovalArtifactDraftTextPackageReviewPreflight}`],
      ["Ready for offline signed approval draft text package review", `${preflight.readyForOfflineSignedApprovalDraftTextPackageReview}`],
      ["Ready for human signed approval draft text package submission", `${preflight.readyForHumanSignedApprovalDraftTextPackageSubmission}`],
      ["Ready for signed approval artifact draft", `${preflight.readyForSignedApprovalArtifactDraft}`],
      ["Ready for signed approval capture", `${preflight.readyForSignedApprovalCapture}`],
      ["Ready for operator value supply", `${preflight.readyForOperatorValueSupply}`],
      ["Ready for operator value submission", `${preflight.readyForOperatorValueSubmission}`],
      ["Ready for evidence import", `${preflight.readyForEvidenceImport}`],
      ["Ready for runtime payload", `${preflight.readyForRuntimePayload}`],
      ["Ready for live execution", `${preflight.readyForLiveExecution}`],
      ["Ready for production execution", `${preflight.readyForProductionExecution}`],
      ["Review criterion count", `${preflight.reviewCriterionCount}`],
      ["Review control count", `${preflight.reviewControlCount}`],
      ["Identity review criterion count", `${preflight.identityReviewCriterionCount}`],
      ["Digest binding review criterion count", `${preflight.digestBindingReviewCriterionCount}`],
      ["Signature envelope review criterion count", `${preflight.signatureEnvelopeReviewCriterionCount}`],
      ["Source evidence review criterion count", `${preflight.sourceEvidenceReviewCriterionCount}`],
      ["Value binding review criterion count", `${preflight.valueBindingReviewCriterionCount}`],
      ["Policy review criterion count", `${preflight.policyReviewCriterionCount}`],
      ["Execution lock review criterion count", `${preflight.executionLockReviewCriterionCount}`],
      ["Archive closeout review criterion count", `${preflight.archiveCloseoutReviewCriterionCount}`],
      ["Digest mode review criterion count", `${preflight.digestModeReviewCriterionCount}`],
      ["Ready review criterion count", `${preflight.readyReviewCriterionCount}`],
      ["Ready review control count", `${preflight.readyReviewControlCount}`],
      ["Digest binding review control count", `${preflight.digestBindingReviewControlCount}`],
      ["Signature envelope review control count", `${preflight.signatureEnvelopeReviewControlCount}`],
      ["Policy review control count", `${preflight.policyReviewControlCount}`],
      ["Execution lock review control count", `${preflight.executionLockReviewControlCount}`],
      ["Archive closeout review control count", `${preflight.archiveCloseoutReviewControlCount}`],
      ["Expected draft text package field count", `${preflight.expectedDraftTextPackageFieldCount}`],
      ["Actual draft text package field count", `${preflight.actualDraftTextPackageFieldCount}`],
      ["Accepted draft text package count", `${preflight.acceptedDraftTextPackageCount}`],
      ["Reviewed draft text package count", `${preflight.reviewedDraftTextPackageCount}`],
      ["Approved draft text package count", `${preflight.approvedDraftTextPackageCount}`],
      ["Rejected draft text package count", `${preflight.rejectedDraftTextPackageCount}`],
      ["Signed draft text count", `${preflight.signedDraftTextCount}`],
      ["Draft signature payload count", `${preflight.draftSignaturePayloadCount}`],
      ["Approval captured", `${preflight.approvalCaptured}`],
      ["Approval grant present", `${preflight.approvalGrantPresent}`],
      ["Signed approval present", `${preflight.signedApprovalPresent}`],
      ["Source signed approval capture artifact draft text package intake digest", `${preflight.sourceSignedApprovalCaptureArtifactDraftTextPackageIntakeDigest}`],
      ["Source signed approval capture artifact draft instruction preflight digest", `${preflight.sourceSignedApprovalCaptureArtifactDraftInstructionPreflightDigest}`],
      ["Source signed approval capture artifact draft authoring readiness digest", `${preflight.sourceSignedApprovalCaptureArtifactDraftAuthoringReadinessDigest}`],
      ["Source signed approval capture artifact draft review package preflight digest", `${preflight.sourceSignedApprovalCaptureArtifactDraftReviewPackagePreflightDigest}`],
      ["Source signed approval capture artifact draft readiness digest", `${preflight.sourceSignedApprovalCaptureArtifactDraftReadinessDigest}`],
      ["Source signed approval capture artifact draft preflight digest", `${preflight.sourceSignedApprovalCaptureArtifactDraftPreflightDigest}`],
      ["Source signed approval capture artifact preflight digest", `${preflight.sourceSignedApprovalCaptureArtifactPreflightDigest}`],
      ["Source signed approval capture preflight digest", `${preflight.sourceSignedApprovalCapturePreflightDigest}`],
      ["Source signed approval template digest", `${preflight.sourceSignedApprovalTemplateDigest}`],
      ["Source approval packet review digest", `${preflight.sourceApprovalPacketReviewDigest}`],
      ["Passed gates", `${preflight.passedGateCount}/${preflight.gateCount}`],
      ["Imports runtime payload", `${preflight.importsRuntimePayload}`],
      ["Accepts synthetic evidence", `${preflight.acceptsSyntheticEvidence}`],
      ["Contains secret value", `${preflight.containsSecretValue}`],
      ["Signed approval capture artifact draft text package review preflight digest", `${preflight.signedApprovalCaptureArtifactDraftTextPackageReviewPreflightDigest}`],
    ],
    trailingNewline: false,
    sections: [
      {
        heading: "Gates",
        lines: renderEntries(preflight.gates),
        bodyLeadingBlankLine: false,
      },
      {
        heading: "Review Criteria",
        lines: trimVerificationTrailingBlankLine(preflight.criteria.flatMap(renderCriterion)),
        bodyLeadingBlankLine: false,
      },
      {
        heading: "Review Controls",
        lines: trimVerificationTrailingBlankLine(preflight.controls.flatMap(renderControl)),
        bodyLeadingBlankLine: false,
      },
      {
        heading: "Blocked Reasons",
        lines: renderVerificationBlockedReasonLines(preflight.blockedReasonCodes),
        bodyLeadingBlankLine: false,
      },
    ],
  });
}

function renderCriterion(
  criterion:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageReviewPreflightCriterion,
): string[] {
  return [
    `### ${criterion.order}. ${criterion.nodeVersion} ${criterion.code}`,
    `- Review criterion name: ${criterion.reviewCriterionName}`,
    `- Kind: ${criterion.kind}`,
    `- Criterion mode: ${criterion.criterionMode}`,
    `- Source intake field: ${criterion.sourceIntakeFieldCode}`,
    `- Source intake field ready: ${criterion.sourceIntakeFieldReady}`,
    `- Source intake field kind: ${criterion.sourceIntakeFieldKind}`,
    `- Source intake field mode: ${criterion.sourceIntakeFieldMode}`,
    `- Source intake field read-only: ${criterion.sourceIntakeFieldReadOnly}`,
    `- Source draft text package field materialized: ${criterion.sourceDraftTextPackageFieldMaterialized}`,
    `- Source draft text package accepted: ${criterion.sourceDraftTextPackageAccepted}`,
    `- Source signed draft text present: ${criterion.sourceSignedDraftTextPresent}`,
    `- Source draft signature payload present: ${criterion.sourceDraftSignaturePayloadPresent}`,
    `- Source approval grant present: ${criterion.sourceApprovalGrantPresent}`,
    `- Source intake guard: ${criterion.sourceIntakeGuardCode}`,
    `- Source intake guard ready: ${criterion.sourceIntakeGuardReady}`,
    `- Source intake guard kind: ${criterion.sourceIntakeGuardKind}`,
    `- Source intake guard read-only: ${criterion.sourceIntakeGuardReadOnly}`,
    `- Source intake guard blocks draft text package acceptance: ${criterion.sourceIntakeGuardBlocksDraftTextPackageAcceptance}`,
    `- Source intake guard blocks signed draft text: ${criterion.sourceIntakeGuardBlocksSignedDraftText}`,
    `- Source intake guard blocks signature payload: ${criterion.sourceIntakeGuardBlocksSignaturePayload}`,
    `- Source intake guard blocks approval grant: ${criterion.sourceIntakeGuardBlocksApprovalGrant}`,
    `- Source intake guard blocks runtime payload: ${criterion.sourceIntakeGuardBlocksRuntimePayload}`,
    `- Source intake guard blocks writes: ${criterion.sourceIntakeGuardBlocksWrites}`,
    `- Source intake guard blocks sibling mutation: ${criterion.sourceIntakeGuardBlocksSiblingMutation}`,
    `- Expected shape: ${criterion.expectedShape}`,
    `- Review purpose: ${criterion.reviewPurpose}`,
    `- Review question: ${criterion.reviewQuestion}`,
    `- Ready for offline signed approval draft text package review criterion: ${criterion.readyForOfflineSignedApprovalDraftTextPackageReviewCriterion}`,
    `- Review criterion materialized: ${criterion.reviewCriterionMaterialized}`,
    `- Draft text package reviewed: ${criterion.draftTextPackageReviewed}`,
    `- Draft text package approved: ${criterion.draftTextPackageApproved}`,
    `- Draft text package rejected: ${criterion.draftTextPackageRejected}`,
    `- Signed draft text present: ${criterion.signedDraftTextPresent}`,
    `- Draft signature payload present: ${criterion.draftSignaturePayloadPresent}`,
    `- Approval grant present: ${criterion.approvalGrantPresent}`,
    `- Ready for signed approval artifact draft: ${criterion.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${criterion.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${criterion.readyForOperatorValueSupply}`,
    `- Ready for evidence import: ${criterion.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${criterion.readyForRuntimePayload}`,
    `- Writes allowed: ${criterion.writesAllowed}`,
    `- Starts services: ${criterion.startsServices}`,
    `- Mutates sibling state: ${criterion.mutatesSiblingState}`,
    "",
  ];
}

function renderControl(
  control:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageReviewPreflightControl,
): string[] {
  return [
    `### ${control.order}. ${control.nodeVersion} ${control.code}`,
    `- Kind: ${control.kind}`,
    `- Source review criterion: ${control.sourceReviewCriterionCode}`,
    `- Source review criterion ready: ${control.sourceReviewCriterionReady}`,
    `- Source intake guard kind: ${control.sourceIntakeGuardKind}`,
    `- Guard code: ${control.guardCode}`,
    `- Guard text: ${control.guardText}`,
    `- Rejects unreviewable criterion: ${control.rejectsUnreviewableCriterion}`,
    `- Blocks draft text package review: ${control.blocksDraftTextPackageReview}`,
    `- Blocks draft text package approval: ${control.blocksDraftTextPackageApproval}`,
    `- Blocks signed draft text: ${control.blocksSignedDraftText}`,
    `- Blocks signature payload: ${control.blocksSignaturePayload}`,
    `- Blocks approval grant: ${control.blocksApprovalGrant}`,
    `- Blocks runtime payload: ${control.blocksRuntimePayload}`,
    `- Blocks writes: ${control.blocksWrites}`,
    `- Blocks sibling mutation: ${control.blocksSiblingMutation}`,
    `- Ready for offline signed approval draft text package review control: ${control.readyForOfflineSignedApprovalDraftTextPackageReviewControl}`,
    `- Ready for signed approval artifact draft: ${control.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${control.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${control.readyForOperatorValueSupply}`,
    `- Ready for evidence import: ${control.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${control.readyForRuntimePayload}`,
    `- Writes allowed: ${control.writesAllowed}`,
    `- Starts services: ${control.startsServices}`,
    `- Mutates sibling state: ${control.mutatesSiblingState}`,
    "",
  ];
}
