import { renderEntries } from "./liveProbeReportUtils.js";
import type { ControlledReadOnlyShardPreviewProfile } from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewTypes.js";

export function renderControlledReadOnlyShardPreviewHandoffRouteCoverageSections(
  profile: ControlledReadOnlyShardPreviewProfile,
): string[] {
  return [
    "## Source Matrix Handoff Route Coverage",
    `- Coverage version: ${profile.preview.sourceMatrixHandoffRouteCoverage.coverageVersion}`,
    `- Input verification version: ${profile.preview.sourceMatrixHandoffRouteCoverage.inputVerificationVersion}`,
    `- Coverage state: ${profile.preview.sourceMatrixHandoffRouteCoverage.coverageState}`,
    `- Ready for read-only handoff route coverage: ${profile.preview.sourceMatrixHandoffRouteCoverage.readyForReadOnlyHandoffRouteCoverage}`,
    `- Route surface: ${profile.preview.sourceMatrixHandoffRouteCoverage.routeSurface}`,
    `- Verification state: ${profile.preview.sourceMatrixHandoffRouteCoverage.verificationState}`,
    `- Covered sections: ${profile.preview.sourceMatrixHandoffRouteCoverage.coveredSections.join(", ")}`,
    `- Covered section count: ${profile.preview.sourceMatrixHandoffRouteCoverage.coveredSectionCount}`,
    `- Coverage digest: ${profile.preview.sourceMatrixHandoffRouteCoverage.coverageDigest.value}`,
    `- Coverage digest scope: ${profile.preview.sourceMatrixHandoffRouteCoverage.coverageDigest.scope}`,
    `- Coverage digest covered section count: ${profile.preview.sourceMatrixHandoffRouteCoverage.coverageDigest.coveredSectionCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverage.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverage.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverage.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverage.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverage.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Route Coverage Verification",
    `- Verification version: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.verificationVersion}`,
    `- Input coverage version: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.inputCoverageVersion}`,
    `- Verification state: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.verificationState}`,
    `- Ready for read-only handoff route coverage verification: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.readyForReadOnlyHandoffRouteCoverageVerification}`,
    `- Gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.passedGateCount}`,
    `- Blocked reason codes: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.blockedReasonCodes.join(", ") || "none"}`,
    `- Coverage digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.coverageDigestValue}`,
    `- Covered section count: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.coveredSectionCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageVerification.mutatesSiblingState}`,
    "",
    "### Handoff Route Coverage Verification Gates",
    ...renderEntries(profile.preview.sourceMatrixHandoffRouteCoverageVerification.gates),
    "",
    "## Source Matrix Handoff Route Coverage Archive Snapshot",
    `- Snapshot version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.snapshotVersion}`,
    `- Input verification version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.inputVerificationVersion}`,
    `- Snapshot state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.snapshotState}`,
    `- Ready for read-only handoff route coverage archive: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.readyForReadOnlyHandoffRouteCoverageArchive}`,
    `- Coverage digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.coverageDigestValue}`,
    `- Snapshot digest: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.snapshotDigest.value}`,
    `- Snapshot digest scope: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.snapshotDigest.scope}`,
    `- Snapshot digest covered section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.snapshotDigest.coveredSectionCount}`,
    `- Archived sections: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.archivedSections.join(", ")}`,
    `- Archived section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.archivedSectionCount}`,
    `- Verification gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.verificationGateCount}`,
    `- Verification passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.verificationPassedGateCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSnapshot.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Route Coverage Archive Verification",
    `- Verification version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.verificationVersion}`,
    `- Input snapshot version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.inputSnapshotVersion}`,
    `- Verification state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.verificationState}`,
    `- Ready for read-only handoff route coverage archive verification: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.readyForReadOnlyHandoffRouteCoverageArchiveVerification}`,
    `- Gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.passedGateCount}`,
    `- Blocked reason codes: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.blockedReasonCodes.join(", ") || "none"}`,
    `- Snapshot digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.snapshotDigestValue}`,
    `- Archived section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.archivedSectionCount}`,
    `- Verification gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.verificationGateCount}`,
    `- Verification passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.verificationPassedGateCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.mutatesSiblingState}`,
    "",
    "### Handoff Route Coverage Archive Verification Gates",
    ...renderEntries(profile.preview.sourceMatrixHandoffRouteCoverageArchiveVerification.gates),
    "",
    "## Source Matrix Handoff Route Coverage Archive Summary",
    `- Summary version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryVersion}`,
    `- Input verification version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.inputVerificationVersion}`,
    `- Summary state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryState}`,
    `- Ready for read-only handoff route coverage archive summary: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.readyForReadOnlyHandoffRouteCoverageArchiveSummary}`,
    `- Verification state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.verificationState}`,
    `- Snapshot digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.snapshotDigestValue}`,
    `- Summary digest: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryDigest.value}`,
    `- Summary digest scope: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryDigest.scope}`,
    `- Summary digest covered line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryDigest.coveredLineCount}`,
    `- Summary lines: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryLines.join("; ")}`,
    `- Summary line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.summaryLineCount}`,
    `- Gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.passedGateCount}`,
    `- Archived section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.archivedSectionCount}`,
    `- Blocked reason count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.blockedReasonCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummary.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Route Coverage Archive Summary Receipt",
    `- Receipt version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptVersion}`,
    `- Input summary version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.inputSummaryVersion}`,
    `- Receipt state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptState}`,
    `- Ready for read-only handoff route coverage archive summary receipt: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.readyForReadOnlyHandoffRouteCoverageArchiveSummaryReceipt}`,
    `- Summary state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.summaryState}`,
    `- Summary digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.summaryDigestValue}`,
    `- Receipt digest: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptDigest.value}`,
    `- Receipt digest scope: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptDigest.scope}`,
    `- Receipt digest covered summary line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptDigest.coveredSummaryLineCount}`,
    `- Receipt digest covered blocked reason count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptDigest.coveredBlockedReasonCount}`,
    `- Receipt lines: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptLines.join("; ")}`,
    `- Receipt line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.receiptLineCount}`,
    `- Summary line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.summaryLineCount}`,
    `- Gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.passedGateCount}`,
    `- Blocked reason count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.blockedReasonCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceipt.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Route Coverage Archive Summary Receipt Archive Snapshot",
    `- Snapshot version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.snapshotVersion}`,
    `- Input receipt version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.inputReceiptVersion}`,
    `- Snapshot state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.snapshotState}`,
    `- Ready for read-only handoff route coverage archive summary receipt archive: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.readyForReadOnlyHandoffRouteCoverageArchiveSummaryReceiptArchive}`,
    `- Receipt digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.receiptDigestValue}`,
    `- Snapshot digest: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.snapshotDigest.value}`,
    `- Snapshot digest scope: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.snapshotDigest.scope}`,
    `- Snapshot digest covered section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.snapshotDigest.coveredSectionCount}`,
    `- Archived sections: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.archivedSections.join(", ")}`,
    `- Archived section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.archivedSectionCount}`,
    `- Receipt line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.receiptLineCount}`,
    `- Summary line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.summaryLineCount}`,
    `- Blocked reason count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.blockedReasonCount}`,
    `- Includes raw credential: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.includesRawCredential}`,
    `- Includes runtime payload: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.includesRuntimePayload}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveSnapshot.mutatesSiblingState}`,
    "",
    "## Source Matrix Handoff Route Coverage Archive Summary Receipt Archive Verification",
    `- Verification version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.verificationVersion}`,
    `- Input snapshot version: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.inputSnapshotVersion}`,
    `- Verification state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.verificationState}`,
    `- Ready for read-only handoff route coverage archive summary receipt archive verification: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.readyForReadOnlyHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification}`,
    `- Gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.gateCount}`,
    `- Passed gate count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.passedGateCount}`,
    `- Blocked reason codes: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.blockedReasonCodes.join(", ") || "none"}`,
    `- Snapshot digest value: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.snapshotDigestValue}`,
    `- Archived section count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.archivedSectionCount}`,
    `- Receipt line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.receiptLineCount}`,
    `- Summary line count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.summaryLineCount}`,
    `- Blocked reason count: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.blockedReasonCount}`,
    `- Requires approval: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.requiresApproval}`,
    `- Requires routing activation: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.requiresRoutingActivation}`,
    `- Requires fresh sibling evidence: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.requiresFreshSiblingEvidence}`,
    `- Starts services: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.startsServices}`,
    `- Mutates sibling state: ${profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.mutatesSiblingState}`,
    "",
    "### Handoff Route Coverage Archive Summary Receipt Archive Verification Gates",
    ...renderEntries(profile.preview.sourceMatrixHandoffRouteCoverageArchiveSummaryReceiptArchiveVerification.gates),
    "",
  ];
}
