import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionPassEvidenceCloseoutProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionPassEvidenceCloseoutTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionPassEvidenceCloseoutMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionPassEvidenceCloseoutProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Closeout state: ${profile.closeoutState}`,
    `- Closeout decision: ${profile.closeoutDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for pass evidence closeout: ${profile.readyForRuntimeExecutionPassEvidenceCloseout}`,
    `- Ready for runtime execution chain handoff: ${profile.readyForRuntimeExecutionChainHandoff}`,
    `- Closeout only: ${profile.closeoutOnly}`,
    `- Reruns smoke: ${profile.rerunsSmoke}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Java / mini-kv recommended parallel: ${profile.javaMiniKvRecommendedParallel}`,
    "",
    "## Archive References",
    "",
    ...profile.archiveReferences.flatMap((reference) => renderEntries(reference)),
    "",
    "## Closeout",
    "",
    ...renderEntries(profile.closeout),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
