import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  JavaV136RuntimeShellPostDecisionPlanIntakeEchoReference,
  ManagedAuditManualSandboxConnectionCredentialResolverRuntimeShellPostDecisionPlanIntakeUpstreamEchoVerificationProfile,
  MiniKvV133RuntimeShellPostDecisionPlanIntakeNonParticipationReceiptReference,
} from "./managedAuditManualSandboxConnectionCredentialResolverRuntimeShellPostDecisionPlanIntakeUpstreamEchoVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverRuntimeShellPostDecisionPlanIntakeUpstreamEchoVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverRuntimeShellPostDecisionPlanIntakeUpstreamEchoVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver runtime shell post-decision plan intake upstream echo verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Verification state: ${profile.verificationState}`,
    `- Ready for upstream echo verification: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverRuntimeShellPostDecisionPlanIntakeUpstreamEchoVerification}`,
    `- Active Node verification version: ${profile.activeNodeVerificationVersion}`,
    `- Legacy Node v302 consumer marker accepted: ${profile.legacyNodeV302ConsumerMarkerAccepted}`,
    `- Runtime shell implemented: ${profile.runtimeShellImplemented}`,
    `- Runtime shell invocation allowed: ${profile.runtimeShellInvocationAllowed}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v301",
    "",
    ...renderEntries(profile.sourceNodeV301),
    "",
    "## Source Node v302",
    "",
    ...renderEntries(profile.sourceNodeV302),
    "",
    "## Java v136 Echo",
    "",
    ...renderJavaReference(profile.upstreamEvidence.javaV136),
    "",
    "## mini-kv v133 Receipt",
    "",
    ...renderMiniKvReference(profile.upstreamEvidence.miniKvV133),
    "",
    "## Echo Verification",
    "",
    ...renderEntries(profile.echoVerification),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No post-decision plan intake upstream echo verification blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No post-decision plan intake upstream echo verification warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No post-decision plan intake upstream echo verification recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderJavaReference(reference: JavaV136RuntimeShellPostDecisionPlanIntakeEchoReference): string[] {
  return [
    ...renderEntries({
      sourceVersion: reference.sourceVersion,
      receiptVersion: reference.receiptVersion,
      echoMode: reference.echoMode,
      sourceSpan: reference.sourceSpan,
      legacyNextNodeVersion: reference.legacyNextNodeVersion,
      evidencePresent: reference.evidencePresent,
      verificationDocumented: reference.verificationDocumented,
      legacyReadyForNodeV302: reference.legacyReadyForNodeV302,
      echoesNodeV301PlanIntake: reference.echoesNodeV301PlanIntake,
      selectedContinuationDecisionEchoed: reference.selectedContinuationDecisionEchoed,
      continuationOptionsEchoed: reference.continuationOptionsEchoed,
      necessityProofEchoed: reference.necessityProofEchoed,
      runtimeImplementationRejectedEchoed: reference.runtimeImplementationRejectedEchoed,
      sideEffectBoundariesClosed: reference.sideEffectBoundariesClosed,
    }),
    "",
    "### Evidence Files",
    "",
    ...renderList(
      reference.evidenceFiles.map((file) => `${file.id}: exists=${file.exists}; size=${file.sizeBytes}; resolved=${file.resolvedPath}`),
      "No Java evidence files.",
    ),
    "",
    "### Expected Snippets",
    "",
    ...renderList(
      reference.expectedSnippets.map((snippet) => `${snippet.id}: matched=${snippet.matched}; resolved=${snippet.resolvedPath}`),
      "No Java expected snippets.",
    ),
  ];
}

function renderMiniKvReference(reference: MiniKvV133RuntimeShellPostDecisionPlanIntakeNonParticipationReceiptReference): string[] {
  return [
    ...renderEntries({
      sourceVersion: reference.sourceVersion,
      receiptVersion: reference.receiptVersion,
      releaseVersion: reference.releaseVersion,
      consumerHint: reference.consumerHint,
      receiptDigest: reference.receiptDigest,
      evidencePresent: reference.evidencePresent,
      verificationDocumented: reference.verificationDocumented,
      legacyReadyForNodeV302: reference.legacyReadyForNodeV302,
      echoesNodeV301PlanIntake: reference.echoesNodeV301PlanIntake,
      planIntakeState: reference.planIntakeState,
      selectedContinuationDecision: reference.selectedContinuationDecision,
      nonParticipationReceiptOnly: reference.nonParticipationReceiptOnly,
      sideEffectBoundariesClosed: reference.sideEffectBoundariesClosed,
    }),
    "",
    "### Evidence Files",
    "",
    ...renderList(
      reference.evidenceFiles.map((file) => `${file.id}: exists=${file.exists}; size=${file.sizeBytes}; resolved=${file.resolvedPath}`),
      "No mini-kv evidence files.",
    ),
    "",
    "### Expected Snippets",
    "",
    ...renderList(
      reference.expectedSnippets.map((snippet) => `${snippet.id}: matched=${snippet.matched}; resolved=${snippet.resolvedPath}`),
      "No mini-kv expected snippets.",
    ),
  ];
}
