import { renderEntries } from "./liveProbeReportUtils.js";
import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReviewControl,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReviewTypes.js";

export function renderControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReviewMarkdown(
  review: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReview,
): string {
  return [
    "# Controlled read-only shard preview live read-only window operator evidence value supply approval packet review",
    "",
    `- Approval packet review version: ${review.approvalPacketReviewVersion}`,
    `- Source approval packet draft version: ${review.sourceApprovalPacketDraftVersion}`,
    `- Review package state: ${review.reviewPackageState}`,
    `- Ready for value supply approval packet review: ${review.readyForValueSupplyApprovalPacketReview}`,
    `- Ready for signed approval capture: ${review.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${review.readyForOperatorValueSupply}`,
    `- Ready for operator value submission: ${review.readyForOperatorValueSubmission}`,
    `- Ready for evidence import: ${review.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${review.readyForRuntimePayload}`,
    `- Ready for live execution: ${review.readyForLiveExecution}`,
    `- Ready for production execution: ${review.readyForProductionExecution}`,
    `- Review control count: ${review.reviewControlCount}`,
    `- Approval field review control count: ${review.approvalFieldReviewControlCount}`,
    `- Policy review control count: ${review.policyReviewControlCount}`,
    `- Source evidence review control count: ${review.sourceEvidenceReviewControlCount}`,
    `- Execution lock review control count: ${review.executionLockReviewControlCount}`,
    `- Closeout review control count: ${review.closeoutReviewControlCount}`,
    `- Manual review required control count: ${review.manualReviewRequiredControlCount}`,
    `- Auto approval blocked control count: ${review.autoApprovalBlockedControlCount}`,
    `- Required approval field covered count: ${review.requiredApprovalFieldCoveredCount}`,
    `- Required review record field covered count: ${review.requiredReviewRecordFieldCoveredCount}`,
    `- Policy requirement satisfied count: ${review.policyRequirementSatisfiedCount}`,
    `- Acceptance criterion count: ${review.acceptanceCriterionCount}`,
    `- Supplied value count: ${review.suppliedValueCount}`,
    `- Accepted value count: ${review.acceptedValueCount}`,
    `- Imported value count: ${review.importedValueCount}`,
    `- Approval captured: ${review.approvalCaptured}`,
    `- Approval grant present: ${review.approvalGrantPresent}`,
    `- Signed approval present: ${review.signedApprovalPresent}`,
    `- Operator identity present: ${review.operatorIdentityPresent}`,
    `- Approval timestamp present: ${review.approvalTimestampPresent}`,
    `- Source approval packet draft digest: ${review.sourceApprovalPacketDraftDigest}`,
    `- Passed gates: ${review.passedGateCount}/${review.gateCount}`,
    `- Imports runtime payload: ${review.importsRuntimePayload}`,
    `- Accepts synthetic evidence: ${review.acceptsSyntheticEvidence}`,
    `- Contains secret value: ${review.containsSecretValue}`,
    `- Approval packet review digest: ${review.approvalPacketReviewDigest}`,
    "",
    "## Gates",
    ...renderEntries(review.gates),
    "",
    "## Controls",
    ...review.controls.flatMap(renderControl),
    "## Blocked Reasons",
    ...(review.blockedReasonCodes.length === 0
      ? ["- none"]
      : review.blockedReasonCodes.map((reason) => `- ${reason}`)),
  ].join("\n");
}

function renderControl(
  control: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplyApprovalPacketReviewControl,
): string[] {
  return [
    `### ${control.order}. ${control.nodeVersion} ${control.code}`,
    `- Kind: ${control.kind}`,
    `- Scope: ${control.scope}`,
    `- Project: ${control.project}`,
    `- Source approval packet draft slot: ${control.sourceApprovalPacketDraftSlotCode}`,
    `- Source approval packet draft slot ready: ${control.sourceApprovalPacketDraftSlotReady}`,
    `- Source approval packet draft slot project: ${control.sourceApprovalPacketDraftSlotProject}`,
    `- Source approval packet draft policy code: ${control.sourceApprovalPacketDraftPolicyCode}`,
    `- Required approval field: ${control.requiredApprovalFieldName}`,
    `- Required approval field present: ${control.requiredApprovalFieldPresent}`,
    `- Required review record field: ${control.requiredReviewRecordFieldName}`,
    `- Required review record field present: ${control.requiredReviewRecordFieldPresent}`,
    `- Expected policy field: ${control.expectedPolicyField}`,
    `- Expected policy value: ${control.expectedPolicyValue}`,
    `- Policy requirement satisfied: ${control.policyRequirementSatisfied}`,
    `- Reviewer question: ${control.reviewerQuestion}`,
    `- Acceptance criterion: ${control.acceptanceCriterion}`,
    `- Blocker code: ${control.blockerCode}`,
    `- Manual review required: ${control.manualReviewRequired}`,
    `- Auto approval allowed: ${control.autoApprovalAllowed}`,
    `- Approval captured: ${control.approvalCaptured}`,
    `- Approval grant present: ${control.approvalGrantPresent}`,
    `- Signed approval present: ${control.signedApprovalPresent}`,
    `- Operator identity present: ${control.operatorIdentityPresent}`,
    `- Approval timestamp present: ${control.approvalTimestampPresent}`,
    `- Supplied value count: ${control.suppliedValueCount}`,
    `- Accepted value count: ${control.acceptedValueCount}`,
    `- Imported value count: ${control.importedValueCount}`,
    `- Ready for value supply approval packet review: ${control.readyForValueSupplyApprovalPacketReview}`,
    `- Ready for signed approval capture: ${control.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${control.readyForOperatorValueSupply}`,
    `- Ready for operator value submission: ${control.readyForOperatorValueSubmission}`,
    `- Ready for evidence import: ${control.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${control.readyForRuntimePayload}`,
    `- Ready for live execution: ${control.readyForLiveExecution}`,
    `- Ready for production execution: ${control.readyForProductionExecution}`,
    `- Imports runtime payload: ${control.importsRuntimePayload}`,
    `- Accepts synthetic evidence: ${control.acceptsSyntheticEvidence}`,
    `- Contains secret value: ${control.containsSecretValue}`,
    `- Writes allowed: ${control.writesAllowed}`,
    `- Starts services: ${control.startsServices}`,
    `- Mutates sibling state: ${control.mutatesSiblingState}`,
    "",
  ];
}
