import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessContractUpstreamEchoVerificationProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessContractUpstreamEchoVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessContractUpstreamEchoVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessContractUpstreamEchoVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver disabled fake harness contract upstream echo verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Verification state: ${profile.verificationState}`,
    `- Ready for upstream echo verification: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverDisabledFakeHarnessContractUpstreamEchoVerification}`,
    `- Consumes Node v288: ${profile.consumesNodeV288DisabledFakeHarnessContract}`,
    `- Consumes Java v122-v126: ${profile.consumesJavaV122V126QualityAndEchoEvidence}`,
    `- Consumes mini-kv v127: ${profile.consumesMiniKvV127DisabledFakeHarnessNonParticipationReceipt}`,
    `- Fake harness runtime enabled: ${profile.fakeHarnessRuntimeEnabled}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v288",
    "",
    ...renderEntries(profile.sourceNodeV288),
    "",
    "## Java v122-v126 Evidence",
    "",
    ...renderEntries({
      evidencePresent: profile.upstreamEchoes.javaV122V126.evidencePresent,
      verificationDocumented: profile.upstreamEchoes.javaV122V126.verificationDocumented,
      evidenceDigest: profile.upstreamEchoes.javaV122V126.evidenceDigest,
      completedVersions: profile.upstreamEchoes.javaV122V126.completedVersions,
      integrationTestSplitVersions: profile.upstreamEchoes.javaV122V126.integrationTestSplitVersions,
      integrationTestSplitComplete: profile.upstreamEchoes.javaV122V126.integrationTestSplitComplete,
      evidenceServiceCatalogStopgapApplied:
        profile.upstreamEchoes.javaV122V126.evidenceServiceCatalogStopgapApplied,
      boundaryCatalogPresent: profile.upstreamEchoes.javaV122V126.boundaryCatalogPresent,
      noFakeHarnessRuntimeDocumented:
        profile.upstreamEchoes.javaV122V126.noFakeHarnessRuntimeDocumented,
      credentialValueBoundaryDocumented:
        profile.upstreamEchoes.javaV122V126.credentialValueBoundaryDocumented,
      rawEndpointBoundaryDocumented:
        profile.upstreamEchoes.javaV122V126.rawEndpointBoundaryDocumented,
      managedAuditConnectionBoundaryDocumented:
        profile.upstreamEchoes.javaV122V126.managedAuditConnectionBoundaryDocumented,
      ledgerAndSqlBoundaryDocumented:
        profile.upstreamEchoes.javaV122V126.ledgerAndSqlBoundaryDocumented,
    }),
    "",
    "## mini-kv v127 Receipt",
    "",
    ...renderEntries({
      evidencePresent: profile.upstreamEchoes.miniKvV127.evidencePresent,
      verificationDocumented: profile.upstreamEchoes.miniKvV127.verificationDocumented,
      receiptDigest: profile.upstreamEchoes.miniKvV127.receiptDigest,
      receiptVersion: profile.upstreamEchoes.miniKvV127.receiptVersion,
      releaseVersion: profile.upstreamEchoes.miniKvV127.releaseVersion,
      consumerHint: profile.upstreamEchoes.miniKvV127.consumerHint,
      sourceContract: profile.upstreamEchoes.miniKvV127.sourceContract,
      contractDigest: profile.upstreamEchoes.miniKvV127.contractDigest,
      readyForNodeV289UpstreamEchoVerification:
        profile.upstreamEchoes.miniKvV127.readyForNodeV289UpstreamEchoVerification,
      readOnly: profile.upstreamEchoes.miniKvV127.readOnly,
      executionAllowed: profile.upstreamEchoes.miniKvV127.executionAllowed,
      fakeHarnessRuntimeEnabled: profile.upstreamEchoes.miniKvV127.fakeHarnessRuntimeEnabled,
      fakeHarnessRuntimeImplemented: profile.upstreamEchoes.miniKvV127.fakeHarnessRuntimeImplemented,
      credentialValueRead: profile.upstreamEchoes.miniKvV127.credentialValueRead,
      rawEndpointUrlParsed: profile.upstreamEchoes.miniKvV127.rawEndpointUrlParsed,
      externalRequestSent: profile.upstreamEchoes.miniKvV127.externalRequestSent,
      connectsManagedAudit: profile.upstreamEchoes.miniKvV127.connectsManagedAudit,
      managedAuditStorageBackend: profile.upstreamEchoes.miniKvV127.managedAuditStorageBackend,
    }),
    "",
    "## Echo Verification",
    "",
    ...renderEntries(profile.echoVerification),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No disabled fake harness contract upstream echo blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No disabled fake harness contract upstream echo warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No disabled fake harness contract upstream echo recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
