import { renderEntries, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyPreparationPlanProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyPreparationPlanTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyPreparationPlanMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyPreparationPlanProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver disabled runtime shell design draft body preparation plan",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Preparation plan state: ${profile.preparationPlanState}`,
    `- Preparation plan decision: ${profile.preparationPlanDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for v341 body preparation plan: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverDisabledRuntimeShellDesignDraftBodyPreparationPlan}`,
    `- Ready for Node v342 body preparation plan archive verification: ${profile.readyForNodeV342DisabledRuntimeShellDesignDraftBodyPreparationPlanArchiveVerification}`,
    `- Ready for disabled runtime shell design draft: ${profile.readyForDisabledRuntimeShellDesignDraft}`,
    `- Ready for disabled runtime shell design draft outline: ${profile.readyForDisabledRuntimeShellDesignDraftOutline}`,
    `- Ready for runtime shell implementation: ${profile.readyForRuntimeShellImplementation}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Credential value read: ${profile.credentialValueRead}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    `- HTTP request sent: ${profile.httpRequestSent}`,
    `- TCP connection attempted: ${profile.tcpConnectionAttempted}`,
    `- Java SQL execution allowed: ${profile.javaSqlExecutionAllowed}`,
    `- mini-kv write command allowed: ${profile.miniKvWriteCommandAllowed}`,
    `- Automatic upstream start: ${profile.automaticUpstreamStart}`,
    "",
    "## Source Node v340",
    "",
    ...renderEntries({
      archiveVerificationState: profile.sourceNodeV340.archiveVerificationState,
      archiveVerificationDecision: profile.sourceNodeV340.archiveVerificationDecision,
      readyForArchiveVerification: profile.sourceNodeV340.readyForArchiveVerification,
      readyForNodeV341DisabledRuntimeShellDesignDraftBodyPreparationPlan:
        profile.sourceNodeV340.readyForNodeV341DisabledRuntimeShellDesignDraftBodyPreparationPlan,
      archiveVerificationDigest: profile.sourceNodeV340.archiveVerificationDigest,
      sourceDecisionDigest: profile.sourceNodeV340.sourceDecisionDigest,
      sourceArchiveVerificationDigest: profile.sourceNodeV340.sourceArchiveVerificationDigest,
      sourceChecks: `${profile.sourceNodeV340.sourcePassedCheckCount}/${profile.sourceNodeV340.sourceCheckCount}`,
      sourceArchiveFiles:
        `${profile.sourceNodeV340.sourcePresentArchiveFileCount}/${profile.sourceNodeV340.sourceArchiveFileCount}`,
      sourceProductionBlockers: profile.sourceNodeV340.sourceProductionBlockerCount,
      sourceBodySections: profile.sourceNodeV340.sourceBodySectionCount,
      sourceEvidenceItems: profile.sourceNodeV340.sourceEvidenceItemCount,
      sourceStopConditions: profile.sourceNodeV340.sourceStopConditionCount,
      sourceDecisionQuestions:
        `${profile.sourceNodeV340.sourceAnsweredDecisionQuestionCount}/${profile.sourceNodeV340.sourceDecisionQuestionCount}`,
      sourcePreparationControls:
        `${profile.sourceNodeV340.sourceEnforcedPreparationControlCount}/${profile.sourceNodeV340.sourcePreparationControlCount}`,
    }),
    "",
    "## Necessity Proof",
    "",
    ...renderEntries(profile.necessityProof),
    "",
    "## Body Preparation Plan",
    "",
    ...renderEntries(profile.bodyPreparationPlan),
    "",
    "## Section Plans",
    "",
    ...profile.sectionPlans.map((entry) =>
      `- ${entry.id}: ${entry.purpose}; planned=${entry.planned}; bodyContentWritten=${entry.bodyContentWritten}`),
    "",
    "## Evidence Mappings",
    "",
    ...profile.evidenceMappings.map((entry) =>
      `- ${entry.id}: ${entry.sourceVersion}; ${entry.evidenceRole}; required=${entry.requiredForFutureBodyDraft}`),
    "",
    "## Draft Guards",
    "",
    ...profile.draftGuards.map((entry) => `- ${entry.id}: ${entry.guard}; enforced=${entry.enforced}`),
    "",
    "## Stop Conditions",
    "",
    ...profile.stopConditions.map((entry) => `- ${entry.code}: ${entry.condition}; action=${entry.action}`),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    `- Checks: ${profile.summary.passedCheckCount}/${profile.summary.checkCount}`,
    `- Source Node v340 checks: ${profile.summary.sourceNodeV340PassedCheckCount}/${profile.summary.sourceNodeV340CheckCount}`,
    `- Source archive files: ${profile.summary.sourcePresentArchiveFileCount}/${profile.summary.sourceArchiveFileCount}`,
    `- Source body sections: ${profile.summary.sourceBodySectionCount}`,
    `- Source evidence items: ${profile.summary.sourceEvidenceItemCount}`,
    `- Source stop conditions: ${profile.summary.sourceStopConditionCount}`,
    `- Section plans: ${profile.summary.plannedSectionCount}/${profile.summary.sectionPlanCount}`,
    `- Evidence mappings: ${profile.summary.evidenceMappingCount}`,
    `- Draft guards: ${profile.summary.enforcedDraftGuardCount}/${profile.summary.draftGuardCount}`,
    `- Stop conditions: ${profile.summary.stopConditionCount}`,
    `- Production blockers: ${profile.summary.productionBlockerCount}`,
    `- Warnings: ${profile.summary.warningCount}`,
    `- Recommendations: ${profile.summary.recommendationCount}`,
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...profile.nextActions.map((item) => `- ${item}`),
    "",
  ].join("\n");
}
