import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplateFieldTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplateTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_TEMPLATE_VERSIONS = [
  "Node v1012",
  "Node v1013",
  "Node v1014",
  "Node v1015",
  "Node v1016",
  "Node v1017",
  "Node v1018",
  "Node v1019",
  "Node v1020",
  "Node v1021",
  "Node v1022",
  "Node v1023",
  "Node v1024",
  "Node v1025",
  "Node v1026",
  "Node v1027",
  "Node v1028",
  "Node v1029",
  "Node v1030",
  "Node v1031",
  "Node v1032",
  "Node v1033",
  "Node v1034",
  "Node v1035",
  "Node v1036",
] as const;

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_TEMPLATE_FIELDS:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplateFieldTemplate[]
  = Object.freeze([
    field("Node v1012", "SIGNED_APPROVAL_TEMPLATE_PACKET_ID", "signedApprovalPacketId", "identity-field",
      "identifier", "VALUE_SUPPLY_APPROVAL_REVIEW_PACKET_ID", "approvalPacketId",
      "SIGNED_TEMPLATE_PACKET_ID_MISSING", "Stable id for the future signed approval template."),
    field("Node v1013", "SIGNED_APPROVAL_TEMPLATE_OPERATOR_IDENTITY", "operatorIdentity", "identity-field",
      "identifier", "VALUE_SUPPLY_APPROVAL_REVIEW_OPERATOR_IDENTITY", "operatorIdentity",
      "SIGNED_TEMPLATE_OPERATOR_IDENTITY_MISSING", "Human operator identity required before capture."),
    field("Node v1014", "SIGNED_APPROVAL_TEMPLATE_OPERATOR_ROLE", "operatorRole", "identity-field",
      "identifier", "VALUE_SUPPLY_APPROVAL_REVIEW_OPERATOR_IDENTITY", "operatorIdentity",
      "SIGNED_TEMPLATE_OPERATOR_ROLE_MISSING", "Role or authority handle for the human operator."),
    field("Node v1015", "SIGNED_APPROVAL_TEMPLATE_APPROVAL_TIMESTAMP", "approvalTimestamp", "time-field",
      "timestamp", "VALUE_SUPPLY_APPROVAL_REVIEW_APPROVAL_TIMESTAMP", "approvalTimestamp",
      "SIGNED_TEMPLATE_APPROVAL_TIMESTAMP_MISSING", "Timestamp required before any approval can be captured."),
    field("Node v1016", "SIGNED_APPROVAL_TEMPLATE_REVIEW_PACKAGE_DIGEST", "sourceReviewPackageDigest",
      "source-evidence-field", "digest", "VALUE_SUPPLY_APPROVAL_REVIEW_DRAFT_DIGEST_COVERAGE",
      "approvalPacketId", "SIGNED_TEMPLATE_REVIEW_DIGEST_MISSING",
      "Digest of the v1011 review package consumed by the template."),
    field("Node v1017", "SIGNED_APPROVAL_TEMPLATE_DRAFT_DIGEST", "sourceApprovalPacketDraftDigest",
      "source-evidence-field", "digest", "VALUE_SUPPLY_APPROVAL_REVIEW_DRAFT_DIGEST_COVERAGE",
      "sourceEnvelopeSlotCode", "SIGNED_TEMPLATE_DRAFT_DIGEST_MISSING",
      "Digest of the v986 draft that the review package consumed."),
    field("Node v1018", "SIGNED_APPROVAL_TEMPLATE_SOURCE_EVIDENCE_VERSION", "sourceEvidenceVersion",
      "source-evidence-field", "identifier", "VALUE_SUPPLY_APPROVAL_REVIEW_SOURCE_EVIDENCE_VERSION",
      "sourceEvidenceVersion", "SIGNED_TEMPLATE_SOURCE_VERSION_MISSING",
      "Source evidence version required for every future approved value."),
    field("Node v1019", "SIGNED_APPROVAL_TEMPLATE_SOURCE_EVIDENCE_FILE", "sourceEvidenceFileId",
      "source-evidence-field", "identifier", "VALUE_SUPPLY_APPROVAL_REVIEW_JAVA_EVIDENCE_COVERAGE",
      "sourceEvidenceFileId", "SIGNED_TEMPLATE_SOURCE_FILE_MISSING",
      "Source evidence file id required before any signed approval can be trusted."),
    field("Node v1020", "SIGNED_APPROVAL_TEMPLATE_SOURCE_EVIDENCE_SNIPPET", "sourceEvidenceSnippetId",
      "source-evidence-field", "identifier", "VALUE_SUPPLY_APPROVAL_REVIEW_MINI_KV_EVIDENCE_COVERAGE",
      "sourceEvidenceSnippetId", "SIGNED_TEMPLATE_SOURCE_SNIPPET_MISSING",
      "Source evidence snippet id required for provenance review."),
    field("Node v1021", "SIGNED_APPROVAL_TEMPLATE_VALUE_SHAPE", "valueShape", "value-shape-field",
      "typed-value-envelope", "VALUE_SUPPLY_APPROVAL_REVIEW_VALUE_SHAPE", "valueShape",
      "SIGNED_TEMPLATE_VALUE_SHAPE_MISSING", "Explicit typed value envelope shape."),
    field("Node v1022", "SIGNED_APPROVAL_TEMPLATE_REDACTED_DIGEST", "redactedValueDigest",
      "value-shape-field", "digest", "VALUE_SUPPLY_APPROVAL_REVIEW_REDACTED_DIGEST",
      "redactedValueDigest", "SIGNED_TEMPLATE_REDACTED_DIGEST_MISSING",
      "Digest of the redacted value, not the raw value."),
    field("Node v1023", "SIGNED_APPROVAL_TEMPLATE_REDACTION_POLICY", "redactionPolicy", "policy-field",
      "policy-code", "VALUE_SUPPLY_APPROVAL_REVIEW_REDACTION_POLICY", "redactionPolicy",
      "SIGNED_TEMPLATE_REDACTION_POLICY_MISSING", "Redact-before-persist policy binding."),
    field("Node v1024", "SIGNED_APPROVAL_TEMPLATE_PROVENANCE_POLICY", "provenancePolicy", "policy-field",
      "policy-code", "VALUE_SUPPLY_APPROVAL_REVIEW_PROVENANCE_POLICY", "provenancePolicy",
      "SIGNED_TEMPLATE_PROVENANCE_POLICY_MISSING", "Source-evidence-required policy binding."),
    field("Node v1025", "SIGNED_APPROVAL_TEMPLATE_MISSING_VALUE_POLICY", "missingValuePolicy", "policy-field",
      "policy-code", "VALUE_SUPPLY_APPROVAL_REVIEW_MISSING_VALUE_POLICY", "missingValuePolicy",
      "SIGNED_TEMPLATE_MISSING_VALUE_POLICY_MISSING", "Fail-closed missing value policy binding."),
    field("Node v1026", "SIGNED_APPROVAL_TEMPLATE_MALFORMED_VALUE_POLICY", "malformedValuePolicy",
      "policy-field", "policy-code", "VALUE_SUPPLY_APPROVAL_REVIEW_MALFORMED_VALUE_POLICY",
      "malformedValuePolicy", "SIGNED_TEMPLATE_MALFORMED_VALUE_POLICY_MISSING",
      "Malformed value rejection policy binding."),
    field("Node v1027", "SIGNED_APPROVAL_TEMPLATE_APPROVAL_POLICY", "approvalPolicy", "policy-field",
      "policy-code", "VALUE_SUPPLY_APPROVAL_REVIEW_SIGNED_HUMAN_POLICY", "operatorIdentity",
      "SIGNED_TEMPLATE_APPROVAL_POLICY_MISSING", "Signed-human-approval-required policy binding."),
    field("Node v1028", "SIGNED_APPROVAL_TEMPLATE_PACKET_POLICY", "packetPolicy", "policy-field",
      "policy-code", "VALUE_SUPPLY_APPROVAL_REVIEW_DRAFT_ONLY_POLICY", "approvalPacketId",
      "SIGNED_TEMPLATE_PACKET_POLICY_MISSING", "Draft-only no-grant policy must remain explicit."),
    field("Node v1029", "SIGNED_APPROVAL_TEMPLATE_OPERATOR_JUSTIFICATION", "operatorJustification",
      "identity-field", "operator-justification", "VALUE_SUPPLY_APPROVAL_REVIEW_PROJECT_JUSTIFICATION",
      "javaApprovalJustification", "SIGNED_TEMPLATE_OPERATOR_JUSTIFICATION_MISSING",
      "Human justification tied to the source project evidence."),
    field("Node v1030", "SIGNED_APPROVAL_TEMPLATE_JAVA_EVIDENCE_COVERAGE", "javaEvidenceCoverageDigest",
      "source-evidence-field", "digest", "VALUE_SUPPLY_APPROVAL_REVIEW_JAVA_EVIDENCE_COVERAGE",
      "sourceEvidenceFileId", "SIGNED_TEMPLATE_JAVA_EVIDENCE_COVERAGE_MISSING",
      "Digest placeholder for Java evidence coverage review."),
    field("Node v1031", "SIGNED_APPROVAL_TEMPLATE_MINI_KV_EVIDENCE_COVERAGE", "miniKvEvidenceCoverageDigest",
      "source-evidence-field", "digest", "VALUE_SUPPLY_APPROVAL_REVIEW_MINI_KV_EVIDENCE_COVERAGE",
      "sourceEvidenceSnippetId", "SIGNED_TEMPLATE_MINI_KV_EVIDENCE_COVERAGE_MISSING",
      "Digest placeholder for mini-kv evidence coverage review."),
    field("Node v1032", "SIGNED_APPROVAL_TEMPLATE_NODE_ENVELOPE_COVERAGE", "nodeEnvelopeCoverageDigest",
      "source-evidence-field", "digest", "VALUE_SUPPLY_APPROVAL_REVIEW_NODE_ENVELOPE_COVERAGE",
      "sourceEnvelopeSlotCode", "SIGNED_TEMPLATE_NODE_ENVELOPE_COVERAGE_MISSING",
      "Digest placeholder for Node envelope coverage review."),
    field("Node v1033", "SIGNED_APPROVAL_TEMPLATE_NO_APPROVAL_CAPTURED_LOCK", "noApprovalCapturedLock",
      "execution-lock-field", "boolean-lock", "VALUE_SUPPLY_APPROVAL_REVIEW_NO_APPROVAL_CAPTURED",
      "operatorIdentity", "SIGNED_TEMPLATE_NO_APPROVAL_CAPTURED_LOCK_MISSING",
      "Lock proving approval has not already been captured."),
    field("Node v1034", "SIGNED_APPROVAL_TEMPLATE_ZERO_VALUE_COUNT_LOCK", "zeroValueCountLock",
      "execution-lock-field", "boolean-lock", "VALUE_SUPPLY_APPROVAL_REVIEW_ZERO_VALUE_COUNTS",
      "valueShape", "SIGNED_TEMPLATE_ZERO_VALUE_COUNT_LOCK_MISSING",
      "Lock proving supplied, accepted, and imported value counts remain zero."),
    field("Node v1035", "SIGNED_APPROVAL_TEMPLATE_WRITE_SERVICE_LOCK", "writeServiceMutationLock",
      "execution-lock-field", "boolean-lock", "VALUE_SUPPLY_APPROVAL_REVIEW_WRITE_AND_SERVICE_BLOCK",
      "miniKvStoreUnchangedProof", "SIGNED_TEMPLATE_WRITE_SERVICE_LOCK_MISSING",
      "Lock proving writes, service starts, and sibling mutation remain blocked."),
    field("Node v1036", "SIGNED_APPROVAL_TEMPLATE_CLOSEOUT", "signedApprovalTemplateCloseout",
      "closeout-field", "identifier", "VALUE_SUPPLY_APPROVAL_REVIEW_CLOSEOUT", "nodeCloseoutPlan",
      "SIGNED_TEMPLATE_CLOSEOUT_MISSING", "Closeout field limiting the next step to capture preflight."),
  ]);

function field(
  nodeVersion: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplateFieldTemplate[
    "nodeVersion"
  ],
  code: string,
  fieldName: string,
  kind: ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplateFieldTemplate[
    "kind"
  ],
  valueClass:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplateFieldTemplate[
      "valueClass"
    ],
  sourceReviewControlCode: string,
  requiredReviewControlFieldName: string,
  missingFieldBlockerCode: string,
  fieldPurpose: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalTemplateFieldTemplate {
  return {
    nodeVersion,
    code,
    fieldName,
    kind,
    valueClass,
    sourceReviewControlCode,
    requiredReviewControlFieldName,
    missingFieldBlockerCode,
    fieldPurpose,
  };
}
