import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverSandboxHandleReviewPrerequisiteIntakeProfile,
  SandboxHandleReviewClosedScope,
  SandboxHandleReviewPrerequisiteInput,
} from "./managedAuditManualSandboxConnectionCredentialResolverSandboxHandleReviewPrerequisiteIntakeTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverSandboxHandleReviewPrerequisiteIntakeMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverSandboxHandleReviewPrerequisiteIntakeProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver sandbox handle review prerequisite intake",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Intake state: ${profile.intakeState}`,
    `- Intake decision: ${profile.intakeDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for v355 archive verification: ${profile.readyForNodeV355SandboxHandleReviewPrerequisiteIntakeArchiveVerification}`,
    `- Prerequisite intake only: ${profile.prerequisiteIntakeOnly}`,
    `- Sandbox handle review only: ${profile.sandboxHandleReviewOnly}`,
    `- Reruns live probe: ${profile.rerunsLiveProbe}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Sends managed audit HTTP/TCP: ${profile.sendsManagedAuditHttpTcp}`,
    `- Credential value requested: ${profile.credentialValueRequested}`,
    `- Credential value read: ${profile.credentialValueRead}`,
    `- Raw endpoint URL requested: ${profile.rawEndpointUrlRequested}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    `- Secret provider instantiated: ${profile.secretProviderInstantiated}`,
    `- Resolver client instantiated: ${profile.resolverClientInstantiated}`,
    `- Runtime shell implemented: ${profile.runtimeShellImplemented}`,
    `- Runtime shell invocation allowed: ${profile.runtimeShellInvocationAllowed}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v353",
    "",
    ...renderEntries(profile.sourceNodeV353),
    "",
    "## Necessity Proof",
    "",
    ...renderEntries(profile.necessityProof),
    "",
    "## Prerequisite Inputs",
    "",
    ...profile.prerequisiteInputs.flatMap(renderPrerequisiteInput),
    "",
    "## Closed Scopes",
    "",
    ...profile.closedScopes.flatMap(renderClosedScope),
    "",
    "## Intake Record",
    "",
    ...renderEntries(profile.intakeRecord),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderPrerequisiteInput(input: SandboxHandleReviewPrerequisiteInput): string[] {
  return [
    `- ${input.id}: ${input.label}`,
    `  - category: ${input.category}`,
    `  - allowedShape: ${input.allowedShape}`,
    `  - requiredBeforeReview: ${input.requiredBeforeReview}`,
    `  - containsSecretValue: ${input.containsSecretValue}`,
    `  - containsRawEndpointUrl: ${input.containsRawEndpointUrl}`,
    `  - allowsNetworkConnection: ${input.allowsNetworkConnection}`,
    `  - allowsRuntimeInvocation: ${input.allowsRuntimeInvocation}`,
    `  - status: ${input.status}`,
    `  - notes: ${input.notes}`,
  ];
}

function renderClosedScope(scope: SandboxHandleReviewClosedScope): string[] {
  return [
    `- ${scope.id}: ${scope.label}`,
    `  - closedBecause: ${scope.closedBecause}`,
    `  - credentialValueRead: ${scope.credentialValueRead}`,
    `  - rawEndpointUrlParsed: ${scope.rawEndpointUrlParsed}`,
    `  - providerClientInstantiated: ${scope.providerClientInstantiated}`,
    `  - runtimeShellInvocationAllowed: ${scope.runtimeShellInvocationAllowed}`,
    `  - managedAuditHttpTcpAllowed: ${scope.managedAuditHttpTcpAllowed}`,
    `  - upstreamMutationAllowed: ${scope.upstreamMutationAllowed}`,
  ];
}
