import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCapturePreflightInputTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCapturePreflightTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_PREFLIGHT_VERSIONS = [
  "Node v1037",
  "Node v1038",
  "Node v1039",
  "Node v1040",
  "Node v1041",
  "Node v1042",
  "Node v1043",
  "Node v1044",
  "Node v1045",
  "Node v1046",
  "Node v1047",
  "Node v1048",
  "Node v1049",
  "Node v1050",
  "Node v1051",
  "Node v1052",
  "Node v1053",
  "Node v1054",
  "Node v1055",
  "Node v1056",
  "Node v1057",
  "Node v1058",
  "Node v1059",
  "Node v1060",
  "Node v1061",
] as const;

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_PREFLIGHT_INPUTS:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCapturePreflightInputTemplate[]
  = Object.freeze([
    input("Node v1037", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_REQUEST_ID", "capturePreflightRequestId",
      "identity-input", "operator-entry-placeholder", "SIGNED_APPROVAL_TEMPLATE_PACKET_ID",
      "signedApprovalPacketId", "CAPTURE_PREFLIGHT_REQUEST_ID_MISSING",
      "Stable id for the future signed approval capture preflight packet."),
    input("Node v1038", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_TEMPLATE_DIGEST", "sourceSignedApprovalTemplateDigest",
      "digest-binding-input", "digest-reference", "SIGNED_APPROVAL_TEMPLATE_REVIEW_PACKAGE_DIGEST",
      "sourceReviewPackageDigest", "CAPTURE_PREFLIGHT_TEMPLATE_DIGEST_MISSING",
      "Digest binding to the v1036 signed approval template."),
    input("Node v1039", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_REVIEW_DIGEST", "sourceApprovalPacketReviewDigest",
      "digest-binding-input", "digest-reference", "SIGNED_APPROVAL_TEMPLATE_DRAFT_DIGEST",
      "sourceApprovalPacketDraftDigest", "CAPTURE_PREFLIGHT_REVIEW_DIGEST_MISSING",
      "Digest binding to the approval packet review consumed by the template."),
    input("Node v1040", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_OPERATOR_IDENTITY", "operatorIdentity",
      "identity-input", "operator-entry-placeholder", "SIGNED_APPROVAL_TEMPLATE_OPERATOR_IDENTITY",
      "operatorIdentity", "CAPTURE_PREFLIGHT_OPERATOR_IDENTITY_MISSING",
      "Human operator identity that must be present before capture can be planned."),
    input("Node v1041", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_OPERATOR_ROLE", "operatorRole",
      "identity-input", "operator-entry-placeholder", "SIGNED_APPROVAL_TEMPLATE_OPERATOR_ROLE",
      "operatorRole", "CAPTURE_PREFLIGHT_OPERATOR_ROLE_MISSING",
      "Human operator role or authority handle required before capture can be planned."),
    input("Node v1042", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_TIMESTAMP_SOURCE", "approvalTimestampSource",
      "time-input", "operator-entry-placeholder", "SIGNED_APPROVAL_TEMPLATE_APPROVAL_TIMESTAMP",
      "approvalTimestamp", "CAPTURE_PREFLIGHT_TIMESTAMP_SOURCE_MISSING",
      "Timestamp source placeholder; this preflight does not capture the timestamp value."),
    input("Node v1043", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_WINDOW_ID", "captureWindowId",
      "identity-input", "operator-entry-placeholder", "SIGNED_APPROVAL_TEMPLATE_PACKET_ID",
      "signedApprovalPacketId", "CAPTURE_PREFLIGHT_WINDOW_ID_MISSING",
      "Manual capture window id placeholder for a later signed approval artifact."),
    input("Node v1044", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_CHANNEL", "captureChannel",
      "capture-channel-input", "policy-code", "SIGNED_APPROVAL_TEMPLATE_PACKET_POLICY",
      "packetPolicy", "CAPTURE_PREFLIGHT_CHANNEL_MISSING",
      "Approved capture channel placeholder; no interactive capture occurs in this version."),
    input("Node v1045", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SIGNATURE_ALGORITHM", "signatureAlgorithmPolicy",
      "signature-policy-input", "policy-code", "SIGNED_APPROVAL_TEMPLATE_APPROVAL_POLICY",
      "approvalPolicy", "CAPTURE_PREFLIGHT_SIGNATURE_ALGORITHM_MISSING",
      "Signature algorithm policy that a later signed approval artifact must declare."),
    input("Node v1046", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SIGNATURE_REDACTION", "signatureMaterialRedactionPolicy",
      "signature-policy-input", "policy-code", "SIGNED_APPROVAL_TEMPLATE_REDACTION_POLICY",
      "redactionPolicy", "CAPTURE_PREFLIGHT_SIGNATURE_REDACTION_MISSING",
      "Policy proving raw signature material will not be persisted by this preview."),
    input("Node v1047", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_APPROVAL_STATEMENT", "approvalStatement",
      "operator-statement-input", "approval-statement", "SIGNED_APPROVAL_TEMPLATE_APPROVAL_POLICY",
      "approvalPolicy", "CAPTURE_PREFLIGHT_APPROVAL_STATEMENT_MISSING",
      "Human-readable approval statement placeholder; no statement is captured now."),
    input("Node v1048", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_OPERATOR_JUSTIFICATION", "operatorJustification",
      "operator-statement-input", "operator-entry-placeholder", "SIGNED_APPROVAL_TEMPLATE_OPERATOR_JUSTIFICATION",
      "operatorJustification", "CAPTURE_PREFLIGHT_OPERATOR_JUSTIFICATION_MISSING",
      "Operator justification mirror from the signed approval template."),
    input("Node v1049", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SOURCE_VERSION", "sourceEvidenceVersion",
      "source-evidence-input", "operator-entry-placeholder", "SIGNED_APPROVAL_TEMPLATE_SOURCE_EVIDENCE_VERSION",
      "sourceEvidenceVersion", "CAPTURE_PREFLIGHT_SOURCE_VERSION_MISSING",
      "Source evidence version required before a later signed approval can be captured."),
    input("Node v1050", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SOURCE_FILE", "sourceEvidenceFileId",
      "source-evidence-input", "operator-entry-placeholder", "SIGNED_APPROVAL_TEMPLATE_SOURCE_EVIDENCE_FILE",
      "sourceEvidenceFileId", "CAPTURE_PREFLIGHT_SOURCE_FILE_MISSING",
      "Source evidence file id required before a later signed approval can be trusted."),
    input("Node v1051", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SOURCE_SNIPPET", "sourceEvidenceSnippetId",
      "source-evidence-input", "operator-entry-placeholder", "SIGNED_APPROVAL_TEMPLATE_SOURCE_EVIDENCE_SNIPPET",
      "sourceEvidenceSnippetId", "CAPTURE_PREFLIGHT_SOURCE_SNIPPET_MISSING",
      "Source evidence snippet id required before a later signed approval can be trusted."),
    input("Node v1052", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_REDACTED_VALUE_DIGEST", "redactedValueDigest",
      "value-binding-input", "digest-reference", "SIGNED_APPROVAL_TEMPLATE_REDACTED_DIGEST",
      "redactedValueDigest", "CAPTURE_PREFLIGHT_REDACTED_VALUE_DIGEST_MISSING",
      "Redacted value digest reference; raw values remain absent."),
    input("Node v1053", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_VALUE_SHAPE", "valueShape",
      "value-binding-input", "operator-entry-placeholder", "SIGNED_APPROVAL_TEMPLATE_VALUE_SHAPE",
      "valueShape", "CAPTURE_PREFLIGHT_VALUE_SHAPE_MISSING",
      "Typed value envelope shape required before later capture."),
    input("Node v1054", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_REDACTION_POLICY", "redactionPolicy",
      "policy-input", "policy-code", "SIGNED_APPROVAL_TEMPLATE_REDACTION_POLICY",
      "redactionPolicy", "CAPTURE_PREFLIGHT_REDACTION_POLICY_MISSING",
      "Redact-before-persist policy mirror for a later capture artifact."),
    input("Node v1055", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_PROVENANCE_POLICY", "provenancePolicy",
      "policy-input", "policy-code", "SIGNED_APPROVAL_TEMPLATE_PROVENANCE_POLICY",
      "provenancePolicy", "CAPTURE_PREFLIGHT_PROVENANCE_POLICY_MISSING",
      "Source-evidence-required policy mirror for a later capture artifact."),
    input("Node v1056", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_NO_RAW_SECRET_LOCK", "noRawSecretLock",
      "execution-lock-input", "boolean-lock", "SIGNED_APPROVAL_TEMPLATE_REDACTED_DIGEST",
      "redactedValueDigest", "CAPTURE_PREFLIGHT_NO_RAW_SECRET_LOCK_MISSING",
      "Lock proving the preflight has not received raw secret or signature material."),
    input("Node v1057", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_NO_GRANT_LOCK", "noApprovalGrantEmittedLock",
      "execution-lock-input", "boolean-lock", "SIGNED_APPROVAL_TEMPLATE_NO_APPROVAL_CAPTURED_LOCK",
      "noApprovalCapturedLock", "CAPTURE_PREFLIGHT_NO_GRANT_LOCK_MISSING",
      "Lock proving no signed approval grant has been emitted."),
    input("Node v1058", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_ZERO_VALUE_SUBMISSION_LOCK", "zeroValueSubmissionLock",
      "execution-lock-input", "boolean-lock", "SIGNED_APPROVAL_TEMPLATE_ZERO_VALUE_COUNT_LOCK",
      "zeroValueCountLock", "CAPTURE_PREFLIGHT_ZERO_VALUE_SUBMISSION_LOCK_MISSING",
      "Lock proving value submission, acceptance, and import counts remain zero."),
    input("Node v1059", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_NO_WRITE_ROUTE_LOCK", "noWriteRouteLock",
      "execution-lock-input", "boolean-lock", "SIGNED_APPROVAL_TEMPLATE_WRITE_SERVICE_LOCK",
      "writeServiceMutationLock", "CAPTURE_PREFLIGHT_NO_WRITE_ROUTE_LOCK_MISSING",
      "Lock proving no write route is enabled by capture preflight."),
    input("Node v1060", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SIBLING_NON_MUTATION_LOCK", "siblingNonMutationLock",
      "execution-lock-input", "boolean-lock", "SIGNED_APPROVAL_TEMPLATE_WRITE_SERVICE_LOCK",
      "writeServiceMutationLock", "CAPTURE_PREFLIGHT_SIBLING_NON_MUTATION_LOCK_MISSING",
      "Lock proving Java and mini-kv remain unchanged by capture preflight."),
    input("Node v1061", "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_CLOSEOUT", "signedApprovalCapturePreflightCloseout",
      "closeout-input", "operator-entry-placeholder", "SIGNED_APPROVAL_TEMPLATE_CLOSEOUT",
      "signedApprovalTemplateCloseout", "CAPTURE_PREFLIGHT_CLOSEOUT_MISSING",
      "Closeout limiting the next step to signed approval capture artifact preflight."),
  ]);

function input(
  nodeVersion:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCapturePreflightInputTemplate[
      "nodeVersion"
    ],
  code: string,
  inputName: string,
  kind:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCapturePreflightInputTemplate[
      "kind"
    ],
  valueMode:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCapturePreflightInputTemplate[
      "valueMode"
    ],
  sourceTemplateFieldCode: string,
  requiredTemplateFieldName: string,
  captureBlockerCode: string,
  inputPurpose: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCapturePreflightInputTemplate {
  return {
    nodeVersion,
    code,
    inputName,
    kind,
    valueMode,
    sourceTemplateFieldCode,
    requiredTemplateFieldName,
    captureBlockerCode,
    inputPurpose,
  };
}
