import { renderEntries } from "./liveProbeReportUtils.js";
import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageIntake,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageIntakeField,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageIntakeGuard,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageIntakeTypes.js";

export function renderControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageIntakeMarkdown(
  intake:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageIntake,
): string {
  return [
    "# Controlled read-only shard preview live read-only window operator evidence value supply signed approval capture artifact draft text package intake",
    "",
    `- Signed approval capture artifact draft text package intake version: ${intake.signedApprovalCaptureArtifactDraftTextPackageIntakeVersion}`,
    `- Source signed approval capture artifact draft instruction preflight version: ${intake.sourceSignedApprovalCaptureArtifactDraftInstructionPreflightVersion}`,
    `- Artifact draft text package intake state: ${intake.artifactDraftTextPackageIntakeState}`,
    `- Ready for signed approval artifact draft text package intake: ${intake.readyForSignedApprovalArtifactDraftTextPackageIntake}`,
    `- Ready for human signed approval draft text package submission: ${intake.readyForHumanSignedApprovalDraftTextPackageSubmission}`,
    `- Ready for human signed approval draft instruction authoring: ${intake.readyForHumanSignedApprovalDraftInstructionAuthoring}`,
    `- Ready for signed approval artifact draft: ${intake.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${intake.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${intake.readyForOperatorValueSupply}`,
    `- Ready for operator value submission: ${intake.readyForOperatorValueSubmission}`,
    `- Ready for evidence import: ${intake.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${intake.readyForRuntimePayload}`,
    `- Ready for live execution: ${intake.readyForLiveExecution}`,
    `- Ready for production execution: ${intake.readyForProductionExecution}`,
    `- Intake field count: ${intake.intakeFieldCount}`,
    `- Intake guard count: ${intake.intakeGuardCount}`,
    `- Identity intake field count: ${intake.identityIntakeFieldCount}`,
    `- Digest binding intake field count: ${intake.digestBindingIntakeFieldCount}`,
    `- Signature envelope intake field count: ${intake.signatureEnvelopeIntakeFieldCount}`,
    `- Source evidence intake field count: ${intake.sourceEvidenceIntakeFieldCount}`,
    `- Value binding intake field count: ${intake.valueBindingIntakeFieldCount}`,
    `- Policy intake field count: ${intake.policyIntakeFieldCount}`,
    `- Execution lock intake field count: ${intake.executionLockIntakeFieldCount}`,
    `- Archive closeout intake field count: ${intake.archiveCloseoutIntakeFieldCount}`,
    `- Digest mode intake field count: ${intake.digestModeIntakeFieldCount}`,
    `- Ready intake field count: ${intake.readyIntakeFieldCount}`,
    `- Ready intake guard count: ${intake.readyIntakeGuardCount}`,
    `- Digest binding intake guard count: ${intake.digestBindingIntakeGuardCount}`,
    `- Signature envelope intake guard count: ${intake.signatureEnvelopeIntakeGuardCount}`,
    `- Policy intake guard count: ${intake.policyIntakeGuardCount}`,
    `- Execution lock intake guard count: ${intake.executionLockIntakeGuardCount}`,
    `- Archive closeout intake guard count: ${intake.archiveCloseoutIntakeGuardCount}`,
    `- Expected draft text package field count: ${intake.expectedDraftTextPackageFieldCount}`,
    `- Actual draft text package field count: ${intake.actualDraftTextPackageFieldCount}`,
    `- Accepted draft text package count: ${intake.acceptedDraftTextPackageCount}`,
    `- Draft instruction materialized count: ${intake.draftInstructionMaterializedCount}`,
    `- Draft artifact created: ${intake.draftArtifactCreated}`,
    `- Signed draft text count: ${intake.signedDraftTextCount}`,
    `- Draft signature payload count: ${intake.draftSignaturePayloadCount}`,
    `- Approval captured: ${intake.approvalCaptured}`,
    `- Approval grant present: ${intake.approvalGrantPresent}`,
    `- Signed approval present: ${intake.signedApprovalPresent}`,
    `- Source signed approval capture artifact draft instruction preflight digest: ${intake.sourceSignedApprovalCaptureArtifactDraftInstructionPreflightDigest}`,
    `- Source signed approval capture artifact draft authoring readiness digest: ${intake.sourceSignedApprovalCaptureArtifactDraftAuthoringReadinessDigest}`,
    `- Source signed approval capture artifact draft review package preflight digest: ${intake.sourceSignedApprovalCaptureArtifactDraftReviewPackagePreflightDigest}`,
    `- Source signed approval capture artifact draft readiness digest: ${intake.sourceSignedApprovalCaptureArtifactDraftReadinessDigest}`,
    `- Source signed approval capture artifact draft preflight digest: ${intake.sourceSignedApprovalCaptureArtifactDraftPreflightDigest}`,
    `- Source signed approval capture artifact preflight digest: ${intake.sourceSignedApprovalCaptureArtifactPreflightDigest}`,
    `- Source signed approval capture preflight digest: ${intake.sourceSignedApprovalCapturePreflightDigest}`,
    `- Source signed approval template digest: ${intake.sourceSignedApprovalTemplateDigest}`,
    `- Source approval packet review digest: ${intake.sourceApprovalPacketReviewDigest}`,
    `- Passed gates: ${intake.passedGateCount}/${intake.gateCount}`,
    `- Imports runtime payload: ${intake.importsRuntimePayload}`,
    `- Accepts synthetic evidence: ${intake.acceptsSyntheticEvidence}`,
    `- Contains secret value: ${intake.containsSecretValue}`,
    `- Signed approval capture artifact draft text package intake digest: ${intake.signedApprovalCaptureArtifactDraftTextPackageIntakeDigest}`,
    "",
    "## Gates",
    ...renderEntries(intake.gates),
    "",
    "## Intake Fields",
    ...intake.fields.flatMap(renderField),
    "## Intake Guards",
    ...intake.guards.flatMap(renderGuard),
    "## Blocked Reasons",
    ...(intake.blockedReasonCodes.length === 0
      ? ["- none"]
      : intake.blockedReasonCodes.map((reason) => `- ${reason}`)),
  ].join("\n");
}

function renderField(
  field:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageIntakeField,
): string[] {
  return [
    `### ${field.order}. ${field.nodeVersion} ${field.code}`,
    `- Intake field name: ${field.intakeFieldName}`,
    `- Kind: ${field.kind}`,
    `- Field mode: ${field.fieldMode}`,
    `- Source instruction slot: ${field.sourceInstructionSlotCode}`,
    `- Source instruction slot ready: ${field.sourceInstructionSlotReady}`,
    `- Source instruction slot kind: ${field.sourceInstructionSlotKind}`,
    `- Source instruction slot mode: ${field.sourceInstructionSlotMode}`,
    `- Source instruction slot read-only: ${field.sourceInstructionSlotReadOnly}`,
    `- Source instruction materialized: ${field.sourceInstructionMaterialized}`,
    `- Source draft artifact created: ${field.sourceDraftArtifactCreated}`,
    `- Source signed draft text present: ${field.sourceSignedDraftTextPresent}`,
    `- Source draft signature payload present: ${field.sourceDraftSignaturePayloadPresent}`,
    `- Source approval grant present: ${field.sourceApprovalGrantPresent}`,
    `- Source instruction guard: ${field.sourceInstructionGuardCode}`,
    `- Source instruction guard ready: ${field.sourceInstructionGuardReady}`,
    `- Source instruction guard kind: ${field.sourceInstructionGuardKind}`,
    `- Source instruction guard read-only: ${field.sourceInstructionGuardReadOnly}`,
    `- Source instruction guard blocks draft artifact creation: ${field.sourceInstructionGuardBlocksDraftArtifactCreation}`,
    `- Source instruction guard blocks signed draft text: ${field.sourceInstructionGuardBlocksSignedDraftText}`,
    `- Source instruction guard blocks signature payload: ${field.sourceInstructionGuardBlocksSignaturePayload}`,
    `- Source instruction guard blocks approval grant: ${field.sourceInstructionGuardBlocksApprovalGrant}`,
    `- Source instruction guard blocks runtime payload: ${field.sourceInstructionGuardBlocksRuntimePayload}`,
    `- Source instruction guard blocks writes: ${field.sourceInstructionGuardBlocksWrites}`,
    `- Source instruction guard blocks sibling mutation: ${field.sourceInstructionGuardBlocksSiblingMutation}`,
    `- Expected shape: ${field.expectedShape}`,
    `- Intake purpose: ${field.intakePurpose}`,
    `- Ready for human signed approval draft text package intake field: ${field.readyForHumanSignedApprovalDraftTextPackageIntakeField}`,
    `- Draft text package field materialized: ${field.draftTextPackageFieldMaterialized}`,
    `- Draft text package accepted: ${field.draftTextPackageAccepted}`,
    `- Signed draft text present: ${field.signedDraftTextPresent}`,
    `- Draft signature payload present: ${field.draftSignaturePayloadPresent}`,
    `- Approval grant present: ${field.approvalGrantPresent}`,
    `- Ready for signed approval artifact draft: ${field.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${field.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${field.readyForOperatorValueSupply}`,
    `- Ready for evidence import: ${field.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${field.readyForRuntimePayload}`,
    `- Writes allowed: ${field.writesAllowed}`,
    `- Starts services: ${field.startsServices}`,
    `- Mutates sibling state: ${field.mutatesSiblingState}`,
    "",
  ];
}

function renderGuard(
  guard:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftTextPackageIntakeGuard,
): string[] {
  return [
    `### ${guard.order}. ${guard.nodeVersion} ${guard.code}`,
    `- Kind: ${guard.kind}`,
    `- Source intake field: ${guard.sourceIntakeFieldCode}`,
    `- Source intake field ready: ${guard.sourceIntakeFieldReady}`,
    `- Source instruction guard kind: ${guard.sourceInstructionGuardKind}`,
    `- Guard code: ${guard.guardCode}`,
    `- Guard text: ${guard.guardText}`,
    `- Rejects missing intake field: ${guard.rejectsMissingIntakeField}`,
    `- Blocks draft text package acceptance: ${guard.blocksDraftTextPackageAcceptance}`,
    `- Blocks signed draft text: ${guard.blocksSignedDraftText}`,
    `- Blocks signature payload: ${guard.blocksSignaturePayload}`,
    `- Blocks approval grant: ${guard.blocksApprovalGrant}`,
    `- Blocks runtime payload: ${guard.blocksRuntimePayload}`,
    `- Blocks writes: ${guard.blocksWrites}`,
    `- Blocks sibling mutation: ${guard.blocksSiblingMutation}`,
    `- Ready for human signed approval draft text package intake guard: ${guard.readyForHumanSignedApprovalDraftTextPackageIntakeGuard}`,
    `- Ready for signed approval artifact draft: ${guard.readyForSignedApprovalArtifactDraft}`,
    `- Ready for signed approval capture: ${guard.readyForSignedApprovalCapture}`,
    `- Ready for operator value supply: ${guard.readyForOperatorValueSupply}`,
    `- Ready for evidence import: ${guard.readyForEvidenceImport}`,
    `- Ready for runtime payload: ${guard.readyForRuntimePayload}`,
    `- Writes allowed: ${guard.writesAllowed}`,
    `- Starts services: ${guard.startsServices}`,
    `- Mutates sibling state: ${guard.mutatesSiblingState}`,
    "",
  ];
}
