import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverMinimalShardReadinessLiveReadGateProfile,
  MinimalShardReadinessLiveReadObservation,
} from "./managedAuditManualSandboxConnectionCredentialResolverMinimalShardReadinessLiveReadGateTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverMinimalShardReadinessLiveReadGateMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverMinimalShardReadinessLiveReadGateProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver minimal shard readiness live-read gate",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Gate state: ${profile.gateState}`,
    `- Gate decision: ${profile.gateDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for minimal shard readiness live-read gate: ${profile.readyForMinimalShardReadinessLiveReadGate}`,
    `- Ready for Node v372 archive verification: ${profile.readyForNodeV372LiveReadArchiveVerification}`,
    `- Live read only: ${profile.liveReadOnly}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Stops Java service: ${profile.stopsJavaService}`,
    `- Stops mini-kv service: ${profile.stopsMiniKvService}`,
    `- Mutates Java state: ${profile.mutatesJavaState}`,
    `- Mutates mini-kv state: ${profile.mutatesMiniKvState}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Sends managed audit HTTP/TCP: ${profile.sendsManagedAuditHttpTcp}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v370",
    "",
    ...renderEntries(profile.sourceNodeV370),
    "",
    "## Gate",
    "",
    ...renderEntries(profile.gate),
    "",
    "## Java Live Read",
    "",
    ...renderLiveRead(profile.liveReads.java),
    "",
    "## mini-kv Live Read",
    "",
    ...renderLiveRead(profile.liveReads.miniKv),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderLiveRead(read: MinimalShardReadinessLiveReadObservation): string[] {
  return [
    `- Project: ${read.project}`,
    `- Source version: ${read.sourceVersion}`,
    `- Status: ${read.status}`,
    `- Attempted: ${read.attempted}`,
    `- Transport: ${read.transport}`,
    `- Endpoint: ${read.endpoint}`,
    `- Command: ${read.command ?? "none"}`,
    `- Status code: ${read.statusCode ?? "none"}`,
    `- Latency ms: ${read.latencyMs ?? "none"}`,
    `- Error code: ${read.errorCode ?? "none"}`,
    `- Error message: ${read.errorMessage ?? "none"}`,
    `- Required fields: ${read.presentRequiredFieldCount}/${read.requiredFieldCount}`,
    `- Missing fields: ${read.missingRequiredFields.length === 0 ? "none" : read.missingRequiredFields.join(", ")}`,
    `- Read only safe: ${read.readOnlySafe}`,
    `- Execution blocked: ${read.executionBlocked}`,
    `- Compatible with v370 evidence: ${read.compatibleWithV370Evidence}`,
    `- Boundary safe: ${read.boundarySafe}`,
    `- Ready for gate: ${read.readyForGate}`,
  ];
}
