import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionPrecheckUpstreamReceiptVerificationProfile,
} from "./managedAuditManualSandboxConnectionPrecheckUpstreamReceiptVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionPrecheckUpstreamReceiptVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionPrecheckUpstreamReceiptVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection precheck upstream receipt verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Verification state: ${profile.verificationState}`,
    `- Ready for upstream receipt verification: ${profile.readyForManagedAuditManualSandboxConnectionPrecheckUpstreamReceiptVerification}`,
    `- Ready for sandbox adapter connection: ${profile.readyForManagedAuditSandboxAdapterConnection}`,
    "",
    "## Source Node v245",
    "",
    ...renderEntries(profile.sourceNodeV245),
    "",
    "## Java v99 Precheck Echo",
    "",
    ...renderEntries(profile.upstreamReceipts.javaV99),
    "",
    "## mini-kv v108 Non-Participation",
    "",
    ...renderEntries(profile.upstreamReceipts.miniKvV108),
    "",
    "## Receipt Verification",
    "",
    ...renderEntries(profile.receiptVerification),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No precheck upstream receipt verification blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No precheck upstream receipt verification warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No precheck upstream receipt verification recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
