import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightGuardTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_GUARDS:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightGuardTemplate[]
  = Object.freeze([
    guard("Node v1137", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REQUEST_MANIFEST_GUARD",
      "identity-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REQUEST_MANIFEST_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_REQUEST_MANIFEST_SLOT_MISSING",
      "Block draft review package preflight unless the request manifest slot is reviewable."),
    guard("Node v1138", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_ARTIFACT_PREFLIGHT_DIGEST_GUARD",
      "digest-binding-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_ARTIFACT_PREFLIGHT_DIGEST_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_ARTIFACT_PREFLIGHT_DIGEST_SLOT_MISSING",
      "Block draft review package preflight unless the artifact preflight digest slot is pinned."),
    guard("Node v1139", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_TEMPLATE_DIGEST_GUARD",
      "digest-binding-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_TEMPLATE_DIGEST_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_TEMPLATE_DIGEST_SLOT_MISSING",
      "Block draft review package preflight unless the template digest slot is pinned."),
    guard("Node v1140", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REVIEW_DIGEST_GUARD",
      "digest-binding-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REVIEW_DIGEST_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_REVIEW_DIGEST_SLOT_MISSING",
      "Block draft review package preflight unless the approval review digest slot is pinned."),
    guard("Node v1141", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_OPERATOR_IDENTITY_GUARD",
      "identity-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_OPERATOR_IDENTITY_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_OPERATOR_IDENTITY_SLOT_MISSING",
      "Block draft review package preflight unless operator identity is reviewable."),
    guard("Node v1142", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_OPERATOR_ROLE_GUARD",
      "identity-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_OPERATOR_ROLE_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_OPERATOR_ROLE_SLOT_MISSING",
      "Block draft review package preflight unless operator role is reviewable."),
    guard("Node v1143", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_WINDOW_ID_GUARD",
      "identity-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_WINDOW_ID_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_WINDOW_ID_SLOT_MISSING",
      "Block draft review package preflight unless the capture window slot is reviewable."),
    guard("Node v1144", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_CHANNEL_POLICY_GUARD",
      "policy-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_CHANNEL_POLICY_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_CHANNEL_POLICY_SLOT_MISSING",
      "Block draft review package preflight unless the channel policy slot is reviewable."),
    guard("Node v1145", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIGNATURE_ALGORITHM_GUARD",
      "signature-envelope-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIGNATURE_ALGORITHM_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_SIGNATURE_ALGORITHM_SLOT_MISSING",
      "Block draft review package preflight unless signature algorithm policy is reviewable."),
    guard("Node v1146", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_DETACHED_SIGNATURE_GUARD",
      "signature-envelope-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_DETACHED_SIGNATURE_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_DETACHED_SIGNATURE_SLOT_MISSING",
      "Block draft review package preflight unless detached signature stays a placeholder."),
    guard("Node v1147", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIGNATURE_REDACTION_GUARD",
      "signature-envelope-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIGNATURE_REDACTION_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_SIGNATURE_REDACTION_SLOT_MISSING",
      "Block draft review package preflight unless signature redaction policy is reviewable."),
    guard("Node v1148", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_APPROVAL_STATEMENT_DIGEST_GUARD",
      "digest-binding-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_APPROVAL_STATEMENT_DIGEST_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_APPROVAL_STATEMENT_DIGEST_SLOT_MISSING",
      "Block draft review package preflight unless the approval statement digest slot is pinned."),
    guard("Node v1149", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_VERSION_GUARD",
      "source-evidence-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_VERSION_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_SOURCE_VERSION_SLOT_MISSING",
      "Block draft review package preflight unless the source version slot is reviewable."),
    guard("Node v1150", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_FILE_GUARD",
      "source-evidence-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_FILE_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_SOURCE_FILE_SLOT_MISSING",
      "Block draft review package preflight unless the source file slot is reviewable."),
    guard("Node v1151", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_SNIPPET_GUARD",
      "source-evidence-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SOURCE_SNIPPET_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_SOURCE_SNIPPET_SLOT_MISSING",
      "Block draft review package preflight unless the source snippet slot is reviewable."),
    guard("Node v1152", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REDACTED_VALUE_DIGEST_GUARD",
      "value-binding-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REDACTED_VALUE_DIGEST_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_REDACTED_VALUE_DIGEST_SLOT_MISSING",
      "Block draft review package preflight unless the redacted value digest slot is pinned."),
    guard("Node v1153", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_VALUE_SHAPE_GUARD",
      "value-binding-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_VALUE_SHAPE_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_VALUE_SHAPE_SLOT_MISSING",
      "Block draft review package preflight unless value shape metadata is reviewable."),
    guard("Node v1154", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REDACTION_POLICY_GUARD",
      "policy-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_REDACTION_POLICY_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_REDACTION_POLICY_SLOT_MISSING",
      "Block draft review package preflight unless redaction policy is reviewable."),
    guard("Node v1155", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_PROVENANCE_POLICY_GUARD",
      "policy-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_PROVENANCE_POLICY_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_PROVENANCE_POLICY_SLOT_MISSING",
      "Block draft review package preflight unless provenance policy is reviewable."),
    guard("Node v1156", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_RAW_SECRET_EMBARGO_GUARD",
      "execution-lock-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_RAW_SECRET_EMBARGO_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_RAW_SECRET_EMBARGO_SLOT_MISSING",
      "Block draft review package preflight if raw secret embargo evidence is missing."),
    guard("Node v1157", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_APPROVAL_GRANT_EMBARGO_GUARD",
      "execution-lock-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_APPROVAL_GRANT_EMBARGO_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_APPROVAL_GRANT_EMBARGO_SLOT_MISSING",
      "Block draft review package preflight if approval grant embargo evidence is missing."),
    guard("Node v1158", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_ZERO_VALUE_IMPORT_EMBARGO_GUARD",
      "execution-lock-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_ZERO_VALUE_IMPORT_EMBARGO_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_ZERO_VALUE_IMPORT_EMBARGO_SLOT_MISSING",
      "Block draft review package preflight if zero value import evidence is missing."),
    guard("Node v1159", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_WRITE_ROUTE_EMBARGO_GUARD",
      "execution-lock-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_WRITE_ROUTE_EMBARGO_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_WRITE_ROUTE_EMBARGO_SLOT_MISSING",
      "Block draft review package preflight if write route embargo evidence is missing."),
    guard("Node v1160", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIBLING_NON_MUTATION_GUARD",
      "execution-lock-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_SIBLING_NON_MUTATION_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_SIBLING_NON_MUTATION_SLOT_MISSING",
      "Block draft review package preflight if sibling non-mutation evidence is missing."),
    guard("Node v1161", "ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_CLOSEOUT_GUARD",
      "archive-closeout-review-package-guard",
      "SIGNED_APPROVAL_CAPTURE_ARTIFACT_DRAFT_REVIEW_PACKAGE_PREFLIGHT_CLOSEOUT_SLOT",
      "REJECT_DRAFT_REVIEW_PACKAGE_NEXT_STEP_NOT_HUMAN_DRAFT_AUTHORING",
      "Block draft review package preflight unless the next step is separate human draft artifact authoring."),
  ]);

function guard(
  nodeVersion:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightGuardTemplate[
      "nodeVersion"
    ],
  code: string,
  kind:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightGuardTemplate[
      "kind"
    ],
  sourcePackageSlotCode: string,
  blockerCode: string,
  guardText: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactDraftReviewPackagePreflightGuardTemplate {
  return {
    nodeVersion,
    code,
    kind,
    sourcePackageSlotCode,
    blockerCode,
    guardText,
  };
}
