import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactPreflightFragmentTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactPreflightTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_VERSIONS = [
  "Node v1062",
  "Node v1063",
  "Node v1064",
  "Node v1065",
  "Node v1066",
  "Node v1067",
  "Node v1068",
  "Node v1069",
  "Node v1070",
  "Node v1071",
  "Node v1072",
  "Node v1073",
  "Node v1074",
  "Node v1075",
  "Node v1076",
  "Node v1077",
  "Node v1078",
  "Node v1079",
  "Node v1080",
  "Node v1081",
  "Node v1082",
  "Node v1083",
  "Node v1084",
  "Node v1085",
  "Node v1086",
] as const;

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_FRAGMENTS:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactPreflightFragmentTemplate[]
  = Object.freeze([
    fragment("Node v1062", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_REQUEST_ID",
      "captureArtifactPreflightRequestId", "identity-fragment", "operator-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_REQUEST_ID", "capturePreflightRequestId",
      "ARTIFACT_PREFLIGHT_REQUEST_ID_MISSING", "Stable id for the future signed approval capture artifact."),
    fragment("Node v1063", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_CAPTURE_PREFLIGHT_DIGEST",
      "sourceSignedApprovalCapturePreflightDigest", "digest-binding-fragment", "digest-reference",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_TEMPLATE_DIGEST", "sourceSignedApprovalTemplateDigest",
      "ARTIFACT_PREFLIGHT_CAPTURE_PREFLIGHT_DIGEST_MISSING",
      "Digest binding to the v1061 capture preflight."),
    fragment("Node v1064", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_TEMPLATE_DIGEST",
      "sourceSignedApprovalTemplateDigest", "digest-binding-fragment", "digest-reference",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_TEMPLATE_DIGEST", "sourceSignedApprovalTemplateDigest",
      "ARTIFACT_PREFLIGHT_TEMPLATE_DIGEST_MISSING", "Digest binding to the v1036 signed approval template."),
    fragment("Node v1065", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_REVIEW_DIGEST",
      "sourceApprovalPacketReviewDigest", "digest-binding-fragment", "digest-reference",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_REVIEW_DIGEST", "sourceApprovalPacketReviewDigest",
      "ARTIFACT_PREFLIGHT_REVIEW_DIGEST_MISSING", "Digest binding to the upstream approval packet review."),
    fragment("Node v1066", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_OPERATOR_IDENTITY",
      "operatorIdentity", "identity-fragment", "operator-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_OPERATOR_IDENTITY", "operatorIdentity",
      "ARTIFACT_PREFLIGHT_OPERATOR_IDENTITY_MISSING", "Operator identity fragment required before artifact draft."),
    fragment("Node v1067", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_OPERATOR_ROLE",
      "operatorRole", "identity-fragment", "operator-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_OPERATOR_ROLE", "operatorRole",
      "ARTIFACT_PREFLIGHT_OPERATOR_ROLE_MISSING", "Operator role fragment required before artifact draft."),
    fragment("Node v1068", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_WINDOW_ID",
      "captureWindowId", "identity-fragment", "operator-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_WINDOW_ID", "captureWindowId",
      "ARTIFACT_PREFLIGHT_WINDOW_ID_MISSING", "Manual capture window id fragment."),
    fragment("Node v1069", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_CHANNEL_POLICY",
      "captureChannelPolicy", "policy-fragment", "policy-code",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_CHANNEL", "captureChannel",
      "ARTIFACT_PREFLIGHT_CHANNEL_POLICY_MISSING", "Capture channel policy fragment."),
    fragment("Node v1070", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SIGNATURE_ALGORITHM",
      "signatureAlgorithmPolicy", "signature-envelope-fragment", "policy-code",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SIGNATURE_ALGORITHM", "signatureAlgorithmPolicy",
      "ARTIFACT_PREFLIGHT_SIGNATURE_ALGORITHM_MISSING", "Signature algorithm policy fragment."),
    fragment("Node v1071", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_DETACHED_SIGNATURE_PLACEHOLDER",
      "detachedSignaturePlaceholder", "signature-envelope-fragment", "detached-signature-placeholder",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_APPROVAL_STATEMENT", "approvalStatement",
      "ARTIFACT_PREFLIGHT_DETACHED_SIGNATURE_PLACEHOLDER_MISSING",
      "Detached signature placeholder; no signature material is captured."),
    fragment("Node v1072", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SIGNATURE_REDACTION",
      "signatureMaterialRedactionPolicy", "signature-envelope-fragment", "policy-code",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SIGNATURE_REDACTION", "signatureMaterialRedactionPolicy",
      "ARTIFACT_PREFLIGHT_SIGNATURE_REDACTION_MISSING", "Signature material redaction policy fragment."),
    fragment("Node v1073", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_APPROVAL_STATEMENT_DIGEST",
      "approvalStatementDigest", "digest-binding-fragment", "digest-reference",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_APPROVAL_STATEMENT", "approvalStatement",
      "ARTIFACT_PREFLIGHT_APPROVAL_STATEMENT_DIGEST_MISSING",
      "Digest placeholder for the future approval statement."),
    fragment("Node v1074", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SOURCE_VERSION",
      "sourceEvidenceVersion", "source-evidence-fragment", "operator-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SOURCE_VERSION", "sourceEvidenceVersion",
      "ARTIFACT_PREFLIGHT_SOURCE_VERSION_MISSING", "Source evidence version fragment."),
    fragment("Node v1075", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SOURCE_FILE",
      "sourceEvidenceFileId", "source-evidence-fragment", "operator-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SOURCE_FILE", "sourceEvidenceFileId",
      "ARTIFACT_PREFLIGHT_SOURCE_FILE_MISSING", "Source evidence file id fragment."),
    fragment("Node v1076", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SOURCE_SNIPPET",
      "sourceEvidenceSnippetId", "source-evidence-fragment", "operator-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SOURCE_SNIPPET", "sourceEvidenceSnippetId",
      "ARTIFACT_PREFLIGHT_SOURCE_SNIPPET_MISSING", "Source evidence snippet id fragment."),
    fragment("Node v1077", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_REDACTED_VALUE_DIGEST",
      "redactedValueDigest", "value-binding-fragment", "digest-reference",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_REDACTED_VALUE_DIGEST", "redactedValueDigest",
      "ARTIFACT_PREFLIGHT_REDACTED_VALUE_DIGEST_MISSING", "Redacted value digest fragment."),
    fragment("Node v1078", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_VALUE_SHAPE",
      "valueShape", "value-binding-fragment", "operator-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_VALUE_SHAPE", "valueShape",
      "ARTIFACT_PREFLIGHT_VALUE_SHAPE_MISSING", "Typed value shape fragment."),
    fragment("Node v1079", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_REDACTION_POLICY",
      "redactionPolicy", "policy-fragment", "policy-code",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_REDACTION_POLICY", "redactionPolicy",
      "ARTIFACT_PREFLIGHT_REDACTION_POLICY_MISSING", "Redaction policy fragment."),
    fragment("Node v1080", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_PROVENANCE_POLICY",
      "provenancePolicy", "policy-fragment", "policy-code",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_PROVENANCE_POLICY", "provenancePolicy",
      "ARTIFACT_PREFLIGHT_PROVENANCE_POLICY_MISSING", "Provenance policy fragment."),
    fragment("Node v1081", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_NO_RAW_SECRET_LOCK",
      "noRawSecretLock", "execution-lock-fragment", "boolean-lock",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_NO_RAW_SECRET_LOCK", "noRawSecretLock",
      "ARTIFACT_PREFLIGHT_NO_RAW_SECRET_LOCK_MISSING", "Lock proving raw signature material is absent."),
    fragment("Node v1082", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_NO_GRANT_LOCK",
      "noApprovalGrantEmittedLock", "execution-lock-fragment", "boolean-lock",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_NO_GRANT_LOCK", "noApprovalGrantEmittedLock",
      "ARTIFACT_PREFLIGHT_NO_GRANT_LOCK_MISSING", "Lock proving no approval grant was emitted."),
    fragment("Node v1083", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_ZERO_VALUE_IMPORT_LOCK",
      "zeroValueImportLock", "execution-lock-fragment", "boolean-lock",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_ZERO_VALUE_SUBMISSION_LOCK", "zeroValueSubmissionLock",
      "ARTIFACT_PREFLIGHT_ZERO_VALUE_IMPORT_LOCK_MISSING", "Lock proving value submission and import stay zero."),
    fragment("Node v1084", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_NO_WRITE_ROUTE_LOCK",
      "noWriteRouteLock", "execution-lock-fragment", "boolean-lock",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_NO_WRITE_ROUTE_LOCK", "noWriteRouteLock",
      "ARTIFACT_PREFLIGHT_NO_WRITE_ROUTE_LOCK_MISSING", "Lock proving no write route is enabled."),
    fragment("Node v1085", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_SIBLING_NON_MUTATION_LOCK",
      "siblingNonMutationLock", "execution-lock-fragment", "boolean-lock",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SIBLING_NON_MUTATION_LOCK", "siblingNonMutationLock",
      "ARTIFACT_PREFLIGHT_SIBLING_NON_MUTATION_LOCK_MISSING", "Lock proving sibling projects remain unchanged."),
    fragment("Node v1086", "SIGNED_APPROVAL_CAPTURE_ARTIFACT_PREFLIGHT_CLOSEOUT",
      "signedApprovalCaptureArtifactPreflightCloseout", "closeout-fragment", "operator-entry-placeholder",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_CLOSEOUT", "signedApprovalCapturePreflightCloseout",
      "ARTIFACT_PREFLIGHT_CLOSEOUT_MISSING", "Closeout limiting the next step to signed approval artifact draft."),
  ]);

function fragment(
  nodeVersion:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactPreflightFragmentTemplate[
      "nodeVersion"
    ],
  code: string,
  fragmentName: string,
  kind:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactPreflightFragmentTemplate[
      "kind"
    ],
  valueMode:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactPreflightFragmentTemplate[
      "valueMode"
    ],
  sourceCaptureInputCode: string,
  requiredCaptureInputName: string,
  artifactBlockerCode: string,
  fragmentPurpose: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCaptureArtifactPreflightFragmentTemplate {
  return {
    nodeVersion,
    code,
    fragmentName,
    kind,
    valueMode,
    sourceCaptureInputCode,
    requiredCaptureInputName,
    artifactBlockerCode,
    fragmentPurpose,
  };
}
