import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ArchiveFileReference,
  ManagedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationSmokeArchiveVerificationProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationSmokeArchiveVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationSmokeArchiveVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationSmokeArchiveVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver minimal read-only integration smoke archive verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Archive verification state: ${profile.archiveVerificationState}`,
    `- Archive result: ${profile.archiveResult}`,
    `- Archive decision: ${profile.archiveDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for archive verification: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationSmokeArchiveVerification}`,
    `- Ready for Node v348 rerun decision: ${profile.readyForNodeV348MinimalReadOnlyIntegrationRerunDecision}`,
    `- Requires Java v153 + mini-kv v144 echo: ${profile.requiresParallelJavaV153MiniKvV144ReadOnlyEcho}`,
    `- Reruns live probe: ${profile.rerunsLiveProbe}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Reads managed audit credential: ${profile.readsManagedAuditCredential}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v346",
    "",
    ...renderEntries(profile.sourceNodeV346),
    "",
    "## Archive Verification",
    "",
    ...renderEntries(profile.archiveVerification),
    "",
    "## Archive References",
    "",
    ...renderArchiveFileReferences([
      profile.archiveReferences.jsonEvidence,
      profile.archiveReferences.markdownEvidence,
      profile.archiveReferences.smokeSummary,
      profile.archiveReferences.browserSnapshot,
      profile.archiveReferences.htmlArchive,
      profile.archiveReferences.screenshot,
      profile.archiveReferences.explanation,
      profile.archiveReferences.codeWalkthrough,
      profile.archiveReferences.activePlan,
      profile.archiveReferences.plansIndex,
    ]),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderArchiveFileReferences(files: readonly ArchiveFileReference[]): string[] {
  return files.map((file) =>
    `- ${file.path}: exists=${file.exists}; bytes=${file.byteLength}; digest=${file.digest ?? "missing"}`);
}
