import { sha256StableJson } from "./liveProbeReportUtils.js";
import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowCommandWorksheet,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowCommandWorksheetTarget,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowCommandWorksheetTypes.js";
import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowEvidencePacket,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowEvidencePacketGates,
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowEvidencePacketRecord,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowEvidencePacketTypes.js";

const EXPECTED_EVIDENCE_PACKET_VERSIONS = [
  "Node v772",
  "Node v773",
  "Node v774",
  "Node v775",
  "Node v776",
  "Node v777",
  "Node v778",
  "Node v779",
  "Node v780",
  "Node v781",
  "Node v782",
  "Node v783",
  "Node v784",
  "Node v785",
  "Node v786",
  "Node v787",
  "Node v788",
  "Node v789",
  "Node v790",
  "Node v791",
] as const;

const REQUIRED_TARGETS: readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowCommandWorksheetTarget[] = [
  "node-http",
  "java-http",
  "mini-kv-tcp",
  "archive",
  "policy",
];

type EvidenceTemplate = Omit<ControlledReadOnlyShardPreviewLiveReadOnlyWindowEvidencePacketRecord,
  "order"
  | "captureState"
  | "runtimePayloadCaptured"
  | "containsSecretValue"
  | "readOnly"
  | "writesAllowed"
  | "automaticServiceStart"
  | "startsServices"
  | "mutatesSiblingState">;

const EVIDENCE_TEMPLATES: readonly EvidenceTemplate[] = Object.freeze([
  record("Node v772", "EVIDENCE_SOURCE_WORKSHEET_CHECK", "source-verification",
    "WORKSHEET_CLOSEOUT_RECORD", "node", "archive", "source-worksheet-verification-record", false,
    ["worksheetVersion", "worksheetState", "worksheetDigest", "blockedReasonCodes"],
    ["worksheet state is ready-for-manual-command-review", "worksheet digest is sha256"],
    "Record digest and state only; do not include command output.", "source-worksheet-blocked"),
  record("Node v773", "EVIDENCE_OPERATOR_CONTEXT_RECORD", "operator-context",
    "WORKSHEET_ENVIRONMENT_LOCK_CHECK", "operator", "policy", "operator-context-record", false,
    ["operatorRole", "approvalReference", "upstreamProbesEnabled", "upstreamActionsEnabled"],
    ["operator context is present", "actions remain disabled"],
    "Record approval reference only; do not include credential values.", "operator-context-missing"),
  record("Node v774", "EVIDENCE_NODE_HEALTH_RECORD", "command-evidence",
    "WORKSHEET_NODE_HEALTH_READ_TEMPLATE", "node", "node-http", "node-health-evidence-record", false,
    ["statusCode", "readOnlyHeaderNames", "latencyMs", "healthSummary"],
    ["status code is 200 or explicitly triaged", "no write route is invoked"],
    "Redact header values and response internals beyond health summary.", "node-health-evidence-failed"),
  record("Node v775", "EVIDENCE_NODE_MARKDOWN_RECORD", "command-evidence",
    "WORKSHEET_NODE_MARKDOWN_READ_TEMPLATE", "node", "node-http", "node-markdown-evidence-record", false,
    ["statusCode", "contentType", "markdownSectionCount", "profileDigest"],
    ["Markdown route returns 200", "command worksheet section is present"],
    "Archive section names and digest only; do not include secret headers.", "node-markdown-evidence-failed"),
  record("Node v776", "EVIDENCE_JAVA_SHARD_READINESS_RECORD", "command-evidence",
    "WORKSHEET_JAVA_SHARD_READINESS_TEMPLATE", "java", "java-http", "java-shard-readiness-evidence-record",
    false, ["statusCode", "shardCount", "slotCount", "routingMode"],
    ["Java response is read-only readiness", "Java was operator-started"],
    "Capture readiness summary only; do not include Java credentials.", "java-shard-readiness-evidence-failed"),
  record("Node v777", "EVIDENCE_MINI_KV_SHARDJSON_RECORD", "command-evidence",
    "WORKSHEET_MINI_KV_SHARDJSON_TEMPLATE", "miniKv", "mini-kv-tcp", "mini-kv-shardjson-evidence-record",
    false, ["command", "shardMapCount", "slotCount", "routingMode"],
    ["command is SHARDJSON", "no LOAD/RESTORE/COMPACT command is sent"],
    "Capture command name and summary counts only.", "mini-kv-shardjson-evidence-failed"),
  record("Node v778", "EVIDENCE_HEADER_REDACTION_RECORD", "policy-evidence",
    "WORKSHEET_HEADER_REDACTION_TEMPLATE", "node", "policy", "header-redaction-evidence-record", false,
    ["headerNameCount", "redactedValueCount", "redactionPolicy"],
    ["every header value is redacted", "no secret value is archived"],
    "Only header names and redaction counts are allowed.", "header-redaction-evidence-failed"),
  record("Node v779", "EVIDENCE_MINI_KV_ALLOWLIST_RECORD", "policy-evidence",
    "WORKSHEET_MINI_KV_ALLOWLIST_TEMPLATE", "miniKv", "policy", "mini-kv-allowlist-evidence-record", false,
    ["allowedCommand", "forbiddenCommandCount", "allowlistDecision"],
    ["SHARDJSON is the only command used", "mutating commands remain forbidden"],
    "Record command names only.", "mini-kv-allowlist-evidence-failed"),
  record("Node v780", "EVIDENCE_FORBIDDEN_OPERATION_RECORD", "policy-evidence",
    "WORKSHEET_FORBIDDEN_OPERATION_CONFIRMATION", "crossProject", "policy",
    "forbidden-operation-evidence-record", false,
    ["writeRoutingEnabled", "loadRestoreCompactAttempted", "siblingMutationAttempted"],
    ["write routing is false", "mutating operations are absent"],
    "Record boolean flags only.", "forbidden-operation-evidence-failed"),
  record("Node v781", "EVIDENCE_NODE_ACCEPTANCE_RULE", "acceptance-rule",
    "WORKSHEET_EVIDENCE_CAPTURE_NODE", "node", "archive", "node-acceptance-rule-record", false,
    ["nodeEvidenceStatus", "nodeDigest", "nodeFailureClass"],
    ["Node evidence is accepted or triaged", "Node digest is sha256 when present"],
    "Record digest and triage class only.", "node-acceptance-rule-failed"),
  record("Node v782", "EVIDENCE_JAVA_ACCEPTANCE_RULE", "acceptance-rule",
    "WORKSHEET_EVIDENCE_CAPTURE_JAVA", "java", "archive", "java-acceptance-rule-record", false,
    ["javaEvidenceStatus", "javaReadOnlyStatus", "javaFailureClass"],
    ["Java evidence is accepted or triaged", "Java read-only status is explicit"],
    "Record readiness summary only.", "java-acceptance-rule-failed"),
  record("Node v783", "EVIDENCE_MINI_KV_ACCEPTANCE_RULE", "acceptance-rule",
    "WORKSHEET_EVIDENCE_CAPTURE_MINI_KV", "miniKv", "archive", "mini-kv-acceptance-rule-record", false,
    ["miniKvEvidenceStatus", "miniKvCommand", "miniKvFailureClass"],
    ["mini-kv evidence is accepted or triaged", "command remains SHARDJSON"],
    "Record command and summary only.", "mini-kv-acceptance-rule-failed"),
  record("Node v784", "EVIDENCE_NODE_CLEANUP_RECORD", "cleanup-record",
    "WORKSHEET_CLEANUP_CAPTURE_NODE", "node", "archive", "node-cleanup-evidence-record", true,
    ["nodeProcessOwner", "nodePidIfStarted", "nodeCloseResult"],
    ["operator-started Node process is closed or not started", "Node cleanup owner is recorded"],
    "Record PID only when operator started it; do not include environment secrets.", "node-cleanup-evidence-missing"),
  record("Node v785", "EVIDENCE_SIBLING_CLEANUP_RECORD", "cleanup-record",
    "WORKSHEET_CLEANUP_CAPTURE_SIBLING", "crossProject", "archive", "sibling-cleanup-evidence-record", true,
    ["javaCleanupOwner", "miniKvCleanupOwner", "siblingCloseResult"],
    ["Node does not own sibling lifecycle", "sibling cleanup result is recorded"],
    "Record owner and close result only.", "sibling-cleanup-evidence-missing"),
  record("Node v786", "EVIDENCE_NODE_FAILURE_TRIAGE_RECORD", "failure-triage",
    "WORKSHEET_FAILURE_TRIAGE_NODE", "node", "policy", "node-failure-triage-evidence-record", false,
    ["nodeFailureClass", "nodeRetryDecision", "nodeStopDecision"],
    ["retry decision is read-only", "stop decision blocks mutation"],
    "Record failure class and decision only.", "node-failure-triage-evidence-missing"),
  record("Node v787", "EVIDENCE_SIBLING_FAILURE_TRIAGE_RECORD", "failure-triage",
    "WORKSHEET_FAILURE_TRIAGE_JAVA_MINI_KV", "crossProject", "policy",
    "sibling-failure-triage-evidence-record", false,
    ["siblingFailureClass", "siblingRetryDecision", "siblingStopDecision"],
    ["retry decision is read-only", "write actions remain disabled"],
    "Record failure class and decision only.", "sibling-failure-triage-evidence-missing"),
  record("Node v788", "EVIDENCE_ARCHIVE_SNAPSHOT_RECORD", "archive-record",
    "WORKSHEET_ARCHIVE_SNAPSHOT_RECORD", "node", "archive", "archive-snapshot-evidence-record", false,
    ["archiveSnapshotDigest", "recordCount", "cleanupRecordCount"],
    ["archive snapshot covers all evidence records", "runtime payload remains excluded"],
    "Archive digests and counts only.", "archive-snapshot-evidence-missing"),
  record("Node v789", "EVIDENCE_ARCHIVE_VERIFICATION_RECORD", "archive-record",
    "WORKSHEET_ARCHIVE_VERIFICATION_RECORD", "node", "archive", "archive-verification-evidence-record", false,
    ["archiveVerificationDigest", "passedGateCount", "blockedReasonCodes"],
    ["archive verification digest is sha256", "blocked reasons are explicit"],
    "Archive verification summary only.", "archive-verification-evidence-missing"),
  record("Node v790", "EVIDENCE_GO_NO_GO_RECEIPT_RECORD", "handoff",
    "WORKSHEET_GO_NO_GO_RECORD", "operator", "policy", "go-no-go-receipt-evidence-record", false,
    ["manualDecision", "decisionScope", "productionExecutionAllowed"],
    ["decision scope is read-only evidence capture", "production execution remains false"],
    "Record decision label only.", "go-no-go-receipt-evidence-missing"),
  record("Node v791", "EVIDENCE_PACKET_CLOSEOUT_RECORD", "closeout",
    "WORKSHEET_CLOSEOUT_RECORD", "node", "archive", "evidence-packet-closeout-record", false,
    ["evidencePacketDigest", "readyForManualEvidenceCapture", "readyForLiveExecution"],
    ["packet is ready for manual evidence capture", "live execution remains false"],
    "Record packet digest and readiness flags only.", "evidence-packet-closeout-blocked"),
]);

export function createControlledReadOnlyShardPreviewLiveReadOnlyWindowEvidencePacket(
  worksheet: ControlledReadOnlyShardPreviewLiveReadOnlyWindowCommandWorksheet,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowEvidencePacket {
  const worksheetStepCodes = new Set(worksheet.steps.map((step) => step.code));
  const records = EVIDENCE_TEMPLATES.map((template, index) => ({
    ...template,
    order: index + 1,
    captureState: "pending-manual-capture" as const,
    runtimePayloadCaptured: false as const,
    containsSecretValue: false as const,
    readOnly: true as const,
    writesAllowed: false as const,
    automaticServiceStart: false as const,
    startsServices: false as const,
    mutatesSiblingState: false as const,
  }));
  const targets = new Set(records.map((record) => record.target));
  const gates: ControlledReadOnlyShardPreviewLiveReadOnlyWindowEvidencePacketGates = {
    sourceWorksheetReady: worksheet.readyForManualCommandReview,
    recordCountComplete: records.length === EXPECTED_EVIDENCE_PACKET_VERSIONS.length,
    versionsSequential: records.every((record, index) =>
      record.nodeVersion === EXPECTED_EVIDENCE_PACKET_VERSIONS[index]),
    eachRecordMapsWorksheetStep: records.every((record) => worksheetStepCodes.has(record.sourceWorksheetStepCode)),
    requiredFieldsPresent: records.every((record) => record.requiredFields.length > 0),
    acceptanceCriteriaPresent: records.every((record) => record.acceptanceCriteria.length > 0),
    redactionRulesPresent: records.every((record) => record.redactionRule.length > 0),
    cleanupRecordsPresent: records.filter((record) => record.cleanupRequired).length === 2,
    targetCoverageComplete: REQUIRED_TARGETS.every((target) => targets.has(target)),
    allRecordsPendingManualCapture: records.every((record) => record.captureState === "pending-manual-capture"),
    noRuntimePayloadCaptured: records.every((record) => !record.runtimePayloadCaptured),
    noSecretValues: records.every((record) => !record.containsSecretValue),
    allRecordsReadOnly: records.every((record) => record.readOnly),
    noWritesAllowed: records.every((record) => !record.writesAllowed),
    noAutomaticServiceStart: records.every((record) => !record.automaticServiceStart && !record.startsServices),
    productionExecutionBlocked: !worksheet.readyForProductionExecution && !worksheet.executionAllowed,
  };
  const blockedReasonCodes = createEvidencePacketBlockedReasons(gates);
  const readyForManualEvidenceCapture = blockedReasonCodes.length === 0;
  const evidencePacketDigest = sha256StableJson({
    evidencePacketVersion: "Node v791",
    inputCommandWorksheetVersion: worksheet.worksheetVersion,
    commandWorksheetDigest: worksheet.worksheetDigest,
    records: records.map((record) => [
      record.order,
      record.nodeVersion,
      record.code,
      record.kind,
      record.sourceWorksheetStepCode,
      record.target,
      record.recordSlot,
      record.requiredFields,
      record.acceptanceCriteria,
      record.cleanupRequired,
      record.failureClass,
    ]),
    gates,
  });

  return {
    evidencePacketVersion: "Node v791",
    inputCommandWorksheetVersion: "Node v771",
    packetState: readyForManualEvidenceCapture ? "ready-for-manual-evidence-capture" : "blocked",
    readyForManualEvidenceCapture,
    readyForLiveExecution: false,
    readyForProductionExecution: false,
    recordCount: records.length,
    targetCount: targets.size,
    commandEvidenceRecordCount: records.filter((record) => record.kind === "command-evidence").length,
    cleanupRecordCount: records.filter((record) => record.cleanupRequired).length,
    failureClassCount: new Set(records.map((record) => record.failureClass)).size,
    requiredFieldCount: records.reduce((count, record) => count + record.requiredFields.length, 0),
    acceptanceCriterionCount: records.reduce((count, record) => count + record.acceptanceCriteria.length, 0),
    gates,
    gateCount: Object.keys(gates).length,
    passedGateCount: Object.values(gates).filter(Boolean).length,
    blockedReasonCodes,
    records,
    evidencePacketDigest,
    executionAllowed: false,
    writeRoutingAllowed: false,
    startsServices: false,
    mutatesSiblingState: false,
    runtimePayloadCaptured: false,
    containsSecretValue: false,
  };
}

function record(
  nodeVersion: EvidenceTemplate["nodeVersion"],
  code: string,
  kind: EvidenceTemplate["kind"],
  sourceWorksheetStepCode: string,
  owner: EvidenceTemplate["owner"],
  target: EvidenceTemplate["target"],
  recordSlot: string,
  cleanupRequired: boolean,
  requiredFields: string[],
  acceptanceCriteria: string[],
  redactionRule: string,
  failureClass: string,
): EvidenceTemplate {
  return {
    nodeVersion,
    code,
    kind,
    sourceWorksheetStepCode,
    owner,
    target,
    recordSlot,
    cleanupRequired,
    requiredFields,
    acceptanceCriteria,
    redactionRule,
    failureClass,
  };
}

function createEvidencePacketBlockedReasons(
  gates: ControlledReadOnlyShardPreviewLiveReadOnlyWindowEvidencePacketGates,
): string[] {
  return [
    gates.sourceWorksheetReady ? null : "SOURCE_COMMAND_WORKSHEET_NOT_READY",
    gates.recordCountComplete ? null : "EVIDENCE_PACKET_RECORD_COUNT_INCOMPLETE",
    gates.versionsSequential ? null : "EVIDENCE_PACKET_VERSIONS_NOT_SEQUENTIAL",
    gates.eachRecordMapsWorksheetStep ? null : "EVIDENCE_PACKET_WORKSHEET_MAPPING_MISSING",
    gates.requiredFieldsPresent ? null : "EVIDENCE_PACKET_REQUIRED_FIELDS_MISSING",
    gates.acceptanceCriteriaPresent ? null : "EVIDENCE_PACKET_ACCEPTANCE_CRITERIA_MISSING",
    gates.redactionRulesPresent ? null : "EVIDENCE_PACKET_REDACTION_RULES_MISSING",
    gates.cleanupRecordsPresent ? null : "EVIDENCE_PACKET_CLEANUP_RECORDS_MISSING",
    gates.targetCoverageComplete ? null : "EVIDENCE_PACKET_TARGET_COVERAGE_INCOMPLETE",
    gates.allRecordsPendingManualCapture ? null : "EVIDENCE_PACKET_RECORD_ALREADY_CAPTURED",
    gates.noRuntimePayloadCaptured ? null : "EVIDENCE_PACKET_RUNTIME_PAYLOAD_CAPTURED",
    gates.noSecretValues ? null : "EVIDENCE_PACKET_SECRET_VALUE_PRESENT",
    gates.allRecordsReadOnly ? null : "EVIDENCE_PACKET_RECORD_NOT_READ_ONLY",
    gates.noWritesAllowed ? null : "EVIDENCE_PACKET_WRITES_ALLOWED",
    gates.noAutomaticServiceStart ? null : "EVIDENCE_PACKET_AUTOMATIC_SERVICE_START_ENABLED",
    gates.productionExecutionBlocked ? null : "EVIDENCE_PACKET_PRODUCTION_EXECUTION_ENABLED",
  ].filter((reason): reason is string => reason !== null);
}
