import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvDeclaredOperatorLifecycleEvidenceIntakeProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvDeclaredOperatorLifecycleEvidenceIntakeTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvDeclaredOperatorLifecycleEvidenceIntakeMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvDeclaredOperatorLifecycleEvidenceIntakeProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Intake state: ${profile.intakeState}`,
    `- Intake decision: ${profile.intakeDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for Node v389 archive verification: ${profile.readyForNodeV389ArchiveVerification}`,
    `- Ready for runtime live-read gate: ${profile.readyForRuntimeLiveReadGate}`,
    `- Evidence intake only: ${profile.evidenceIntakeOnly}`,
    `- Declared operator lifecycle evidence present: ${profile.declaredOperatorLifecycleEvidencePresent}`,
    `- Runtime gate requires separate approval: ${profile.runtimeGateRequiresSeparateApproval}`,
    `- Live read gate allowed: ${profile.liveReadGateAllowed}`,
    `- Runtime probe allowed: ${profile.runtimeProbeAllowed}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Stops Java service: ${profile.stopsJavaService}`,
    `- Stops mini-kv service: ${profile.stopsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Active shard prototype enabled: ${profile.activeShardPrototypeEnabled}`,
    "",
    "## Source Node v387",
    "",
    ...renderEntries(profile.sourceNodeV387),
    "",
    "## Java v161 Declared Operator Lifecycle",
    "",
    ...renderEntries(profile.javaDeclaredOperatorLifecycle),
    "",
    "## mini-kv v152 Declared Operator Lifecycle",
    "",
    ...renderEntries(profile.miniKvDeclaredOperatorLifecycle),
    "",
    "## mini-kv v151 Frozen Operator Template",
    "",
    ...renderEntries(profile.miniKvFrozenOperatorTemplate),
    "",
    "## Evidence Files",
    "",
    ...[
      profile.javaDeclaredOperatorLifecycleFile,
      profile.miniKvDeclaredOperatorLifecycleFile,
      profile.miniKvFrozenOperatorTemplateFile,
    ].map((file) =>
      `- ${file.id}: exists=${file.exists}; fallback=${file.usedHistoricalFallback}; bytes=${file.byteLength}; digest=${file.digest}; resolved=${file.resolvedPath}`),
    "",
    "## Intake",
    "",
    ...renderEntries(profile.intake),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
