import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  JavaV145SignedHumanApprovalArtifactContractIntakeEchoReference,
  ManagedAuditManualSandboxConnectionCredentialResolverSignedHumanApprovalArtifactContractUpstreamEchoVerificationProfile,
  MiniKvV138SignedHumanApprovalArtifactContractIntakeNonParticipationReceiptReference,
} from "./managedAuditManualSandboxConnectionCredentialResolverSignedHumanApprovalArtifactContractUpstreamEchoVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverSignedHumanApprovalArtifactContractUpstreamEchoVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverSignedHumanApprovalArtifactContractUpstreamEchoVerificationProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver signed human approval artifact contract upstream echo verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Verification state: ${profile.verificationState}`,
    `- Runtime shell chain decision: ${profile.runtimeShellChainDecision}`,
    `- Ready for upstream echo verification: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverSignedHumanApprovalArtifactContractUpstreamEchoVerification}`,
    `- Active Node verification version: ${profile.activeNodeVerificationVersion}`,
    `- Runtime shell implemented: ${profile.runtimeShellImplemented}`,
    `- Runtime shell invocation allowed: ${profile.runtimeShellInvocationAllowed}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v314",
    "",
    ...renderEntries({
      sourceVersion: profile.sourceNodeV314.sourceVersion,
      profileVersion: profile.sourceNodeV314.profileVersion,
      contractState: profile.sourceNodeV314.contractState,
      readyForArtifactIntake: profile.sourceNodeV314.readyForArtifactIntake,
      contractDigest: profile.sourceNodeV314.contractDigest,
      nextJavaVersion: profile.sourceNodeV314.nextJavaVersion,
      nextMiniKvVersion: profile.sourceNodeV314.nextMiniKvVersion,
      nextNodeVerificationVersion: profile.sourceNodeV314.nextNodeVerificationVersion,
      readyForParallelJavaV145MiniKvV138Echo: profile.sourceNodeV314.readyForParallelJavaV145MiniKvV138Echo,
    }),
    "",
    "## Java v145 Echo",
    "",
    ...renderJavaReference(profile.upstreamEvidence.javaV145),
    "",
    "## mini-kv v138 Receipt",
    "",
    ...renderMiniKvReference(profile.upstreamEvidence.miniKvV138),
    "",
    "## Echo Verification",
    "",
    ...renderEntries(profile.echoVerification),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No signed human approval artifact contract upstream echo verification blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No signed human approval artifact contract upstream echo verification warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No signed human approval artifact contract upstream echo verification recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderJavaReference(reference: JavaV145SignedHumanApprovalArtifactContractIntakeEchoReference): string[] {
  return [
    ...renderEntries({
      sourceVersion: reference.sourceVersion,
      receiptVersion: reference.receiptVersion,
      echoMode: reference.echoMode,
      sourceSpan: reference.sourceSpan,
      nextNodeVersion: reference.nextNodeVersion,
      evidencePresent: reference.evidencePresent,
      verificationDocumented: reference.verificationDocumented,
      echoesNodeV314Plan: reference.echoesNodeV314Plan,
      readyForNodeV315: reference.readyForNodeV315,
      artifactContractEchoed: reference.artifactContractEchoed,
      requiredFieldCountEchoed: reference.requiredFieldCountEchoed,
      prohibitedFieldCountEchoed: reference.prohibitedFieldCountEchoed,
      rejectionReasonCountEchoed: reference.rejectionReasonCountEchoed,
      noGoBoundaryCountEchoed: reference.noGoBoundaryCountEchoed,
      upstreamEchoRequestsEchoed: reference.upstreamEchoRequestsEchoed,
      necessityProofEchoed: reference.necessityProofEchoed,
      sideEffectBoundariesClosed: reference.sideEffectBoundariesClosed,
    }),
    "",
    "### Evidence Files",
    "",
    ...renderList(
      reference.evidenceFiles.map((file) => `${file.id}: exists=${file.exists}; size=${file.sizeBytes}; resolved=${file.resolvedPath}`),
      "No Java evidence files.",
    ),
    "",
    "### Expected Snippets",
    "",
    ...renderList(
      reference.expectedSnippets.map((snippet) => `${snippet.id}: matched=${snippet.matched}; resolved=${snippet.resolvedPath}`),
      "No Java expected snippets.",
    ),
  ];
}

function renderMiniKvReference(
  reference: MiniKvV138SignedHumanApprovalArtifactContractIntakeNonParticipationReceiptReference,
): string[] {
  return [
    ...renderEntries({
      sourceVersion: reference.sourceVersion,
      receiptVersion: reference.receiptVersion,
      releaseVersion: reference.releaseVersion,
      consumerHint: reference.consumerHint,
      receiptDigest: reference.receiptDigest,
      evidencePresent: reference.evidencePresent,
      verificationDocumented: reference.verificationDocumented,
      echoesNodeV314Plan: reference.echoesNodeV314Plan,
      readyForNodeV315: reference.readyForNodeV315,
      sourceNodeV314ProfileVersion: reference.sourceNodeV314ProfileVersion,
      sourceNodeV314ContractState: reference.sourceNodeV314ContractState,
      sourceNodeV314ContractDigest: reference.sourceNodeV314ContractDigest,
      requiredFieldCount: reference.requiredFieldCount,
      prohibitedFieldCount: reference.prohibitedFieldCount,
      rejectionReasonCount: reference.rejectionReasonCount,
      noGoBoundaryCount: reference.noGoBoundaryCount,
      upstreamEchoRequestCount: reference.upstreamEchoRequestCount,
      nonParticipationReceiptOnly: reference.nonParticipationReceiptOnly,
      sideEffectBoundariesClosed: reference.sideEffectBoundariesClosed,
    }),
    "",
    "### Evidence Files",
    "",
    ...renderList(
      reference.evidenceFiles.map((file) => `${file.id}: exists=${file.exists}; size=${file.sizeBytes}; resolved=${file.resolvedPath}`),
      "No mini-kv evidence files.",
    ),
    "",
    "### Expected Snippets",
    "",
    ...renderList(
      reference.expectedSnippets.map((snippet) => `${snippet.id}: matched=${snippet.matched}; resolved=${snippet.resolvedPath}`),
      "No mini-kv expected snippets.",
    ),
  ];
}


