import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionApprovedLocalLoopbackReadOnlySmokeProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionApprovedLocalLoopbackReadOnlySmokeTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionApprovedLocalLoopbackReadOnlySmokeMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionApprovedLocalLoopbackReadOnlySmokeProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Smoke state: ${profile.smokeState}`,
    `- Smoke decision: ${profile.smokeDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Java source version: ${profile.javaSourceVersion}`,
    `- mini-kv source version: ${profile.miniKvSourceVersion}`,
    `- Ready for approved local loopback read-only smoke: ${profile.readyForRuntimeExecutionApprovedLocalLoopbackReadOnlySmoke}`,
    `- Ready for pass evidence archive: ${profile.readyForRuntimeExecutionPassEvidenceArchive}`,
    `- Upstream probes enabled: ${profile.upstreamProbesEnabled}`,
    `- Upstream actions enabled: ${profile.upstreamActionsEnabled}`,
    `- Starts Java service from route: ${profile.startsJavaServiceFromRoute}`,
    `- Starts mini-kv service from route: ${profile.startsMiniKvServiceFromRoute}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v406",
    "",
    ...renderEntries(profile.sourceNodeV406),
    "",
    "## Targets",
    "",
    ...profile.targets.flatMap((target) => renderEntries(target)),
    "",
    "## Records",
    "",
    ...profile.records.flatMap((record) => renderEntries(record)),
    "",
    "## Smoke Session",
    "",
    ...renderEntries(profile.smokeSession),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
