import type {
  ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCapturePreflightAttestationTemplate,
} from "./managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCapturePreflightTypes.js";

export const CONTROLLED_READ_ONLY_SHARD_PREVIEW_VALUE_SUPPLY_SIGNED_APPROVAL_CAPTURE_PREFLIGHT_ATTESTATIONS:
  readonly ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCapturePreflightAttestationTemplate[]
  = Object.freeze([
    attestation("Node v1037", "CAPTURE_PREFLIGHT_REQUEST_ID_REQUIRED", "required-input-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_REQUEST_ID", "REJECT_CAPTURE_REQUEST_ID_MISSING",
      "Reject capture preflight without a stable capturePreflightRequestId."),
    attestation("Node v1038", "CAPTURE_PREFLIGHT_TEMPLATE_DIGEST_BOUND", "digest-binding-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_TEMPLATE_DIGEST", "REJECT_CAPTURE_TEMPLATE_DIGEST_MISSING",
      "Reject capture preflight without the v1036 signed approval template digest."),
    attestation("Node v1039", "CAPTURE_PREFLIGHT_REVIEW_DIGEST_BOUND", "digest-binding-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_REVIEW_DIGEST", "REJECT_CAPTURE_REVIEW_DIGEST_MISSING",
      "Reject capture preflight without the upstream approval packet review digest."),
    attestation("Node v1040", "CAPTURE_PREFLIGHT_OPERATOR_IDENTITY_REQUIRED", "required-input-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_OPERATOR_IDENTITY", "REJECT_CAPTURE_OPERATOR_IDENTITY_MISSING",
      "Reject capture preflight without an operator identity placeholder."),
    attestation("Node v1041", "CAPTURE_PREFLIGHT_OPERATOR_ROLE_REQUIRED", "required-input-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_OPERATOR_ROLE", "REJECT_CAPTURE_OPERATOR_ROLE_MISSING",
      "Reject capture preflight without an operator role placeholder."),
    attestation("Node v1042", "CAPTURE_PREFLIGHT_TIMESTAMP_SOURCE_REQUIRED", "required-input-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_TIMESTAMP_SOURCE", "REJECT_CAPTURE_TIMESTAMP_SOURCE_MISSING",
      "Reject capture preflight without a timestamp source placeholder."),
    attestation("Node v1043", "CAPTURE_PREFLIGHT_WINDOW_ID_REQUIRED", "required-input-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_WINDOW_ID", "REJECT_CAPTURE_WINDOW_ID_MISSING",
      "Reject capture preflight without a manual capture window id placeholder."),
    attestation("Node v1044", "CAPTURE_PREFLIGHT_CHANNEL_REQUIRED", "required-input-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_CHANNEL", "REJECT_CAPTURE_CHANNEL_MISSING",
      "Reject capture preflight without a declared capture channel policy."),
    attestation("Node v1045", "CAPTURE_PREFLIGHT_SIGNATURE_ALGORITHM_POLICY", "policy-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SIGNATURE_ALGORITHM", "REJECT_SIGNATURE_ALGORITHM_POLICY_MISSING",
      "Reject capture preflight without a signature algorithm policy."),
    attestation("Node v1046", "CAPTURE_PREFLIGHT_SIGNATURE_REDACTION_POLICY", "policy-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SIGNATURE_REDACTION", "REJECT_SIGNATURE_REDACTION_POLICY_MISSING",
      "Reject capture preflight without signature material redaction policy."),
    attestation("Node v1047", "CAPTURE_PREFLIGHT_APPROVAL_STATEMENT_REQUIRED", "required-input-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_APPROVAL_STATEMENT", "REJECT_APPROVAL_STATEMENT_MISSING",
      "Reject capture preflight without an approval statement placeholder."),
    attestation("Node v1048", "CAPTURE_PREFLIGHT_OPERATOR_JUSTIFICATION_REQUIRED", "required-input-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_OPERATOR_JUSTIFICATION", "REJECT_OPERATOR_JUSTIFICATION_MISSING",
      "Reject capture preflight without operator justification placeholder."),
    attestation("Node v1049", "CAPTURE_PREFLIGHT_SOURCE_VERSION_REQUIRED", "required-input-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SOURCE_VERSION", "REJECT_SOURCE_VERSION_MISSING",
      "Reject capture preflight without the source evidence version."),
    attestation("Node v1050", "CAPTURE_PREFLIGHT_SOURCE_FILE_REQUIRED", "required-input-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SOURCE_FILE", "REJECT_SOURCE_FILE_MISSING",
      "Reject capture preflight without the source evidence file id."),
    attestation("Node v1051", "CAPTURE_PREFLIGHT_SOURCE_SNIPPET_REQUIRED", "required-input-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SOURCE_SNIPPET", "REJECT_SOURCE_SNIPPET_MISSING",
      "Reject capture preflight without the source evidence snippet id."),
    attestation("Node v1052", "CAPTURE_PREFLIGHT_REDACTED_VALUE_DIGEST_REQUIRED", "required-input-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_REDACTED_VALUE_DIGEST", "REJECT_REDACTED_VALUE_DIGEST_MISSING",
      "Reject capture preflight without the redacted value digest reference."),
    attestation("Node v1053", "CAPTURE_PREFLIGHT_VALUE_SHAPE_REQUIRED", "required-input-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_VALUE_SHAPE", "REJECT_VALUE_SHAPE_MISSING",
      "Reject capture preflight without the typed value shape."),
    attestation("Node v1054", "CAPTURE_PREFLIGHT_REDACTION_POLICY_BOUND", "policy-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_REDACTION_POLICY", "REJECT_REDACTION_POLICY_MISSING",
      "Reject capture preflight without redact-before-persist policy."),
    attestation("Node v1055", "CAPTURE_PREFLIGHT_PROVENANCE_POLICY_BOUND", "policy-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_PROVENANCE_POLICY", "REJECT_PROVENANCE_POLICY_MISSING",
      "Reject capture preflight without source-evidence-required provenance policy."),
    attestation("Node v1056", "CAPTURE_PREFLIGHT_NO_RAW_SECRET_LOCK", "no-execution-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_NO_RAW_SECRET_LOCK", "REJECT_RAW_SECRET_PRESENT",
      "Block capture preflight if raw secret or signature material is present."),
    attestation("Node v1057", "CAPTURE_PREFLIGHT_NO_GRANT_LOCK", "no-execution-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_NO_GRANT_LOCK", "REJECT_APPROVAL_GRANT_EMITTED",
      "Block capture preflight if a signed approval grant has already been emitted."),
    attestation("Node v1058", "CAPTURE_PREFLIGHT_ZERO_VALUE_SUBMISSION_LOCK", "no-execution-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_ZERO_VALUE_SUBMISSION_LOCK", "REJECT_VALUE_SUBMISSION_NONZERO",
      "Block capture preflight if value submission, acceptance, or import counts are nonzero."),
    attestation("Node v1059", "CAPTURE_PREFLIGHT_NO_WRITE_ROUTE_LOCK", "no-execution-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_NO_WRITE_ROUTE_LOCK", "REJECT_WRITE_ROUTE_ENABLED",
      "Block capture preflight if any write route is enabled."),
    attestation("Node v1060", "CAPTURE_PREFLIGHT_SIBLING_NON_MUTATION_LOCK", "no-execution-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_SIBLING_NON_MUTATION_LOCK", "REJECT_SIBLING_MUTATION_ENABLED",
      "Block capture preflight if Java or mini-kv mutation is enabled."),
    attestation("Node v1061", "CAPTURE_PREFLIGHT_CLOSEOUT_ONLY", "closeout-attestation",
      "SIGNED_APPROVAL_CAPTURE_PREFLIGHT_CLOSEOUT", "REJECT_NEXT_STEP_NOT_CAPTURE_ARTIFACT_PREFLIGHT",
      "Close the preflight at signed approval capture artifact planning only."),
  ]);

function attestation(
  nodeVersion:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCapturePreflightAttestationTemplate[
      "nodeVersion"
    ],
  code: string,
  kind:
    ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCapturePreflightAttestationTemplate[
      "kind"
    ],
  sourceCaptureInputCode: string,
  rejectionCode: string,
  attestationText: string,
): ControlledReadOnlyShardPreviewLiveReadOnlyWindowOperatorEvidenceValueSupplySignedApprovalCapturePreflightAttestationTemplate {
  return {
    nodeVersion,
    code,
    kind,
    sourceCaptureInputCode,
    rejectionCode,
    attestationText,
  };
}
