import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverDisabledImplementationCandidateReviewProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverDisabledImplementationCandidateReviewTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverDisabledImplementationCandidateReviewMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverDisabledImplementationCandidateReviewProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver disabled implementation candidate review",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Review state: ${profile.reviewState}`,
    `- Ready for disabled implementation candidate review: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverDisabledImplementationCandidateReview}`,
    `- Ready for disabled resolver interface candidate: ${profile.readyForDisabledResolverInterfaceCandidate}`,
    `- Disabled implementation candidate review only: ${profile.disabledImplementationCandidateReviewOnly}`,
    `- Real resolver implementation allowed: ${profile.realResolverImplementationAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v272",
    "",
    ...renderEntries(profile.sourceNodeV272),
    "",
    "## Candidate Review",
    "",
    ...renderEntries({
      candidateVersion: profile.disabledImplementationCandidate.candidateVersion,
      candidateMode: profile.disabledImplementationCandidate.candidateMode,
      sourceSpan: profile.disabledImplementationCandidate.sourceSpan,
      candidateDigest: profile.disabledImplementationCandidate.candidateDigest,
      candidateDecisionCount: profile.disabledImplementationCandidate.candidateDecisionCount,
      candidateReadyDecisionCount: profile.disabledImplementationCandidate.candidateReadyDecisionCount,
      approvalRequiredDecisionCount: profile.disabledImplementationCandidate.approvalRequiredDecisionCount,
      disabledInterfaceCandidateAllowed: profile.disabledImplementationCandidate.disabledInterfaceCandidateAllowed,
      fakeWiringReviewAllowed: profile.disabledImplementationCandidate.fakeWiringReviewAllowed,
      realResolverImplementationAllowed: profile.disabledImplementationCandidate.realResolverImplementationAllowed,
      secretProviderRuntimeAllowed: profile.disabledImplementationCandidate.secretProviderRuntimeAllowed,
      credentialValueReadAllowed: profile.disabledImplementationCandidate.credentialValueReadAllowed,
      rawEndpointUrlParseAllowed: profile.disabledImplementationCandidate.rawEndpointUrlParseAllowed,
      externalRequestAllowed: profile.disabledImplementationCandidate.externalRequestAllowed,
      schemaMigrationAllowed: profile.disabledImplementationCandidate.schemaMigrationAllowed,
      approvalLedgerWriteAllowed: profile.disabledImplementationCandidate.approvalLedgerWriteAllowed,
      automaticUpstreamStartAllowed: profile.disabledImplementationCandidate.automaticUpstreamStartAllowed,
    }),
    "",
    "## Boundary Decisions",
    "",
    ...profile.disabledImplementationCandidate.decisions.map((decision) =>
      `- ${decision.code}: ${decision.disposition}; requirement=${decision.requirementFromV268}; owner=${decision.owner}; rule=${decision.candidateRule}`),
    "",
    "## Interface Shape",
    "",
    ...renderEntries(profile.disabledImplementationCandidate.interfaceShape),
    "",
    "## Fake Wiring Review",
    "",
    ...renderEntries(profile.disabledImplementationCandidate.fakeWiringReview),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No disabled implementation candidate review blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No disabled implementation candidate review warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No disabled implementation candidate review recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
