import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionLiveReadGateProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionLiveReadGateTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionLiveReadGateMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvRuntimeExecutionLiveReadGateProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Gate state: ${profile.gateState}`,
    `- Gate decision: ${profile.gateDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Java source version: ${profile.javaSourceVersion}`,
    `- mini-kv source version: ${profile.miniKvSourceVersion}`,
    `- Ready for runtime execution live-read gate: ${profile.readyForRuntimeExecutionLiveReadGate}`,
    `- Ready for approved local loopback read-only smoke: ${profile.readyForApprovedLocalLoopbackReadOnlySmoke}`,
    `- Runtime execution packet executable: ${profile.runtimeExecutionPacketExecutable}`,
    `- Runtime gate approval present: ${profile.runtimeGateApprovalPresent}`,
    `- Execution attempted: ${profile.executionAttempted}`,
    `- Runtime smoke attempted: ${profile.runtimeSmokeAttempted}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v405",
    "",
    ...renderEntries(profile.sourceNodeV405),
    "",
    "## Service Targets",
    "",
    ...profile.serviceTargets.flatMap((target) => renderEntries(target)),
    "",
    "## Live Read Gate",
    "",
    ...renderEntries(profile.liveReadGate),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
