import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type { MinimalReadOnlyIntegrationSmokeTargetResult } from "./managedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationSmokeRehearsalTypes.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationSmokeRerunArchiveProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationSmokeRerunArchiveTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationSmokeRerunArchiveMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverMinimalReadOnlyIntegrationSmokeRerunArchiveProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver minimal read-only integration smoke rerun archive",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Rerun archive state: ${profile.rerunArchiveState}`,
    `- Rerun archive result: ${profile.rerunArchiveResult}`,
    `- Rerun archive decision: ${profile.rerunArchiveDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- External read window confirmed: ${profile.externalReadWindowConfirmed}`,
    `- Live probe performed now: ${profile.liveProbePerformedNow}`,
    `- Requires Java v153 + mini-kv v144 echo: ${profile.requiresParallelJavaV153MiniKvV144ReadOnlyEcho}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Mutates Java state: ${profile.mutatesJavaState}`,
    `- Mutates mini-kv state: ${profile.mutatesMiniKvState}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Reads managed audit credential: ${profile.readsManagedAuditCredential}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v348",
    "",
    ...renderEntries(profile.sourceNodeV348),
    "",
    "## Rerun Archive",
    "",
    ...renderEntries(profile.rerunArchive),
    "",
    "## Target Results",
    "",
    ...profile.targetResults.flatMap(renderTargetResult),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderTargetResult(target: MinimalReadOnlyIntegrationSmokeTargetResult): string[] {
  return [
    `- ${target.project} ${target.methodOrCommand}:`,
    `  - targetName: ${target.targetName}`,
    `  - status: ${target.status}`,
    `  - readOnly: ${target.readOnly}`,
    `  - mutatesState: ${target.mutatesState}`,
    `  - attempted: ${target.attempted}`,
    `  - latencyMs: ${target.latencyMs ?? "n/a"}`,
    `  - statusCode: ${target.statusCode ?? "n/a"}`,
    `  - responseShape: ${target.responseShape}`,
    `  - errorCode: ${target.errorCode ?? "n/a"}`,
    `  - errorMessage: ${target.errorMessage ?? "n/a"}`,
  ];
}
