import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverImplementationPlanDraftProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverImplementationPlanDraftTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverImplementationPlanDraftMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverImplementationPlanDraftProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver implementation plan draft",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Plan state: ${profile.planState}`,
    `- Ready for implementation plan draft: ${profile.readyForManagedAuditManualSandboxConnectionCredentialResolverImplementationPlanDraft}`,
    `- Ready for Java v121 + mini-kv v126 echo: ${profile.readyForJavaV121MiniKvV126Echo}`,
    `- Ready for real resolver implementation: ${profile.readyForManagedAuditResolverImplementation}`,
    `- Real resolver implementation allowed: ${profile.realResolverImplementationAllowed}`,
    `- Test-only fake harness allowed: ${profile.testOnlyFakeHarnessAllowed}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    "",
    "## Source Node v282",
    "",
    ...renderEntries(profile.sourceNodeV282),
    "",
    "## Implementation Plan",
    "",
    ...renderEntries({
      planVersion: profile.implementationPlan.planVersion,
      planMode: profile.implementationPlan.planMode,
      sourceSpan: profile.implementationPlan.sourceSpan,
      planDigest: profile.implementationPlan.planDigest,
      interfaceBoundaryCount: profile.implementationPlan.interfaceBoundaryCount,
      requiredArtifactCount: profile.implementationPlan.requiredArtifactCount,
      prohibitedActionCount: profile.implementationPlan.prohibitedActionCount,
      allInterfaceBoundariesDefined: profile.implementationPlan.allInterfaceBoundariesDefined,
      allRequiredArtifactsNamed: profile.implementationPlan.allRequiredArtifactsNamed,
      realResolverImplementationAllowed: profile.implementationPlan.realResolverImplementationAllowed,
      testOnlyFakeHarnessAllowed: profile.implementationPlan.testOnlyFakeHarnessAllowed,
      secretProviderRuntimeAllowed: profile.implementationPlan.secretProviderRuntimeAllowed,
      credentialValueReadAllowed: profile.implementationPlan.credentialValueReadAllowed,
      rawEndpointUrlParseAllowed: profile.implementationPlan.rawEndpointUrlParseAllowed,
      rawEndpointUrlRenderAllowed: profile.implementationPlan.rawEndpointUrlRenderAllowed,
      externalRequestAllowed: profile.implementationPlan.externalRequestAllowed,
      schemaMigrationAllowed: profile.implementationPlan.schemaMigrationAllowed,
      approvalLedgerWriteAllowed: profile.implementationPlan.approvalLedgerWriteAllowed,
      automaticUpstreamStartAllowed: profile.implementationPlan.automaticUpstreamStartAllowed,
    }),
    "",
    "## Interface Boundaries",
    "",
    ...profile.implementationPlan.interfaceBoundaries.map((boundary) =>
      `- ${boundary.code}: ${boundary.status}; source=${boundary.sourceBoundary}; owner=${boundary.owner}; requiredArtifacts=${boundary.requiredArtifacts.join(",")}`),
    "",
    "## Java v121 Echo Requirements",
    "",
    ...profile.implementationPlan.javaV121EchoRequirements.map((requirement) =>
      `- ${requirement.id}: ${requirement.requirement}`),
    "",
    "## mini-kv v126 Receipt Requirements",
    "",
    ...profile.implementationPlan.miniKvV126ReceiptRequirements.map((requirement) =>
      `- ${requirement.id}: ${requirement.requirement}`),
    "",
    "## Implementation Plan Review",
    "",
    ...renderEntries(profile.implementationPlanReview),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No credential resolver implementation plan draft blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No credential resolver implementation plan draft warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No credential resolver implementation plan draft recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
