import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverSandboxHandleReviewContractDecisionProfile,
  SandboxHandleReviewContractInput,
  SandboxHandleReviewContractSection,
} from "./managedAuditManualSandboxConnectionCredentialResolverSandboxHandleReviewContractDecisionTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverSandboxHandleReviewContractDecisionMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverSandboxHandleReviewContractDecisionProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver sandbox handle review contract decision",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Decision state: ${profile.decisionState}`,
    `- Decision: ${profile.decision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for v357 archive verification: ${profile.readyForNodeV357SandboxHandleReviewContractDecisionArchiveVerification}`,
    `- Contract decision only: ${profile.contractDecisionOnly}`,
    `- Sandbox handle review only: ${profile.sandboxHandleReviewOnly}`,
    `- Reruns live probe: ${profile.rerunsLiveProbe}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Sends managed audit HTTP/TCP: ${profile.sendsManagedAuditHttpTcp}`,
    `- Credential value requested: ${profile.credentialValueRequested}`,
    `- Credential value read: ${profile.credentialValueRead}`,
    `- Raw endpoint URL requested: ${profile.rawEndpointUrlRequested}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    `- Secret provider instantiated: ${profile.secretProviderInstantiated}`,
    `- Resolver client instantiated: ${profile.resolverClientInstantiated}`,
    `- Runtime shell implemented: ${profile.runtimeShellImplemented}`,
    `- Runtime shell invocation allowed: ${profile.runtimeShellInvocationAllowed}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v355",
    "",
    ...renderEntries(profile.sourceNodeV355),
    "",
    "## Necessity Proof",
    "",
    ...renderEntries(profile.necessityProof),
    "",
    "## Contract Inputs",
    "",
    ...profile.contractInputs.flatMap(renderContractInput),
    "",
    "## Contract Sections",
    "",
    ...profile.contractSections.flatMap(renderContractSection),
    "",
    "## Decision Record",
    "",
    ...renderEntries(profile.decisionRecord),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderContractInput(input: SandboxHandleReviewContractInput): string[] {
  return [
    `- ${input.id}: ${input.label}`,
    `  - category: ${input.category}`,
    `  - sourcePrerequisiteId: ${input.sourcePrerequisiteId}`,
    `  - contractRequirement: ${input.contractRequirement}`,
    `  - containsSecretValue: ${input.containsSecretValue}`,
    `  - containsRawEndpointUrl: ${input.containsRawEndpointUrl}`,
    `  - allowsNetworkConnection: ${input.allowsNetworkConnection}`,
    `  - allowsRuntimeInvocation: ${input.allowsRuntimeInvocation}`,
    `  - status: ${input.status}`,
  ];
}

function renderContractSection(section: SandboxHandleReviewContractSection): string[] {
  return [
    `- ${section.id}: ${section.title}`,
    `  - decisionRule: ${section.decisionRule}`,
    `  - acceptsOnlyOpaqueReference: ${section.acceptsOnlyOpaqueReference}`,
    `  - containsSecretValue: ${section.containsSecretValue}`,
    `  - containsRawEndpointUrl: ${section.containsRawEndpointUrl}`,
    `  - opensManagedAuditConnection: ${section.opensManagedAuditConnection}`,
    `  - invokesRuntimeShell: ${section.invokesRuntimeShell}`,
    `  - mutatesUpstreamState: ${section.mutatesUpstreamState}`,
  ];
}
