import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverShardReadinessContractConsumerGateProfile,
  ShardReadinessEvidenceAssessment,
} from "./managedAuditManualSandboxConnectionCredentialResolverShardReadinessContractConsumerGateTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverShardReadinessContractConsumerGateMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverShardReadinessContractConsumerGateProfile,
): string {
  return [
    "# Managed audit manual sandbox connection credential resolver shard readiness contract consumer gate",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Gate state: ${profile.gateState}`,
    `- Gate decision: ${profile.gateDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for shard readiness contract consumer gate: ${profile.readyForShardReadinessContractConsumerGate}`,
    `- Ready for Node v371 minimal shard readiness live-read gate: ${profile.readyForNodeV371MinimalShardReadinessLiveReadGate}`,
    `- Contract consumer only: ${profile.contractConsumerOnly}`,
    `- Reruns live probe: ${profile.rerunsLiveProbe}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Mutates Java state: ${profile.mutatesJavaState}`,
    `- Mutates mini-kv state: ${profile.mutatesMiniKvState}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Sends managed audit HTTP/TCP: ${profile.sendsManagedAuditHttpTcp}`,
    `- Credential value requested: ${profile.credentialValueRequested}`,
    `- Raw endpoint URL parsed: ${profile.rawEndpointUrlParsed}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Source Node v369",
    "",
    ...renderEntries(profile.sourceNodeV369),
    "",
    "## Gate",
    "",
    ...renderEntries(profile.gate),
    "",
    "## Java Shard Readiness",
    "",
    ...renderShardReadiness(profile.javaShardReadiness),
    "",
    "## mini-kv Shard Readiness",
    "",
    ...renderShardReadiness(profile.miniKvShardReadiness),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderShardReadiness(assessment: ShardReadinessEvidenceAssessment): string[] {
  return [
    `- Project: ${assessment.project}`,
    `- Source version: ${assessment.sourceVersion}`,
    `- Ready for Node consumption: ${assessment.readyForNodeConsumption}`,
    `- Required fields: ${assessment.presentRequiredFieldCount}/${assessment.requiredFieldCount}`,
    `- Missing fields: ${assessment.missingRequiredFields.length === 0 ? "none" : assessment.missingRequiredFields.join(", ")}`,
    `- Read only safe: ${assessment.readOnlySafe}`,
    `- Execution blocked: ${assessment.executionBlocked}`,
    `- Routing mode present: ${assessment.routingModePresent}`,
    `- Status accepted: ${assessment.statusAccepted}`,
    `- Source-specific prototype value accepted: ${assessment.sourceSpecificPrototypeValueAccepted}`,
    `- Boundary safe: ${assessment.boundarySafe}`,
    `- Evidence file: ${assessment.evidenceFile.configuredPath}`,
    `- Resolved path: ${assessment.evidenceFile.resolvedPath}`,
    `- Used historical fallback: ${assessment.evidenceFile.usedHistoricalFallback}`,
    `- Historical fallback available: ${assessment.evidenceFile.historicalFallbackAvailable}`,
    `- Digest: ${assessment.evidenceFile.digest ?? "missing"}`,
    "- Evidence:",
    ...renderEntries(assessment.evidence).map((line) => `  ${line}`),
  ];
}
