import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type {
  ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvActiveShardPlanBoundaryHandoffIntakeArchiveVerificationProfile,
} from "./managedAuditManualSandboxConnectionCredentialResolverJavaMiniKvActiveShardPlanBoundaryHandoffIntakeArchiveVerificationTypes.js";

export function renderManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvActiveShardPlanBoundaryHandoffIntakeArchiveVerificationMarkdown(
  profile: ManagedAuditManualSandboxConnectionCredentialResolverJavaMiniKvActiveShardPlanBoundaryHandoffIntakeArchiveVerificationProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Archive verification state: ${profile.archiveVerificationState}`,
    `- Archive verification decision: ${profile.archiveVerificationDecision}`,
    `- Active Node version: ${profile.activeNodeVersion}`,
    `- Source Node version: ${profile.sourceNodeVersion}`,
    `- Ready for Node v384 next boundary evidence or live gate: ${profile.readyForNodeV384NextBoundaryEvidenceOrLiveGate}`,
    `- Archive verification only: ${profile.archiveVerificationOnly}`,
    `- Reruns live read: ${profile.rerunsLiveRead}`,
    `- Starts Java service: ${profile.startsJavaService}`,
    `- Starts mini-kv service: ${profile.startsMiniKvService}`,
    `- Stops Java service: ${profile.stopsJavaService}`,
    `- Stops mini-kv service: ${profile.stopsMiniKvService}`,
    `- Connects managed audit: ${profile.connectsManagedAudit}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    `- Active shard prototype enabled: ${profile.activeShardPrototypeEnabled}`,
    "",
    "## Source Node v382",
    "",
    ...renderEntries(profile.sourceNodeV382),
    "",
    "## Replay From Frozen Evidence",
    "",
    ...renderEntries(profile.replay),
    "",
    "## Archive Verification",
    "",
    ...renderEntries(profile.archiveVerification),
    "",
    "## Archive References",
    "",
    ...Object.values(profile.archiveReferences)
      .filter((value): value is { path: string; exists: boolean; byteLength: number; digest: string | null } =>
        typeof value === "object" && value !== null && "path" in value)
      .map((file) => `- ${file.path}: exists=${file.exists}; bytes=${file.byteLength}; digest=${file.digest}`),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
