import { renderList } from "./operationApprovalEvidenceReaders.js";
import type { OperationApprovalEvidenceReport, OperationApprovalEvidenceVerification } from "./operationApprovalEvidenceTypes.js";

export function renderOperationApprovalEvidenceMarkdown(report: OperationApprovalEvidenceReport): string {
  return [
    "# Operation approval evidence report",
    "",
    `- Service: ${report.service}`,
    `- Generated at: ${report.generatedAt}`,
    `- State: ${report.state}`,
    `- Request id: ${report.requestId}`,
    `- Decision id: ${report.decisionId ?? "missing"}`,
    `- Intent id: ${report.intentId}`,
    `- Action: ${report.summary.action}`,
    `- Target: ${report.summary.target}`,
    `- Evidence digest: ${report.evidenceDigest.algorithm}:${report.evidenceDigest.value}`,
    "",
    "## Approval Request",
    "",
    `- Request status: ${report.summary.requestStatus}`,
    `- Requested by: ${report.request.requestedBy}`,
    `- Reviewer: ${report.request.reviewer}`,
    `- Decision reason: ${report.request.decisionReason}`,
    `- Ready for approval request: ${report.summary.readyForApprovalRequest}`,
    `- Preflight digest: ${report.summary.preflightDigest.algorithm}:${report.summary.preflightDigest.value}`,
    `- Preview digest: ${report.summary.previewDigest.algorithm}:${report.summary.previewDigest.value}`,
    "",
    "## Reviewer Decision",
    "",
    `- Decision: ${report.summary.decision}`,
    `- Reviewer: ${report.summary.reviewer}`,
    `- Upstream touched: ${report.summary.upstreamTouched}`,
    `- Decision digest: ${report.summary.decisionDigest === undefined ? "missing" : `${report.summary.decisionDigest.algorithm}:${report.summary.decisionDigest.value}`}`,
    "",
    "## Upstream Evidence",
    "",
    `- Java approval-status: ${report.summary.javaApprovalStatus} - ${report.upstreamEvidence.javaApprovalStatus.message}`,
    `- Java approved for replay: ${report.summary.javaApprovedForReplay === undefined ? "unknown" : report.summary.javaApprovedForReplay}`,
    `- Java evidence version: ${report.summary.javaEvidenceVersion ?? "unknown"}`,
    `- Java approval digest: ${report.summary.javaApprovalDigest ?? "unknown"}`,
    `- Java replay eligibility digest: ${report.summary.javaReplayEligibilityDigest ?? "unknown"}`,
    `- Java execution contract: ${report.summary.javaExecutionContractStatus} - ${report.upstreamEvidence.javaExecutionContract.message}`,
    `- Java contract version: ${report.summary.javaContractVersion ?? "unknown"}`,
    `- Java contract digest: ${report.summary.javaContractDigest ?? "unknown"}`,
    `- Java replay preconditions satisfied: ${report.summary.javaReplayPreconditionsSatisfied === undefined ? "unknown" : report.summary.javaReplayPreconditionsSatisfied}`,
    `- Java digest verification mode: ${report.summary.javaDigestVerificationMode ?? "unknown"}`,
    `- mini-kv EXPLAINJSON coverage: ${report.summary.miniKvExplainCoverage} - ${report.upstreamEvidence.miniKvExplainCoverage.message}`,
    `- mini-kv schema version: ${report.summary.miniKvSchemaVersion ?? "unknown"}`,
    `- mini-kv command digest: ${report.summary.miniKvCommandDigest ?? "unknown"}`,
    `- mini-kv side_effect_count: ${report.summary.miniKvSideEffectCount ?? "unknown"}`,
    `- mini-kv CHECKJSON contract: ${report.summary.miniKvExecutionContractStatus} - ${report.upstreamEvidence.miniKvExecutionContract.message}`,
    `- mini-kv CHECKJSON read_only: ${report.summary.miniKvCheckReadOnly === undefined ? "unknown" : report.summary.miniKvCheckReadOnly}`,
    `- mini-kv CHECKJSON execution_allowed: ${report.summary.miniKvCheckExecutionAllowed === undefined ? "unknown" : report.summary.miniKvCheckExecutionAllowed}`,
    `- mini-kv CHECKJSON durability: ${report.summary.miniKvCheckDurability ?? "unknown"}`,
    "",
    "### mini-kv side_effects",
    "",
    ...renderList(report.summary.miniKvSideEffects, "No mini-kv side_effects reported."),
    "",
    "## Expected Side Effects",
    "",
    ...renderList(report.request.expectedSideEffects, "No expected side effects."),
    "",
    "## Hard Blockers",
    "",
    ...renderList(report.request.hardBlockers, "No hard blockers."),
    "",
    "## Warnings",
    "",
    ...renderList(report.request.warnings, "No warnings."),
    "",
    "## Next Actions",
    "",
    ...renderList(report.nextActions, "No next actions."),
    "",
  ].join("\n");
}

export function renderOperationApprovalEvidenceVerificationMarkdown(verification: OperationApprovalEvidenceVerification): string {
  return [
    "# Operation approval evidence verification",
    "",
    `- Service: ${verification.service}`,
    `- Verified at: ${verification.verifiedAt}`,
    `- Valid: ${verification.valid}`,
    `- Request id: ${verification.requestId}`,
    `- Decision id: ${verification.decisionId ?? "missing"}`,
    `- State: ${verification.state}`,
    `- Stored digest: ${verification.storedDigest.algorithm}:${verification.storedDigest.value}`,
    `- Recomputed digest: ${verification.recomputedDigest.algorithm}:${verification.recomputedDigest.value}`,
    "",
    "## Checks",
    "",
    `- Digest valid: ${verification.checks.digestValid}`,
    `- Request matches: ${verification.checks.requestMatches}`,
    `- Decision present: ${verification.checks.decisionPresent}`,
    `- Decision matches request: ${verification.checks.decisionMatchesRequest}`,
    `- Request preview digest valid: ${verification.checks.requestPreviewDigestValid}`,
    `- Decision digest valid: ${verification.checks.decisionDigestValid}`,
    `- Summary matches: ${verification.checks.summaryMatches}`,
    `- Upstream evidence matches summary: ${verification.checks.upstreamEvidenceMatchesSummary}`,
    `- Java approval digest evidence valid: ${verification.checks.javaApprovalDigestEvidenceValid}`,
    `- Java execution contract evidence valid: ${verification.checks.javaExecutionContractEvidenceValid}`,
    `- mini-kv command digest evidence valid: ${verification.checks.miniKvCommandDigestEvidenceValid}`,
    `- mini-kv side_effect_count matches: ${verification.checks.miniKvSideEffectCountMatches}`,
    `- mini-kv execution contract evidence valid: ${verification.checks.miniKvExecutionContractEvidenceValid}`,
    `- Next actions match: ${verification.checks.nextActionsMatch}`,
    `- Upstream untouched: ${verification.checks.upstreamUntouched}`,
    "",
    "## Next Actions",
    "",
    ...renderList(verification.nextActions, "No next actions."),
    "",
  ].join("\n");
}
