import type {
  OpsPromotionDeploymentExecutionRecord,
  OpsPromotionDeploymentExecutionRecordItem,
  OpsPromotionDeploymentExecutionRecordVerification,
  OpsPromotionDeploymentExecutionRecordVerificationItem,
  OpsPromotionDeploymentExecutionReceipt,
  OpsPromotionDeploymentExecutionReceiptItem,
  OpsPromotionDeploymentExecutionReceiptVerification,
  OpsPromotionDeploymentExecutionReceiptVerificationItem,
} from "./opsPromotionArchiveBundleTypes.js";

export function renderOpsPromotionDeploymentExecutionRecordMarkdown(record: OpsPromotionDeploymentExecutionRecord): string {
  const lines = [
    "# Promotion deployment execution record",
    "",
    `- Service: ${record.service}`,
    `- Generated at: ${record.generatedAt}`,
    `- Execution name: ${record.executionName}`,
    `- Change record name: ${record.changeRecordName}`,
    `- Approval name: ${record.approvalName}`,
    `- Release archive name: ${record.releaseArchiveName}`,
    `- Evidence name: ${record.evidenceName}`,
    `- Completion name: ${record.completionName}`,
    `- Closure name: ${record.closureName}`,
    `- Receipt name: ${record.receiptName}`,
    `- Certificate name: ${record.certificateName}`,
    `- Package name: ${record.packageName}`,
    `- Archive name: ${record.archiveName}`,
    `- State: ${record.state}`,
    `- Valid: ${record.valid}`,
    `- Handoff ready: ${record.handoffReady}`,
    `- Approval ready: ${record.approvalReady}`,
    `- Change ready: ${record.changeReady}`,
    `- Execution ready: ${record.executionReady}`,
    `- Execution digest: ${record.executionDigest.algorithm}:${record.executionDigest.value}`,
    `- Change digest: ${record.changeDigest.algorithm}:${record.changeDigest.value}`,
    `- Verified change digest: ${record.verifiedChangeDigest.algorithm}:${record.verifiedChangeDigest.value}`,
    `- Approval digest: ${record.approvalDigest.algorithm}:${record.approvalDigest.value}`,
    `- Release archive digest: ${record.releaseArchiveDigest.algorithm}:${record.releaseArchiveDigest.value}`,
    `- Covered fields: ${record.executionDigest.coveredFields.join(", ")}`,
    "",
    "## Decision",
    "",
    `- Total decisions: ${record.decision.totalDecisions}`,
    `- Latest decision id: ${record.decision.latestDecisionId ?? "none"}`,
    `- Latest outcome: ${record.decision.latestOutcome ?? "none"}`,
    "",
    "## Verification",
    "",
    `- Change record verified: ${record.verification.changeRecordVerified}`,
    `- Change digest valid: ${record.verification.changeDigestValid}`,
    `- Change items valid: ${record.verification.changeItemsValid}`,
    `- Change reference valid: ${record.verification.changeReferenceValid}`,
    `- Closeout ready: ${record.verification.closeoutReady}`,
    `- Change item count: ${record.verification.changeItemCount}`,
    `- Execution item count: ${record.verification.executionItemCount}`,
    "",
    "## Execution Items",
    "",
    ...renderDeploymentExecutionRecordItems(record.executionItems),
    "",
    "## Next Actions",
    "",
    ...record.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentExecutionRecordVerificationMarkdown(
  verification: OpsPromotionDeploymentExecutionRecordVerification,
): string {
  const lines = [
    "# Promotion deployment execution record verification",
    "",
    `- Service: ${verification.service}`,
    `- Generated at: ${verification.generatedAt}`,
    `- Execution name: ${verification.executionName}`,
    `- Change record name: ${verification.changeRecordName}`,
    `- Approval name: ${verification.approvalName}`,
    `- Release archive name: ${verification.releaseArchiveName}`,
    `- Evidence name: ${verification.evidenceName}`,
    `- Completion name: ${verification.completionName}`,
    `- Closure name: ${verification.closureName}`,
    `- Receipt name: ${verification.receiptName}`,
    `- Certificate name: ${verification.certificateName}`,
    `- Package name: ${verification.packageName}`,
    `- Archive name: ${verification.archiveName}`,
    `- State: ${verification.state}`,
    `- Handoff ready: ${verification.handoffReady}`,
    `- Approval ready: ${verification.approvalReady}`,
    `- Change ready: ${verification.changeReady}`,
    `- Execution ready: ${verification.executionReady}`,
    `- Valid: ${verification.valid}`,
    `- Execution digest: ${verification.executionDigest.algorithm}:${verification.executionDigest.value}`,
    `- Recomputed execution digest: ${verification.recomputedExecutionDigest.algorithm}:${verification.recomputedExecutionDigest.value}`,
    "",
    "## Checks",
    "",
    `- Execution digest valid: ${verification.checks.executionDigestValid}`,
    `- Covered fields match: ${verification.checks.coveredFieldsMatch}`,
    `- Execution items valid: ${verification.checks.executionItemsValid}`,
    `- Execution name matches: ${verification.checks.executionNameMatches}`,
    `- Change record name matches: ${verification.checks.changeRecordNameMatches}`,
    `- Approval name matches: ${verification.checks.approvalNameMatches}`,
    `- Release archive name matches: ${verification.checks.releaseArchiveNameMatches}`,
    `- Evidence name matches: ${verification.checks.evidenceNameMatches}`,
    `- Completion name matches: ${verification.checks.completionNameMatches}`,
    `- Closure name matches: ${verification.checks.closureNameMatches}`,
    `- Receipt name matches: ${verification.checks.receiptNameMatches}`,
    `- Certificate name matches: ${verification.checks.certificateNameMatches}`,
    `- Package name matches: ${verification.checks.packageNameMatches}`,
    `- Archive name matches: ${verification.checks.archiveNameMatches}`,
    `- Valid matches: ${verification.checks.validMatches}`,
    `- State matches: ${verification.checks.stateMatches}`,
    `- Handoff ready matches: ${verification.checks.handoffReadyMatches}`,
    `- Approval ready matches: ${verification.checks.approvalReadyMatches}`,
    `- Change ready matches: ${verification.checks.changeReadyMatches}`,
    `- Execution ready matches: ${verification.checks.executionReadyMatches}`,
    `- Change digest matches: ${verification.checks.changeDigestMatches}`,
    `- Verified change digest matches: ${verification.checks.verifiedChangeDigestMatches}`,
    `- Approval digest matches: ${verification.checks.approvalDigestMatches}`,
    `- Release archive digest matches: ${verification.checks.releaseArchiveDigestMatches}`,
    `- Decision matches: ${verification.checks.decisionMatches}`,
    `- Verification matches: ${verification.checks.verificationMatches}`,
    `- Next actions match: ${verification.checks.nextActionsMatch}`,
    "",
    "## Execution Items",
    "",
    ...renderDeploymentExecutionRecordVerificationItems(verification.executionItems),
    "",
    "## Summary",
    "",
    `- Total decisions: ${verification.summary.totalDecisions}`,
    `- Latest decision id: ${verification.summary.latestDecisionId ?? "none"}`,
    `- Execution item count: ${verification.summary.executionItemCount}`,
    `- Handoff ready: ${verification.summary.handoffReady}`,
    `- Approval ready: ${verification.summary.approvalReady}`,
    `- Change ready: ${verification.summary.changeReady}`,
    `- Execution ready: ${verification.summary.executionReady}`,
    `- Closeout ready: ${verification.summary.closeoutReady}`,
    "",
    "## Next Actions",
    "",
    ...verification.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentExecutionReceiptMarkdown(receipt: OpsPromotionDeploymentExecutionReceipt): string {
  const lines = [
    "# Promotion deployment execution receipt",
    "",
    `- Service: ${receipt.service}`,
    `- Generated at: ${receipt.generatedAt}`,
    `- Receipt name: ${receipt.receiptName}`,
    `- Execution name: ${receipt.executionName}`,
    `- Change record name: ${receipt.changeRecordName}`,
    `- Approval name: ${receipt.approvalName}`,
    `- Release archive name: ${receipt.releaseArchiveName}`,
    `- Evidence name: ${receipt.evidenceName}`,
    `- Completion name: ${receipt.completionName}`,
    `- Closure name: ${receipt.closureName}`,
    `- Receipt record name: ${receipt.receiptRecordName}`,
    `- Certificate name: ${receipt.certificateName}`,
    `- Package name: ${receipt.packageName}`,
    `- Archive name: ${receipt.archiveName}`,
    `- State: ${receipt.state}`,
    `- Valid: ${receipt.valid}`,
    `- Handoff ready: ${receipt.handoffReady}`,
    `- Approval ready: ${receipt.approvalReady}`,
    `- Change ready: ${receipt.changeReady}`,
    `- Execution ready: ${receipt.executionReady}`,
    `- Receipt ready: ${receipt.receiptReady}`,
    `- Receipt digest: ${receipt.receiptDigest.algorithm}:${receipt.receiptDigest.value}`,
    `- Execution digest: ${receipt.executionDigest.algorithm}:${receipt.executionDigest.value}`,
    `- Verified execution digest: ${receipt.verifiedExecutionDigest.algorithm}:${receipt.verifiedExecutionDigest.value}`,
    `- Change digest: ${receipt.changeDigest.algorithm}:${receipt.changeDigest.value}`,
    `- Approval digest: ${receipt.approvalDigest.algorithm}:${receipt.approvalDigest.value}`,
    `- Release archive digest: ${receipt.releaseArchiveDigest.algorithm}:${receipt.releaseArchiveDigest.value}`,
    `- Covered fields: ${receipt.receiptDigest.coveredFields.join(", ")}`,
    "",
    "## Decision",
    "",
    `- Total decisions: ${receipt.decision.totalDecisions}`,
    `- Latest decision id: ${receipt.decision.latestDecisionId ?? "none"}`,
    `- Latest outcome: ${receipt.decision.latestOutcome ?? "none"}`,
    "",
    "## Verification",
    "",
    `- Execution record verified: ${receipt.verification.executionRecordVerified}`,
    `- Execution digest valid: ${receipt.verification.executionDigestValid}`,
    `- Execution items valid: ${receipt.verification.executionItemsValid}`,
    `- Execution reference valid: ${receipt.verification.executionReferenceValid}`,
    `- Closeout ready: ${receipt.verification.closeoutReady}`,
    `- Execution item count: ${receipt.verification.executionItemCount}`,
    `- Receipt item count: ${receipt.verification.receiptItemCount}`,
    "",
    "## Receipt Items",
    "",
    ...renderDeploymentExecutionReceiptItems(receipt.receiptItems),
    "",
    "## Next Actions",
    "",
    ...receipt.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentExecutionReceiptVerificationMarkdown(
  verification: OpsPromotionDeploymentExecutionReceiptVerification,
): string {
  const lines = [
    "# Promotion deployment execution receipt verification",
    "",
    `- Service: ${verification.service}`,
    `- Generated at: ${verification.generatedAt}`,
    `- Receipt name: ${verification.receiptName}`,
    `- Execution name: ${verification.executionName}`,
    `- Change record name: ${verification.changeRecordName}`,
    `- Approval name: ${verification.approvalName}`,
    `- Release archive name: ${verification.releaseArchiveName}`,
    `- Evidence name: ${verification.evidenceName}`,
    `- Completion name: ${verification.completionName}`,
    `- Closure name: ${verification.closureName}`,
    `- Receipt record name: ${verification.receiptRecordName}`,
    `- Certificate name: ${verification.certificateName}`,
    `- Package name: ${verification.packageName}`,
    `- Archive name: ${verification.archiveName}`,
    `- State: ${verification.state}`,
    `- Handoff ready: ${verification.handoffReady}`,
    `- Approval ready: ${verification.approvalReady}`,
    `- Change ready: ${verification.changeReady}`,
    `- Execution ready: ${verification.executionReady}`,
    `- Receipt ready: ${verification.receiptReady}`,
    `- Valid: ${verification.valid}`,
    `- Receipt digest: ${verification.receiptDigest.algorithm}:${verification.receiptDigest.value}`,
    `- Recomputed receipt digest: ${verification.recomputedReceiptDigest.algorithm}:${verification.recomputedReceiptDigest.value}`,
    "",
    "## Checks",
    "",
    `- Receipt digest valid: ${verification.checks.receiptDigestValid}`,
    `- Covered fields match: ${verification.checks.coveredFieldsMatch}`,
    `- Receipt items valid: ${verification.checks.receiptItemsValid}`,
    `- Receipt name matches: ${verification.checks.receiptNameMatches}`,
    `- Execution name matches: ${verification.checks.executionNameMatches}`,
    `- Change record name matches: ${verification.checks.changeRecordNameMatches}`,
    `- Approval name matches: ${verification.checks.approvalNameMatches}`,
    `- Release archive name matches: ${verification.checks.releaseArchiveNameMatches}`,
    `- Evidence name matches: ${verification.checks.evidenceNameMatches}`,
    `- Completion name matches: ${verification.checks.completionNameMatches}`,
    `- Closure name matches: ${verification.checks.closureNameMatches}`,
    `- Receipt record name matches: ${verification.checks.receiptRecordNameMatches}`,
    `- Certificate name matches: ${verification.checks.certificateNameMatches}`,
    `- Package name matches: ${verification.checks.packageNameMatches}`,
    `- Archive name matches: ${verification.checks.archiveNameMatches}`,
    `- Valid matches: ${verification.checks.validMatches}`,
    `- State matches: ${verification.checks.stateMatches}`,
    `- Handoff ready matches: ${verification.checks.handoffReadyMatches}`,
    `- Approval ready matches: ${verification.checks.approvalReadyMatches}`,
    `- Change ready matches: ${verification.checks.changeReadyMatches}`,
    `- Execution ready matches: ${verification.checks.executionReadyMatches}`,
    `- Receipt ready matches: ${verification.checks.receiptReadyMatches}`,
    `- Execution digest matches: ${verification.checks.executionDigestMatches}`,
    `- Verified execution digest matches: ${verification.checks.verifiedExecutionDigestMatches}`,
    `- Change digest matches: ${verification.checks.changeDigestMatches}`,
    `- Approval digest matches: ${verification.checks.approvalDigestMatches}`,
    `- Release archive digest matches: ${verification.checks.releaseArchiveDigestMatches}`,
    `- Decision matches: ${verification.checks.decisionMatches}`,
    `- Verification matches: ${verification.checks.verificationMatches}`,
    `- Next actions match: ${verification.checks.nextActionsMatch}`,
    "",
    "## Receipt Items",
    "",
    ...renderDeploymentExecutionReceiptVerificationItems(verification.receiptItems),
    "",
    "## Summary",
    "",
    `- Total decisions: ${verification.summary.totalDecisions}`,
    `- Latest decision id: ${verification.summary.latestDecisionId ?? "none"}`,
    `- Receipt item count: ${verification.summary.receiptItemCount}`,
    `- Handoff ready: ${verification.summary.handoffReady}`,
    `- Approval ready: ${verification.summary.approvalReady}`,
    `- Change ready: ${verification.summary.changeReady}`,
    `- Execution ready: ${verification.summary.executionReady}`,
    `- Receipt ready: ${verification.summary.receiptReady}`,
    `- Closeout ready: ${verification.summary.closeoutReady}`,
    "",
    "## Next Actions",
    "",
    ...verification.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



function renderDeploymentExecutionRecordItems(items: OpsPromotionDeploymentExecutionRecordItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Digest: ${item.digest.algorithm}:${item.digest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentExecutionRecordVerificationItems(items: OpsPromotionDeploymentExecutionRecordVerificationItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Valid matches: ${item.validMatches}`,
    `- Source matches: ${item.sourceMatches}`,
    `- Detail matches: ${item.detailMatches}`,
    `- Digest matches: ${item.digestMatches}`,
    `- Execution item digest: ${item.executionItemDigest.algorithm}:${item.executionItemDigest.value}`,
    `- Recomputed digest: ${item.recomputedDigest.algorithm}:${item.recomputedDigest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentExecutionReceiptItems(items: OpsPromotionDeploymentExecutionReceiptItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Digest: ${item.digest.algorithm}:${item.digest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentExecutionReceiptVerificationItems(items: OpsPromotionDeploymentExecutionReceiptVerificationItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Valid matches: ${item.validMatches}`,
    `- Source matches: ${item.sourceMatches}`,
    `- Detail matches: ${item.detailMatches}`,
    `- Digest matches: ${item.digestMatches}`,
    `- Receipt item digest: ${item.receiptItemDigest.algorithm}:${item.receiptItemDigest.value}`,
    `- Recomputed digest: ${item.recomputedDigest.algorithm}:${item.recomputedDigest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}
