import type { OpsPromotionEvidenceReport } from "./opsPromotionEvidenceReport.js";
import type {
  OpsPromotionArchiveAttestation,
  OpsPromotionArchiveAttestationEvidenceSource,
  OpsPromotionArchiveAttestationVerification,
  OpsPromotionArchiveBundle,
  OpsPromotionArchiveManifest,
  OpsPromotionArchiveManifestArtifact,
  OpsPromotionArchiveVerification,
  OpsPromotionArchiveVerificationArtifact,
  OpsPromotionDeploymentApproval,
  OpsPromotionDeploymentApprovalItem,
  OpsPromotionDeploymentApprovalVerification,
  OpsPromotionDeploymentApprovalVerificationItem,
  OpsPromotionDeploymentChangeRecord,
  OpsPromotionDeploymentChangeRecordItem,
  OpsPromotionDeploymentChangeRecordVerification,
  OpsPromotionDeploymentChangeRecordVerificationItem,
  OpsPromotionDeploymentExecutionReceipt,
  OpsPromotionDeploymentExecutionReceiptItem,
  OpsPromotionDeploymentExecutionReceiptVerification,
  OpsPromotionDeploymentExecutionReceiptVerificationItem,
  OpsPromotionDeploymentExecutionRecord,
  OpsPromotionDeploymentExecutionRecordItem,
  OpsPromotionDeploymentExecutionRecordVerification,
  OpsPromotionDeploymentExecutionRecordVerificationItem,
  OpsPromotionHandoffCertificate,
  OpsPromotionHandoffCertificateAttachment,
  OpsPromotionHandoffCertificateVerification,
  OpsPromotionHandoffCertificateVerificationAttachment,
  OpsPromotionHandoffClosure,
  OpsPromotionHandoffClosureItem,
  OpsPromotionHandoffClosureVerification,
  OpsPromotionHandoffClosureVerificationItem,
  OpsPromotionHandoffCompletion,
  OpsPromotionHandoffCompletionStep,
  OpsPromotionHandoffCompletionVerification,
  OpsPromotionHandoffCompletionVerificationStep,
  OpsPromotionHandoffPackage,
  OpsPromotionHandoffPackageAttachment,
  OpsPromotionHandoffPackageVerification,
  OpsPromotionHandoffPackageVerificationAttachment,
  OpsPromotionHandoffReceipt,
  OpsPromotionHandoffReceiptMilestone,
  OpsPromotionHandoffReceiptVerification,
  OpsPromotionHandoffReceiptVerificationMilestone,
  OpsPromotionReleaseArchive,
  OpsPromotionReleaseArchiveItem,
  OpsPromotionReleaseArchiveVerification,
  OpsPromotionReleaseArchiveVerificationItem,
  OpsPromotionReleaseAuditTrailRecord,
  OpsPromotionReleaseAuditTrailRecordItem,
  OpsPromotionReleaseEvidence,
  OpsPromotionReleaseEvidenceItem,
  OpsPromotionReleaseEvidenceVerification,
  OpsPromotionReleaseEvidenceVerificationItem,
} from "./opsPromotionArchiveBundleTypes.js";

export function renderOpsPromotionReleaseEvidenceMarkdown(evidence: OpsPromotionReleaseEvidence): string {
  const lines = [
    "# Promotion release evidence",
    "",
    `- Service: ${evidence.service}`,
    `- Generated at: ${evidence.generatedAt}`,
    `- Evidence name: ${evidence.evidenceName}`,
    `- Completion name: ${evidence.completionName}`,
    `- Closure name: ${evidence.closureName}`,
    `- Receipt name: ${evidence.receiptName}`,
    `- Certificate name: ${evidence.certificateName}`,
    `- Package name: ${evidence.packageName}`,
    `- Archive name: ${evidence.archiveName}`,
    `- State: ${evidence.state}`,
    `- Valid: ${evidence.valid}`,
    `- Handoff ready: ${evidence.handoffReady}`,
    `- Evidence digest: ${evidence.evidenceDigest.algorithm}:${evidence.evidenceDigest.value}`,
    `- Completion digest: ${evidence.completionDigest.algorithm}:${evidence.completionDigest.value}`,
    `- Verified completion digest: ${evidence.verifiedCompletionDigest.algorithm}:${evidence.verifiedCompletionDigest.value}`,
    `- Closure digest: ${evidence.closureDigest.algorithm}:${evidence.closureDigest.value}`,
    `- Verified closure digest: ${evidence.verifiedClosureDigest.algorithm}:${evidence.verifiedClosureDigest.value}`,
    `- Covered fields: ${evidence.evidenceDigest.coveredFields.join(", ")}`,
    "",
    "## Decision",
    "",
    `- Total decisions: ${evidence.decision.totalDecisions}`,
    `- Latest decision id: ${evidence.decision.latestDecisionId ?? "none"}`,
    `- Latest outcome: ${evidence.decision.latestOutcome ?? "none"}`,
    "",
    "## Verification",
    "",
    `- Completion verified: ${evidence.verification.completionVerified}`,
    `- Completion digest valid: ${evidence.verification.completionDigestValid}`,
    `- Completion steps valid: ${evidence.verification.completionStepsValid}`,
    `- Closure reference valid: ${evidence.verification.closureReferenceValid}`,
    `- Closeout ready: ${evidence.verification.closeoutReady}`,
    `- Completion step count: ${evidence.verification.completionStepCount}`,
    `- Evidence item count: ${evidence.verification.evidenceItemCount}`,
    "",
    "## Evidence Items",
    "",
    ...renderReleaseEvidenceItems(evidence.evidenceItems),
    "",
    "## Next Actions",
    "",
    ...evidence.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionReleaseEvidenceVerificationMarkdown(
  verification: OpsPromotionReleaseEvidenceVerification,
): string {
  const lines = [
    "# Promotion release evidence verification",
    "",
    `- Service: ${verification.service}`,
    `- Generated at: ${verification.generatedAt}`,
    `- Evidence name: ${verification.evidenceName}`,
    `- Completion name: ${verification.completionName}`,
    `- Closure name: ${verification.closureName}`,
    `- Receipt name: ${verification.receiptName}`,
    `- Certificate name: ${verification.certificateName}`,
    `- Package name: ${verification.packageName}`,
    `- Archive name: ${verification.archiveName}`,
    `- State: ${verification.state}`,
    `- Handoff ready: ${verification.handoffReady}`,
    `- Valid: ${verification.valid}`,
    `- Evidence digest: ${verification.evidenceDigest.algorithm}:${verification.evidenceDigest.value}`,
    `- Recomputed evidence digest: ${verification.recomputedEvidenceDigest.algorithm}:${verification.recomputedEvidenceDigest.value}`,
    "",
    "## Checks",
    "",
    `- Evidence digest valid: ${verification.checks.evidenceDigestValid}`,
    `- Covered fields match: ${verification.checks.coveredFieldsMatch}`,
    `- Evidence items valid: ${verification.checks.evidenceItemsValid}`,
    `- Evidence name matches: ${verification.checks.evidenceNameMatches}`,
    `- Completion name matches: ${verification.checks.completionNameMatches}`,
    `- Closure name matches: ${verification.checks.closureNameMatches}`,
    `- Receipt name matches: ${verification.checks.receiptNameMatches}`,
    `- Certificate name matches: ${verification.checks.certificateNameMatches}`,
    `- Package name matches: ${verification.checks.packageNameMatches}`,
    `- Archive name matches: ${verification.checks.archiveNameMatches}`,
    `- Valid matches: ${verification.checks.validMatches}`,
    `- State matches: ${verification.checks.stateMatches}`,
    `- Handoff ready matches: ${verification.checks.handoffReadyMatches}`,
    `- Completion digest matches: ${verification.checks.completionDigestMatches}`,
    `- Verified completion digest matches: ${verification.checks.verifiedCompletionDigestMatches}`,
    `- Closure digest matches: ${verification.checks.closureDigestMatches}`,
    `- Verified closure digest matches: ${verification.checks.verifiedClosureDigestMatches}`,
    `- Decision matches: ${verification.checks.decisionMatches}`,
    `- Verification matches: ${verification.checks.verificationMatches}`,
    `- Next actions match: ${verification.checks.nextActionsMatch}`,
    "",
    "## Evidence Items",
    "",
    ...renderReleaseEvidenceVerificationItems(verification.evidenceItems),
    "",
    "## Summary",
    "",
    `- Total decisions: ${verification.summary.totalDecisions}`,
    `- Latest decision id: ${verification.summary.latestDecisionId ?? "none"}`,
    `- Evidence item count: ${verification.summary.evidenceItemCount}`,
    `- Handoff ready: ${verification.summary.handoffReady}`,
    `- Closeout ready: ${verification.summary.closeoutReady}`,
    "",
    "## Next Actions",
    "",
    ...verification.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionReleaseArchiveMarkdown(releaseArchive: OpsPromotionReleaseArchive): string {
  const lines = [
    "# Promotion release archive",
    "",
    `- Service: ${releaseArchive.service}`,
    `- Generated at: ${releaseArchive.generatedAt}`,
    `- Release archive name: ${releaseArchive.releaseArchiveName}`,
    `- Evidence name: ${releaseArchive.evidenceName}`,
    `- Completion name: ${releaseArchive.completionName}`,
    `- Closure name: ${releaseArchive.closureName}`,
    `- Receipt name: ${releaseArchive.receiptName}`,
    `- Certificate name: ${releaseArchive.certificateName}`,
    `- Package name: ${releaseArchive.packageName}`,
    `- Archive name: ${releaseArchive.archiveName}`,
    `- State: ${releaseArchive.state}`,
    `- Valid: ${releaseArchive.valid}`,
    `- Handoff ready: ${releaseArchive.handoffReady}`,
    `- Release archive digest: ${releaseArchive.releaseArchiveDigest.algorithm}:${releaseArchive.releaseArchiveDigest.value}`,
    `- Evidence digest: ${releaseArchive.evidenceDigest.algorithm}:${releaseArchive.evidenceDigest.value}`,
    `- Verified evidence digest: ${releaseArchive.verifiedEvidenceDigest.algorithm}:${releaseArchive.verifiedEvidenceDigest.value}`,
    `- Completion digest: ${releaseArchive.completionDigest.algorithm}:${releaseArchive.completionDigest.value}`,
    `- Closure digest: ${releaseArchive.closureDigest.algorithm}:${releaseArchive.closureDigest.value}`,
    `- Covered fields: ${releaseArchive.releaseArchiveDigest.coveredFields.join(", ")}`,
    "",
    "## Decision",
    "",
    `- Total decisions: ${releaseArchive.decision.totalDecisions}`,
    `- Latest decision id: ${releaseArchive.decision.latestDecisionId ?? "none"}`,
    `- Latest outcome: ${releaseArchive.decision.latestOutcome ?? "none"}`,
    "",
    "## Verification",
    "",
    `- Evidence verified: ${releaseArchive.verification.evidenceVerified}`,
    `- Evidence digest valid: ${releaseArchive.verification.evidenceDigestValid}`,
    `- Evidence items valid: ${releaseArchive.verification.evidenceItemsValid}`,
    `- Evidence reference valid: ${releaseArchive.verification.evidenceReferenceValid}`,
    `- Closeout ready: ${releaseArchive.verification.closeoutReady}`,
    `- Evidence item count: ${releaseArchive.verification.evidenceItemCount}`,
    `- Archive item count: ${releaseArchive.verification.archiveItemCount}`,
    "",
    "## Archive Items",
    "",
    ...renderReleaseArchiveItems(releaseArchive.archiveItems),
    "",
    "## Next Actions",
    "",
    ...releaseArchive.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionReleaseArchiveVerificationMarkdown(
  verification: OpsPromotionReleaseArchiveVerification,
): string {
  const lines = [
    "# Promotion release archive verification",
    "",
    `- Service: ${verification.service}`,
    `- Generated at: ${verification.generatedAt}`,
    `- Release archive name: ${verification.releaseArchiveName}`,
    `- Evidence name: ${verification.evidenceName}`,
    `- Completion name: ${verification.completionName}`,
    `- Closure name: ${verification.closureName}`,
    `- Receipt name: ${verification.receiptName}`,
    `- Certificate name: ${verification.certificateName}`,
    `- Package name: ${verification.packageName}`,
    `- Archive name: ${verification.archiveName}`,
    `- State: ${verification.state}`,
    `- Handoff ready: ${verification.handoffReady}`,
    `- Valid: ${verification.valid}`,
    `- Release archive digest: ${verification.releaseArchiveDigest.algorithm}:${verification.releaseArchiveDigest.value}`,
    `- Recomputed release archive digest: ${verification.recomputedReleaseArchiveDigest.algorithm}:${verification.recomputedReleaseArchiveDigest.value}`,
    "",
    "## Checks",
    "",
    `- Release archive digest valid: ${verification.checks.releaseArchiveDigestValid}`,
    `- Covered fields match: ${verification.checks.coveredFieldsMatch}`,
    `- Archive items valid: ${verification.checks.archiveItemsValid}`,
    `- Release archive name matches: ${verification.checks.releaseArchiveNameMatches}`,
    `- Evidence name matches: ${verification.checks.evidenceNameMatches}`,
    `- Completion name matches: ${verification.checks.completionNameMatches}`,
    `- Closure name matches: ${verification.checks.closureNameMatches}`,
    `- Receipt name matches: ${verification.checks.receiptNameMatches}`,
    `- Certificate name matches: ${verification.checks.certificateNameMatches}`,
    `- Package name matches: ${verification.checks.packageNameMatches}`,
    `- Archive name matches: ${verification.checks.archiveNameMatches}`,
    `- Valid matches: ${verification.checks.validMatches}`,
    `- State matches: ${verification.checks.stateMatches}`,
    `- Handoff ready matches: ${verification.checks.handoffReadyMatches}`,
    `- Evidence digest matches: ${verification.checks.evidenceDigestMatches}`,
    `- Verified evidence digest matches: ${verification.checks.verifiedEvidenceDigestMatches}`,
    `- Completion digest matches: ${verification.checks.completionDigestMatches}`,
    `- Closure digest matches: ${verification.checks.closureDigestMatches}`,
    `- Decision matches: ${verification.checks.decisionMatches}`,
    `- Verification matches: ${verification.checks.verificationMatches}`,
    `- Next actions match: ${verification.checks.nextActionsMatch}`,
    "",
    "## Archive Items",
    "",
    ...renderReleaseArchiveVerificationItems(verification.archiveItems),
    "",
    "## Summary",
    "",
    `- Total decisions: ${verification.summary.totalDecisions}`,
    `- Latest decision id: ${verification.summary.latestDecisionId ?? "none"}`,
    `- Archive item count: ${verification.summary.archiveItemCount}`,
    `- Handoff ready: ${verification.summary.handoffReady}`,
    `- Closeout ready: ${verification.summary.closeoutReady}`,
    "",
    "## Next Actions",
    "",
    ...verification.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentApprovalMarkdown(approval: OpsPromotionDeploymentApproval): string {
  const lines = [
    "# Promotion deployment approval",
    "",
    `- Service: ${approval.service}`,
    `- Generated at: ${approval.generatedAt}`,
    `- Approval name: ${approval.approvalName}`,
    `- Release archive name: ${approval.releaseArchiveName}`,
    `- Evidence name: ${approval.evidenceName}`,
    `- Completion name: ${approval.completionName}`,
    `- Closure name: ${approval.closureName}`,
    `- Receipt name: ${approval.receiptName}`,
    `- Certificate name: ${approval.certificateName}`,
    `- Package name: ${approval.packageName}`,
    `- Archive name: ${approval.archiveName}`,
    `- State: ${approval.state}`,
    `- Valid: ${approval.valid}`,
    `- Handoff ready: ${approval.handoffReady}`,
    `- Approval ready: ${approval.approvalReady}`,
    `- Approval digest: ${approval.approvalDigest.algorithm}:${approval.approvalDigest.value}`,
    `- Release archive digest: ${approval.releaseArchiveDigest.algorithm}:${approval.releaseArchiveDigest.value}`,
    `- Verified release archive digest: ${approval.verifiedReleaseArchiveDigest.algorithm}:${approval.verifiedReleaseArchiveDigest.value}`,
    `- Evidence digest: ${approval.evidenceDigest.algorithm}:${approval.evidenceDigest.value}`,
    `- Covered fields: ${approval.approvalDigest.coveredFields.join(", ")}`,
    "",
    "## Decision",
    "",
    `- Total decisions: ${approval.decision.totalDecisions}`,
    `- Latest decision id: ${approval.decision.latestDecisionId ?? "none"}`,
    `- Latest outcome: ${approval.decision.latestOutcome ?? "none"}`,
    "",
    "## Verification",
    "",
    `- Release archive verified: ${approval.verification.releaseArchiveVerified}`,
    `- Release archive digest valid: ${approval.verification.releaseArchiveDigestValid}`,
    `- Archive items valid: ${approval.verification.archiveItemsValid}`,
    `- Release archive reference valid: ${approval.verification.releaseArchiveReferenceValid}`,
    `- Closeout ready: ${approval.verification.closeoutReady}`,
    `- Archive item count: ${approval.verification.archiveItemCount}`,
    `- Approval item count: ${approval.verification.approvalItemCount}`,
    "",
    "## Approval Items",
    "",
    ...renderDeploymentApprovalItems(approval.approvalItems),
    "",
    "## Next Actions",
    "",
    ...approval.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentApprovalVerificationMarkdown(
  verification: OpsPromotionDeploymentApprovalVerification,
): string {
  const lines = [
    "# Promotion deployment approval verification",
    "",
    `- Service: ${verification.service}`,
    `- Generated at: ${verification.generatedAt}`,
    `- Approval name: ${verification.approvalName}`,
    `- Release archive name: ${verification.releaseArchiveName}`,
    `- Evidence name: ${verification.evidenceName}`,
    `- Completion name: ${verification.completionName}`,
    `- Closure name: ${verification.closureName}`,
    `- Receipt name: ${verification.receiptName}`,
    `- Certificate name: ${verification.certificateName}`,
    `- Package name: ${verification.packageName}`,
    `- Archive name: ${verification.archiveName}`,
    `- State: ${verification.state}`,
    `- Handoff ready: ${verification.handoffReady}`,
    `- Approval ready: ${verification.approvalReady}`,
    `- Valid: ${verification.valid}`,
    `- Approval digest: ${verification.approvalDigest.algorithm}:${verification.approvalDigest.value}`,
    `- Recomputed approval digest: ${verification.recomputedApprovalDigest.algorithm}:${verification.recomputedApprovalDigest.value}`,
    "",
    "## Checks",
    "",
    `- Approval digest valid: ${verification.checks.approvalDigestValid}`,
    `- Covered fields match: ${verification.checks.coveredFieldsMatch}`,
    `- Approval items valid: ${verification.checks.approvalItemsValid}`,
    `- Approval name matches: ${verification.checks.approvalNameMatches}`,
    `- Release archive name matches: ${verification.checks.releaseArchiveNameMatches}`,
    `- Evidence name matches: ${verification.checks.evidenceNameMatches}`,
    `- Completion name matches: ${verification.checks.completionNameMatches}`,
    `- Closure name matches: ${verification.checks.closureNameMatches}`,
    `- Receipt name matches: ${verification.checks.receiptNameMatches}`,
    `- Certificate name matches: ${verification.checks.certificateNameMatches}`,
    `- Package name matches: ${verification.checks.packageNameMatches}`,
    `- Archive name matches: ${verification.checks.archiveNameMatches}`,
    `- Valid matches: ${verification.checks.validMatches}`,
    `- State matches: ${verification.checks.stateMatches}`,
    `- Handoff ready matches: ${verification.checks.handoffReadyMatches}`,
    `- Approval ready matches: ${verification.checks.approvalReadyMatches}`,
    `- Release archive digest matches: ${verification.checks.releaseArchiveDigestMatches}`,
    `- Verified release archive digest matches: ${verification.checks.verifiedReleaseArchiveDigestMatches}`,
    `- Evidence digest matches: ${verification.checks.evidenceDigestMatches}`,
    `- Decision matches: ${verification.checks.decisionMatches}`,
    `- Verification matches: ${verification.checks.verificationMatches}`,
    `- Next actions match: ${verification.checks.nextActionsMatch}`,
    "",
    "## Approval Items",
    "",
    ...renderDeploymentApprovalVerificationItems(verification.approvalItems),
    "",
    "## Summary",
    "",
    `- Total decisions: ${verification.summary.totalDecisions}`,
    `- Latest decision id: ${verification.summary.latestDecisionId ?? "none"}`,
    `- Approval item count: ${verification.summary.approvalItemCount}`,
    `- Handoff ready: ${verification.summary.handoffReady}`,
    `- Approval ready: ${verification.summary.approvalReady}`,
    `- Closeout ready: ${verification.summary.closeoutReady}`,
    "",
    "## Next Actions",
    "",
    ...verification.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentChangeRecordMarkdown(changeRecord: OpsPromotionDeploymentChangeRecord): string {
  const lines = [
    "# Promotion deployment change record",
    "",
    `- Service: ${changeRecord.service}`,
    `- Generated at: ${changeRecord.generatedAt}`,
    `- Change record name: ${changeRecord.changeRecordName}`,
    `- Approval name: ${changeRecord.approvalName}`,
    `- Release archive name: ${changeRecord.releaseArchiveName}`,
    `- Evidence name: ${changeRecord.evidenceName}`,
    `- Completion name: ${changeRecord.completionName}`,
    `- Closure name: ${changeRecord.closureName}`,
    `- Receipt name: ${changeRecord.receiptName}`,
    `- Certificate name: ${changeRecord.certificateName}`,
    `- Package name: ${changeRecord.packageName}`,
    `- Archive name: ${changeRecord.archiveName}`,
    `- State: ${changeRecord.state}`,
    `- Valid: ${changeRecord.valid}`,
    `- Handoff ready: ${changeRecord.handoffReady}`,
    `- Approval ready: ${changeRecord.approvalReady}`,
    `- Change ready: ${changeRecord.changeReady}`,
    `- Change digest: ${changeRecord.changeDigest.algorithm}:${changeRecord.changeDigest.value}`,
    `- Approval digest: ${changeRecord.approvalDigest.algorithm}:${changeRecord.approvalDigest.value}`,
    `- Verified approval digest: ${changeRecord.verifiedApprovalDigest.algorithm}:${changeRecord.verifiedApprovalDigest.value}`,
    `- Release archive digest: ${changeRecord.releaseArchiveDigest.algorithm}:${changeRecord.releaseArchiveDigest.value}`,
    `- Covered fields: ${changeRecord.changeDigest.coveredFields.join(", ")}`,
    "",
    "## Decision",
    "",
    `- Total decisions: ${changeRecord.decision.totalDecisions}`,
    `- Latest decision id: ${changeRecord.decision.latestDecisionId ?? "none"}`,
    `- Latest outcome: ${changeRecord.decision.latestOutcome ?? "none"}`,
    "",
    "## Verification",
    "",
    `- Approval verified: ${changeRecord.verification.approvalVerified}`,
    `- Approval digest valid: ${changeRecord.verification.approvalDigestValid}`,
    `- Approval items valid: ${changeRecord.verification.approvalItemsValid}`,
    `- Approval reference valid: ${changeRecord.verification.approvalReferenceValid}`,
    `- Closeout ready: ${changeRecord.verification.closeoutReady}`,
    `- Approval item count: ${changeRecord.verification.approvalItemCount}`,
    `- Change item count: ${changeRecord.verification.changeItemCount}`,
    "",
    "## Change Items",
    "",
    ...renderDeploymentChangeRecordItems(changeRecord.changeItems),
    "",
    "## Next Actions",
    "",
    ...changeRecord.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentChangeRecordVerificationMarkdown(
  verification: OpsPromotionDeploymentChangeRecordVerification,
): string {
  const lines = [
    "# Promotion deployment change record verification",
    "",
    `- Service: ${verification.service}`,
    `- Generated at: ${verification.generatedAt}`,
    `- Change record name: ${verification.changeRecordName}`,
    `- Approval name: ${verification.approvalName}`,
    `- Release archive name: ${verification.releaseArchiveName}`,
    `- Evidence name: ${verification.evidenceName}`,
    `- Completion name: ${verification.completionName}`,
    `- Closure name: ${verification.closureName}`,
    `- Receipt name: ${verification.receiptName}`,
    `- Certificate name: ${verification.certificateName}`,
    `- Package name: ${verification.packageName}`,
    `- Archive name: ${verification.archiveName}`,
    `- State: ${verification.state}`,
    `- Handoff ready: ${verification.handoffReady}`,
    `- Approval ready: ${verification.approvalReady}`,
    `- Change ready: ${verification.changeReady}`,
    `- Valid: ${verification.valid}`,
    `- Change digest: ${verification.changeDigest.algorithm}:${verification.changeDigest.value}`,
    `- Recomputed change digest: ${verification.recomputedChangeDigest.algorithm}:${verification.recomputedChangeDigest.value}`,
    "",
    "## Checks",
    "",
    `- Change digest valid: ${verification.checks.changeDigestValid}`,
    `- Covered fields match: ${verification.checks.coveredFieldsMatch}`,
    `- Change items valid: ${verification.checks.changeItemsValid}`,
    `- Change record name matches: ${verification.checks.changeRecordNameMatches}`,
    `- Approval name matches: ${verification.checks.approvalNameMatches}`,
    `- Release archive name matches: ${verification.checks.releaseArchiveNameMatches}`,
    `- Evidence name matches: ${verification.checks.evidenceNameMatches}`,
    `- Completion name matches: ${verification.checks.completionNameMatches}`,
    `- Closure name matches: ${verification.checks.closureNameMatches}`,
    `- Receipt name matches: ${verification.checks.receiptNameMatches}`,
    `- Certificate name matches: ${verification.checks.certificateNameMatches}`,
    `- Package name matches: ${verification.checks.packageNameMatches}`,
    `- Archive name matches: ${verification.checks.archiveNameMatches}`,
    `- Valid matches: ${verification.checks.validMatches}`,
    `- State matches: ${verification.checks.stateMatches}`,
    `- Handoff ready matches: ${verification.checks.handoffReadyMatches}`,
    `- Approval ready matches: ${verification.checks.approvalReadyMatches}`,
    `- Change ready matches: ${verification.checks.changeReadyMatches}`,
    `- Approval digest matches: ${verification.checks.approvalDigestMatches}`,
    `- Verified approval digest matches: ${verification.checks.verifiedApprovalDigestMatches}`,
    `- Release archive digest matches: ${verification.checks.releaseArchiveDigestMatches}`,
    `- Decision matches: ${verification.checks.decisionMatches}`,
    `- Verification matches: ${verification.checks.verificationMatches}`,
    `- Next actions match: ${verification.checks.nextActionsMatch}`,
    "",
    "## Change Items",
    "",
    ...renderDeploymentChangeRecordVerificationItems(verification.changeItems),
    "",
    "## Summary",
    "",
    `- Total decisions: ${verification.summary.totalDecisions}`,
    `- Latest decision id: ${verification.summary.latestDecisionId ?? "none"}`,
    `- Change item count: ${verification.summary.changeItemCount}`,
    `- Handoff ready: ${verification.summary.handoffReady}`,
    `- Approval ready: ${verification.summary.approvalReady}`,
    `- Change ready: ${verification.summary.changeReady}`,
    `- Closeout ready: ${verification.summary.closeoutReady}`,
    "",
    "## Next Actions",
    "",
    ...verification.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentExecutionRecordMarkdown(record: OpsPromotionDeploymentExecutionRecord): string {
  const lines = [
    "# Promotion deployment execution record",
    "",
    `- Service: ${record.service}`,
    `- Generated at: ${record.generatedAt}`,
    `- Execution name: ${record.executionName}`,
    `- Change record name: ${record.changeRecordName}`,
    `- Approval name: ${record.approvalName}`,
    `- Release archive name: ${record.releaseArchiveName}`,
    `- Evidence name: ${record.evidenceName}`,
    `- Completion name: ${record.completionName}`,
    `- Closure name: ${record.closureName}`,
    `- Receipt name: ${record.receiptName}`,
    `- Certificate name: ${record.certificateName}`,
    `- Package name: ${record.packageName}`,
    `- Archive name: ${record.archiveName}`,
    `- State: ${record.state}`,
    `- Valid: ${record.valid}`,
    `- Handoff ready: ${record.handoffReady}`,
    `- Approval ready: ${record.approvalReady}`,
    `- Change ready: ${record.changeReady}`,
    `- Execution ready: ${record.executionReady}`,
    `- Execution digest: ${record.executionDigest.algorithm}:${record.executionDigest.value}`,
    `- Change digest: ${record.changeDigest.algorithm}:${record.changeDigest.value}`,
    `- Verified change digest: ${record.verifiedChangeDigest.algorithm}:${record.verifiedChangeDigest.value}`,
    `- Approval digest: ${record.approvalDigest.algorithm}:${record.approvalDigest.value}`,
    `- Release archive digest: ${record.releaseArchiveDigest.algorithm}:${record.releaseArchiveDigest.value}`,
    `- Covered fields: ${record.executionDigest.coveredFields.join(", ")}`,
    "",
    "## Decision",
    "",
    `- Total decisions: ${record.decision.totalDecisions}`,
    `- Latest decision id: ${record.decision.latestDecisionId ?? "none"}`,
    `- Latest outcome: ${record.decision.latestOutcome ?? "none"}`,
    "",
    "## Verification",
    "",
    `- Change record verified: ${record.verification.changeRecordVerified}`,
    `- Change digest valid: ${record.verification.changeDigestValid}`,
    `- Change items valid: ${record.verification.changeItemsValid}`,
    `- Change reference valid: ${record.verification.changeReferenceValid}`,
    `- Closeout ready: ${record.verification.closeoutReady}`,
    `- Change item count: ${record.verification.changeItemCount}`,
    `- Execution item count: ${record.verification.executionItemCount}`,
    "",
    "## Execution Items",
    "",
    ...renderDeploymentExecutionRecordItems(record.executionItems),
    "",
    "## Next Actions",
    "",
    ...record.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentExecutionRecordVerificationMarkdown(
  verification: OpsPromotionDeploymentExecutionRecordVerification,
): string {
  const lines = [
    "# Promotion deployment execution record verification",
    "",
    `- Service: ${verification.service}`,
    `- Generated at: ${verification.generatedAt}`,
    `- Execution name: ${verification.executionName}`,
    `- Change record name: ${verification.changeRecordName}`,
    `- Approval name: ${verification.approvalName}`,
    `- Release archive name: ${verification.releaseArchiveName}`,
    `- Evidence name: ${verification.evidenceName}`,
    `- Completion name: ${verification.completionName}`,
    `- Closure name: ${verification.closureName}`,
    `- Receipt name: ${verification.receiptName}`,
    `- Certificate name: ${verification.certificateName}`,
    `- Package name: ${verification.packageName}`,
    `- Archive name: ${verification.archiveName}`,
    `- State: ${verification.state}`,
    `- Handoff ready: ${verification.handoffReady}`,
    `- Approval ready: ${verification.approvalReady}`,
    `- Change ready: ${verification.changeReady}`,
    `- Execution ready: ${verification.executionReady}`,
    `- Valid: ${verification.valid}`,
    `- Execution digest: ${verification.executionDigest.algorithm}:${verification.executionDigest.value}`,
    `- Recomputed execution digest: ${verification.recomputedExecutionDigest.algorithm}:${verification.recomputedExecutionDigest.value}`,
    "",
    "## Checks",
    "",
    `- Execution digest valid: ${verification.checks.executionDigestValid}`,
    `- Covered fields match: ${verification.checks.coveredFieldsMatch}`,
    `- Execution items valid: ${verification.checks.executionItemsValid}`,
    `- Execution name matches: ${verification.checks.executionNameMatches}`,
    `- Change record name matches: ${verification.checks.changeRecordNameMatches}`,
    `- Approval name matches: ${verification.checks.approvalNameMatches}`,
    `- Release archive name matches: ${verification.checks.releaseArchiveNameMatches}`,
    `- Evidence name matches: ${verification.checks.evidenceNameMatches}`,
    `- Completion name matches: ${verification.checks.completionNameMatches}`,
    `- Closure name matches: ${verification.checks.closureNameMatches}`,
    `- Receipt name matches: ${verification.checks.receiptNameMatches}`,
    `- Certificate name matches: ${verification.checks.certificateNameMatches}`,
    `- Package name matches: ${verification.checks.packageNameMatches}`,
    `- Archive name matches: ${verification.checks.archiveNameMatches}`,
    `- Valid matches: ${verification.checks.validMatches}`,
    `- State matches: ${verification.checks.stateMatches}`,
    `- Handoff ready matches: ${verification.checks.handoffReadyMatches}`,
    `- Approval ready matches: ${verification.checks.approvalReadyMatches}`,
    `- Change ready matches: ${verification.checks.changeReadyMatches}`,
    `- Execution ready matches: ${verification.checks.executionReadyMatches}`,
    `- Change digest matches: ${verification.checks.changeDigestMatches}`,
    `- Verified change digest matches: ${verification.checks.verifiedChangeDigestMatches}`,
    `- Approval digest matches: ${verification.checks.approvalDigestMatches}`,
    `- Release archive digest matches: ${verification.checks.releaseArchiveDigestMatches}`,
    `- Decision matches: ${verification.checks.decisionMatches}`,
    `- Verification matches: ${verification.checks.verificationMatches}`,
    `- Next actions match: ${verification.checks.nextActionsMatch}`,
    "",
    "## Execution Items",
    "",
    ...renderDeploymentExecutionRecordVerificationItems(verification.executionItems),
    "",
    "## Summary",
    "",
    `- Total decisions: ${verification.summary.totalDecisions}`,
    `- Latest decision id: ${verification.summary.latestDecisionId ?? "none"}`,
    `- Execution item count: ${verification.summary.executionItemCount}`,
    `- Handoff ready: ${verification.summary.handoffReady}`,
    `- Approval ready: ${verification.summary.approvalReady}`,
    `- Change ready: ${verification.summary.changeReady}`,
    `- Execution ready: ${verification.summary.executionReady}`,
    `- Closeout ready: ${verification.summary.closeoutReady}`,
    "",
    "## Next Actions",
    "",
    ...verification.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentExecutionReceiptMarkdown(receipt: OpsPromotionDeploymentExecutionReceipt): string {
  const lines = [
    "# Promotion deployment execution receipt",
    "",
    `- Service: ${receipt.service}`,
    `- Generated at: ${receipt.generatedAt}`,
    `- Receipt name: ${receipt.receiptName}`,
    `- Execution name: ${receipt.executionName}`,
    `- Change record name: ${receipt.changeRecordName}`,
    `- Approval name: ${receipt.approvalName}`,
    `- Release archive name: ${receipt.releaseArchiveName}`,
    `- Evidence name: ${receipt.evidenceName}`,
    `- Completion name: ${receipt.completionName}`,
    `- Closure name: ${receipt.closureName}`,
    `- Receipt record name: ${receipt.receiptRecordName}`,
    `- Certificate name: ${receipt.certificateName}`,
    `- Package name: ${receipt.packageName}`,
    `- Archive name: ${receipt.archiveName}`,
    `- State: ${receipt.state}`,
    `- Valid: ${receipt.valid}`,
    `- Handoff ready: ${receipt.handoffReady}`,
    `- Approval ready: ${receipt.approvalReady}`,
    `- Change ready: ${receipt.changeReady}`,
    `- Execution ready: ${receipt.executionReady}`,
    `- Receipt ready: ${receipt.receiptReady}`,
    `- Receipt digest: ${receipt.receiptDigest.algorithm}:${receipt.receiptDigest.value}`,
    `- Execution digest: ${receipt.executionDigest.algorithm}:${receipt.executionDigest.value}`,
    `- Verified execution digest: ${receipt.verifiedExecutionDigest.algorithm}:${receipt.verifiedExecutionDigest.value}`,
    `- Change digest: ${receipt.changeDigest.algorithm}:${receipt.changeDigest.value}`,
    `- Approval digest: ${receipt.approvalDigest.algorithm}:${receipt.approvalDigest.value}`,
    `- Release archive digest: ${receipt.releaseArchiveDigest.algorithm}:${receipt.releaseArchiveDigest.value}`,
    `- Covered fields: ${receipt.receiptDigest.coveredFields.join(", ")}`,
    "",
    "## Decision",
    "",
    `- Total decisions: ${receipt.decision.totalDecisions}`,
    `- Latest decision id: ${receipt.decision.latestDecisionId ?? "none"}`,
    `- Latest outcome: ${receipt.decision.latestOutcome ?? "none"}`,
    "",
    "## Verification",
    "",
    `- Execution record verified: ${receipt.verification.executionRecordVerified}`,
    `- Execution digest valid: ${receipt.verification.executionDigestValid}`,
    `- Execution items valid: ${receipt.verification.executionItemsValid}`,
    `- Execution reference valid: ${receipt.verification.executionReferenceValid}`,
    `- Closeout ready: ${receipt.verification.closeoutReady}`,
    `- Execution item count: ${receipt.verification.executionItemCount}`,
    `- Receipt item count: ${receipt.verification.receiptItemCount}`,
    "",
    "## Receipt Items",
    "",
    ...renderDeploymentExecutionReceiptItems(receipt.receiptItems),
    "",
    "## Next Actions",
    "",
    ...receipt.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentExecutionReceiptVerificationMarkdown(
  verification: OpsPromotionDeploymentExecutionReceiptVerification,
): string {
  const lines = [
    "# Promotion deployment execution receipt verification",
    "",
    `- Service: ${verification.service}`,
    `- Generated at: ${verification.generatedAt}`,
    `- Receipt name: ${verification.receiptName}`,
    `- Execution name: ${verification.executionName}`,
    `- Change record name: ${verification.changeRecordName}`,
    `- Approval name: ${verification.approvalName}`,
    `- Release archive name: ${verification.releaseArchiveName}`,
    `- Evidence name: ${verification.evidenceName}`,
    `- Completion name: ${verification.completionName}`,
    `- Closure name: ${verification.closureName}`,
    `- Receipt record name: ${verification.receiptRecordName}`,
    `- Certificate name: ${verification.certificateName}`,
    `- Package name: ${verification.packageName}`,
    `- Archive name: ${verification.archiveName}`,
    `- State: ${verification.state}`,
    `- Handoff ready: ${verification.handoffReady}`,
    `- Approval ready: ${verification.approvalReady}`,
    `- Change ready: ${verification.changeReady}`,
    `- Execution ready: ${verification.executionReady}`,
    `- Receipt ready: ${verification.receiptReady}`,
    `- Valid: ${verification.valid}`,
    `- Receipt digest: ${verification.receiptDigest.algorithm}:${verification.receiptDigest.value}`,
    `- Recomputed receipt digest: ${verification.recomputedReceiptDigest.algorithm}:${verification.recomputedReceiptDigest.value}`,
    "",
    "## Checks",
    "",
    `- Receipt digest valid: ${verification.checks.receiptDigestValid}`,
    `- Covered fields match: ${verification.checks.coveredFieldsMatch}`,
    `- Receipt items valid: ${verification.checks.receiptItemsValid}`,
    `- Receipt name matches: ${verification.checks.receiptNameMatches}`,
    `- Execution name matches: ${verification.checks.executionNameMatches}`,
    `- Change record name matches: ${verification.checks.changeRecordNameMatches}`,
    `- Approval name matches: ${verification.checks.approvalNameMatches}`,
    `- Release archive name matches: ${verification.checks.releaseArchiveNameMatches}`,
    `- Evidence name matches: ${verification.checks.evidenceNameMatches}`,
    `- Completion name matches: ${verification.checks.completionNameMatches}`,
    `- Closure name matches: ${verification.checks.closureNameMatches}`,
    `- Receipt record name matches: ${verification.checks.receiptRecordNameMatches}`,
    `- Certificate name matches: ${verification.checks.certificateNameMatches}`,
    `- Package name matches: ${verification.checks.packageNameMatches}`,
    `- Archive name matches: ${verification.checks.archiveNameMatches}`,
    `- Valid matches: ${verification.checks.validMatches}`,
    `- State matches: ${verification.checks.stateMatches}`,
    `- Handoff ready matches: ${verification.checks.handoffReadyMatches}`,
    `- Approval ready matches: ${verification.checks.approvalReadyMatches}`,
    `- Change ready matches: ${verification.checks.changeReadyMatches}`,
    `- Execution ready matches: ${verification.checks.executionReadyMatches}`,
    `- Receipt ready matches: ${verification.checks.receiptReadyMatches}`,
    `- Execution digest matches: ${verification.checks.executionDigestMatches}`,
    `- Verified execution digest matches: ${verification.checks.verifiedExecutionDigestMatches}`,
    `- Change digest matches: ${verification.checks.changeDigestMatches}`,
    `- Approval digest matches: ${verification.checks.approvalDigestMatches}`,
    `- Release archive digest matches: ${verification.checks.releaseArchiveDigestMatches}`,
    `- Decision matches: ${verification.checks.decisionMatches}`,
    `- Verification matches: ${verification.checks.verificationMatches}`,
    `- Next actions match: ${verification.checks.nextActionsMatch}`,
    "",
    "## Receipt Items",
    "",
    ...renderDeploymentExecutionReceiptVerificationItems(verification.receiptItems),
    "",
    "## Summary",
    "",
    `- Total decisions: ${verification.summary.totalDecisions}`,
    `- Latest decision id: ${verification.summary.latestDecisionId ?? "none"}`,
    `- Receipt item count: ${verification.summary.receiptItemCount}`,
    `- Handoff ready: ${verification.summary.handoffReady}`,
    `- Approval ready: ${verification.summary.approvalReady}`,
    `- Change ready: ${verification.summary.changeReady}`,
    `- Execution ready: ${verification.summary.executionReady}`,
    `- Receipt ready: ${verification.summary.receiptReady}`,
    `- Closeout ready: ${verification.summary.closeoutReady}`,
    "",
    "## Next Actions",
    "",
    ...verification.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionReleaseAuditTrailRecordMarkdown(record: OpsPromotionReleaseAuditTrailRecord): string {
  const lines = [
    "# Promotion release audit trail record",
    "",
    `- Service: ${record.service}`,
    `- Generated at: ${record.generatedAt}`,
    `- Audit trail name: ${record.auditTrailName}`,
    `- Receipt name: ${record.receiptName}`,
    `- Execution name: ${record.executionName}`,
    `- Change record name: ${record.changeRecordName}`,
    `- Approval name: ${record.approvalName}`,
    `- Release archive name: ${record.releaseArchiveName}`,
    `- Evidence name: ${record.evidenceName}`,
    `- Completion name: ${record.completionName}`,
    `- Closure name: ${record.closureName}`,
    `- Receipt record name: ${record.receiptRecordName}`,
    `- Certificate name: ${record.certificateName}`,
    `- Package name: ${record.packageName}`,
    `- Archive name: ${record.archiveName}`,
    `- State: ${record.state}`,
    `- Valid: ${record.valid}`,
    `- Handoff ready: ${record.handoffReady}`,
    `- Approval ready: ${record.approvalReady}`,
    `- Change ready: ${record.changeReady}`,
    `- Execution ready: ${record.executionReady}`,
    `- Receipt ready: ${record.receiptReady}`,
    `- Audit ready: ${record.auditReady}`,
    `- Audit digest: ${record.auditDigest.algorithm}:${record.auditDigest.value}`,
    `- Receipt digest: ${record.receiptDigest.algorithm}:${record.receiptDigest.value}`,
    `- Verified receipt digest: ${record.verifiedReceiptDigest.algorithm}:${record.verifiedReceiptDigest.value}`,
    `- Execution digest: ${record.executionDigest.algorithm}:${record.executionDigest.value}`,
    `- Change digest: ${record.changeDigest.algorithm}:${record.changeDigest.value}`,
    `- Approval digest: ${record.approvalDigest.algorithm}:${record.approvalDigest.value}`,
    `- Release archive digest: ${record.releaseArchiveDigest.algorithm}:${record.releaseArchiveDigest.value}`,
    `- Covered fields: ${record.auditDigest.coveredFields.join(", ")}`,
    "",
    "## Decision",
    "",
    `- Total decisions: ${record.decision.totalDecisions}`,
    `- Latest decision id: ${record.decision.latestDecisionId ?? "none"}`,
    `- Latest outcome: ${record.decision.latestOutcome ?? "none"}`,
    "",
    "## Verification",
    "",
    `- Receipt verified: ${record.verification.receiptVerified}`,
    `- Receipt digest valid: ${record.verification.receiptDigestValid}`,
    `- Receipt items valid: ${record.verification.receiptItemsValid}`,
    `- Receipt reference valid: ${record.verification.receiptReferenceValid}`,
    `- Closeout ready: ${record.verification.closeoutReady}`,
    `- Receipt item count: ${record.verification.receiptItemCount}`,
    `- Audit item count: ${record.verification.auditItemCount}`,
    "",
    "## Audit Items",
    "",
    ...renderReleaseAuditTrailItems(record.auditItems),
    "",
    "## Next Actions",
    "",
    ...record.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



function renderReleaseEvidenceItems(items: OpsPromotionReleaseEvidenceItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Digest: ${item.digest.algorithm}:${item.digest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderReleaseEvidenceVerificationItems(items: OpsPromotionReleaseEvidenceVerificationItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Valid matches: ${item.validMatches}`,
    `- Source matches: ${item.sourceMatches}`,
    `- Detail matches: ${item.detailMatches}`,
    `- Digest matches: ${item.digestMatches}`,
    `- Evidence digest: ${item.evidenceDigest.algorithm}:${item.evidenceDigest.value}`,
    `- Recomputed digest: ${item.recomputedDigest.algorithm}:${item.recomputedDigest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderReleaseArchiveItems(items: OpsPromotionReleaseArchiveItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Digest: ${item.digest.algorithm}:${item.digest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderReleaseArchiveVerificationItems(items: OpsPromotionReleaseArchiveVerificationItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Valid matches: ${item.validMatches}`,
    `- Source matches: ${item.sourceMatches}`,
    `- Detail matches: ${item.detailMatches}`,
    `- Digest matches: ${item.digestMatches}`,
    `- Release archive digest: ${item.releaseArchiveDigest.algorithm}:${item.releaseArchiveDigest.value}`,
    `- Recomputed digest: ${item.recomputedDigest.algorithm}:${item.recomputedDigest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentApprovalItems(items: OpsPromotionDeploymentApprovalItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Digest: ${item.digest.algorithm}:${item.digest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentApprovalVerificationItems(items: OpsPromotionDeploymentApprovalVerificationItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Valid matches: ${item.validMatches}`,
    `- Source matches: ${item.sourceMatches}`,
    `- Detail matches: ${item.detailMatches}`,
    `- Digest matches: ${item.digestMatches}`,
    `- Approval digest: ${item.approvalDigest.algorithm}:${item.approvalDigest.value}`,
    `- Recomputed digest: ${item.recomputedDigest.algorithm}:${item.recomputedDigest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentChangeRecordItems(items: OpsPromotionDeploymentChangeRecordItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Digest: ${item.digest.algorithm}:${item.digest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentChangeRecordVerificationItems(items: OpsPromotionDeploymentChangeRecordVerificationItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Valid matches: ${item.validMatches}`,
    `- Source matches: ${item.sourceMatches}`,
    `- Detail matches: ${item.detailMatches}`,
    `- Digest matches: ${item.digestMatches}`,
    `- Change item digest: ${item.changeItemDigest.algorithm}:${item.changeItemDigest.value}`,
    `- Recomputed digest: ${item.recomputedDigest.algorithm}:${item.recomputedDigest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentExecutionRecordItems(items: OpsPromotionDeploymentExecutionRecordItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Digest: ${item.digest.algorithm}:${item.digest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentExecutionRecordVerificationItems(items: OpsPromotionDeploymentExecutionRecordVerificationItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Valid matches: ${item.validMatches}`,
    `- Source matches: ${item.sourceMatches}`,
    `- Detail matches: ${item.detailMatches}`,
    `- Digest matches: ${item.digestMatches}`,
    `- Execution item digest: ${item.executionItemDigest.algorithm}:${item.executionItemDigest.value}`,
    `- Recomputed digest: ${item.recomputedDigest.algorithm}:${item.recomputedDigest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentExecutionReceiptItems(items: OpsPromotionDeploymentExecutionReceiptItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Digest: ${item.digest.algorithm}:${item.digest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentExecutionReceiptVerificationItems(items: OpsPromotionDeploymentExecutionReceiptVerificationItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Valid matches: ${item.validMatches}`,
    `- Source matches: ${item.sourceMatches}`,
    `- Detail matches: ${item.detailMatches}`,
    `- Digest matches: ${item.digestMatches}`,
    `- Receipt item digest: ${item.receiptItemDigest.algorithm}:${item.receiptItemDigest.value}`,
    `- Recomputed digest: ${item.recomputedDigest.algorithm}:${item.recomputedDigest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderReleaseAuditTrailItems(items: OpsPromotionReleaseAuditTrailRecordItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Digest: ${item.digest.algorithm}:${item.digest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}


