import type {
  OpsPromotionDeploymentApproval,
  OpsPromotionDeploymentApprovalItem,
  OpsPromotionDeploymentApprovalVerification,
  OpsPromotionDeploymentApprovalVerificationItem,
  OpsPromotionDeploymentChangeRecord,
  OpsPromotionDeploymentChangeRecordItem,
  OpsPromotionDeploymentChangeRecordVerification,
  OpsPromotionDeploymentChangeRecordVerificationItem,
} from "./opsPromotionArchiveBundleTypes.js";

export function renderOpsPromotionDeploymentApprovalMarkdown(approval: OpsPromotionDeploymentApproval): string {
  const lines = [
    "# Promotion deployment approval",
    "",
    `- Service: ${approval.service}`,
    `- Generated at: ${approval.generatedAt}`,
    `- Approval name: ${approval.approvalName}`,
    `- Release archive name: ${approval.releaseArchiveName}`,
    `- Evidence name: ${approval.evidenceName}`,
    `- Completion name: ${approval.completionName}`,
    `- Closure name: ${approval.closureName}`,
    `- Receipt name: ${approval.receiptName}`,
    `- Certificate name: ${approval.certificateName}`,
    `- Package name: ${approval.packageName}`,
    `- Archive name: ${approval.archiveName}`,
    `- State: ${approval.state}`,
    `- Valid: ${approval.valid}`,
    `- Handoff ready: ${approval.handoffReady}`,
    `- Approval ready: ${approval.approvalReady}`,
    `- Approval digest: ${approval.approvalDigest.algorithm}:${approval.approvalDigest.value}`,
    `- Release archive digest: ${approval.releaseArchiveDigest.algorithm}:${approval.releaseArchiveDigest.value}`,
    `- Verified release archive digest: ${approval.verifiedReleaseArchiveDigest.algorithm}:${approval.verifiedReleaseArchiveDigest.value}`,
    `- Evidence digest: ${approval.evidenceDigest.algorithm}:${approval.evidenceDigest.value}`,
    `- Covered fields: ${approval.approvalDigest.coveredFields.join(", ")}`,
    "",
    "## Decision",
    "",
    `- Total decisions: ${approval.decision.totalDecisions}`,
    `- Latest decision id: ${approval.decision.latestDecisionId ?? "none"}`,
    `- Latest outcome: ${approval.decision.latestOutcome ?? "none"}`,
    "",
    "## Verification",
    "",
    `- Release archive verified: ${approval.verification.releaseArchiveVerified}`,
    `- Release archive digest valid: ${approval.verification.releaseArchiveDigestValid}`,
    `- Archive items valid: ${approval.verification.archiveItemsValid}`,
    `- Release archive reference valid: ${approval.verification.releaseArchiveReferenceValid}`,
    `- Closeout ready: ${approval.verification.closeoutReady}`,
    `- Archive item count: ${approval.verification.archiveItemCount}`,
    `- Approval item count: ${approval.verification.approvalItemCount}`,
    "",
    "## Approval Items",
    "",
    ...renderDeploymentApprovalItems(approval.approvalItems),
    "",
    "## Next Actions",
    "",
    ...approval.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentApprovalVerificationMarkdown(
  verification: OpsPromotionDeploymentApprovalVerification,
): string {
  const lines = [
    "# Promotion deployment approval verification",
    "",
    `- Service: ${verification.service}`,
    `- Generated at: ${verification.generatedAt}`,
    `- Approval name: ${verification.approvalName}`,
    `- Release archive name: ${verification.releaseArchiveName}`,
    `- Evidence name: ${verification.evidenceName}`,
    `- Completion name: ${verification.completionName}`,
    `- Closure name: ${verification.closureName}`,
    `- Receipt name: ${verification.receiptName}`,
    `- Certificate name: ${verification.certificateName}`,
    `- Package name: ${verification.packageName}`,
    `- Archive name: ${verification.archiveName}`,
    `- State: ${verification.state}`,
    `- Handoff ready: ${verification.handoffReady}`,
    `- Approval ready: ${verification.approvalReady}`,
    `- Valid: ${verification.valid}`,
    `- Approval digest: ${verification.approvalDigest.algorithm}:${verification.approvalDigest.value}`,
    `- Recomputed approval digest: ${verification.recomputedApprovalDigest.algorithm}:${verification.recomputedApprovalDigest.value}`,
    "",
    "## Checks",
    "",
    `- Approval digest valid: ${verification.checks.approvalDigestValid}`,
    `- Covered fields match: ${verification.checks.coveredFieldsMatch}`,
    `- Approval items valid: ${verification.checks.approvalItemsValid}`,
    `- Approval name matches: ${verification.checks.approvalNameMatches}`,
    `- Release archive name matches: ${verification.checks.releaseArchiveNameMatches}`,
    `- Evidence name matches: ${verification.checks.evidenceNameMatches}`,
    `- Completion name matches: ${verification.checks.completionNameMatches}`,
    `- Closure name matches: ${verification.checks.closureNameMatches}`,
    `- Receipt name matches: ${verification.checks.receiptNameMatches}`,
    `- Certificate name matches: ${verification.checks.certificateNameMatches}`,
    `- Package name matches: ${verification.checks.packageNameMatches}`,
    `- Archive name matches: ${verification.checks.archiveNameMatches}`,
    `- Valid matches: ${verification.checks.validMatches}`,
    `- State matches: ${verification.checks.stateMatches}`,
    `- Handoff ready matches: ${verification.checks.handoffReadyMatches}`,
    `- Approval ready matches: ${verification.checks.approvalReadyMatches}`,
    `- Release archive digest matches: ${verification.checks.releaseArchiveDigestMatches}`,
    `- Verified release archive digest matches: ${verification.checks.verifiedReleaseArchiveDigestMatches}`,
    `- Evidence digest matches: ${verification.checks.evidenceDigestMatches}`,
    `- Decision matches: ${verification.checks.decisionMatches}`,
    `- Verification matches: ${verification.checks.verificationMatches}`,
    `- Next actions match: ${verification.checks.nextActionsMatch}`,
    "",
    "## Approval Items",
    "",
    ...renderDeploymentApprovalVerificationItems(verification.approvalItems),
    "",
    "## Summary",
    "",
    `- Total decisions: ${verification.summary.totalDecisions}`,
    `- Latest decision id: ${verification.summary.latestDecisionId ?? "none"}`,
    `- Approval item count: ${verification.summary.approvalItemCount}`,
    `- Handoff ready: ${verification.summary.handoffReady}`,
    `- Approval ready: ${verification.summary.approvalReady}`,
    `- Closeout ready: ${verification.summary.closeoutReady}`,
    "",
    "## Next Actions",
    "",
    ...verification.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentChangeRecordMarkdown(changeRecord: OpsPromotionDeploymentChangeRecord): string {
  const lines = [
    "# Promotion deployment change record",
    "",
    `- Service: ${changeRecord.service}`,
    `- Generated at: ${changeRecord.generatedAt}`,
    `- Change record name: ${changeRecord.changeRecordName}`,
    `- Approval name: ${changeRecord.approvalName}`,
    `- Release archive name: ${changeRecord.releaseArchiveName}`,
    `- Evidence name: ${changeRecord.evidenceName}`,
    `- Completion name: ${changeRecord.completionName}`,
    `- Closure name: ${changeRecord.closureName}`,
    `- Receipt name: ${changeRecord.receiptName}`,
    `- Certificate name: ${changeRecord.certificateName}`,
    `- Package name: ${changeRecord.packageName}`,
    `- Archive name: ${changeRecord.archiveName}`,
    `- State: ${changeRecord.state}`,
    `- Valid: ${changeRecord.valid}`,
    `- Handoff ready: ${changeRecord.handoffReady}`,
    `- Approval ready: ${changeRecord.approvalReady}`,
    `- Change ready: ${changeRecord.changeReady}`,
    `- Change digest: ${changeRecord.changeDigest.algorithm}:${changeRecord.changeDigest.value}`,
    `- Approval digest: ${changeRecord.approvalDigest.algorithm}:${changeRecord.approvalDigest.value}`,
    `- Verified approval digest: ${changeRecord.verifiedApprovalDigest.algorithm}:${changeRecord.verifiedApprovalDigest.value}`,
    `- Release archive digest: ${changeRecord.releaseArchiveDigest.algorithm}:${changeRecord.releaseArchiveDigest.value}`,
    `- Covered fields: ${changeRecord.changeDigest.coveredFields.join(", ")}`,
    "",
    "## Decision",
    "",
    `- Total decisions: ${changeRecord.decision.totalDecisions}`,
    `- Latest decision id: ${changeRecord.decision.latestDecisionId ?? "none"}`,
    `- Latest outcome: ${changeRecord.decision.latestOutcome ?? "none"}`,
    "",
    "## Verification",
    "",
    `- Approval verified: ${changeRecord.verification.approvalVerified}`,
    `- Approval digest valid: ${changeRecord.verification.approvalDigestValid}`,
    `- Approval items valid: ${changeRecord.verification.approvalItemsValid}`,
    `- Approval reference valid: ${changeRecord.verification.approvalReferenceValid}`,
    `- Closeout ready: ${changeRecord.verification.closeoutReady}`,
    `- Approval item count: ${changeRecord.verification.approvalItemCount}`,
    `- Change item count: ${changeRecord.verification.changeItemCount}`,
    "",
    "## Change Items",
    "",
    ...renderDeploymentChangeRecordItems(changeRecord.changeItems),
    "",
    "## Next Actions",
    "",
    ...changeRecord.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



export function renderOpsPromotionDeploymentChangeRecordVerificationMarkdown(
  verification: OpsPromotionDeploymentChangeRecordVerification,
): string {
  const lines = [
    "# Promotion deployment change record verification",
    "",
    `- Service: ${verification.service}`,
    `- Generated at: ${verification.generatedAt}`,
    `- Change record name: ${verification.changeRecordName}`,
    `- Approval name: ${verification.approvalName}`,
    `- Release archive name: ${verification.releaseArchiveName}`,
    `- Evidence name: ${verification.evidenceName}`,
    `- Completion name: ${verification.completionName}`,
    `- Closure name: ${verification.closureName}`,
    `- Receipt name: ${verification.receiptName}`,
    `- Certificate name: ${verification.certificateName}`,
    `- Package name: ${verification.packageName}`,
    `- Archive name: ${verification.archiveName}`,
    `- State: ${verification.state}`,
    `- Handoff ready: ${verification.handoffReady}`,
    `- Approval ready: ${verification.approvalReady}`,
    `- Change ready: ${verification.changeReady}`,
    `- Valid: ${verification.valid}`,
    `- Change digest: ${verification.changeDigest.algorithm}:${verification.changeDigest.value}`,
    `- Recomputed change digest: ${verification.recomputedChangeDigest.algorithm}:${verification.recomputedChangeDigest.value}`,
    "",
    "## Checks",
    "",
    `- Change digest valid: ${verification.checks.changeDigestValid}`,
    `- Covered fields match: ${verification.checks.coveredFieldsMatch}`,
    `- Change items valid: ${verification.checks.changeItemsValid}`,
    `- Change record name matches: ${verification.checks.changeRecordNameMatches}`,
    `- Approval name matches: ${verification.checks.approvalNameMatches}`,
    `- Release archive name matches: ${verification.checks.releaseArchiveNameMatches}`,
    `- Evidence name matches: ${verification.checks.evidenceNameMatches}`,
    `- Completion name matches: ${verification.checks.completionNameMatches}`,
    `- Closure name matches: ${verification.checks.closureNameMatches}`,
    `- Receipt name matches: ${verification.checks.receiptNameMatches}`,
    `- Certificate name matches: ${verification.checks.certificateNameMatches}`,
    `- Package name matches: ${verification.checks.packageNameMatches}`,
    `- Archive name matches: ${verification.checks.archiveNameMatches}`,
    `- Valid matches: ${verification.checks.validMatches}`,
    `- State matches: ${verification.checks.stateMatches}`,
    `- Handoff ready matches: ${verification.checks.handoffReadyMatches}`,
    `- Approval ready matches: ${verification.checks.approvalReadyMatches}`,
    `- Change ready matches: ${verification.checks.changeReadyMatches}`,
    `- Approval digest matches: ${verification.checks.approvalDigestMatches}`,
    `- Verified approval digest matches: ${verification.checks.verifiedApprovalDigestMatches}`,
    `- Release archive digest matches: ${verification.checks.releaseArchiveDigestMatches}`,
    `- Decision matches: ${verification.checks.decisionMatches}`,
    `- Verification matches: ${verification.checks.verificationMatches}`,
    `- Next actions match: ${verification.checks.nextActionsMatch}`,
    "",
    "## Change Items",
    "",
    ...renderDeploymentChangeRecordVerificationItems(verification.changeItems),
    "",
    "## Summary",
    "",
    `- Total decisions: ${verification.summary.totalDecisions}`,
    `- Latest decision id: ${verification.summary.latestDecisionId ?? "none"}`,
    `- Change item count: ${verification.summary.changeItemCount}`,
    `- Handoff ready: ${verification.summary.handoffReady}`,
    `- Approval ready: ${verification.summary.approvalReady}`,
    `- Change ready: ${verification.summary.changeReady}`,
    `- Closeout ready: ${verification.summary.closeoutReady}`,
    "",
    "## Next Actions",
    "",
    ...verification.nextActions.map((action) => `- ${action}`),
    "",
  ];

  return lines.join("\n");
}



function renderDeploymentApprovalItems(items: OpsPromotionDeploymentApprovalItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Digest: ${item.digest.algorithm}:${item.digest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentApprovalVerificationItems(items: OpsPromotionDeploymentApprovalVerificationItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Valid matches: ${item.validMatches}`,
    `- Source matches: ${item.sourceMatches}`,
    `- Detail matches: ${item.detailMatches}`,
    `- Digest matches: ${item.digestMatches}`,
    `- Approval digest: ${item.approvalDigest.algorithm}:${item.approvalDigest.value}`,
    `- Recomputed digest: ${item.recomputedDigest.algorithm}:${item.recomputedDigest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentChangeRecordItems(items: OpsPromotionDeploymentChangeRecordItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Digest: ${item.digest.algorithm}:${item.digest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}



function renderDeploymentChangeRecordVerificationItems(items: OpsPromotionDeploymentChangeRecordVerificationItem[]): string[] {
  return items.flatMap((item) => [
    `### ${item.name}`,
    "",
    `- Valid: ${item.valid}`,
    `- Valid matches: ${item.validMatches}`,
    `- Source matches: ${item.sourceMatches}`,
    `- Detail matches: ${item.detailMatches}`,
    `- Digest matches: ${item.digestMatches}`,
    `- Change item digest: ${item.changeItemDigest.algorithm}:${item.changeItemDigest.value}`,
    `- Recomputed digest: ${item.recomputedDigest.algorithm}:${item.recomputedDigest.value}`,
    `- Source: ${item.source}`,
    `- Detail: ${item.detail}`,
    "",
  ]);
}
