import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ProductionLiveProbeRealReadSmokeReadOnlyWindowCaptureReleaseEvidenceReviewProfile,
} from "./productionLiveProbeRealReadSmokeReadOnlyWindowCaptureReleaseEvidenceReviewTypes.js";

export function renderProductionLiveProbeRealReadSmokeReadOnlyWindowCaptureReleaseEvidenceReviewMarkdown(
  profile: ProductionLiveProbeRealReadSmokeReadOnlyWindowCaptureReleaseEvidenceReviewProfile,
): string {
  return [
    "# Production live probe real-read smoke read-only window capture release evidence review",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Review state: ${profile.reviewState}`,
    `- Ready for read-only capture release evidence review: ${profile.readyForReadOnlyCaptureReleaseEvidenceReview}`,
    `- Ready for production pass evidence: ${profile.readyForProductionPassEvidence}`,
    `- Ready for production operations: ${profile.readyForProductionOperations}`,
    `- Read only: ${profile.readOnly}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Review",
    "",
    ...renderEntries(profile.review),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Artifacts",
    "",
    "### Archive Verification",
    "",
    ...renderEntries(profile.artifacts.archiveVerification),
    "",
    "### Java Field Guide",
    "",
    ...renderEntries(profile.artifacts.javaFieldGuide),
    "",
    "### mini-kv Field Guide",
    "",
    ...renderEntries(profile.artifacts.miniKvFieldGuide),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No read-only capture release evidence review blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No read-only capture release evidence review warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No read-only capture release evidence review recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
