import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ProductionLiveProbeRealReadSmokeReadOnlyWindowCaptureArchiveProfile,
} from "./productionLiveProbeRealReadSmokeReadOnlyWindowCaptureArchiveTypes.js";

export function renderProductionLiveProbeRealReadSmokeReadOnlyWindowCaptureArchiveMarkdown(
  profile: ProductionLiveProbeRealReadSmokeReadOnlyWindowCaptureArchiveProfile,
): string {
  return [
    "# Production live probe real-read smoke read-only window capture archive",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Archive state: ${profile.archiveState}`,
    `- Ready for read-only capture archive: ${profile.readyForReadOnlyCaptureArchive}`,
    `- Ready for production pass evidence archive: ${profile.readyForProductionPassEvidenceArchive}`,
    `- Ready for production operations: ${profile.readyForProductionOperations}`,
    `- Read only: ${profile.readOnly}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Archive",
    "",
    ...renderEntries(profile.archive),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Artifacts",
    "",
    "### Live Capture",
    "",
    ...renderEntries(profile.artifacts.liveCapture),
    "",
    "### Readiness Packet",
    "",
    ...renderEntries(profile.artifacts.readinessPacket),
    "",
    "### Java Reference",
    "",
    ...renderEntries(profile.artifacts.javaReference),
    "",
    "### mini-kv Reference",
    "",
    ...renderEntries(profile.artifacts.miniKvReference),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No read-only window capture archive blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No read-only window capture archive warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No read-only window capture archive recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
