import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ProductionLiveProbeCapturedWindowRecord,
  ProductionLiveProbeRealReadSmokeReadOnlyWindowLiveCaptureProfile,
} from "./productionLiveProbeRealReadSmokeReadOnlyWindowLiveCaptureTypes.js";

export function renderProductionLiveProbeRealReadSmokeReadOnlyWindowLiveCaptureMarkdown(
  profile: ProductionLiveProbeRealReadSmokeReadOnlyWindowLiveCaptureProfile,
): string {
  return [
    "# Production live probe real-read smoke read-only window live capture",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Capture state: ${profile.captureState}`,
    `- Ready for read-only live capture: ${profile.readyForReadOnlyLiveCapture}`,
    `- Ready for production pass evidence candidate: ${profile.readyForProductionPassEvidenceCandidate}`,
    `- Ready for production operations: ${profile.readyForProductionOperations}`,
    `- Read only: ${profile.readOnly}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Capture",
    "",
    ...renderEntries(profile.capture),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Captured Records",
    "",
    ...profile.capturedRecords.flatMap(renderCapturedRecord),
    "## Artifacts",
    "",
    "### Readiness Packet",
    "",
    ...renderEntries(profile.artifacts.readinessPacket),
    "",
    "### Smoke Harness",
    "",
    ...renderEntries(profile.artifacts.smokeHarness),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No read-only window live capture blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No read-only window live capture warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No read-only window live capture recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}

function renderCapturedRecord(record: ProductionLiveProbeCapturedWindowRecord): string[] {
  return [
    `### ${record.id}`,
    "",
    `- Capture status: ${record.captureStatus}`,
    `- Source status: ${record.sourceStatus}`,
    `- Target: ${record.target}`,
    `- Protocol: ${record.protocol}`,
    `- Read only: ${record.readOnly}`,
    `- Mutates state: ${record.mutatesState}`,
    `- Attempted: ${record.attempted}`,
    `- Message: ${record.message}`,
    `- Evidence summary: ${JSON.stringify(record.evidenceSummary)}`,
    "",
  ];
}
