import {
  renderEntries,
  renderList,
  renderMessages,
} from "./liveProbeReportUtils.js";
import type {
  ProductionLiveProbeRealReadSmokeReadOnlyWindowCaptureArchiveVerificationProfile,
} from "./productionLiveProbeRealReadSmokeReadOnlyWindowCaptureArchiveVerificationTypes.js";

export function renderProductionLiveProbeRealReadSmokeReadOnlyWindowCaptureArchiveVerificationMarkdown(
  profile: ProductionLiveProbeRealReadSmokeReadOnlyWindowCaptureArchiveVerificationProfile,
): string {
  return [
    "# Production live probe real-read smoke read-only window capture archive verification",
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Verification state: ${profile.verificationState}`,
    `- Ready for read-only capture archive verification: ${profile.readyForReadOnlyCaptureArchiveVerification}`,
    `- Ready for production operations: ${profile.readyForProductionOperations}`,
    `- Read only: ${profile.readOnly}`,
    `- Execution allowed: ${profile.executionAllowed}`,
    "",
    "## Verification",
    "",
    ...renderEntries(profile.verification),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Artifacts",
    "",
    "### Archive",
    "",
    ...renderEntries(profile.artifacts.archive),
    "",
    "### Live Capture",
    "",
    ...renderEntries(profile.artifacts.liveCapture),
    "",
    "### Readiness Packet",
    "",
    ...renderEntries(profile.artifacts.readinessPacket),
    "",
    "### Java Reference",
    "",
    ...renderEntries(profile.artifacts.javaReference),
    "",
    "### mini-kv Reference",
    "",
    ...renderEntries(profile.artifacts.miniKvReference),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No read-only window capture archive verification blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No read-only window capture archive verification warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No read-only window capture archive verification recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
