import { renderEntries, renderList, renderMessages } from "./liveProbeReportUtils.js";
import type { ProductionShardExecutionReadinessProfile } from "./productionShardExecutionReadinessTypes.js";

export function renderProductionShardExecutionReadinessMarkdown(
  profile: ProductionShardExecutionReadinessProfile,
): string {
  return [
    `# ${profile.title}`,
    "",
    `- Service: ${profile.service}`,
    `- Generated at: ${profile.generatedAt}`,
    `- Profile version: ${profile.profileVersion}`,
    `- Stage: ${profile.stage.stageId}`,
    `- Active Node version: ${profile.stage.activeNodeVersion}`,
    `- Source Node version: ${profile.stage.sourceNodeVersion}`,
    `- State: ${profile.stage.state}`,
    `- Decision: ${profile.stage.decision}`,
    `- Ready for next stage: ${profile.readyForNextStage}`,
    `- Ready for production shard execution: ${profile.readyForProductionShardExecution}`,
    `- Execution allowed: ${profile.safety.executionAllowed}`,
    `- Java / mini-kv recommended parallel: ${profile.javaMiniKvRecommendedParallel}`,
    "",
    "## Stage",
    "",
    ...renderEntries(profile.stage),
    "",
    "## Safety Boundary",
    "",
    ...renderEntries(profile.safety),
    "",
    "## Sources",
    "",
    ...profile.sources.flatMap((source) => renderEntries(source)),
    "",
    "## Controls",
    "",
    ...profile.controls.flatMap((control) => renderEntries(control)),
    "",
    "## Stage Payload",
    "",
    ...renderEntries(profile.stagePayload),
    "",
    "## Checks",
    "",
    ...renderEntries(profile.checks),
    "",
    "## Summary",
    "",
    ...renderEntries(profile.summary),
    "",
    "## Production Blockers",
    "",
    ...renderMessages(profile.productionBlockers, "No production blockers."),
    "",
    "## Warnings",
    "",
    ...renderMessages(profile.warnings, "No warnings."),
    "",
    "## Recommendations",
    "",
    ...renderMessages(profile.recommendations, "No recommendations."),
    "",
    "## Evidence Endpoints",
    "",
    ...renderEntries(profile.evidenceEndpoints),
    "",
    "## Next Actions",
    "",
    ...renderList(profile.nextActions, "No next actions."),
    "",
  ].join("\n");
}
