import type {
  JavaRollbackApprovalRecordReference,
  MiniKvRestoreDrillEvidenceReference,
} from "./releaseWindowReadinessPacketTypes.js";

export const JAVA_V61_ROLLBACK_APPROVAL_RECORD: JavaRollbackApprovalRecordReference = Object.freeze({
  project: "advanced-order-platform",
  plannedVersion: "Java v61",
  evidenceTag: "v61订单平台rollback-approval-record-fixture",
  fixtureVersion: "java-rollback-approval-record-fixture.v1",
  scenario: "ROLLBACK_APPROVAL_RECORD_FIXTURE_SAMPLE",
  sourceEvidenceEndpoint: "/api/v1/ops/evidence",
  fixtureEndpoint: "/contracts/rollback-approval-record.fixture.json",
  fixtureSource: "src/main/resources/static/contracts/rollback-approval-record.fixture.json",
  archivePath: "c/61",
  fixtureMode: "READ_ONLY_APPROVAL_RECORD_FIXTURE",
  fixtureGoal: "Capture the human rollback approval record shape for a release window packet without executing rollback or reading secret values.",
  approvalRecord: {
    reviewer: "rollback-reviewer-placeholder",
    approvalTimestampPlaceholder: "approval-timestamp-placeholder",
    rollbackTarget: "release-tag-or-artifact-version-placeholder",
    approvalStatus: "PENDING_OPERATOR_CONFIRMATION",
    operatorMustReplacePlaceholders: true,
  } as JavaRollbackApprovalRecordReference["approvalRecord"],
  databaseMigration: {
    directionOptions: [
      "forward-only",
      "rollback-script-reviewed",
      "no-database-change",
    ],
    selectedDirection: "no-database-change",
    rollbackSqlExecutionAllowed: false,
    requiresProductionDatabase: false,
  } as JavaRollbackApprovalRecordReference["databaseMigration"],
  requiredRecordFieldNames: [
    "reviewer",
    "approval-timestamp-placeholder",
    "rollback-target",
    "database-migration-direction",
    "rollback-sql-review-gate",
    "no-secret-value-boundary",
  ] as JavaRollbackApprovalRecordReference["requiredRecordFieldNames"],
  recordArtifacts: [
    "/contracts/rollback-approval-handoff.sample.json",
    "/contracts/rollback-sql-review-gate.sample.json",
    "/contracts/production-deployment-runbook-contract.sample.json",
    "/contracts/production-secret-source-contract.sample.json",
    "/contracts/release-bundle-manifest.sample.json",
  ] as JavaRollbackApprovalRecordReference["recordArtifacts"],
  noSecretValueBoundaries: [
    "Record fixture stores metadata only",
    "Secret values must not be read by Java or Node when rendering this record",
    "Secret values must not be embedded in approval record JSON",
    "Node may render the release window packet only",
  ] as JavaRollbackApprovalRecordReference["noSecretValueBoundaries"],
  nodeConsumption: {
    nodeMayConsume: true,
    nodeMayRenderReleaseWindowPacket: true,
    nodeMayTriggerRollback: false,
    nodeMayExecuteRollbackSql: false,
    nodeMayModifyRuntimeConfig: false,
    nodeMayReadSecretValues: false,
    requiresUpstreamActionsEnabled: false,
  } as JavaRollbackApprovalRecordReference["nodeConsumption"],
  boundaries: {
    rollbackExecutionAllowed: false,
    rollbackSqlExecutionAllowed: false,
    requiresProductionDatabase: false,
    requiresProductionSecrets: false,
    changesOrderCreateSemantics: false,
    changesPaymentOrInventoryTransaction: false,
    changesOutboxOrReplayExecution: false,
    changesOrderTransactionSemantics: false,
    connectsMiniKv: false,
  } as JavaRollbackApprovalRecordReference["boundaries"],
  forbiddenOperations: [
    "Executing Java rollback from this fixture",
    "Executing database rollback SQL from this fixture",
    "Connecting production database from this fixture",
    "Reading production secret values from this fixture",
    "Embedding secret values in approval record JSON",
    "Triggering Java rollback from Node",
    "POST /api/v1/orders",
    "POST /api/v1/failed-events/{id}/replay",
  ] as JavaRollbackApprovalRecordReference["forbiddenOperations"],
  readOnlyEvidence: true,
  executionAllowed: false,
});

export const MINI_KV_V70_RESTORE_DRILL_EVIDENCE: MiniKvRestoreDrillEvidenceReference = Object.freeze({
  project: "mini-kv",
  plannedVersion: "mini-kv v70",
  evidenceTag: "第七十版恢复演练证据",
  drillVersion: "mini-kv-restore-drill-evidence.v1",
  evidencePath: "fixtures/release/restore-drill-evidence.json",
  archivePath: "c/70",
  projectVersion: "0.70.0",
  releaseVersion: "v70",
  readOnly: true,
  executionAllowed: false,
  restoreExecutionAllowed: false,
  orderAuthoritative: false,
  noRuntimeCommandAdded: true,
  restoreDrillTarget: {
    targetReleaseVersion: "v70",
    currentReleaseVersion: "v70",
    previousEvidence: [
      "fixtures/release/verification-manifest.json",
      "fixtures/release/release-artifact-digest-package.json",
      "fixtures/release/artifact-digest-compatibility-matrix.json",
      "fixtures/release/restore-dry-run-operator-package.json",
    ],
    digestComparisonPlaceholder: "sha256:<operator-recorded-restore-drill-digest>",
    comparisonBasis: [
      "release artifact digest package v69",
      "artifact digest compatibility matrix v68",
    ],
    operatorConfirmationRequired: true,
  } as MiniKvRestoreDrillEvidenceReference["restoreDrillTarget"],
  restoreDrillCommands: [
    "INFOJSON",
    "CHECKJSON LOAD data/restore-drill.snap",
    "CHECKJSON COMPACT",
    "CHECKJSON SETNXEX restore:drill-token 30 value",
    "STORAGEJSON",
    "HEALTH",
    "GET restore:drill-token",
    "QUIT",
  ] as MiniKvRestoreDrillEvidenceReference["restoreDrillCommands"],
  restoreDrillExpected: [
    "INFOJSON version matches 0.70.0",
    "CHECKJSON LOAD reports store_replace_from_snapshot without executing LOAD",
    "CHECKJSON COMPACT reports wal_rewrite_when_enabled without executing COMPACT",
    "CHECKJSON SETNXEX reports write risks without token claim",
    "STORAGEJSON keeps order_authoritative=false",
    "GET restore:drill-token returns (nil)",
  ] as MiniKvRestoreDrillEvidenceReference["restoreDrillExpected"],
  writeCommandsExecuted: false,
  adminCommandsExecuted: false,
  operatorConfirmation: {
    required: true,
    fields: [
      "restore_operator_id",
      "restore_drill_target_reviewed_at",
      "digest_comparison_recorded_at",
      "fixture_digest_recorded_at",
      "restore_drill_profile_reviewed",
      "boundary_reviewed",
    ],
  } as MiniKvRestoreDrillEvidenceReference["operatorConfirmation"],
  fixtureInputs: [
    "fixtures/release/verification-manifest.json",
    "fixtures/release/release-artifact-digest-package.json",
    "fixtures/release/artifact-digest-compatibility-matrix.json",
    "fixtures/release/restore-dry-run-operator-package.json",
    "fixtures/release/runtime-artifact-bundle-manifest.json",
    "fixtures/release/restore-compatibility-handoff.json",
    "fixtures/readonly/infojson-empty-inline.json",
    "fixtures/recovery/restart-recovery-evidence.json",
    "fixtures/ttl-token/recovery-evidence.json",
  ],
  boundaries: [
    "restore drill evidence fixture only",
    "digest comparison placeholder only",
    "restore drill command profile only",
    "no runtime command added",
    "does not execute restore",
    "does not execute LOAD/COMPACT/SETNXEX",
    "does not run Java or Node",
    "does not open UPSTREAM_ACTIONS_ENABLED",
    "not connected to Java transaction chain",
    "mini-kv remains not Java order authority",
  ],
});

export const ENDPOINTS = Object.freeze({
  releaseWindowReadinessPacketJson: "/api/v1/production/release-window-readiness-packet",
  releaseWindowReadinessPacketMarkdown: "/api/v1/production/release-window-readiness-packet?format=markdown",
  deploymentEvidenceIntakeGateJson: "/api/v1/production/deployment-evidence-intake-gate",
  deploymentEvidenceVerificationJson: "/api/v1/production/deployment-evidence-verification",
  javaRollbackApprovalRecordFixture: "/contracts/rollback-approval-record.fixture.json",
  miniKvRestoreDrillEvidence: "fixtures/release/restore-drill-evidence.json",
  currentRoadmap: "docs/plans/v169-post-production-environment-preflight-roadmap.md",
});
