export const dashboardClientOperationsScript = "\n" + [
  "",
  "    document.body.addEventListener(\"click\", async (event) => {",
  "      const button = event.target.closest(\"button[data-action]\");",
  "      if (!button) {",
  "        return;",
  "      }",
  "",
  "      const action = button.dataset.action;",
  "      button.disabled = true;",
  "      try {",
  "        if (action === \"products\") {",
  "          write(await api(\"/api/v1/order-platform/products\"));",
  "        }",
  "        if (action === \"outbox\") {",
  "          write(await api(\"/api/v1/order-platform/outbox/events\"));",
  "        }",
  "        if (action === \"order\") {",
  "          write(await api(\"/api/v1/order-platform/orders/\" + encodeURIComponent($(\"orderId\").value)));",
  "        }",
  "        if (action === \"failedEventReadiness\") {",
  "          write(await refreshFailedEventReadiness());",
  "        }",
  "        if (action === \"createOrder\") {",
  "          write(await api(\"/api/v1/order-platform/orders\", {",
  "            method: \"POST\",",
  "            headers: { \"idempotency-key\": $(\"idempotencyKey\").value },",
  "            body: $(\"orderBody\").value,",
  "          }));",
  "        }",
  "        if (action === \"kvGet\") {",
  "          write(await api(\"/api/v1/mini-kv/\" + encodeURIComponent($(\"kvKey\").value)));",
  "        }",
  "        if (action === \"kvSet\") {",
  "          const body = { value: $(\"kvValue\").value };",
  "          const ttl = Number($(\"kvTtl\").value);",
  "          if (Number.isInteger(ttl) && ttl > 0) {",
  "            body.ttlSeconds = ttl;",
  "          }",
  "          write(await api(\"/api/v1/mini-kv/\" + encodeURIComponent($(\"kvKey\").value), {",
  "            method: \"PUT\",",
  "            body: JSON.stringify(body),",
  "          }));",
  "        }",
  "        if (action === \"kvDelete\") {",
  "          write(await api(\"/api/v1/mini-kv/\" + encodeURIComponent($(\"kvKey\").value), { method: \"DELETE\" }));",
  "        }",
  "        if (action === \"kvPing\") {",
  "          write(await api(\"/api/v1/mini-kv/status\"));",
  "        }",
  "        if (action === \"rawCommand\") {",
  "          write(await api(\"/api/v1/mini-kv/commands\", {",
  "            method: \"POST\",",
  "            body: JSON.stringify({ command: $(\"rawCommand\").value }),",
  "          }));",
  "        }",
  "        if (action === \"kvInventory\") {",
  "          write(await refreshMiniKvKeyInventory());",
  "        }",
  "        if (action === \"auditSummary\") {",
  "          write(await refreshAudit());",
  "        }",
  "        if (action === \"auditEvents\") {",
  "          write(await api(\"/api/v1/audit/events?limit=20\"));",
  "          void refreshAudit().catch(() => {});",
  "        }",
  "        if (action === \"runtimeConfig\") {",
  "          write(await refreshRuntimeConfig());",
  "        }",
  "        if (action === \"upstreamOverview\") {",
  "          write(await refreshUpstreamOverview());",
  "        }",
  "        if (action === \"fixtureDiagnostics\") {",
  "          write(await refreshFixtureDiagnostics());",
  "        }",
  "        if (action === \"fixtureReportMarkdown\") {",
  "          const response = await fetch(\"/api/v1/upstream-contract-fixtures?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"fixtureDriftMarkdown\") {",
  "          const response = await fetch(\"/api/v1/upstream-contract-fixtures/drift-diagnostics?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"scenarioMatrix\") {",
  "          write(await refreshScenarioMatrix());",
  "        }",
  "        if (action === \"scenarioMatrixMarkdown\") {",
  "          const response = await fetch(\"/api/v1/upstream-contract-fixtures/scenario-matrix?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"scenarioVerification\") {",
  "          write(await refreshScenarioVerification());",
  "        }",
  "        if (action === \"scenarioVerificationMarkdown\") {",
  "          const response = await fetch(\"/api/v1/upstream-contract-fixtures/scenario-matrix/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"scenarioArchiveBundle\") {",
  "          write(await refreshScenarioArchiveBundle());",
  "        }",
  "        if (action === \"scenarioArchiveBundleMarkdown\") {",
  "          const response = await fetch(\"/api/v1/upstream-contract-fixtures/scenario-matrix/verification/archive-bundle?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"scenarioArchiveVerification\") {",
  "          write(await refreshScenarioArchiveVerification());",
  "        }",
  "        if (action === \"scenarioArchiveVerificationMarkdown\") {",
  "          const response = await fetch(\"/api/v1/upstream-contract-fixtures/scenario-matrix/verification/archive-bundle/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsSummary\") {",
  "          write(await refreshOpsSummary());",
  "        }",
  "        if (action === \"opsReadiness\") {",
  "          write(await refreshOpsReadiness());",
  "        }",
  "        if (action === \"opsRunbook\") {",
  "          write(await api(\"/api/v1/ops/runbook\"));",
  "        }",
  "        if (action === \"opsCreateCheckpoint\") {",
  "          write(await api(\"/api/v1/ops/checkpoints\", {",
  "            method: \"POST\",",
  "            body: JSON.stringify({",
  "              actor: $(\"operatorId\").value || \"dashboard\",",
  "              note: $(\"intentReason\").value || \"dashboard checkpoint\",",
  "            }),",
  "          }));",
  "        }",
  "        if (action === \"opsListCheckpoints\") {",
  "          write(await api(\"/api/v1/ops/checkpoints?limit=10\"));",
  "        }",
  "        if (action === \"opsDiffCheckpoints\") {",
  "          const listed = await api(\"/api/v1/ops/checkpoints?limit=2\");",
  "          if (listed.checkpoints.length < 2) {",
  "            write({ error: \"NEED_TWO_CHECKPOINTS\", message: \"Create at least two checkpoints before diffing.\" });",
  "          } else {",
  "            const target = listed.checkpoints[0];",
  "            const base = listed.checkpoints[1];",
  "            write(await api(\"/api/v1/ops/checkpoints/diff?baseId=\" + encodeURIComponent(base.id) + \"&targetId=\" + encodeURIComponent(target.id)));",
  "          }",
  "        }",
  "        if (action === \"opsSetBaseline\") {",
  "          const listed = await api(\"/api/v1/ops/checkpoints?limit=1\");",
  "          if (listed.checkpoints.length < 1) {",
  "            write({ error: \"NEED_CHECKPOINT\", message: \"Create a checkpoint before setting the baseline.\" });",
  "          } else {",
  "            write(await api(\"/api/v1/ops/baseline\", {",
  "              method: \"PUT\",",
  "              body: JSON.stringify({",
  "                checkpointId: listed.checkpoints[0].id,",
  "                actor: $(\"operatorId\").value || \"dashboard\",",
  "                note: $(\"intentReason\").value || \"dashboard baseline\",",
  "              }),",
  "            }));",
  "          }",
  "        }",
  "        if (action === \"opsBaseline\") {",
  "          write(await api(\"/api/v1/ops/baseline\"));",
  "        }",
  "        if (action === \"opsPromotionReview\") {",
  "          write(await api(\"/api/v1/ops/promotion-review\"));",
  "        }",
  "        if (action === \"opsRecordPromotionDecision\") {",
  "          write(await api(\"/api/v1/ops/promotion-decisions\", {",
  "            method: \"POST\",",
  "            body: JSON.stringify({",
  "              reviewer: $(\"operatorId\").value || \"dashboard\",",
  "              note: $(\"intentReason\").value || \"dashboard promotion decision\",",
  "            }),",
  "          }));",
  "        }",
  "        if (action === \"opsPromotionDecisions\") {",
  "          write(await api(\"/api/v1/ops/promotion-decisions?limit=10\"));",
  "        }",
  "        if (action === \"opsVerifyPromotionDecision\") {",
  "          const listed = await api(\"/api/v1/ops/promotion-decisions?limit=1\");",
  "          if (listed.decisions.length < 1) {",
  "            write({ error: \"NEED_PROMOTION_DECISION\", message: \"Record a promotion decision before verification.\" });",
  "          } else {",
  "            write(await api(\"/api/v1/ops/promotion-decisions/\" + encodeURIComponent(listed.decisions[0].id) + \"/verification\"));",
  "          }",
  "        }",
  "        if (action === \"opsPromotionEvidence\") {",
  "          const listed = await api(\"/api/v1/ops/promotion-decisions?limit=1\");",
  "          if (listed.decisions.length < 1) {",
  "            write({ error: \"NEED_PROMOTION_DECISION\", message: \"Record a promotion decision before building evidence.\" });",
  "          } else {",
  "            const response = await fetch(\"/api/v1/ops/promotion-decisions/\" + encodeURIComponent(listed.decisions[0].id) + \"/evidence?format=markdown\");",
  "            if (!response.ok) {",
  "              throw await response.json();",
  "            }",
  "            output.textContent = await response.text();",
  "          }",
  "        }",
  "        if (action === \"opsPromotionIntegrity\") {",
  "          write(await api(\"/api/v1/ops/promotion-decisions/integrity\"));",
  "        }",
  "        if (action === \"opsPromotionIntegrityReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-decisions/integrity?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionArchive\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive\"));",
  "        }",
  "        if (action === \"opsPromotionArchiveReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionArchiveManifest\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/manifest\"));",
  "        }",
  "        if (action === \"opsPromotionArchiveManifestReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/manifest?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionArchiveVerification\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/verification\"));",
  "        }",
  "        if (action === \"opsPromotionArchiveVerificationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionArchiveAttestation\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/attestation\"));",
  "        }",
  "        if (action === \"opsPromotionArchiveAttestationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/attestation?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionArchiveAttestationVerification\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/attestation/verification\"));",
  "        }",
  "        if (action === \"opsPromotionArchiveAttestationVerificationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/attestation/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionHandoffPackage\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/handoff-package\"));",
  "        }",
  "        if (action === \"opsPromotionHandoffPackageReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/handoff-package?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionHandoffPackageVerification\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/handoff-package/verification\"));",
  "        }",
  "        if (action === \"opsPromotionHandoffPackageVerificationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/handoff-package/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionHandoffCertificate\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/handoff-certificate\"));",
  "        }",
  "        if (action === \"opsPromotionHandoffCertificateReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/handoff-certificate?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionHandoffCertificateVerification\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/handoff-certificate/verification\"));",
  "        }",
  "        if (action === \"opsPromotionHandoffCertificateVerificationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/handoff-certificate/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionHandoffReceipt\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/handoff-receipt\"));",
  "        }",
  "        if (action === \"opsPromotionHandoffReceiptReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/handoff-receipt?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionHandoffReceiptVerification\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/handoff-receipt/verification\"));",
  "        }",
  "        if (action === \"opsPromotionHandoffReceiptVerificationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/handoff-receipt/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionHandoffClosure\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/handoff-closure\"));",
  "        }",
  "        if (action === \"opsPromotionHandoffClosureReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/handoff-closure?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionHandoffClosureVerification\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/handoff-closure/verification\"));",
  "        }",
  "        if (action === \"opsPromotionHandoffClosureVerificationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/handoff-closure/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionHandoffCompletion\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/handoff-completion\"));",
  "        }",
  "        if (action === \"opsPromotionHandoffCompletionReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/handoff-completion?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
].join("\n");
