export const dashboardClientActionsScript = "\n" + [
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionHandoffCompletionVerification\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/handoff-completion/verification\"));",
  "        }",
  "        if (action === \"opsPromotionHandoffCompletionVerificationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/handoff-completion/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionReleaseEvidence\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/release-evidence\"));",
  "        }",
  "        if (action === \"opsPromotionReleaseEvidenceReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/release-evidence?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionReleaseEvidenceVerification\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/release-evidence/verification\"));",
  "        }",
  "        if (action === \"opsPromotionReleaseEvidenceVerificationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/release-evidence/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionReleaseArchive\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/release-archive\"));",
  "        }",
  "        if (action === \"opsPromotionReleaseArchiveReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/release-archive?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionReleaseArchiveVerification\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/release-archive/verification\"));",
  "        }",
  "        if (action === \"opsPromotionReleaseArchiveVerificationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/release-archive/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionDeploymentApproval\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/deployment-approval\"));",
  "        }",
  "        if (action === \"opsPromotionDeploymentApprovalReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/deployment-approval?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionDeploymentApprovalVerification\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/deployment-approval/verification\"));",
  "        }",
  "        if (action === \"opsPromotionDeploymentApprovalVerificationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/deployment-approval/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionDeploymentChangeRecord\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/deployment-change-record\"));",
  "        }",
  "        if (action === \"opsPromotionDeploymentChangeRecordReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/deployment-change-record?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionDeploymentChangeRecordVerification\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/deployment-change-record/verification\"));",
  "        }",
  "        if (action === \"opsPromotionDeploymentChangeRecordVerificationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/deployment-change-record/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionDeploymentExecutionRecord\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/deployment-execution-record\"));",
  "        }",
  "        if (action === \"opsPromotionDeploymentExecutionRecordReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/deployment-execution-record?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionDeploymentExecutionRecordVerification\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/deployment-execution-record/verification\"));",
  "        }",
  "        if (action === \"opsPromotionDeploymentExecutionRecordVerificationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/deployment-execution-record/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionDeploymentExecutionReceipt\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/deployment-execution-receipt\"));",
  "        }",
  "        if (action === \"opsPromotionDeploymentExecutionReceiptReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/deployment-execution-receipt?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionDeploymentExecutionReceiptVerification\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/deployment-execution-receipt/verification\"));",
  "        }",
  "        if (action === \"opsPromotionDeploymentExecutionReceiptVerificationReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/deployment-execution-receipt/verification?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsPromotionReleaseAuditTrailRecord\") {",
  "          write(await api(\"/api/v1/ops/promotion-archive/release-audit-trail-record\"));",
  "        }",
  "        if (action === \"opsPromotionReleaseAuditTrailRecordReport\") {",
  "          const response = await fetch(\"/api/v1/ops/promotion-archive/release-audit-trail-record?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"opsHandoffReport\") {",
  "          write(await api(\"/api/v1/ops/handoff-report?limit=10\"));",
  "        }",
  "        if (action === \"planAction\") {",
  "          write(await api(\"/api/v1/action-plans\", {",
  "            method: \"POST\",",
  "            body: JSON.stringify({ action: $(\"planAction\").value }),",
  "          }));",
  "        }",
  "        if (action === \"planCatalog\") {",
  "          write(await api(\"/api/v1/action-plans/catalog\"));",
  "        }",
  "        if (action === \"createIntent\") {",
  "          const headers = {};",
  "          if ($(\"intentKey\").value.trim()) {",
  "            headers[\"idempotency-key\"] = $(\"intentKey\").value.trim();",
  "          }",
  "          const intent = await api(\"/api/v1/operation-intents\", {",
  "            method: \"POST\",",
  "            headers,",
  "            body: JSON.stringify({",
  "              action: $(\"planAction\").value,",
  "              operatorId: $(\"operatorId\").value,",
  "              role: $(\"operatorRole\").value,",
  "              reason: $(\"intentReason\").value,",
  "            }),",
  "          });",
  "          $(\"intentId\").value = intent.id;",
  "          $(\"confirmText\").value = intent.confirmation.requiredText;",
  "          write(intent);",
  "        }",
  "        if (action === \"listIntents\") {",
  "          write(await api(\"/api/v1/operation-intents?limit=20\"));",
  "        }",
  "        if (action === \"confirmIntent\") {",
  "          write(await api(\"/api/v1/operation-intents/\" + encodeURIComponent($(\"intentId\").value) + \"/confirm\", {",
  "            method: \"POST\",",
  "            body: JSON.stringify({",
  "              operatorId: $(\"operatorId\").value,",
  "              confirmText: $(\"confirmText\").value,",
  "            }),",
  "          }));",
  "        }",
  "        if (action === \"dispatchIntent\") {",
  "          write(await api(\"/api/v1/operation-dispatches\", {",
  "            method: \"POST\",",
  "            body: JSON.stringify({",
  "              intentId: $(\"intentId\").value,",
  "              requestedBy: $(\"operatorId\").value || \"dashboard\",",
  "              mode: \"dry-run\",",
  "            }),",
  "          }));",
  "        }",
  "        if (action === \"intentPreflight\") {",
  "          const query = new URLSearchParams();",
  "          const failedEventId = $(\"failedEventId\").value.trim();",
  "          const keyPrefix = $(\"kvPrefix\").value.trim();",
  "          if (failedEventId) {",
  "            query.set(\"failedEventId\", failedEventId);",
  "          }",
  "          if (keyPrefix) {",
  "            query.set(\"keyPrefix\", keyPrefix);",
  "          }",
  "          const suffix = query.toString() ? \"?\" + query.toString() : \"\";",
  "          write(await api(\"/api/v1/operation-intents/\" + encodeURIComponent($(\"intentId\").value) + \"/preflight\" + suffix));",
  "        }",
  "        if (action === \"intentPreflightReport\") {",
  "          const query = new URLSearchParams();",
  "          const failedEventId = $(\"failedEventId\").value.trim();",
  "          const keyPrefix = $(\"kvPrefix\").value.trim();",
  "          query.set(\"format\", \"markdown\");",
  "          if (failedEventId) {",
  "            query.set(\"failedEventId\", failedEventId);",
  "          }",
  "          if (keyPrefix) {",
  "            query.set(\"keyPrefix\", keyPrefix);",
  "          }",
  "          const response = await fetch(\"/api/v1/operation-intents/\" + encodeURIComponent($(\"intentId\").value) + \"/preflight/report?\" + query.toString());",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"intentPreflightVerification\") {",
  "          const query = new URLSearchParams();",
  "          const failedEventId = $(\"failedEventId\").value.trim();",
  "          const keyPrefix = $(\"kvPrefix\").value.trim();",
  "          if (failedEventId) {",
  "            query.set(\"failedEventId\", failedEventId);",
  "          }",
  "          if (keyPrefix) {",
  "            query.set(\"keyPrefix\", keyPrefix);",
  "          }",
  "          const suffix = query.toString() ? \"?\" + query.toString() : \"\";",
  "          write(await api(\"/api/v1/operation-intents/\" + encodeURIComponent($(\"intentId\").value) + \"/preflight/verification\" + suffix));",
  "        }",
  "        if (action === \"intentExecutionPreview\") {",
  "          const query = new URLSearchParams();",
  "          const failedEventId = $(\"failedEventId\").value.trim();",
  "          const keyPrefix = $(\"kvPrefix\").value.trim();",
  "          const command = $(\"rawCommand\").value.trim();",
  "          const key = $(\"kvKey\").value.trim();",
  "          const value = $(\"kvValue\").value.trim();",
  "          if (failedEventId) {",
  "            query.set(\"failedEventId\", failedEventId);",
  "          }",
  "          if (keyPrefix) {",
  "            query.set(\"keyPrefix\", keyPrefix);",
  "          }",
  "          if (command) {",
  "            query.set(\"command\", command);",
  "          }",
  "          if (key) {",
  "            query.set(\"key\", key);",
  "          }",
  "          if (value) {",
  "            query.set(\"value\", value);",
  "          }",
  "          const suffix = query.toString() ? \"?\" + query.toString() : \"\";",
  "          write(await api(\"/api/v1/operation-intents/\" + encodeURIComponent($(\"intentId\").value) + \"/execution-preview\" + suffix));",
  "        }",
  "        if (action === \"createApprovalRequest\") {",
  "          const body = {",
  "            intentId: $(\"intentId\").value,",
  "            requestedBy: $(\"operatorId\").value || \"dashboard\",",
  "            reviewer: $(\"operatorId\").value || \"unassigned\",",
  "            decisionReason: $(\"intentReason\").value || \"dashboard approval request\",",
  "          };",
  "          const failedEventId = $(\"failedEventId\").value.trim();",
  "          const keyPrefix = $(\"kvPrefix\").value.trim();",
  "          const command = $(\"rawCommand\").value.trim();",
  "          const key = $(\"kvKey\").value.trim();",
  "          const value = $(\"kvValue\").value.trim();",
  "          if (failedEventId) {",
  "            body.failedEventId = failedEventId;",
  "          }",
  "          if (keyPrefix) {",
  "            body.keyPrefix = keyPrefix;",
  "          }",
  "          if (command) {",
  "            body.command = command;",
  "          }",
  "          if (key) {",
  "            body.key = key;",
  "          }",
  "          if (value) {",
  "            body.value = value;",
  "          }",
  "          const approvalRequest = await api(\"/api/v1/operation-approval-requests\", {",
  "            method: \"POST\",",
  "            body: JSON.stringify(body),",
  "          });",
  "          $(\"approvalRequestId\").value = approvalRequest.requestId;",
  "          write(approvalRequest);",
  "        }",
  "        if (action === \"listApprovalRequests\") {",
  "          write(await api(\"/api/v1/operation-approval-requests?limit=20\"));",
  "        }",
  "        if (action === \"approveApprovalRequest\" || action === \"rejectApprovalRequest\") {",
  "          const approvalDecision = await api(\"/api/v1/operation-approval-requests/\" + encodeURIComponent($(\"approvalRequestId\").value) + \"/decision\", {",
  "            method: \"POST\",",
  "            body: JSON.stringify({",
  "              decision: action === \"approveApprovalRequest\" ? \"approved\" : \"rejected\",",
  "              reviewer: $(\"operatorId\").value || \"dashboard-reviewer\",",
  "              reason: $(\"approvalDecisionReason\").value || \"dashboard approval decision\",",
  "            }),",
  "          });",
  "          write(approvalDecision);",
  "        }",
  "        if (action === \"listApprovalDecisions\") {",
  "          write(await api(\"/api/v1/operation-approval-decisions?limit=20\"));",
  "        }",
  "        if (action === \"approvalEvidenceReport\") {",
  "          const response = await fetch(\"/api/v1/operation-approval-requests/\" + encodeURIComponent($(\"approvalRequestId\").value) + \"/evidence?format=markdown\");",
  "          if (!response.ok) {",
  "            throw await response.json();",
  "          }",
  "          output.textContent = await response.text();",
  "        }",
  "        if (action === \"approvalEvidenceVerification\") {",
  "          write(await api(\"/api/v1/operation-approval-requests/\" + encodeURIComponent($(\"approvalRequestId\").value) + \"/verification\"));",
  "        }",
  "        if (action === \"intentTimeline\") {",
  "          write(await api(\"/api/v1/operation-intents/\" + encodeURIComponent($(\"intentId\").value) + \"/timeline?limit=30\"));",
  "        }",
  "        if (action === \"intentEvents\") {",
  "          write(await api(\"/api/v1/operation-intent-events?limit=30\"));",
  "        }",
  "        if (action === \"listDispatches\") {",
  "          write(await api(\"/api/v1/operation-dispatches?limit=20\"));",
  "        }",
  "      } catch (error) {",
  "        write(error);",
  "      } finally {",
  "        button.disabled = false;",
  "      }",
  "    });",
  "",
  "    const events = new EventSource(\"/api/v1/events/ops\");",
  "    events.addEventListener(\"snapshot\", (event) => renderSnapshot(JSON.parse(event.data)));",
  "    events.addEventListener(\"error\", () => flash(\"Live stream disconnected; polling fallback is active.\"));",
  "    setInterval(() => {",
  "      if (events.readyState !== EventSource.OPEN) {",
  "        void refreshStatus().catch(write);",
  "      }",
  "    }, 5000);",
  "    void refreshStatus().catch(write);",
  "    void refreshAudit().catch(() => {});",
  "    void refreshRuntimeConfig().catch(() => {});",
  "    void refreshUpstreamOverview().catch(() => {});",
  "    void refreshFixtureDiagnostics().catch(() => {});",
  "    void refreshScenarioMatrix().catch(() => {});",
  "    void refreshScenarioVerification().catch(() => {});",
  "    void refreshScenarioArchiveBundle().catch(() => {});",
  "    void refreshScenarioArchiveVerification().catch(() => {});",
  "    void refreshOpsSummary().catch(() => {});",
  "    void refreshOpsReadiness().catch(() => {});",
  "",
].join("\n");
