export const dashboardClientCoreScript = [
  "",
  "    const $ = (id) => document.getElementById(id);",
  "    const output = $(\"output\");",
  "",
  "    function setBadge(id, state) {",
  "      const el = $(id);",
  "      el.className = \"badge \" + state;",
  "      el.textContent = state;",
  "    }",
  "",
  "    function write(data) {",
  "      output.textContent = JSON.stringify(data, null, 2);",
  "    }",
  "",
  "    function flash(message) {",
  "      output.textContent = message + \"\\n\" + output.textContent;",
  "    }",
  "",
  "    function setText(id, value) {",
  "      $(id).textContent = value === undefined || value === null || value === \"\" ? \"-\" : String(value);",
  "    }",
  "",
  "    function formatBool(value) {",
  "      if (value === true) {",
  "        return \"yes\";",
  "      }",
  "      if (value === false) {",
  "        return \"no\";",
  "      }",
  "      return \"-\";",
  "    }",
  "",
  "    function formatNumber(value) {",
  "      return Number.isFinite(value) ? String(value) : \"-\";",
  "    }",
  "",
  "    function formatAvailable(value) {",
  "      return value === true ? \"available\" : \"missing\";",
  "    }",
  "",
  "    function formatList(value) {",
  "      return Array.isArray(value) && value.length > 0 ? value.join(\", \") : \"-\";",
  "    }",
  "",
  "    function formatDigest(value) {",
  "      return typeof value === \"string\" && value.length > 0 ? value : \"-\";",
  "    }",
  "",
  "    function formatCheckRatio(checks, prefix) {",
  "      const entries = Object.entries(checks || {}).filter(([name]) => name.startsWith(prefix));",
  "      const passing = entries.filter(([, value]) => value === true).length;",
  "      return entries.length === 0 ? \"-\" : passing + \"/\" + entries.length + \" ok\";",
  "    }",
  "",
  "    async function api(path, options = {}) {",
  "      const response = await fetch(path, {",
  "        ...options,",
  "        headers: {",
  "          \"content-type\": \"application/json\",",
  "          ...(options.headers || {}),",
  "        },",
  "      });",
  "      const text = await response.text();",
  "      const data = text ? JSON.parse(text) : null;",
  "      if (!response.ok) {",
  "        throw data;",
  "      }",
  "      return data;",
  "    }",
  "",
  "    function renderUpstreamOverview(overview) {",
  "      const java = overview.upstreams.javaOrderPlatform;",
  "      const kv = overview.upstreams.miniKv;",
  "      const javaSignals = java.signals || {};",
  "      const kvSignals = kv.signals || {};",
  "      const javaOrders = javaSignals.orders || {};",
  "      const javaOutbox = javaSignals.outbox || {};",
  "      const commandCounts = kvSignals.commandCatalogCounts || {};",
  "",
  "      setBadge(\"overviewOverallState\", overview.overallState);",
  "      setText(\"overviewSafety\", \"probes \" + (overview.safety.upstreamProbesEnabled ? \"on\" : \"off\") + \" / actions \" + (overview.safety.upstreamActionsEnabled ? \"on\" : \"off\"));",
  "      setText(\"overviewJavaState\", java.state + (java.latencyMs === undefined ? \"\" : \" / \" + java.latencyMs + \"ms\"));",
  "      setText(\"overviewKvState\", kv.state + (kv.latencyMs === undefined ? \"\" : \" / \" + kv.latencyMs + \"ms\"));",
  "      setText(\"overviewNextAction\", overview.recommendedNextActions[0]);",
  "",
  "      setText(\"javaHealthSignal\", javaSignals.healthStatus || java.state);",
  "      setText(\"javaBusinessSignal\", formatAvailable(javaSignals.businessOverviewAvailable));",
  "      setText(\"javaOrdersSignal\", \"orders \" + formatNumber(javaOrders.total) + \" / outbox \" + formatNumber(javaOutbox.pending));",
  "      setText(\"javaFailedSummarySignal\", formatAvailable(javaSignals.failedEventSummaryAvailable));",
  "      setText(\"javaBacklogSignal\", formatNumber(javaSignals.failedEventReplayBacklog));",
  "      setText(\"javaApprovalsSignal\", formatNumber(javaSignals.failedEventPendingReplayApprovals));",
  "",
  "      setText(\"kvIdentitySignal\", (kvSignals.version || \"-\") + \" / \" + ((kvSignals.protocol || []).join(\",\") || \"-\"));",
  "      setText(\"kvStoreSignal\", \"keys \" + formatNumber(kvSignals.liveKeys));",
  "      setText(\"kvWalSignal\", \"wal \" + formatBool(kvSignals.walEnabled) + \" / metrics \" + formatBool(kvSignals.metricsEnabled));",
  "      setText(\"kvCommandSignal\", formatAvailable(kvSignals.commandCatalogAvailable) + \" / total \" + formatNumber(commandCounts.total));",
  "      setText(\"kvRiskSignal\", \"write \" + formatNumber(kvSignals.writeCommandCount) + \" / admin \" + formatNumber(kvSignals.adminCommandCount) + \" / mutating \" + formatNumber(kvSignals.mutatingCommandCount));",
  "      setText(\"kvInventorySignal\", formatAvailable(kvSignals.keyInventoryAvailable) + \" / count \" + formatNumber(kvSignals.keyInventoryKeyCount));",
  "      setText(\"kvInventoryTruncatedSignal\", formatBool(kvSignals.keyInventoryTruncated) + \" / limit \" + formatNumber(kvSignals.keyInventoryLimit));",
  "      setText(\"kvInventoryKeysSignal\", formatList(kvSignals.keyInventorySampleKeys));",
  "    }",
  "",
  "    function renderFailedEventReadiness(readiness) {",
  "      const state = readiness.exists === false",
  "        ? \"not found\"",
  "        : (readiness.eligibleForReplay ? \"eligible\" : \"blocked\");",
  "      setText(\"failedEventReadinessSignal\", state + \" / approval \" + (readiness.requiresApproval ? \"required\" : \"not required\"));",
  "      setText(\"failedEventBlockersSignal\", formatList(readiness.blockedBy));",
  "      setText(\"failedEventNextActionsSignal\", formatList(readiness.nextAllowedActions));",
  "    }",
  "",
  "    async function refreshFailedEventReadiness() {",
  "      const failedEventId = $(\"failedEventId\").value.trim();",
  "      if (!/^\\\\d+$/.test(failedEventId)) {",
  "        throw { error: \"FAILED_EVENT_ID_REQUIRED\", message: \"Enter a numeric failed event ID.\" };",
  "      }",
  "      const readiness = await api(\"/api/v1/order-platform/failed-events/\" + encodeURIComponent(failedEventId) + \"/replay-readiness\");",
  "      renderFailedEventReadiness(readiness);",
  "      return readiness;",
  "    }",
  "",
  "    function renderMiniKvKeyInventory(result) {",
  "      const inventory = result.inventory || result;",
  "      setText(\"kvInventorySignal\", \"prefix \" + (inventory.prefix || \"-\") + \" / count \" + formatNumber(inventory.key_count));",
  "      setText(\"kvInventoryTruncatedSignal\", formatBool(inventory.truncated) + \" / limit \" + formatNumber(inventory.limit));",
  "      setText(\"kvInventoryKeysSignal\", formatList(inventory.keys));",
  "    }",
  "",
  "    function renderFixtureDiagnostics(report, drift) {",
  "      setBadge(\"fixtureReportState\", report.valid ? \"online\" : \"degraded\");",
  "      setText(\"fixtureDigestSignal\", report.fixtureDigest.algorithm + \":\" + report.fixtureDigest.value);",
  "      setText(\"fixtureJavaStatusSignal\", report.summary.javaFixtureStatus);",
  "      setText(\"fixtureMiniKvStatusSignal\", report.summary.miniKvFixtureStatus);",
  "",
  "      setText(\"fixtureJavaContractDigestSignal\", formatDigest(report.summary.javaContractDigest));",
  "      setText(\"fixtureJavaPreconditionsSignal\", formatBool(report.summary.javaReplayPreconditionsSatisfied));",
  "      setText(\"fixtureJavaExecutionChecksSignal\", formatCheckRatio(report.checks, \"java\"));",
  "      setText(\"fixtureJavaSideEffectsSignal\", formatNumber(report.summary.javaExpectedSideEffectCount));",
  "",
  "      setText(\"fixtureMiniKvCommandDigestSignal\", formatDigest(report.summary.miniKvCommandDigest));",
  "      setText(\"fixtureMiniKvReadExecuteSignal\", \"read_only \" + formatBool(report.summary.miniKvReadOnly) + \" / execution_allowed \" + formatBool(report.summary.miniKvExecutionAllowed));",
  "      setText(\"fixtureMiniKvSideEffectsSignal\", formatNumber(report.summary.miniKvSideEffectCount));",
  "      setText(\"fixtureDriftSignal\", (drift.summary.issueCount > 0 ? \"yes\" : \"no\") + \" / issues \" + formatNumber(drift.summary.issueCount) + \" / errors \" + formatNumber(drift.summary.errorCount));",
  "      setText(\"fixtureDriftMappingSignal\", \"missing \" + formatNumber(drift.summary.missingMappingCount) + \" / total \" + formatNumber(drift.mappings.length));",
  "    }",
  "",
  "    async function refreshFixtureDiagnostics() {",
  "      const [report, drift] = await Promise.all([",
  "        api(\"/api/v1/upstream-contract-fixtures\"),",
  "        api(\"/api/v1/upstream-contract-fixtures/drift-diagnostics\"),",
  "      ]);",
  "      renderFixtureDiagnostics(report, drift);",
  "      return { fixtureReport: report, driftDiagnostics: drift };",
  "    }",
  "",
  "    function findScenario(matrix, id) {",
  "      return (matrix.scenarios || []).find((scenario) => scenario.id === id);",
  "    }",
  "",
  "    function formatScenarioStatus(scenario) {",
  "      if (!scenario) {",
  "        return \"-\";",
  "      }",
  "      return [",
  "        \"valid \" + formatBool(scenario.valid),",
  "        \"ready \" + formatBool(scenario.diagnosticReady),",
  "        \"failing \" + formatNumber(scenario.failingCheckCount) + \"/\" + formatNumber(scenario.checkCount),",
  "      ].join(\" / \");",
  "    }",
  "",
  "    function renderScenarioMatrix(matrix) {",
  "      setBadge(\"scenarioMatrixState\", matrix.valid ? \"online\" : \"degraded\");",
  "      setText(\"scenarioMatrixDigestSignal\", matrix.matrixDigest.algorithm + \":\" + matrix.matrixDigest.value);",
  "      setText(",
  "        \"scenarioMatrixCountSignal\",",
  "        formatNumber(matrix.summary.validScenarios) + \"/\" + formatNumber(matrix.summary.totalScenarios) + \" valid / ready \" + formatNumber(matrix.summary.diagnosticReadyScenarios),",
  "      );",
  "      setText(",
  "        \"scenarioMatrixIssueSignal\",",
  "        \"issues \" + formatNumber(matrix.summary.issueCount) + \" / drift \" + formatBool(matrix.driftSummary.hasDrift),",
  "      );",
  "      setText(\"scenarioJavaApprovedSignal\", formatScenarioStatus(findScenario(matrix, \"java-approved-replay-contract\")));",
  "      setText(\"scenarioJavaBlockedSignal\", formatScenarioStatus(findScenario(matrix, \"java-blocked-replay-contract\")));",
  "      setText(\"scenarioMiniKvWriteSignal\", formatScenarioStatus(findScenario(matrix, \"mini-kv-write-checkjson\")));",
  "      setText(\"scenarioMiniKvReadSignal\", formatScenarioStatus(findScenario(matrix, \"mini-kv-read-checkjson\")));",
  "      setText(\"scenarioMatrixDriftSignal\", \"issues \" + formatNumber(matrix.driftSummary.issueCount));",
  "    }",
  "",
  "    async function refreshScenarioMatrix() {",
  "      const matrix = await api(\"/api/v1/upstream-contract-fixtures/scenario-matrix\");",
  "      renderScenarioMatrix(matrix);",
  "      return matrix;",
  "    }",
  "",
  "    function renderScenarioVerification(verification) {",
  "      const checks = verification.checks || {};",
  "      setBadge(\"scenarioVerificationState\", verification.valid ? \"online\" : \"degraded\");",
  "      setText(\"scenarioVerificationValidSignal\", formatBool(verification.valid));",
  "      setText(\"scenarioVerificationDigestSignal\", formatBool(checks.matrixDigestValid));",
  "      setText(",
  "        \"scenarioVerificationScenarioCountSignal\",",
  "        formatBool(checks.scenarioCountValid) + \" / total \" + formatNumber(verification.summary.totalScenarios),",
  "      );",
  "      setText(\"scenarioVerificationBlockedReplaySignal\", formatBool(checks.blockedReplaySemanticsStable));",
  "      setText(\"scenarioVerificationMiniKvReadSignal\", formatBool(checks.miniKvReadSemanticsStable));",
  "      setText(\"scenarioVerificationMatrixValiditySignal\", formatBool(checks.matrixValidityConsistent));",
  "      setText(",
  "        \"scenarioVerificationExpectedIdsSignal\",",
  "        \"present \" + formatBool(checks.expectedScenarioIdsPresent) + \" / unexpected \" + formatBool(!checks.noUnexpectedScenarioIds),",
  "      );",
  "      setText(\"scenarioVerificationSourcePathsSignal\", formatBool(checks.sourcePathsPresent));",
  "      setText(",
  "        \"scenarioVerificationDriftSignal\",",
  "        formatBool(checks.driftIssueCountMatches) + \" / issues \" + formatNumber(verification.summary.issueCount),",
  "      );",
  "    }",
  "",
  "    async function refreshScenarioVerification() {",
  "      const verification = await api(\"/api/v1/upstream-contract-fixtures/scenario-matrix/verification\");",
  "      renderScenarioVerification(verification);",
  "      return verification;",
  "    }",
  "",
  "    function renderScenarioArchiveBundle(bundle) {",
  "      const summary = bundle.summary || {};",
  "      setBadge(\"scenarioArchiveBundleState\", bundle.valid ? \"online\" : \"degraded\");",
  "      setText(\"scenarioArchiveBundleValidSignal\", formatBool(bundle.valid));",
  "      setText(",
  "        \"scenarioArchiveBundleReadExecuteSignal\",",
  "        \"read_only \" + formatBool(bundle.readOnly) + \" / execution_allowed \" + formatBool(bundle.executionAllowed),",
  "      );",
  "      setText(",
  "        \"scenarioArchiveBundleSourcePathSignal\",",
  "        formatNumber(summary.sourcePathCount) + \"/\" + formatNumber(summary.totalScenarios),",
  "      );",
  "      setText(\"scenarioArchiveBundleDigestSignal\", bundle.archiveBundleDigest.algorithm + \":\" + bundle.archiveBundleDigest.value);",
  "      setText(\"scenarioArchiveBundleVerificationDigestSignal\", bundle.digests.verificationDigest);",
  "      setText(\"scenarioArchiveBundleMatrixDigestSignal\", bundle.digests.matrixDigest);",
  "      setText(",
  "        \"scenarioArchiveBundleScenarioSignal\",",
  "        formatNumber(summary.validScenarios) + \"/\" + formatNumber(summary.totalScenarios) + \" valid / ready \" + formatNumber(summary.diagnosticReadyScenarios),",
  "      );",
  "      setText(\"scenarioArchiveBundleIssueSignal\", formatNumber(summary.issueCount));",
  "      setText(\"scenarioArchiveBundleEvidenceSignal\", formatNumber((bundle.scenarioEvidence || []).length) + \" records\");",
  "    }",
  "",
  "    async function refreshScenarioArchiveBundle() {",
  "      const bundle = await api(\"/api/v1/upstream-contract-fixtures/scenario-matrix/verification/archive-bundle\");",
  "      renderScenarioArchiveBundle(bundle);",
  "      return bundle;",
  "    }",
  "",
  "    function renderScenarioArchiveVerification(verification) {",
  "      const checks = verification.checks || {};",
  "      const summary = verification.summary || {};",
  "      setBadge(\"scenarioArchiveVerificationState\", verification.valid ? \"online\" : \"degraded\");",
  "      setText(\"scenarioArchiveVerificationValidSignal\", formatBool(verification.valid));",
  "      setText(\"scenarioArchiveVerificationDigestSignal\", formatBool(checks.archiveBundleDigestValid));",
  "      setText(\"scenarioArchiveVerificationVerificationDigestSignal\", formatBool(checks.verificationDigestValid));",
  "      setText(\"scenarioArchiveVerificationReadOnlySignal\", formatBool(checks.readOnlyStillTrue));",
  "      setText(\"scenarioArchiveVerificationExecutionSignal\", formatBool(checks.executionAllowedStillFalse));",
  "      setText(\"scenarioArchiveVerificationBundleValiditySignal\", formatBool(checks.bundleValidityConsistent));",
  "      setText(",
  "        \"scenarioArchiveVerificationSourcePathSignal\",",
  "        formatBool(checks.sourcePathCountValid) + \" / \" + formatNumber(summary.sourcePathCount) + \"/\" + formatNumber(summary.totalScenarios),",
  "      );",
  "      setText(",
  "        \"scenarioArchiveVerificationScenarioEvidenceSignal\",",
  "        formatBool(checks.scenarioEvidenceCountValid) + \" / \" + formatNumber(summary.scenarioEvidenceCount),",
  "      );",
  "      setText(",
  "        \"scenarioArchiveVerificationIssueSignal\",",
  "        \"issues \" + formatNumber(summary.issueCount) + \" / clean \" + formatBool(checks.noScenarioIssues),",
  "      );",
  "    }",
  "",
  "    async function refreshScenarioArchiveVerification() {",
  "      const verification = await api(\"/api/v1/upstream-contract-fixtures/scenario-matrix/verification/archive-bundle/verification\");",
  "      renderScenarioArchiveVerification(verification);",
  "      return verification;",
  "    }",
  "",
  "    async function refreshMiniKvKeyInventory() {",
  "      const prefix = $(\"kvPrefix\").value.trim();",
  "      const query = prefix.length > 0 ? \"?prefix=\" + encodeURIComponent(prefix) : \"\";",
  "      const inventory = await api(\"/api/v1/mini-kv/keys\" + query);",
  "      renderMiniKvKeyInventory(inventory);",
  "      return inventory;",
  "    }",
  "",
  "    async function refreshUpstreamOverview() {",
  "      const overview = await api(\"/api/v1/upstreams/overview\");",
  "      renderUpstreamOverview(overview);",
  "      return overview;",
  "    }",
  "",
  "    function renderSnapshot(snapshot) {",
  "      $(\"sampledAt\").textContent = \"Sampled \" + snapshot.sampledAt;",
  "      setBadge(\"nodeState\", snapshot.node.state);",
  "      $(\"nodeUptime\").textContent = snapshot.node.uptimeSeconds + \"s\";",
  "      $(\"nodeMeta\").textContent = \"pid \" + snapshot.node.pid + \" on \" + snapshot.node.version;",
  "",
  "      setBadge(\"javaState\", snapshot.javaOrderPlatform.state);",
  "      $(\"javaLatency\").textContent = snapshot.javaOrderPlatform.latencyMs === undefined ? \"-\" : snapshot.javaOrderPlatform.latencyMs + \"ms\";",
  "      $(\"javaMessage\").textContent = snapshot.javaOrderPlatform.message || \"\";",
  "",
  "      setBadge(\"kvState\", snapshot.miniKv.state);",
  "      $(\"kvLatency\").textContent = snapshot.miniKv.latencyMs === undefined ? \"-\" : snapshot.miniKv.latencyMs + \"ms\";",
  "      $(\"kvMessage\").textContent = snapshot.miniKv.message || \"\";",
  "    }",
  "",
  "    async function refreshStatus() {",
  "      renderSnapshot(await api(\"/api/v1/sources/status\"));",
  "    }",
  "",
  "    async function refreshAudit() {",
  "      const summary = await api(\"/api/v1/audit/summary\");",
  "      $(\"auditTotal\").textContent = summary.total;",
  "      $(\"auditSuccess\").textContent = summary.success;",
  "      $(\"auditErrors\").textContent = summary.clientError + summary.serverError;",
  "      $(\"auditAverage\").textContent = summary.averageDurationMs + \"ms\";",
  "      $(\"auditLatest\").textContent = summary.latest ? summary.latest.method + \" \" + summary.latest.path : \"No requests yet\";",
  "      return summary;",
  "    }",
  "",
  "    async function refreshRuntimeConfig() {",
  "      const config = await api(\"/api/v1/runtime/config\");",
  "      $(\"probeMode\").textContent = config.safety.upstreamProbesEnabled ? \"on\" : \"off\";",
  "      $(\"actionMode\").textContent = config.safety.upstreamActionsEnabled ? \"on\" : \"off\";",
  "      $(\"orderUpstream\").textContent = config.upstreams.orderPlatformUrl;",
  "      $(\"kvUpstream\").textContent = config.upstreams.miniKv;",
  "      return config;",
  "    }",
  "",
  "    async function refreshOpsSummary() {",
  "      const summary = await api(\"/api/v1/ops/summary\");",
  "      $(\"opsIntentTotal\").textContent = summary.intents.total;",
  "      $(\"opsIntentSignal\").textContent = \"blocked \" + summary.signals.blockedIntents + \" / pending \" + summary.signals.pendingConfirmations;",
  "      $(\"opsDispatchTotal\").textContent = summary.dispatches.total;",
  "      $(\"opsDispatchSignal\").textContent = \"rejected \" + summary.signals.rejectedDispatches + \" / dry-run \" + summary.signals.dryRunDispatches;",
  "      $(\"opsEventTotal\").textContent = summary.events.total;",
  "      $(\"opsEventSignal\").textContent = summary.events.latest ? summary.events.latest.type : \"No events yet\";",
  "      $(\"opsRateLimited\").textContent = summary.signals.rateLimitedRequests;",
  "      $(\"opsRateLimitConfig\").textContent = summary.mutationRateLimit.maxRequests + \" per \" + Math.round(summary.mutationRateLimit.windowMs / 1000) + \"s\";",
  "      return summary;",
  "    }",
  "",
  "    async function refreshOpsReadiness() {",
  "      const readiness = await api(\"/api/v1/ops/readiness\");",
  "      $(\"opsReadinessState\").textContent = readiness.state;",
  "      $(\"opsReadinessReady\").textContent = readiness.readyForUpstreamExecution ? \"ready for execution\" : \"not ready for execution\";",
  "      $(\"opsReadinessBlockers\").textContent = readiness.blockers;",
  "      $(\"opsReadinessWarnings\").textContent = readiness.warnings;",
  "      const firstBlocker = readiness.checks.find((check) => check.severity === \"blocker\");",
  "      const firstWarning = readiness.checks.find((check) => check.severity === \"warning\");",
  "      $(\"opsReadinessBlockerText\").textContent = firstBlocker ? firstBlocker.code : \"No blockers\";",
  "      $(\"opsReadinessWarningText\").textContent = firstWarning ? firstWarning.code : \"No warnings\";",
  "      $(\"opsReadinessNext\").textContent = readiness.nextActions[0] || \"No action needed\";",
  "      return readiness;",
  "    }",
].join("\n");
