import type {
  ControlledReadOnlyShardPreviewSourceMatrix,
} from "../../src/services/managedAuditManualSandboxConnectionCredentialResolverControlledReadOnlyShardPreviewTypes.js";

export function readySourceMatrix(): ControlledReadOnlyShardPreviewSourceMatrix {
  return {
    sources: [
      {
        source: "java",
        project: "advanced-order-platform",
        version: "Java v289",
        releaseVersion: null,
        status: "passed-read",
        readyForPreview: true,
        readOnlySafe: true,
        executionBlocked: true,
        shardEnabled: false,
        shardCount: 0,
        slotCount: 0,
        routingMode: "read-only-preview",
        endpoint: "GET /api/v1/ops/shard-readiness",
        command: null,
        latencyMs: 3,
      },
      {
        source: "miniKv",
        project: "mini-kv",
        version: "0.262.0",
        releaseVersion: "v262",
        status: "passed-read",
        readyForPreview: true,
        readOnlySafe: true,
        executionBlocked: true,
        shardEnabled: false,
        shardCount: 1,
        slotCount: 16,
        routingMode: "single-shard-readiness-prototype",
        endpoint: "127.0.0.1 mini-kv TCP",
        command: "SHARDJSON",
        latencyMs: 4,
      },
    ],
    sourceCount: 2,
    readySourceCount: 2,
    failedSourceCount: 0,
    skippedSourceCount: 0,
    routingModes: ["read-only-preview", "single-shard-readiness-prototype"],
    shardCountDelta: 1,
    slotCountDelta: 16,
    shardCountsComparable: true,
    slotCountsComparable: true,
    allSourcesReady: true,
  };
}

export function blockedSourceMatrix(): ControlledReadOnlyShardPreviewSourceMatrix {
  return {
    sources: [
      {
        source: "java",
        project: "advanced-order-platform",
        version: null,
        releaseVersion: null,
        status: "skipped-probes-disabled",
        readyForPreview: false,
        readOnlySafe: false,
        executionBlocked: false,
        shardEnabled: null,
        shardCount: null,
        slotCount: null,
        routingMode: null,
        endpoint: "GET /api/v1/ops/shard-readiness",
        command: null,
        latencyMs: null,
      },
      {
        source: "miniKv",
        project: "mini-kv",
        version: null,
        releaseVersion: null,
        status: "skipped-probes-disabled",
        readyForPreview: false,
        readOnlySafe: false,
        executionBlocked: false,
        shardEnabled: null,
        shardCount: null,
        slotCount: null,
        routingMode: null,
        endpoint: "127.0.0.1 mini-kv TCP",
        command: "SHARDJSON",
        latencyMs: null,
      },
    ],
    sourceCount: 2,
    readySourceCount: 0,
    failedSourceCount: 0,
    skippedSourceCount: 2,
    routingModes: [],
    shardCountDelta: null,
    slotCountDelta: null,
    shardCountsComparable: false,
    slotCountsComparable: false,
    allSourcesReady: false,
  };
}
