create table products (
    id bigint generated by default as identity primary key,
    sku varchar(64) not null,
    name varchar(120) not null,
    price numeric(12, 2) not null,
    active boolean not null,
    constraint uk_products_sku unique (sku)
);

create table inventory_items (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    available integer not null,
    reserved integer not null,
    version bigint not null,
    constraint uk_inventory_items_product unique (product_id)
);

create table orders (
    id bigint generated by default as identity primary key,
    customer_id uuid not null,
    idempotency_key varchar(120) not null,
    status varchar(32) not null,
    total_amount numeric(12, 2) not null,
    created_at timestamp(6) with time zone not null,
    paid_at timestamp(6) with time zone,
    shipped_at timestamp(6) with time zone,
    completed_at timestamp(6) with time zone,
    refunded_at timestamp(6) with time zone,
    canceled_at timestamp(6) with time zone,
    version bigint not null,
    constraint uk_orders_idempotency_key unique (idempotency_key)
);

create table order_lines (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    product_name varchar(120) not null,
    unit_price numeric(12, 2) not null,
    quantity integer not null,
    line_total numeric(12, 2) not null,
    constraint fk_order_lines_order foreign key (order_id) references orders (id)
);

create table order_status_history (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    from_status varchar(32),
    to_status varchar(32) not null,
    action varchar(80) not null,
    changed_at timestamp(6) with time zone not null
);

create index idx_order_status_history_order_changed
    on order_status_history (order_id, changed_at);

create table payment_transactions (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    amount numeric(12, 2) not null,
    status varchar(32) not null,
    provider varchar(40) not null,
    provider_transaction_id varchar(80) not null,
    created_at timestamp(6) with time zone not null,
    completed_at timestamp(6) with time zone,
    constraint uk_payment_transactions_provider_transaction unique (provider_transaction_id)
);

create index idx_payment_transactions_order_created
    on payment_transactions (order_id, created_at);

create table outbox_events (
    id uuid primary key,
    aggregate_type varchar(64) not null,
    aggregate_id varchar(64) not null,
    event_type varchar(80) not null,
    payload text not null,
    created_at timestamp(6) with time zone not null,
    published_at timestamp(6) with time zone
);

create table inventory_movements (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    type varchar(40) not null,
    quantity integer not null,
    available_before integer not null,
    reserved_before integer not null,
    available_after integer not null,
    reserved_after integer not null,
    created_at timestamp(6) with time zone not null
);

create index idx_inventory_movements_product_created
    on inventory_movements (product_id, created_at);
