create table failed_event_replay_attempts (
    id bigint generated by default as identity primary key,
    failed_event_message_id bigint not null,
    operator_id varchar(80) not null,
    requested_event_id varchar(80),
    requested_event_type varchar(80),
    requested_aggregate_type varchar(64),
    requested_aggregate_id varchar(64),
    requested_payload text,
    effective_event_id varchar(80),
    effective_event_type varchar(80),
    effective_aggregate_type varchar(64),
    effective_aggregate_id varchar(64),
    effective_payload text,
    status varchar(32) not null,
    error_message varchar(500),
    attempted_at timestamp(6) with time zone not null,
    constraint fk_failed_event_replay_attempts_message
        foreign key (failed_event_message_id) references failed_event_messages (id)
);

create index idx_failed_event_replay_attempts_message
    on failed_event_replay_attempts (failed_event_message_id, attempted_at);
