create table notification_messages (
    id bigint generated by default as identity primary key,
    event_id uuid not null,
    event_type varchar(80) not null,
    order_id bigint not null,
    channel varchar(32) not null,
    status varchar(32) not null,
    recipient varchar(120) not null,
    subject varchar(160) not null,
    content varchar(500) not null,
    payload text not null,
    created_at timestamp(6) with time zone not null,
    constraint uk_notification_messages_event unique (event_id)
);

create index idx_notification_messages_order_created
    on notification_messages (order_id, created_at);
