create table failed_event_messages (
    id bigint generated by default as identity primary key,
    message_id varchar(120) not null,
    event_id varchar(80),
    event_type varchar(80),
    aggregate_type varchar(64),
    aggregate_id varchar(64),
    source_queue varchar(160),
    dead_letter_queue varchar(160) not null,
    failure_reason varchar(500) not null,
    payload text not null,
    failed_at timestamp(6) with time zone not null,
    constraint uk_failed_event_messages_message unique (message_id)
);

create index idx_failed_event_messages_failed_at
    on failed_event_messages (failed_at);
