services:
  postgres:
    image: postgres:16-alpine
    container_name: advanced-order-postgres
    environment:
      POSTGRES_DB: order_platform
      POSTGRES_USER: order_app
      POSTGRES_PASSWORD: order_app
    ports:
      - "5432:5432"
    volumes:
      - order-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: advanced-order-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: advanced-order-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: order_app
      RABBITMQ_DEFAULT_PASS: order_app
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  order-postgres-data:
