spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/order_platform}
    username: ${DB_USERNAME:order_app}
    password: ${DB_PASSWORD:order_app}
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: "classpath:db/migration/{vendor}"
