import type {
  OpsPromotionDeploymentApproval,
  OpsPromotionDeploymentApprovalVerification,
  OpsPromotionDeploymentChangeRecord,
  OpsPromotionDeploymentChangeRecordVerification,
} from "../opsPromotionArchiveBundleTypes.js";
import {
  formatMarkdownDigest,
  renderMarkdownBullets,
  renderMarkdownFields,
  type MarkdownDocumentSpec,
} from "../promotionMarkdownEngine.js";
import {
  checkedDetailLines,
  decisionLines,
  detailItemLines,
  summaryLines,
} from "./stage.js";

export function approvalSpec(
  approval: OpsPromotionDeploymentApproval,
): MarkdownDocumentSpec {
  return {
    title: "Promotion deployment approval",
    fields: [
      ["Service", approval.service],
      ["Generated at", approval.generatedAt],
      ["Approval name", approval.approvalName],
      ["Release archive name", approval.releaseArchiveName],
      ["Evidence name", approval.evidenceName],
      ["Completion name", approval.completionName],
      ["Closure name", approval.closureName],
      ["Receipt name", approval.receiptName],
      ["Certificate name", approval.certificateName],
      ["Package name", approval.packageName],
      ["Archive name", approval.archiveName],
      ["State", approval.state],
      ["Valid", approval.valid],
      ["Handoff ready", approval.handoffReady],
      ["Approval ready", approval.approvalReady],
      ["Approval digest", formatMarkdownDigest(approval.approvalDigest)],
      ["Release archive digest", formatMarkdownDigest(approval.releaseArchiveDigest)],
      ["Verified release archive digest", formatMarkdownDigest(approval.verifiedReleaseArchiveDigest)],
      ["Evidence digest", formatMarkdownDigest(approval.evidenceDigest)],
      ["Covered fields", approval.approvalDigest.coveredFields.join(", ")],
    ],
    sections: [
      ["Decision", decisionLines(approval.decision)],
      ["Verification", renderMarkdownFields([
        ["Release archive verified", approval.verification.releaseArchiveVerified],
        ["Release archive digest valid", approval.verification.releaseArchiveDigestValid],
        ["Archive items valid", approval.verification.archiveItemsValid],
        ["Release archive reference valid", approval.verification.releaseArchiveReferenceValid],
        ["Closeout ready", approval.verification.closeoutReady],
        ["Archive item count", approval.verification.archiveItemCount],
        ["Approval item count", approval.verification.approvalItemCount],
      ])],
      ["Approval Items", detailItemLines(approval.approvalItems)],
      ["Next Actions", renderMarkdownBullets(approval.nextActions)],
    ],
  };
}

export function approvalCheckSpec(
  verification: OpsPromotionDeploymentApprovalVerification,
): MarkdownDocumentSpec {
  return {
    title: "Promotion deployment approval verification",
    fields: [
      ["Service", verification.service],
      ["Generated at", verification.generatedAt],
      ["Approval name", verification.approvalName],
      ["Release archive name", verification.releaseArchiveName],
      ["Evidence name", verification.evidenceName],
      ["Completion name", verification.completionName],
      ["Closure name", verification.closureName],
      ["Receipt name", verification.receiptName],
      ["Certificate name", verification.certificateName],
      ["Package name", verification.packageName],
      ["Archive name", verification.archiveName],
      ["State", verification.state],
      ["Handoff ready", verification.handoffReady],
      ["Approval ready", verification.approvalReady],
      ["Valid", verification.valid],
      ["Approval digest", formatMarkdownDigest(verification.approvalDigest)],
      ["Recomputed approval digest", formatMarkdownDigest(verification.recomputedApprovalDigest)],
    ],
    sections: [
      ["Checks", renderMarkdownFields([
        ["Approval digest valid", verification.checks.approvalDigestValid],
        ["Covered fields match", verification.checks.coveredFieldsMatch],
        ["Approval items valid", verification.checks.approvalItemsValid],
        ["Approval name matches", verification.checks.approvalNameMatches],
        ["Release archive name matches", verification.checks.releaseArchiveNameMatches],
        ["Evidence name matches", verification.checks.evidenceNameMatches],
        ["Completion name matches", verification.checks.completionNameMatches],
        ["Closure name matches", verification.checks.closureNameMatches],
        ["Receipt name matches", verification.checks.receiptNameMatches],
        ["Certificate name matches", verification.checks.certificateNameMatches],
        ["Package name matches", verification.checks.packageNameMatches],
        ["Archive name matches", verification.checks.archiveNameMatches],
        ["Valid matches", verification.checks.validMatches],
        ["State matches", verification.checks.stateMatches],
        ["Handoff ready matches", verification.checks.handoffReadyMatches],
        ["Approval ready matches", verification.checks.approvalReadyMatches],
        ["Release archive digest matches", verification.checks.releaseArchiveDigestMatches],
        ["Verified release archive digest matches", verification.checks.verifiedReleaseArchiveDigestMatches],
        ["Evidence digest matches", verification.checks.evidenceDigestMatches],
        ["Decision matches", verification.checks.decisionMatches],
        ["Verification matches", verification.checks.verificationMatches],
        ["Next actions match", verification.checks.nextActionsMatch],
      ])],
      ["Approval Items", checkedDetailLines(
        verification.approvalItems,
        "Approval digest",
        (item) => item.approvalDigest,
      )],
      ["Summary", summaryLines(verification.summary, [
        ["Approval item count", verification.summary.approvalItemCount],
        ["Handoff ready", verification.summary.handoffReady],
        ["Approval ready", verification.summary.approvalReady],
        ["Closeout ready", verification.summary.closeoutReady],
      ])],
      ["Next Actions", renderMarkdownBullets(verification.nextActions)],
    ],
  };
}

export function changeRecordSpec(
  record: OpsPromotionDeploymentChangeRecord,
): MarkdownDocumentSpec {
  return {
    title: "Promotion deployment change record",
    fields: [
      ["Service", record.service],
      ["Generated at", record.generatedAt],
      ["Change record name", record.changeRecordName],
      ["Approval name", record.approvalName],
      ["Release archive name", record.releaseArchiveName],
      ["Evidence name", record.evidenceName],
      ["Completion name", record.completionName],
      ["Closure name", record.closureName],
      ["Receipt name", record.receiptName],
      ["Certificate name", record.certificateName],
      ["Package name", record.packageName],
      ["Archive name", record.archiveName],
      ["State", record.state],
      ["Valid", record.valid],
      ["Handoff ready", record.handoffReady],
      ["Approval ready", record.approvalReady],
      ["Change ready", record.changeReady],
      ["Change digest", formatMarkdownDigest(record.changeDigest)],
      ["Approval digest", formatMarkdownDigest(record.approvalDigest)],
      ["Verified approval digest", formatMarkdownDigest(record.verifiedApprovalDigest)],
      ["Release archive digest", formatMarkdownDigest(record.releaseArchiveDigest)],
      ["Covered fields", record.changeDigest.coveredFields.join(", ")],
    ],
    sections: [
      ["Decision", decisionLines(record.decision)],
      ["Verification", renderMarkdownFields([
        ["Approval verified", record.verification.approvalVerified],
        ["Approval digest valid", record.verification.approvalDigestValid],
        ["Approval items valid", record.verification.approvalItemsValid],
        ["Approval reference valid", record.verification.approvalReferenceValid],
        ["Closeout ready", record.verification.closeoutReady],
        ["Approval item count", record.verification.approvalItemCount],
        ["Change item count", record.verification.changeItemCount],
      ])],
      ["Change Items", detailItemLines(record.changeItems)],
      ["Next Actions", renderMarkdownBullets(record.nextActions)],
    ],
  };
}

export function changeRecordCheckSpec(
  verification: OpsPromotionDeploymentChangeRecordVerification,
): MarkdownDocumentSpec {
  return {
    title: "Promotion deployment change record verification",
    fields: [
      ["Service", verification.service],
      ["Generated at", verification.generatedAt],
      ["Change record name", verification.changeRecordName],
      ["Approval name", verification.approvalName],
      ["Release archive name", verification.releaseArchiveName],
      ["Evidence name", verification.evidenceName],
      ["Completion name", verification.completionName],
      ["Closure name", verification.closureName],
      ["Receipt name", verification.receiptName],
      ["Certificate name", verification.certificateName],
      ["Package name", verification.packageName],
      ["Archive name", verification.archiveName],
      ["State", verification.state],
      ["Handoff ready", verification.handoffReady],
      ["Approval ready", verification.approvalReady],
      ["Change ready", verification.changeReady],
      ["Valid", verification.valid],
      ["Change digest", formatMarkdownDigest(verification.changeDigest)],
      ["Recomputed change digest", formatMarkdownDigest(verification.recomputedChangeDigest)],
    ],
    sections: [
      ["Checks", renderMarkdownFields([
        ["Change digest valid", verification.checks.changeDigestValid],
        ["Covered fields match", verification.checks.coveredFieldsMatch],
        ["Change items valid", verification.checks.changeItemsValid],
        ["Change record name matches", verification.checks.changeRecordNameMatches],
        ["Approval name matches", verification.checks.approvalNameMatches],
        ["Release archive name matches", verification.checks.releaseArchiveNameMatches],
        ["Evidence name matches", verification.checks.evidenceNameMatches],
        ["Completion name matches", verification.checks.completionNameMatches],
        ["Closure name matches", verification.checks.closureNameMatches],
        ["Receipt name matches", verification.checks.receiptNameMatches],
        ["Certificate name matches", verification.checks.certificateNameMatches],
        ["Package name matches", verification.checks.packageNameMatches],
        ["Archive name matches", verification.checks.archiveNameMatches],
        ["Valid matches", verification.checks.validMatches],
        ["State matches", verification.checks.stateMatches],
        ["Handoff ready matches", verification.checks.handoffReadyMatches],
        ["Approval ready matches", verification.checks.approvalReadyMatches],
        ["Change ready matches", verification.checks.changeReadyMatches],
        ["Approval digest matches", verification.checks.approvalDigestMatches],
        ["Verified approval digest matches", verification.checks.verifiedApprovalDigestMatches],
        ["Release archive digest matches", verification.checks.releaseArchiveDigestMatches],
        ["Decision matches", verification.checks.decisionMatches],
        ["Verification matches", verification.checks.verificationMatches],
        ["Next actions match", verification.checks.nextActionsMatch],
      ])],
      ["Change Items", checkedDetailLines(
        verification.changeItems,
        "Change item digest",
        (item) => item.changeItemDigest,
      )],
      ["Summary", summaryLines(verification.summary, [
        ["Change item count", verification.summary.changeItemCount],
        ["Handoff ready", verification.summary.handoffReady],
        ["Approval ready", verification.summary.approvalReady],
        ["Change ready", verification.summary.changeReady],
        ["Closeout ready", verification.summary.closeoutReady],
      ])],
      ["Next Actions", renderMarkdownBullets(verification.nextActions)],
    ],
  };
}
