import type {
  OpsPromotionDeploymentExecutionReceipt,
  OpsPromotionDeploymentExecutionReceiptVerification,
  OpsPromotionDeploymentExecutionRecord,
  OpsPromotionDeploymentExecutionRecordVerification,
} from "../opsPromotionArchiveBundleTypes.js";
import {
  formatMarkdownDigest,
  renderMarkdownBullets,
  renderMarkdownFields,
  type MarkdownDocumentSpec,
} from "../promotionMarkdownEngine.js";
import {
  checkedDetailLines,
  decisionLines,
  detailItemLines,
  summaryLines,
} from "./stage.js";

export function executionRecordSpec(
  record: OpsPromotionDeploymentExecutionRecord,
): MarkdownDocumentSpec {
  return {
    title: "Promotion deployment execution record",
    fields: [
      ["Service", record.service],
      ["Generated at", record.generatedAt],
      ["Execution name", record.executionName],
      ["Change record name", record.changeRecordName],
      ["Approval name", record.approvalName],
      ["Release archive name", record.releaseArchiveName],
      ["Evidence name", record.evidenceName],
      ["Completion name", record.completionName],
      ["Closure name", record.closureName],
      ["Receipt name", record.receiptName],
      ["Certificate name", record.certificateName],
      ["Package name", record.packageName],
      ["Archive name", record.archiveName],
      ["State", record.state],
      ["Valid", record.valid],
      ["Handoff ready", record.handoffReady],
      ["Approval ready", record.approvalReady],
      ["Change ready", record.changeReady],
      ["Execution ready", record.executionReady],
      ["Execution digest", formatMarkdownDigest(record.executionDigest)],
      ["Change digest", formatMarkdownDigest(record.changeDigest)],
      ["Verified change digest", formatMarkdownDigest(record.verifiedChangeDigest)],
      ["Approval digest", formatMarkdownDigest(record.approvalDigest)],
      ["Release archive digest", formatMarkdownDigest(record.releaseArchiveDigest)],
      ["Covered fields", record.executionDigest.coveredFields.join(", ")],
    ],
    sections: [
      ["Decision", decisionLines(record.decision)],
      ["Verification", renderMarkdownFields([
        ["Change record verified", record.verification.changeRecordVerified],
        ["Change digest valid", record.verification.changeDigestValid],
        ["Change items valid", record.verification.changeItemsValid],
        ["Change reference valid", record.verification.changeReferenceValid],
        ["Closeout ready", record.verification.closeoutReady],
        ["Change item count", record.verification.changeItemCount],
        ["Execution item count", record.verification.executionItemCount],
      ])],
      ["Execution Items", detailItemLines(record.executionItems)],
      ["Next Actions", renderMarkdownBullets(record.nextActions)],
    ],
  };
}

export function executionRecordCheckSpec(
  verification: OpsPromotionDeploymentExecutionRecordVerification,
): MarkdownDocumentSpec {
  return {
    title: "Promotion deployment execution record verification",
    fields: [
      ["Service", verification.service],
      ["Generated at", verification.generatedAt],
      ["Execution name", verification.executionName],
      ["Change record name", verification.changeRecordName],
      ["Approval name", verification.approvalName],
      ["Release archive name", verification.releaseArchiveName],
      ["Evidence name", verification.evidenceName],
      ["Completion name", verification.completionName],
      ["Closure name", verification.closureName],
      ["Receipt name", verification.receiptName],
      ["Certificate name", verification.certificateName],
      ["Package name", verification.packageName],
      ["Archive name", verification.archiveName],
      ["State", verification.state],
      ["Handoff ready", verification.handoffReady],
      ["Approval ready", verification.approvalReady],
      ["Change ready", verification.changeReady],
      ["Execution ready", verification.executionReady],
      ["Valid", verification.valid],
      ["Execution digest", formatMarkdownDigest(verification.executionDigest)],
      ["Recomputed execution digest", formatMarkdownDigest(verification.recomputedExecutionDigest)],
    ],
    sections: [
      ["Checks", renderMarkdownFields([
        ["Execution digest valid", verification.checks.executionDigestValid],
        ["Covered fields match", verification.checks.coveredFieldsMatch],
        ["Execution items valid", verification.checks.executionItemsValid],
        ["Execution name matches", verification.checks.executionNameMatches],
        ["Change record name matches", verification.checks.changeRecordNameMatches],
        ["Approval name matches", verification.checks.approvalNameMatches],
        ["Release archive name matches", verification.checks.releaseArchiveNameMatches],
        ["Evidence name matches", verification.checks.evidenceNameMatches],
        ["Completion name matches", verification.checks.completionNameMatches],
        ["Closure name matches", verification.checks.closureNameMatches],
        ["Receipt name matches", verification.checks.receiptNameMatches],
        ["Certificate name matches", verification.checks.certificateNameMatches],
        ["Package name matches", verification.checks.packageNameMatches],
        ["Archive name matches", verification.checks.archiveNameMatches],
        ["Valid matches", verification.checks.validMatches],
        ["State matches", verification.checks.stateMatches],
        ["Handoff ready matches", verification.checks.handoffReadyMatches],
        ["Approval ready matches", verification.checks.approvalReadyMatches],
        ["Change ready matches", verification.checks.changeReadyMatches],
        ["Execution ready matches", verification.checks.executionReadyMatches],
        ["Change digest matches", verification.checks.changeDigestMatches],
        ["Verified change digest matches", verification.checks.verifiedChangeDigestMatches],
        ["Approval digest matches", verification.checks.approvalDigestMatches],
        ["Release archive digest matches", verification.checks.releaseArchiveDigestMatches],
        ["Decision matches", verification.checks.decisionMatches],
        ["Verification matches", verification.checks.verificationMatches],
        ["Next actions match", verification.checks.nextActionsMatch],
      ])],
      ["Execution Items", checkedDetailLines(
        verification.executionItems,
        "Execution item digest",
        (item) => item.executionItemDigest,
      )],
      ["Summary", summaryLines(verification.summary, [
        ["Execution item count", verification.summary.executionItemCount],
        ["Handoff ready", verification.summary.handoffReady],
        ["Approval ready", verification.summary.approvalReady],
        ["Change ready", verification.summary.changeReady],
        ["Execution ready", verification.summary.executionReady],
        ["Closeout ready", verification.summary.closeoutReady],
      ])],
      ["Next Actions", renderMarkdownBullets(verification.nextActions)],
    ],
  };
}

export function executionReceiptSpec(
  receipt: OpsPromotionDeploymentExecutionReceipt,
): MarkdownDocumentSpec {
  return {
    title: "Promotion deployment execution receipt",
    fields: [
      ["Service", receipt.service],
      ["Generated at", receipt.generatedAt],
      ["Receipt name", receipt.receiptName],
      ["Execution name", receipt.executionName],
      ["Change record name", receipt.changeRecordName],
      ["Approval name", receipt.approvalName],
      ["Release archive name", receipt.releaseArchiveName],
      ["Evidence name", receipt.evidenceName],
      ["Completion name", receipt.completionName],
      ["Closure name", receipt.closureName],
      ["Receipt record name", receipt.receiptRecordName],
      ["Certificate name", receipt.certificateName],
      ["Package name", receipt.packageName],
      ["Archive name", receipt.archiveName],
      ["State", receipt.state],
      ["Valid", receipt.valid],
      ["Handoff ready", receipt.handoffReady],
      ["Approval ready", receipt.approvalReady],
      ["Change ready", receipt.changeReady],
      ["Execution ready", receipt.executionReady],
      ["Receipt ready", receipt.receiptReady],
      ["Receipt digest", formatMarkdownDigest(receipt.receiptDigest)],
      ["Execution digest", formatMarkdownDigest(receipt.executionDigest)],
      ["Verified execution digest", formatMarkdownDigest(receipt.verifiedExecutionDigest)],
      ["Change digest", formatMarkdownDigest(receipt.changeDigest)],
      ["Approval digest", formatMarkdownDigest(receipt.approvalDigest)],
      ["Release archive digest", formatMarkdownDigest(receipt.releaseArchiveDigest)],
      ["Covered fields", receipt.receiptDigest.coveredFields.join(", ")],
    ],
    sections: [
      ["Decision", decisionLines(receipt.decision)],
      ["Verification", renderMarkdownFields([
        ["Execution record verified", receipt.verification.executionRecordVerified],
        ["Execution digest valid", receipt.verification.executionDigestValid],
        ["Execution items valid", receipt.verification.executionItemsValid],
        ["Execution reference valid", receipt.verification.executionReferenceValid],
        ["Closeout ready", receipt.verification.closeoutReady],
        ["Execution item count", receipt.verification.executionItemCount],
        ["Receipt item count", receipt.verification.receiptItemCount],
      ])],
      ["Receipt Items", detailItemLines(receipt.receiptItems)],
      ["Next Actions", renderMarkdownBullets(receipt.nextActions)],
    ],
  };
}

export function executionReceiptCheckSpec(
  verification: OpsPromotionDeploymentExecutionReceiptVerification,
): MarkdownDocumentSpec {
  return {
    title: "Promotion deployment execution receipt verification",
    fields: [
      ["Service", verification.service],
      ["Generated at", verification.generatedAt],
      ["Receipt name", verification.receiptName],
      ["Execution name", verification.executionName],
      ["Change record name", verification.changeRecordName],
      ["Approval name", verification.approvalName],
      ["Release archive name", verification.releaseArchiveName],
      ["Evidence name", verification.evidenceName],
      ["Completion name", verification.completionName],
      ["Closure name", verification.closureName],
      ["Receipt record name", verification.receiptRecordName],
      ["Certificate name", verification.certificateName],
      ["Package name", verification.packageName],
      ["Archive name", verification.archiveName],
      ["State", verification.state],
      ["Handoff ready", verification.handoffReady],
      ["Approval ready", verification.approvalReady],
      ["Change ready", verification.changeReady],
      ["Execution ready", verification.executionReady],
      ["Receipt ready", verification.receiptReady],
      ["Valid", verification.valid],
      ["Receipt digest", formatMarkdownDigest(verification.receiptDigest)],
      ["Recomputed receipt digest", formatMarkdownDigest(verification.recomputedReceiptDigest)],
    ],
    sections: [
      ["Checks", renderMarkdownFields([
        ["Receipt digest valid", verification.checks.receiptDigestValid],
        ["Covered fields match", verification.checks.coveredFieldsMatch],
        ["Receipt items valid", verification.checks.receiptItemsValid],
        ["Receipt name matches", verification.checks.receiptNameMatches],
        ["Execution name matches", verification.checks.executionNameMatches],
        ["Change record name matches", verification.checks.changeRecordNameMatches],
        ["Approval name matches", verification.checks.approvalNameMatches],
        ["Release archive name matches", verification.checks.releaseArchiveNameMatches],
        ["Evidence name matches", verification.checks.evidenceNameMatches],
        ["Completion name matches", verification.checks.completionNameMatches],
        ["Closure name matches", verification.checks.closureNameMatches],
        ["Receipt record name matches", verification.checks.receiptRecordNameMatches],
        ["Certificate name matches", verification.checks.certificateNameMatches],
        ["Package name matches", verification.checks.packageNameMatches],
        ["Archive name matches", verification.checks.archiveNameMatches],
        ["Valid matches", verification.checks.validMatches],
        ["State matches", verification.checks.stateMatches],
        ["Handoff ready matches", verification.checks.handoffReadyMatches],
        ["Approval ready matches", verification.checks.approvalReadyMatches],
        ["Change ready matches", verification.checks.changeReadyMatches],
        ["Execution ready matches", verification.checks.executionReadyMatches],
        ["Receipt ready matches", verification.checks.receiptReadyMatches],
        ["Execution digest matches", verification.checks.executionDigestMatches],
        ["Verified execution digest matches", verification.checks.verifiedExecutionDigestMatches],
        ["Change digest matches", verification.checks.changeDigestMatches],
        ["Approval digest matches", verification.checks.approvalDigestMatches],
        ["Release archive digest matches", verification.checks.releaseArchiveDigestMatches],
        ["Decision matches", verification.checks.decisionMatches],
        ["Verification matches", verification.checks.verificationMatches],
        ["Next actions match", verification.checks.nextActionsMatch],
      ])],
      ["Receipt Items", checkedDetailLines(
        verification.receiptItems,
        "Receipt item digest",
        (item) => item.receiptItemDigest,
      )],
      ["Summary", summaryLines(verification.summary, [
        ["Receipt item count", verification.summary.receiptItemCount],
        ["Handoff ready", verification.summary.handoffReady],
        ["Approval ready", verification.summary.approvalReady],
        ["Change ready", verification.summary.changeReady],
        ["Execution ready", verification.summary.executionReady],
        ["Receipt ready", verification.summary.receiptReady],
        ["Closeout ready", verification.summary.closeoutReady],
      ])],
      ["Next Actions", renderMarkdownBullets(verification.nextActions)],
    ],
  };
}
